rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
AESAE_CDB <- aesae
# Post processing for compare
AESAE_CDB <- AESAE_CDB %>% mutate(across(everything(), as.character))
AESAE_CDB$DLASTMOD <- substring(AESAE_CDB$DLASTMOD,1,16)
AESAE_CDB$CX_LASTCODEDAT <- substring(AESAE_CDB$CX_LASTCODEDAT,1,16)
AESAE_CDB$X_AESTTIM <- substring(AESAE_CDB$X_AESTTIM,1,5)
AESAE_CDB$X_AEENTIM <- substring(AESAE_CDB$X_AEENTIM,1,5)
AESAE_CDB <- AESAE_CDB %>% mutate_if(is.character, ~replace_na(.,""))
AESAE_CDB <- AESAE_CDB[order(AESAE_CDB$STUDYID,AESAE_CDB$COUNTRY,AESAE_CDB$SITENUM,AESAE_CDB$SUBJID,AESAE_CDB$VISITNUM,AESAE_CDB$VISITDT,AESAE_CDB$FORMID,as.integer(AESAE_CDB$FORMSEQ),as.integer(AESAE_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

AE_SAE_01 <- ae_sae_01
AE_SAE_01 <- AE_SAE_01 %>% mutate(across(everything(), as.character))
AE_SAE_01 <- AE_SAE_01 %>% mutate_if(is.character, ~replace_na(.,""))

 
#-----------  FINAL union query--
AESAE_UNION <-
  sqldf(
    " SELECT
	'EIK1001-005_TST3'  'STUDYID'
	,'EDC'  'SOURCE'
	,AE_SAE_01.COUNTRY  'COUNTRY'
	,AE_SAE_01.SITENUM  'SITENUM'
	,AE_SAE_01.SUBJID  'SUBJID'
		,S1.STATUS 'SUBJSTATUS'
	,AE_SAE_01.EGROUPDEF  'EGID'
	,AE_SAE_01.ESEQ  'EGSEQ'
	,CASE AE_SAE_01.EGROUPDEF
	   WHEN 'eg_TRTA1C' THEN AE_SAE_01.EGROUP||' '||AE_SAE_01.EVENT
	   ELSE AE_SAE_01.EVENT
	   END AS 'VISIT'
,CASE 
WHEN AE_SAE_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN AE_SAE_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN AE_SAE_01.EVENTEID= 'ev_DAY1' THEN AE_SAE_01.ESEQ + 0.01
WHEN AE_SAE_01.EVENTEID= 'ev_DAY8' THEN AE_SAE_01.ESEQ + 0.08
WHEN AE_SAE_01.EVENTEID= 'ev_DAY15' THEN AE_SAE_01.ESEQ + 0.15
WHEN AE_SAE_01.EVENTEID= 'ev_TUPB' THEN 41 + AE_SAE_01.ESEQ * 0.01
WHEN AE_SAE_01.EVENTEID= 'ev_EOT' THEN 60
WHEN AE_SAE_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN AE_SAE_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN AE_SAE_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN AE_SAE_01.EVENTEID= 'ev_PTFU' THEN 75 + AE_SAE_01.ESEQ * 0.01
WHEN AE_SAE_01.EVENTEID= 'ev_LFU' THEN 80 + AE_SAE_01.ESEQ * 0.01
WHEN AE_SAE_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN AE_SAE_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN AE_SAE_01.EVENTEID= 'ev_UNS' THEN 99 + AE_SAE_01.ESEQ * 0.01
ELSE AE_SAE_01.EVENTEID
END as 'VISITNUM'
	,AE_SAE_01.EVENTDT  'VISITDT'
	,AE_SAE_01.FORM  'FORM'
	,AE_SAE_01.FORMDEF  'FORMID'
	,AE_SAE_01.FSEQ  'FORMSEQ'
	,CASE AE_SAE_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE AE_SAE_01.FORMSTATUS
	   END AS 'FORMSTATUS'
	,AE_SAE_01.IGSEQ  'IGSEQ'
	,AE_SAE_01.DLASTMOD  'DLASTMOD'
	,AE_SAE_01.V_AETERM  'V_AETERM'
	,AE_SAE_01.V_QVAL_AESI  'V_QVAL_AESI'
	,AE_SAE_01.V_QVAL_CRSCASE 'V_QVAL_CRSCASE'
	,AE_SAE_01.V_QVAL_DOSLMTOX  'V_QVAL_DOSLMTOX'
	,AE_SAE_01.V_AESTDTC  'V_AESTDTC'
	,AE_SAE_01.V_AESTDTC_DT  'V_AESTDAT'
	,AE_SAE_01.V_AESTDTC_TM  'V_AESTTIM'
,AE_SAE_01.V_AESTDTC  'X_AESTDTC'
,AE_SAE_01.V_AESTDTC_DT  'X_AESTDAT'
,AE_SAE_01.V_AESTDTC_TM  'X_AESTTIM'
	,AE_SAE_01.V_AEONGO  'V_AEONGO'
	,AE_SAE_01.V_AEENDTC  'V_AEENDTC'
	,AE_SAE_01.V_AEENDTC_DT  'V_AEENDAT'
	,AE_SAE_01.V_AEENDTC_TM  'V_AEENTIM'
,AE_SAE_01.V_AEENDTC  'X_AEENDTC'
,AE_SAE_01.V_AEENDTC_DT  'X_AEENDAT'
,AE_SAE_01.V_AEENDTC_TM 'X_AEENTIM'

	
	,AE_SAE_01.V_AEREL_EIK1001  'V_AEREL_EIK1001'
	,AE_SAE_01.V_AEREL_PEMBROLIZUMAB  'V_AEREL_PEMBROLIZUMAB'
	,AE_SAE_01.V_AEREL_PEMETREXED  'V_AEREL_PEMETREXED'
	,AE_SAE_01.V_AEREL_PACLITAXEL  'V_AEREL_PACLITAXEL'
	,AE_SAE_01.V_AEREL_CARBOPLATIN  'V_AEREL_CARBOPLATIN'
	,AE_SAE_01.DV_AEREL_OVERALL  'DV_AEREL_OVERALL'
	
	,AE_SAE_01.V_AETOXGR_CTCAE  'V_AETOXGR_CTCAE'
	,AE_SAE_01.V_AETOXGR_ASTCT  'V_AETOXGR_ASTCT'
	,AE_SAE_01.V_AESER  'V_AESER'
	,AE_SAE_01.V_AESDTH  'V_AESDTH'
	,AE_SAE_01.V_AESLIFE  'V_AESLIFE'
	,AE_SAE_01.V_AESHOSP  'V_AESHOSP'
	,AE_SAE_01.V_AESDISAB  'V_AESDISAB'
	,AE_SAE_01.V_AESCONG  'V_AESCONG'
	,AE_SAE_01.V_AESMIE  'V_AESMIE'
	,AE_SAE_01.V_AEACN_EIK1001  'V_AEACN_EIK1001'
	
	,AE_SAE_01.V_AEACN_PEMBROLIZUMAB  'V_AEACN_PEMBROLIZUMAB'
	
	,AE_SAE_01.V_AEACN_PEMETREXED  'V_AEACN_PEMETREXED'
	,AE_SAE_01.V_AEACN_PACLITAXEL  'V_AEACN_PACLITAXEL'
  ,AE_SAE_01.V_AEACN_CARBOPLATIN  'V_AEACN_CARBOPLATIN'
   ,AE_SAE_01.DV_AEACN_OVERALL 'DV_AEACN_OVERALL'
  
  
  ,AE_SAE_01.V_AEOUT  'V_AEOUT'
  ,AE_SAE_01.CRSTATUS  'CX_CRSTATUS'
	,AE_SAE_01.DICTVER  'CV_QVAL_DICTVER'
	,AE_SAE_01.SOC  'CV_AESOC'
	,AE_SAE_01.SOCID  'CV_AESOCCD'
	,AE_SAE_01.HLGT  'CV_AEHLGT'
	,AE_SAE_01.HLGTID  'CV_AEHLGTCD'
	,AE_SAE_01.HLT  'CV_AEHLT'
	,AE_SAE_01.HLTID  'CV_AEHLTCD'
	,AE_SAE_01.PT  'CV_AEDECOD'
	,AE_SAE_01.PTID  'CV_AEPTCD'
	,AE_SAE_01.LLT  'CV_AELLT'
	,AE_SAE_01.LLTID  'CV_AELLTCD'
	
	,AE_SAE_01.PRIMPATH  'CX_PRIMPATH'
	,AE_SAE_01.LASTCODEDAT  'CX_LASTCODEDAT'	,AE_SAE_01.LASTCODEDBY  'CX_LASTCODEDBY'
	
	FROM
	AE_SAE_01 AE_SAE_01,
	SUBJECTS S1
	WHERE
	S1.SUBJID=AE_SAE_01.SUBJID
  AND S1.SITENUM=AE_SAE_01.SITENUM
	AND AE_SAE_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
	AND AE_SAE_01.FORMILB !='true'
  
	 "
  )
# AND AE_SAE_01.FORMILB !='true'

# ,AE_SAE_01.V_AESTDTC  'X_AESTDTC'
# ,AE_SAE_01.V_AESTDTC_DT  'X_AESTDAT'
# ,AE_SAE_01.V_AESTDTC_TM  'X_AESTIM'
# 
# ,AE_SAE_01.V_AEENDTC  'X_AEENDTC'
# ,AE_SAE_01.V_AEENDTC_DT  'X_AEENDAT'
# ,AE_SAE_01.V_AEENDTC_TM  'X_AEENTIM'





dim(AE_SAE_01)
dim(AESAE_UNION)
dim(AESAE_CDB)
# , ,AE_SAE_01.V_AEREL_OVERALL
# Call the function -Convert_Date_Vals 
CharDate_Cols <-c("V_AESTDTC","V_AESTDAT","V_AEENDTC","V_AEENDAT")
datetime_columns <- NULL
table_name <- c("AESAE_UNION")
AESAE_EDC <- Convert_Date_Vals(AESAE_UNION, CharDate_Cols,datetime_columns,table_name)
AESAE_EDC$X_AESTDTC<-date_time_split(AESAE_EDC$X_AESTDTC) 
AESAE_EDC$X_AEENDTC<-date_time_split(AESAE_EDC$X_AEENDTC) 

# Arrange columns same as CDB
AESAE_EDC <- AESAE_EDC[names(AESAE_CDB)]

# Post processing for compare
AESAE_EDC$DLASTMOD <- substring(AESAE_EDC$DLASTMOD,1,16)
AESAE_EDC$CX_LASTCODEDAT <- substring(AESAE_EDC$CX_LASTCODEDAT,1,16)
AESAE_EDC$X_AESTTIM <- gsub("UN:UN", "", AESAE_EDC$X_AESTTIM)
AESAE_EDC$X_AEENTIM <- gsub("UN:UN", "", AESAE_EDC$X_AEENTIM)
AESAE_EDC <- AESAE_EDC %>% mutate(across(everything(), as.character))
AESAE_EDC <- AESAE_EDC %>% mutate_if(is.character, ~replace_na(.,""))
AESAE_EDC <- AESAE_EDC[order(AESAE_EDC$STUDYID,AESAE_EDC$COUNTRY,AESAE_EDC$SITENUM,AESAE_EDC$SUBJID,AESAE_EDC$VISITDT,AESAE_EDC$FORMID,as.integer(AESAE_EDC$FORMSEQ),as.integer(AESAE_EDC$IGSEQ)), ]

#Generate Compare Summary Report
AESAE_EDC <- AESAE_EDC %>% mutate(across(everything(), as.character))
AESAE_CDB <- AESAE_CDB %>% mutate(across(everything(), as.character))
AESAE_SUMMARY <- capture.output(summary(comparedf(AESAE_EDC, AESAE_CDB)))
print(AESAE_SUMMARY)

#Export Summary Report
addWorksheet(wb, "AESAE_SUMMARY")
writeData(wb, sheet = "AESAE_SUMMARY", x = AESAE_SUMMARY, headerStyle = openxlsx_getOp("headerStyle"),
          borders = openxlsx_getOp("borders", "none")
          )

#Export QC Datasets
write_xpt(AESAE_EDC,"QC Output/Datasets/EDC/AESAE_EDC.xpt")
write_xpt(AESAE_CDB,"QC Output/Datasets/CDB/AESAE_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)