rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
BEBIOMRKR_CDB <- bebiomrkr
# Post processing for compare
BEBIOMRKR_CDB <- BEBIOMRKR_CDB %>% mutate(across(everything(), as.character))
BEBIOMRKR_CDB$DLASTMOD <- substring(BEBIOMRKR_CDB$DLASTMOD,1,16)
BEBIOMRKR_CDB <- BEBIOMRKR_CDB %>% mutate_if(is.character, ~replace_na(.,""))
BEBIOMRKR_CDB <- BEBIOMRKR_CDB[order(BEBIOMRKR_CDB$STUDYID,BEBIOMRKR_CDB$COUNTRY,BEBIOMRKR_CDB$SITENUM,BEBIOMRKR_CDB$SUBJID,BEBIOMRKR_CDB$VISITNUM,BEBIOMRKR_CDB$VISITDT,BEBIOMRKR_CDB$FORMID,as.integer(BEBIOMRKR_CDB$FORMSEQ),as.integer(BEBIOMRKR_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

BE_BIOMRKR_01 <- be_biomrkr_01
BE_BIOMRKR_01 <- BE_BIOMRKR_01 %>% mutate(across(everything(), as.character))
BE_BIOMRKR_01 <- BE_BIOMRKR_01 %>% mutate_if(is.character, ~replace_na(.,""))

BE_BIOMRKRUNS_01 <- be_biomrkruns_01
BE_BIOMRKRUNS_01 <- BE_BIOMRKRUNS_01 %>% mutate(across(everything(), as.character))
BE_BIOMRKRUNS_01 <- BE_BIOMRKRUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))



#-----------  FINAL union query--
BEBIOMRKR_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_BIOMRKR_01.COUNTRY  'COUNTRY'
,BE_BIOMRKR_01.SITENUM  'SITENUM'
,BE_BIOMRKR_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,BE_BIOMRKR_01.EGROUPDEF  'EGID'
,BE_BIOMRKR_01.ESEQ  'EGSEQ'
,CASE BE_BIOMRKR_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN BE_BIOMRKR_01.EGROUP||' '||BE_BIOMRKR_01.EVENT
   ELSE BE_BIOMRKR_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_DAY1' THEN BE_BIOMRKR_01.ESEQ + 0.01
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_DAY8' THEN BE_BIOMRKR_01.ESEQ + 0.08
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_DAY15' THEN BE_BIOMRKR_01.ESEQ + 0.15
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_BIOMRKR_01.ESEQ * 0.01
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_BIOMRKR_01.ESEQ * 0.01
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_LFU' THEN 80 + BE_BIOMRKR_01.ESEQ * 0.01
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_BIOMRKR_01.EVENTEID= 'ev_UNS' THEN 99 + BE_BIOMRKR_01.ESEQ * 0.01
ELSE BE_BIOMRKR_01.EVENTEID
END as 'VISITNUM'
,BE_BIOMRKR_01.EVENTDT  'VISITDT'
,BE_BIOMRKR_01.FORM  'FORM'
,BE_BIOMRKR_01.FORMDEF  'FORMID'
,BE_BIOMRKR_01.FSEQ  'FORMSEQ'
,CASE BE_BIOMRKR_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  BE_BIOMRKR_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,BE_BIOMRKR_01.IGSEQ  'IGSEQ'
,BE_BIOMRKR_01.DLASTMOD  'DLASTMOD'
,BE_BIOMRKR_01.V_QVAL_BEOCCUR  'V_QVAL_BEOCCUR'
,BE_BIOMRKR_01.V_QVAL_BEREASND  'V_QVAL_BEREASND'
,BE_BIOMRKR_01.DV_BESCAT  'V_BESCAT'
,BE_BIOMRKR_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
--,BE_BIOMRKR_01.DV_QVAL_BETPT  'V_QVAL_BETPTNUM'--

,CASE BE_BIOMRKR_01.DV_QVAL_BETPT 
	   WHEN '0.0' THEN '0'
	   WHEN '1.0' THEN '1'
	   WHEN '2.0' THEN '2'
	   WHEN '3.0' THEN '3'
	   WHEN '4.0' THEN '4'
	   WHEN '6.0' THEN '6'
	   WHEN '24.0' THEN '24'
	   ELSE  BE_BIOMRKR_01.DV_QVAL_BETPT
	   END AS 'V_QVAL_BETPTNUM'

	   
,BE_BIOMRKR_01.DV_QVAL_BETPT_D  'V_QVAL_BETPT'

,BE_BIOMRKR_01.DV_QVAL_BETPTREF 'V_QVAL_BETPTREF'
,BE_BIOMRKR_01.V_QVAL_BESTAT  'V_QVAL_BESTAT'
,BE_BIOMRKR_01.V_BEDTC  'V_BEDTC'
,BE_BIOMRKR_01.V_BEDTC_DT  'V_BEDAT'
,BE_BIOMRKR_01.V_BEDTC_TM 'V_BETIM'
,BE_BIOMRKR_01.V_BEDTC  'X_BEDTC'
,BE_BIOMRKR_01.V_BEDTC_DT  'X_BEDAT'
,BE_BIOMRKR_01.V_BEDTC_TM 'X_BETIM'
FROM
              BE_BIOMRKR_01 BE_BIOMRKR_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=BE_BIOMRKR_01.SUBJID
              AND S1.SITENUM=BE_BIOMRKR_01.SITENUM
              AND BE_BIOMRKR_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
   
UNION
SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,BE_BIOMRKRUNS_01.COUNTRY  'COUNTRY'
,BE_BIOMRKRUNS_01.SITENUM  'SITENUM'
,BE_BIOMRKRUNS_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,BE_BIOMRKRUNS_01.EGROUPDEF  'EGID'
,BE_BIOMRKRUNS_01.ESEQ  'EGSEQ'
,CASE BE_BIOMRKRUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN BE_BIOMRKRUNS_01.EGROUP||' '||BE_BIOMRKRUNS_01.EVENT
   ELSE BE_BIOMRKRUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_DAY1' THEN BE_BIOMRKRUNS_01.ESEQ + 0.01
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_DAY8' THEN BE_BIOMRKRUNS_01.ESEQ + 0.08
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_DAY15' THEN BE_BIOMRKRUNS_01.ESEQ + 0.15
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_BIOMRKRUNS_01.ESEQ * 0.01
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_BIOMRKRUNS_01.ESEQ * 0.01
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_LFU' THEN 80 + BE_BIOMRKRUNS_01.ESEQ * 0.01
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_BIOMRKRUNS_01.EVENTEID= 'ev_UNS' THEN 99 + BE_BIOMRKRUNS_01.ESEQ * 0.01
ELSE BE_BIOMRKRUNS_01.EVENTEID
END as 'VISITNUM' 
,BE_BIOMRKRUNS_01.EVENTDT  'VISITDT'
,BE_BIOMRKRUNS_01.FORM  'FORM'
,BE_BIOMRKRUNS_01.FORMDEF  'FORMID'
,BE_BIOMRKRUNS_01.FSEQ  'FORMSEQ'
,CASE BE_BIOMRKRUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE BE_BIOMRKRUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,BE_BIOMRKRUNS_01.IGSEQ  'IGSEQ'
,BE_BIOMRKRUNS_01.DLASTMOD  'DLASTMOD'
,NULL  'V_QVAL_BEOCCUR'
,NULL  'V_QVAL_BEREASND'
,BE_BIOMRKRUNS_01.DV_BESCAT  'V_BESCAT'
,BE_BIOMRKRUNS_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
,NULL 'V_QVAL_BETPTNUM'
,NULL 'V_QVAL_BETPT'
,NULL 'V_QVAL_BETPTREF'
,NULL 'V_QVAL_BESTAT'
,BE_BIOMRKRUNS_01.V_BEDTC 'V_BEDTC'
,BE_BIOMRKRUNS_01.V_BEDTC_DT  'V_BEDAT'
,BE_BIOMRKRUNS_01.V_BEDTC_TM  'V_BETIM'
,BE_BIOMRKRUNS_01.V_BEDTC 'X_BEDTC'
,BE_BIOMRKRUNS_01.V_BEDTC_DT 'X_BEDAT'
,BE_BIOMRKRUNS_01.V_BEDTC_TM 'X_BETIM'
FROM
              BE_BIOMRKRUNS_01 BE_BIOMRKRUNS_01,
              SUBJECTS S1
WHERE
              S1.SUBJID=BE_BIOMRKRUNS_01.SUBJID
               AND S1.SITENUM=BE_BIOMRKRUNS_01.SITENUM
              AND BE_BIOMRKRUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
    
"
)

# 
# AND BE_BIOMRKR_01.FORMILB !='true'
# AND BE_BIOMRKRUNS_01.FORMILB !='true'

# Call the function -Convert_Date_Vals
CharDate_Cols <- c("V_BEDAT","V_BEDTC")
datetime_columns <- NULL # c("")
table_name <- c("BEBIOMRKR_UNION")
BEBIOMRKR_EDC <- Convert_Date_Vals(BEBIOMRKR_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
BEBIOMRKR_EDC <- BEBIOMRKR_EDC[names(BEBIOMRKR_CDB)]

# Post processing for compare
BEBIOMRKR_EDC$DLASTMOD <- substring(BEBIOMRKR_EDC$DLASTMOD,1,16)
BEBIOMRKR_EDC$V_BETIM <- substring(BEBIOMRKR_EDC$V_BETIM,1,5)
BEBIOMRKR_EDC <- BEBIOMRKR_EDC %>% mutate_if(is.character, ~replace_na(.,""))
BEBIOMRKR_EDC <- BEBIOMRKR_EDC %>% mutate(across(everything(), as.character))
BEBIOMRKR_EDC <- BEBIOMRKR_EDC[order(BEBIOMRKR_EDC$STUDYID,BEBIOMRKR_EDC$COUNTRY,BEBIOMRKR_EDC$SITENUM,BEBIOMRKR_EDC$SUBJID,BEBIOMRKR_EDC$VISITNUM,BEBIOMRKR_EDC$VISITDT,BEBIOMRKR_EDC$FORMID,as.integer(BEBIOMRKR_EDC$FORMSEQ),as.integer(BEBIOMRKR_EDC$IGSEQ)), ]

#Generate Compare Summary Report
# BEBIOMRKR_EDC <- BEBIOMRKR_EDC %>% mutate(across(everything(), as.character))
# BEBIOMRKR_CDB <- BEBIOMRKR_CDB %>% mutate(across(everything(), as.character))
BEBIOMRKR_SUMMARY <- capture.output(summary(comparedf(BEBIOMRKR_EDC, BEBIOMRKR_CDB)))
print(BEBIOMRKR_SUMMARY)

#Export Summary Report
addWorksheet(wb, "BEBIOMRKR_SUMMARY")
writeData(wb, sheet = "BEBIOMRKR_SUMMARY", x = BEBIOMRKR_SUMMARY)

#Export QC Datasets
write_xpt(BEBIOMRKR_EDC,"QC Output/Datasets/EDC/BEBIOMRKR_EDC.xpt")
write_xpt(BEBIOMRKR_CDB,"QC Output/Datasets/CDB/BEBIOMRKR_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)