rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
BECTDNA_CDB <- bectdna
# Post processing for compare
BECTDNA_CDB <- BECTDNA_CDB %>% mutate(across(everything(), as.character))
BECTDNA_CDB$DLASTMOD <- substring(BECTDNA_CDB$DLASTMOD,1,16)
BECTDNA_CDB <- BECTDNA_CDB %>% mutate_if(is.character, ~replace_na(.,""))
BECTDNA_CDB <- BECTDNA_CDB[order(BECTDNA_CDB$STUDYID,BECTDNA_CDB$COUNTRY,BECTDNA_CDB$SITENUM,BECTDNA_CDB$SUBJID,BECTDNA_CDB$VISITNUM,BECTDNA_CDB$VISITDT,BECTDNA_CDB$VISITDT,BECTDNA_CDB$EGID,as.integer(BECTDNA_CDB$FORMSEQ),as.integer(BECTDNA_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

BE_CTDNA_01 <- be_ctdna_01
BE_CTDNA_01 <- BE_CTDNA_01 %>% mutate(across(everything(), as.character))
BE_CTDNA_01 <- BE_CTDNA_01 %>% mutate_if(is.character, ~replace_na(.,""))

BE_CTDNA_02 <- be_ctdna_02
BE_CTDNA_02 <- BE_CTDNA_02 %>% mutate(across(everything(), as.character))
BE_CTDNA_02 <- BE_CTDNA_02 %>% mutate_if(is.character, ~replace_na(.,""))

BE_CTDNAUNS_01 <- be_ctdnauns_01
BE_CTDNAUNS_01 <- BE_CTDNAUNS_01 %>% mutate(across(everything(), as.character))
BE_CTDNAUNS_01 <- BE_CTDNAUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))




# BE_CTDNAUNS_01<- create_function(BE_CTDNA_01, "DV_QVAL_BETPT_D")
# 

#-----------  FINAL union query--
BECTDNA_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_CTDNA_01.COUNTRY  'COUNTRY'
,BE_CTDNA_01.SITENUM  'SITENUM'
,BE_CTDNA_01.SUBJID  'SUBJID'
,S1.STATUS  'SUBJSTATUS'
,BE_CTDNA_01.EGROUPDEF  'EGID'
,BE_CTDNA_01.ESEQ  'EGSEQ'
,CASE BE_CTDNA_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN BE_CTDNA_01.EGROUP||' '||BE_CTDNA_01.EVENT
   ELSE BE_CTDNA_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN BE_CTDNA_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_CTDNA_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_CTDNA_01.EVENTEID= 'ev_DAY1' THEN BE_CTDNA_01.ESEQ + 0.01
WHEN BE_CTDNA_01.EVENTEID= 'ev_DAY8' THEN BE_CTDNA_01.ESEQ + 0.08
WHEN BE_CTDNA_01.EVENTEID= 'ev_DAY15' THEN BE_CTDNA_01.ESEQ + 0.15
WHEN BE_CTDNA_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_CTDNA_01.ESEQ * 0.01
WHEN BE_CTDNA_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_CTDNA_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_CTDNA_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_CTDNA_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_CTDNA_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_CTDNA_01.ESEQ * 0.01
WHEN BE_CTDNA_01.EVENTEID= 'ev_LFU' THEN 80 + BE_CTDNA_01.ESEQ * 0.01
WHEN BE_CTDNA_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_CTDNA_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_CTDNA_01.EVENTEID= 'ev_UNS' THEN 99 + BE_CTDNA_01.ESEQ * 0.01
ELSE BE_CTDNA_01.EVENTEID
END as 'VISITNUM'

,BE_CTDNA_01.EVENTDT  'VISITDT'
,BE_CTDNA_01.FORM  'FORM'
,BE_CTDNA_01.FORMDEF  'FORMID'
,BE_CTDNA_01.FSEQ  'FORMSEQ'
,CASE BE_CTDNA_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE BE_CTDNA_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,BE_CTDNA_01.IGSEQ  'IGSEQ'
,BE_CTDNA_01.DLASTMOD  'DLASTMOD'
,BE_CTDNA_01.DV_BESCAT  'V_BESCAT'
,BE_CTDNA_01.V_QVAL_BEOCCUR  'V_QVAL_BEOCCUR'
,BE_CTDNA_01.V_QVAL_BEREASND  'V_QVAL_BEREASND'
,BE_CTDNA_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
,CASE BE_CTDNA_01.DV_QVAL_BETPT 
WHEN '0.0' THEN '0'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '3.0' THEN '3'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
ELSE  BE_CTDNA_01.DV_QVAL_BETPT
END AS 'V_QVAL_BETPTNUM'
,BE_CTDNA_01.DV_QVAL_BETPT_D 'V_QVAL_BETPT'
,BE_CTDNA_01.DV_QVAL_BETPTREF  'V_QVAL_BETPTREF'
,BE_CTDNA_01.V_QVAL_BESTAT  'V_QVAL_BESTAT'
,BE_CTDNA_01.V_BEDTC  'V_BEDTC'
,BE_CTDNA_01.V_BEDTC_DT  'V_BEDAT'
,BE_CTDNA_01.V_BEDTC_TM  'V_BETIM'
,BE_CTDNA_01.V_BEDTC  'X_BEDTC'
,BE_CTDNA_01.V_BEDTC_DT  'X_BEDAT'
,BE_CTDNA_01.V_BEDTC_TM  'X_BETIM'
FROM
              BE_CTDNA_01 BE_CTDNA_01,
              SUBJECTS S1
WHERE
              S1.SUBJID=BE_CTDNA_01.SUBJID
              AND S1.SITENUM=BE_CTDNA_01.SITENUM
              AND BE_CTDNA_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
              AND BE_CTDNA_01.FORMILB !='true'
   
UNION
SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,BE_CTDNA_02.COUNTRY  'COUNTRY'
,BE_CTDNA_02.SITENUM  'SITENUM'
,BE_CTDNA_02.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,BE_CTDNA_02.EGROUPDEF  'EGID'
,BE_CTDNA_02.ESEQ  'EGSEQ'
,CASE BE_CTDNA_02.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN BE_CTDNA_02.EGROUP||' '||BE_CTDNA_02.EVENT
   ELSE BE_CTDNA_02.EVENT
   END AS 'VISIT'
,CASE 
WHEN BE_CTDNA_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_CTDNA_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_CTDNA_02.EVENTEID= 'ev_DAY1' THEN BE_CTDNA_02.ESEQ + 0.01
WHEN BE_CTDNA_02.EVENTEID= 'ev_DAY8' THEN BE_CTDNA_02.ESEQ + 0.08
WHEN BE_CTDNA_02.EVENTEID= 'ev_DAY15' THEN BE_CTDNA_02.ESEQ + 0.15
WHEN BE_CTDNA_02.EVENTEID= 'ev_TUPB' THEN 41 + BE_CTDNA_02.ESEQ * 0.01
WHEN BE_CTDNA_02.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_CTDNA_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_CTDNA_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_CTDNA_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_CTDNA_02.EVENTEID= 'ev_PTFU' THEN 75 + BE_CTDNA_02.ESEQ * 0.01
WHEN BE_CTDNA_02.EVENTEID= 'ev_LFU' THEN 80 + BE_CTDNA_02.ESEQ * 0.01
WHEN BE_CTDNA_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_CTDNA_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_CTDNA_02.EVENTEID= 'ev_UNS' THEN 99 + BE_CTDNA_02.ESEQ * 0.01
ELSE BE_CTDNA_02.EVENTEID
END as 'VISITNUM'
    
,BE_CTDNA_02.EVENTDT  'VISITDT'
,BE_CTDNA_02.FORM  'FORM'
,BE_CTDNA_02.FORMDEF  'FORMID'
,BE_CTDNA_02.FSEQ  'FORMSEQ'
,CASE BE_CTDNA_02.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE BE_CTDNA_02.FORMSTATUS
	   END AS 'FORMSTATUS'
,BE_CTDNA_02.IGSEQ  'IGSEQ'
,BE_CTDNA_02.DLASTMOD  'DLASTMOD'
,BE_CTDNA_02.DV_BESCAT  'V_BESCAT'
,BE_CTDNA_02.V_QVAL_BEOCCUR  'V_QVAL_BEOCCUR'
,BE_CTDNA_02.V_QVAL_BEREASND  'V_QVAL_BEREASND'
,BE_CTDNA_02.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
,NULL 'V_QVAL_BETPTNUM'
,NULL 'V_QVAL_BETPT'
,NULL 'V_QVAL_BETPTREF'
,NULL'V_QVAL_BESTAT'
,BE_CTDNA_02.V_BEDTC 'V_BEDTC'
,BE_CTDNA_02.V_BEDTC_DT   'V_BEDAT_DT'
,BE_CTDNA_02.V_BEDTC_TM  'V_BETIM'
,BE_CTDNA_02.V_BEDTC 'X_BEDTC'
,BE_CTDNA_02.V_BEDTC_DT   'X_BEDAT_DT'
,BE_CTDNA_02.V_BEDTC_TM  'X_BETIM'
FROM
BE_CTDNA_02 BE_CTDNA_02,
SUBJECTS S1
WHERE
              S1.SUBJID=BE_CTDNA_02.SUBJID
               AND S1.SITENUM=BE_CTDNA_02.SITENUM
              AND BE_CTDNA_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
              AND BE_CTDNA_02.FORMILB !='true'
    
UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_CTDNAUNS_01.COUNTRY  'COUNTRY'
,BE_CTDNAUNS_01.SITENUM  'SITENUM'
,BE_CTDNAUNS_01.SUBJID  'SUBJID'
,S1.STATUS 'SUBJSTATUS'
,BE_CTDNAUNS_01.EGROUPDEF  'EGID'
,BE_CTDNAUNS_01.ESEQ  'EGSEQ'
,CASE BE_CTDNAUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN BE_CTDNAUNS_01.EGROUP||' '||BE_CTDNAUNS_01.EVENT
   ELSE BE_CTDNAUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_DAY1' THEN BE_CTDNAUNS_01.ESEQ + 0.01
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_DAY8' THEN BE_CTDNAUNS_01.ESEQ + 0.08
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_DAY15' THEN BE_CTDNAUNS_01.ESEQ + 0.15
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_CTDNAUNS_01.ESEQ * 0.01
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_CTDNAUNS_01.ESEQ * 0.01
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_LFU' THEN 80 + BE_CTDNAUNS_01.ESEQ * 0.01
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_CTDNAUNS_01.EVENTEID= 'ev_UNS' THEN 99 + BE_CTDNAUNS_01.ESEQ * 0.01
ELSE BE_CTDNAUNS_01.EVENTEID
END as 'VISITNUM'
,BE_CTDNAUNS_01.EVENTDT  'VISITDT'
,BE_CTDNAUNS_01.FORM  'FORM'
,BE_CTDNAUNS_01.FORMDEF  'FORMID'
,BE_CTDNAUNS_01.FSEQ  'FORMSEQ'
,CASE BE_CTDNAUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE BE_CTDNAUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,BE_CTDNAUNS_01.IGSEQ  'IGSEQ'
,BE_CTDNAUNS_01.DLASTMOD  'DLASTMOD'
,BE_CTDNAUNS_01.DV_BESCAT  'V_BESCAT'
,NULL 'V_QVAL_BEOCCUR'
,NULL  'V_QVAL_BEREASND'
,BE_CTDNAUNS_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
,NULL 'V_QVAL_BETPTNUM'
,NULL 'V_QVAL_BETPT'
,NULL 'V_QVAL_BETPTREF'
,NULL'V_QVAL_BESTAT'
,BE_CTDNAUNS_01.V_BEDTC 'V_BEDTC'
,BE_CTDNAUNS_01.V_BEDTC_DT   'V_BEDAT_DT'
,BE_CTDNAUNS_01.V_BEDTC_TM  'V_BETIM'
,BE_CTDNAUNS_01.V_BEDTC 'X_BEDTC'
,BE_CTDNAUNS_01.V_BEDTC_DT   'X_BEDAT_DT'
,BE_CTDNAUNS_01.V_BEDTC_TM  'X_BETIM'
FROM
BE_CTDNAUNS_01 BE_CTDNAUNS_01,
SUBJECTS S1
WHERE
              S1.SUBJID=BE_CTDNAUNS_01.SUBJID
              AND S1.SITENUM=BE_CTDNAUNS_01.SITENUM
              AND BE_CTDNAUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit')
              AND BE_CTDNAUNS_01.FORMILB !='true'

  "
  )

# AND BE_CTDNA_01.FORMILB !='true'
# AND BE_CTDNA_02.FORMILB !='true'
# AND BE_CTDNAUNS_01.FORMILB !='true'
# Specify which columns to pass to the function
CharDate_Cols <- c("V_BEDTC","V_BEDAT")
datetime_columns <- NULL # c("")
table_name <- c("BECTDNA_UNION")
BECTDNA_EDC <- Convert_Date_Vals(BECTDNA_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
BECTDNA_EDC<-BECTDNA_EDC[names(BECTDNA_CDB)]

# Post processing for compare
BECTDNA_EDC$DLASTMOD <- substring(BECTDNA_EDC$DLASTMOD,1,16)
BECTDNA_EDC$V_BETIM <- substring(BECTDNA_EDC$V_BETIM,1,5)
BECTDNA_EDC <- BECTDNA_EDC %>% mutate_if(is.character, ~replace_na(.,""))
BECTDNA_EDC <- BECTDNA_EDC[order(BECTDNA_EDC$STUDYID,BECTDNA_EDC$COUNTRY,BECTDNA_EDC$SITENUM,BECTDNA_EDC$SUBJID,BECTDNA_EDC$VISITNUM,BECTDNA_EDC$VISITDT,BECTDNA_EDC$VISITDT,BECTDNA_EDC$EGID,as.integer(BECTDNA_EDC$FORMSEQ),as.integer(BECTDNA_EDC$IGSEQ)), ]

# BECTDNA_EDC <-BECTDNA_EDC %>% filter(SUBJID !="SCR-0009")
# BECTDNA_CDB <-BECTDNA_CDB %>% filter(SUBJID !="SCR-0009")
#Generate Compare Summary Report
BECTDNA_EDC <-BECTDNA_EDC %>% mutate(across(everything(), as.character))
BECTDNA_CDB <- BECTDNA_CDB %>% mutate(across(everything(), as.character))
BECTDNA_SUMMARY <- capture.output(summary(comparedf(BECTDNA_EDC, BECTDNA_CDB)))
print(BECTDNA_SUMMARY)

#Export Summary Report
addWorksheet(wb, "BECTDNA_SUMMARY")
writeData(wb, sheet = "BECTDNA_SUMMARY", x = BECTDNA_SUMMARY)

#Export QC Datasets
write_xpt(BECTDNA_EDC,"QC Output/Datasets/EDC/BECTDNA_EDC.xpt")
write_xpt(BECTDNA_CDB,"QC Output/Datasets/CDB/BECTDNA_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)