rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
BEDNA_CDB <- bedna
# Post processing for compare
BEDNA_CDB <- BEDNA_CDB %>% mutate(across(everything(), as.character))
BEDNA_CDB$DLASTMOD <- substring(BEDNA_CDB$DLASTMOD,1,16)
BEDNA_CDB <- BEDNA_CDB %>% mutate_if(is.character, ~replace_na(.,""))
BEDNA_CDB <- BEDNA_CDB[order(BEDNA_CDB$STUDYID,BEDNA_CDB$COUNTRY,BEDNA_CDB$SITENUM,BEDNA_CDB$SUBJID,BEDNA_CDB$VISITDT,BEDNA_CDB$FORMID,as.integer(BEDNA_CDB$FORMSEQ),as.integer(BEDNA_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

BE_DNA_01 <- be_dna_01
BE_DNA_01 <- BE_DNA_01 %>% mutate(across(everything(), as.character))
BE_DNA_01 <- BE_DNA_01 %>% mutate_if(is.character, ~replace_na(.,""))

BE_DNAUNS_01 <- be_dnauns_01
BE_DNAUNS_01 <- BE_DNAUNS_01 %>% mutate(across(everything(), as.character))
BE_DNAUNS_01 <- BE_DNAUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))


#-----------  FINAL union query--
BEDNA_UNION <-
  sqldf(
    "
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_DNA_01.COUNTRY  'COUNTRY'
,BE_DNA_01.SITENUM  'SITENUM'
,BE_DNA_01.SUBJID  'SUBJID'

,	 S1.STATUS 'SUBJSTATUS'
,BE_DNA_01.EGROUPDEF  'EGID'
,BE_DNA_01.ESEQ  'EGSEQ'
,CASE BE_DNA_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN BE_DNA_01.EGROUP||' '||BE_DNA_01.EVENT
ELSE BE_DNA_01.EVENT
END AS 'VISIT'
,CASE 
WHEN BE_DNA_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_DNA_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_DNA_01.EVENTEID= 'ev_DAY1' THEN BE_DNA_01.ESEQ + 0.01
WHEN BE_DNA_01.EVENTEID= 'ev_DAY8' THEN BE_DNA_01.ESEQ + 0.08
WHEN BE_DNA_01.EVENTEID= 'ev_DAY15' THEN BE_DNA_01.ESEQ + 0.15
WHEN BE_DNA_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_DNA_01.ESEQ * 0.01
WHEN BE_DNA_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_DNA_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_DNA_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_DNA_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_DNA_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_DNA_01.ESEQ * 0.01
WHEN BE_DNA_01.EVENTEID= 'ev_LFU' THEN 80 + BE_DNA_01.ESEQ * 0.01
WHEN BE_DNA_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_DNA_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_DNA_01.EVENTEID= 'ev_UNS' THEN 99 + BE_DNA_01.ESEQ * 0.01
ELSE BE_DNA_01.EVENTEID
END as 'VISITNUM'
,BE_DNA_01.EVENTDT  'VISITDT'
,BE_DNA_01.FORM  'FORM'
,BE_DNA_01.FORMDEF  'FORMID'
,BE_DNA_01.FSEQ  'FORMSEQ'
,CASE BE_DNA_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE BE_DNA_01.FORMSTATUS
END AS 'FORMSTATUS'
,BE_DNA_01.IGSEQ  'IGSEQ'
,BE_DNA_01.DLASTMOD  'DLASTMOD'
,BE_DNA_01.DV_BESCAT  'V_BESCAT'
,BE_DNA_01.V_QVAL_BEOCCUR  'V_QVAL_BEOCCUR'
,BE_DNA_01.V_QVAL_BEREASND  'V_QVAL_BEREASND'
,BE_DNA_01.DV_QVAL_BESPEC   'V_QVAL_BESPEC'
,CASE BE_DNA_01.DV_QVAL_BETPT 
WHEN '0.0' THEN '0'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '3.0' THEN '3'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
ELSE  BE_DNA_01.DV_QVAL_BETPT
END AS 'V_QVAL_BETPTNUM'
,BE_DNA_01.DV_QVAL_BETPT_D   'V_QVAL_BETPT'
,BE_DNA_01.DV_QVAL_BETPTREF   'V_QVAL_BETPTREF'
,BE_DNA_01.V_QVAL_BESTAT   'V_QVAL_BESTAT'
,BE_DNA_01.V_BEDTC   'V_BEDTC'
,BE_DNA_01.V_BEDTC_DT  'V_BEDAT'
,BE_DNA_01.V_BEDTC_TM  'V_BETIM'
,BE_DNA_01.V_BEDTC   'X_BEDTC'
,BE_DNA_01.V_BEDTC_DT  'X_BEDAT'
,BE_DNA_01.V_BEDTC_TM  'X_BETIM'
FROM
BE_DNA_01 BE_DNA_01,
SUBJECTS S1
WHERE
S1.SUBJID=BE_DNA_01.SUBJID
AND S1.SITENUM=BE_DNA_01.SITENUM
AND BE_DNA_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND BE_DNA_01.FORMILB !='true'
UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_DNAUNS_01.COUNTRY  'COUNTRY'
,BE_DNAUNS_01.SITENUM  'SITENUM'
,BE_DNAUNS_01.SUBJID  'SUBJID'

,	 S1.STATUS 'SUBJSTATUS'
,BE_DNAUNS_01.EGROUPDEF  'EGID'
,BE_DNAUNS_01.ESEQ  'EGSEQ'
,CASE BE_DNAUNS_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN BE_DNAUNS_01.EGROUP||' '||BE_DNAUNS_01.EVENT
ELSE BE_DNAUNS_01.EVENT
END AS 'VISIT'
,CASE 
WHEN BE_DNAUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_DNAUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_DNAUNS_01.EVENTEID= 'ev_DAY1' THEN BE_DNAUNS_01.ESEQ + 0.01
WHEN BE_DNAUNS_01.EVENTEID= 'ev_DAY8' THEN BE_DNAUNS_01.ESEQ + 0.08
WHEN BE_DNAUNS_01.EVENTEID= 'ev_DAY15' THEN BE_DNAUNS_01.ESEQ + 0.15
WHEN BE_DNAUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_DNAUNS_01.ESEQ * 0.01
WHEN BE_DNAUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_DNAUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_DNAUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_DNAUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_DNAUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_DNAUNS_01.ESEQ * 0.01
WHEN BE_DNAUNS_01.EVENTEID= 'ev_LFU' THEN 80 + BE_DNAUNS_01.ESEQ * 0.01
WHEN BE_DNAUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_DNAUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_DNAUNS_01.EVENTEID= 'ev_UNS' THEN 99 + BE_DNAUNS_01.ESEQ * 0.01
ELSE BE_DNAUNS_01.EVENTEID
END as 'VISITNUM'
,BE_DNAUNS_01.EVENTDT  'VISITDT'
,BE_DNAUNS_01.FORM  'FORM'
,BE_DNAUNS_01.FORMDEF  'FORMID'
,BE_DNAUNS_01.FSEQ  'FORMSEQ'
,CASE BE_DNAUNS_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE BE_DNAUNS_01.FORMSTATUS
END AS 'FORMSTATUS'
,BE_DNAUNS_01.IGSEQ  'IGSEQ'
,BE_DNAUNS_01.DLASTMOD  'DLASTMOD'
,BE_DNAUNS_01.DV_BESCAT  'V_BESCAT'
,NULL  'V_QVAL_BEOCCUR'
,NULL  'V_QVAL_BEREASND'
,BE_DNAUNS_01.DV_QVAL_BESPEC   'V_QVAL_BESPEC'
,NULL   'V_QVAL_BETPTNUM'
,NULL   'V_QVAL_BETPT'
,NULL   'V_QVAL_BETPTREF'
,NULL  'V_QVAL_BESTAT'
,BE_DNAUNS_01.V_BEDTC   'V_BEDTC'
,BE_DNAUNS_01.V_BEDTC_DT  'V_BEDAT'
,BE_DNAUNS_01.V_BEDTC_TM  'V_BETIM'
,BE_DNAUNS_01.V_BEDTC   'X_BEDTC'
,BE_DNAUNS_01.V_BEDTC_DT  'X_BEDAT'
,BE_DNAUNS_01.V_BEDTC_TM  'X_BETIM'
FROM
BE_DNAUNS_01 BE_DNAUNS_01,
SUBJECTS S1
WHERE
S1.SUBJID=BE_DNAUNS_01.SUBJID
AND S1.SITENUM=BE_DNAUNS_01.SITENUM
AND BE_DNAUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND BE_DNAUNS_01.FORMILB !='true'
")


# AND BE_DNA_01.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <-  c("V_BEDTC","V_BEDAT")
datetime_columns <-NULL
table_name <- c("BEDNA_UNION")
BEDNA_EDC <- Convert_Date_Vals(BEDNA_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
BEDNA_EDC <- BEDNA_EDC[names(BEDNA_CDB)]

# Post processing for compare
rownames(BEDNA_EDC) <- NULL
BEDNA_EDC$DLASTMOD <- substring(BEDNA_EDC$DLASTMOD,1,16)
BEDNA_EDC$V_BETIM <- substring(BEDNA_EDC$V_BETIM,1,5)
BEDNA_EDC <- BEDNA_EDC %>% mutate_if(is.character, ~replace_na(.,""))
BEDNA_EDC <- BEDNA_EDC[order(BEDNA_EDC$STUDYID,BEDNA_EDC$COUNTRY,BEDNA_EDC$SITENUM,BEDNA_EDC$SUBJID,BEDNA_EDC$VISITDT,BEDNA_EDC$FORMID,as.integer(BEDNA_EDC$FORMSEQ),as.integer(BEDNA_EDC$IGSEQ)), ]

#Generate Compare Summary Report
BEDNA_EDC <- BEDNA_EDC %>% mutate(across(everything(), as.character))
BEDNA_CDB <- BEDNA_CDB %>% mutate(across(everything(), as.character))
BEDNA_SUMMARY <- capture.output(summary(comparedf(BEDNA_EDC, BEDNA_CDB)))
print(BEDNA_SUMMARY)

#Export Summary Report
addWorksheet(wb, "BEDNA_SUMMARY")
writeData(wb, sheet = "BEDNA_SUMMARY", x = BEDNA_SUMMARY)

#Export QC Datasets
write_xpt(BEDNA_EDC,"QC Output/Datasets/EDC/BEDNA_EDC.xpt")
write_xpt(BEDNA_CDB,"QC Output/Datasets/CDB/BEDNA_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)