rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
BERNA_CDB <- berna
# Post processing for compare
BERNA_CDB <- BERNA_CDB %>% mutate(across(everything(), as.character))
BERNA_CDB$DLASTMOD <- substring(BERNA_CDB$DLASTMOD,1,16)
BERNA_CDB <- BERNA_CDB %>% mutate_if(is.character, ~replace_na(.,""))
BERNA_CDB <- BERNA_CDB[order(BERNA_CDB$STUDYID,BERNA_CDB$COUNTRY,BERNA_CDB$SITENUM,BERNA_CDB$SUBJID,BERNA_CDB$VISITDT,BERNA_CDB$FORMID,as.integer(BERNA_CDB$FORMSEQ),as.integer(BERNA_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

BE_RNA_01 <- be_rna_01
BE_RNA_01 <- BE_RNA_01 %>% mutate(across(everything(), as.character))
BE_RNA_01 <- BE_RNA_01 %>% mutate_if(is.character, ~replace_na(.,""))

BE_RNAUNS_01 <- be_rnauns_01
BE_RNAUNS_01 <- BE_RNAUNS_01 %>% mutate(across(everything(), as.character))
BE_RNAUNS_01 <- BE_RNAUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))




#-----------  FINAL union query--
BERNA_UNION <-
  sqldf(
    "SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_RNA_01.COUNTRY  'COUNTRY'
,BE_RNA_01.SITENUM  'SITENUM'
,BE_RNA_01.SUBJID  'SUBJID'
,S1.STATUS 'SUBJSTATUS'
,BE_RNA_01.EGROUPDEF  'EGID'
,BE_RNA_01.ESEQ  'EGSEQ'
,CASE BE_RNA_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN BE_RNA_01.EGROUP||' '||BE_RNA_01.EVENT
ELSE BE_RNA_01.EVENT
END AS 'VISIT'
,CASE 
WHEN BE_RNA_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_RNA_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_RNA_01.EVENTEID= 'ev_DAY1' THEN BE_RNA_01.ESEQ + 0.01
WHEN BE_RNA_01.EVENTEID= 'ev_DAY8' THEN BE_RNA_01.ESEQ + 0.08
WHEN BE_RNA_01.EVENTEID= 'ev_DAY15' THEN BE_RNA_01.ESEQ + 0.15
WHEN BE_RNA_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_RNA_01.ESEQ * 0.01
WHEN BE_RNA_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_RNA_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_RNA_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_RNA_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_RNA_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_RNA_01.ESEQ * 0.01
WHEN BE_RNA_01.EVENTEID= 'ev_LFU' THEN 80 + BE_RNA_01.ESEQ * 0.01
WHEN BE_RNA_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_RNA_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_RNA_01.EVENTEID= 'ev_UNS' THEN 99 + BE_RNA_01.ESEQ * 0.01
ELSE BE_RNA_01.EVENTEID
END as 'VISITNUM'

,BE_RNA_01.EVENTDT  'VISITDT'
,BE_RNA_01.FORM  'FORM'
,BE_RNA_01.FORMDEF  'FORMID'
,BE_RNA_01.FSEQ  'FORMSEQ'
,CASE BE_RNA_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE BE_RNA_01.FORMSTATUS
END AS 'FORMSTATUS'
,BE_RNA_01.IGSEQ  'IGSEQ'
,BE_RNA_01.DLASTMOD  'DLASTMOD'
,BE_RNA_01.DV_BESCAT 'V_BESCAT'
,BE_RNA_01.V_QVAL_BEOCCUR   'V_QVAL_BEOCCUR'
,BE_RNA_01.V_QVAL_BEREASND   'V_QVAL_BEREASND'
,BE_RNA_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'
,CASE BE_RNA_01.DV_QVAL_BETPT 
WHEN '0.0' THEN '0'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '3.0' THEN '3'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
ELSE  BE_RNA_01.DV_QVAL_BETPT
END AS 'V_QVAL_BETPTNUM'
,BE_RNA_01.DV_QVAL_BETPT_D   'V_QVAL_BETPT'
,BE_RNA_01.DV_QVAL_BETPTREF   'V_QVAL_BETPTREF'
,BE_RNA_01.V_QVAL_BESTAT  'V_QVAL_BESTAT'
,BE_RNA_01.V_BEDTC  'V_BEDTC'
,BE_RNA_01.V_BEDTC_DT  'V_BEDAT'
,BE_RNA_01.V_BEDTC_TM 'V_BETIM'
,BE_RNA_01.V_BEDTC  'X_BEDTC'
,BE_RNA_01.V_BEDTC_DT  'X_BEDAT'
,BE_RNA_01.V_BEDTC_TM 'X_BETIM'
FROM
BE_RNA_01 BE_RNA_01,
SUBJECTS S1
WHERE
S1.SUBJID=BE_RNA_01.SUBJID
AND S1.SITENUM=BE_RNA_01.SITENUM
AND BE_RNA_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND BE_RNA_01.FORMILB !='true'


UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_RNAUNS_01.COUNTRY  'COUNTRY'
,BE_RNAUNS_01.SITENUM  'SITENUM'
,BE_RNAUNS_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,BE_RNAUNS_01.EGROUPDEF  'EGID'
,BE_RNAUNS_01.ESEQ  'EGSEQ'
,CASE BE_RNAUNS_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN BE_RNAUNS_01.EGROUP||' '||BE_RNAUNS_01.EVENT
ELSE BE_RNAUNS_01.EVENT
END AS 'VISIT'
,CASE 
WHEN BE_RNAUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_RNAUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_RNAUNS_01.EVENTEID= 'ev_DAY1' THEN BE_RNAUNS_01.ESEQ + 0.01
WHEN BE_RNAUNS_01.EVENTEID= 'ev_DAY8' THEN BE_RNAUNS_01.ESEQ + 0.08
WHEN BE_RNAUNS_01.EVENTEID= 'ev_DAY15' THEN BE_RNAUNS_01.ESEQ + 0.15
WHEN BE_RNAUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_RNAUNS_01.ESEQ * 0.01
WHEN BE_RNAUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_RNAUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_RNAUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_RNAUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_RNAUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_RNAUNS_01.ESEQ * 0.01
WHEN BE_RNAUNS_01.EVENTEID= 'ev_LFU' THEN 80 + BE_RNAUNS_01.ESEQ * 0.01
WHEN BE_RNAUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_RNAUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_RNAUNS_01.EVENTEID= 'ev_UNS' THEN 99 + BE_RNAUNS_01.ESEQ * 0.01
ELSE BE_RNAUNS_01.EVENTEID
END as 'VISITNUM'
,BE_RNAUNS_01.EVENTDT  'VISITDT'
,BE_RNAUNS_01.FORM  'FORM'
,BE_RNAUNS_01.FORMDEF  'FORMID'
,BE_RNAUNS_01.FSEQ  'FORMSEQ'
,CASE BE_RNAUNS_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE BE_RNAUNS_01.FORMSTATUS
END AS 'FORMSTATUS'
,BE_RNAUNS_01.IGSEQ  'IGSEQ'
,BE_RNAUNS_01.DLASTMOD  'DLASTMOD'
,BE_RNAUNS_01.DV_BESCAT 'V_BESCAT'
,NULL   'V_QVAL_BEOCCUR'
,NULL 'V_QVAL_BEREASND'
,BE_RNAUNS_01.DV_QVAL_BESPEC  'V_QVAL_BESPEC'

,NULL  'V_QVAL_BETPTNUM'
,NULL 'V_QVAL_BETPT'
,NULL 'V_QVAL_BETPTREF'
,NULL 'V_QVAL_BESTAT'
,BE_RNAUNS_01.V_BEDTC  'V_BEDTC'
,BE_RNAUNS_01.V_BEDTC_DT  'V_BEDAT'
,BE_RNAUNS_01.V_BEDTC_TM  'V_BETIM'
,BE_RNAUNS_01.V_BEDTC  'X_BEDTC'
,BE_RNAUNS_01.V_BEDTC_DT  'X_BEDAT'
,BE_RNAUNS_01.V_BEDTC_TM  'X_BETIM'
FROM
BE_RNAUNS_01 BE_RNAUNS_01,
SUBJECTS S1
WHERE
S1.SUBJID=BE_RNAUNS_01.SUBJID
AND S1.SITENUM=BE_RNAUNS_01.SITENUM
AND BE_RNAUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND BE_RNAUNS_01.FORMILB !='true'

")

# AND BE_RNA_01.FORMILB !='true'
# AND BE_RNAUNS_01.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <-  c("V_BEDTC","V_BEDAT")
datetime_columns <-NULL
table_name <- c("BERNA_UNION")
BERNA_EDC <- Convert_Date_Vals(BERNA_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
BERNA_EDC <- BERNA_EDC[names(BERNA_CDB)]

# Post processing for compare
rownames(BERNA_EDC) <- NULL
BERNA_EDC$DLASTMOD <- substring(BERNA_EDC$DLASTMOD,1,16)
BERNA_EDC$V_BETIM <- substring(BERNA_EDC$V_BETIM,1,5)
BERNA_EDC <- BERNA_EDC %>% mutate_if(is.character, ~replace_na(.,""))
BERNA_EDC <- BERNA_EDC[order(BERNA_EDC$STUDYID,BERNA_EDC$COUNTRY,BERNA_EDC$SITENUM,BERNA_EDC$SUBJID,BERNA_EDC$VISITDT,BERNA_EDC$FORMID,as.integer(BERNA_EDC$FORMSEQ),as.integer(BERNA_EDC$IGSEQ)), ]

#RNArate Compare Summary Report
BERNA_EDC <- BERNA_EDC %>% mutate(across(everything(), as.character))
BERNA_CDB <- BERNA_CDB %>% mutate(across(everything(), as.character))
BERNA_SUMMARY <- capture.output(summary(comparedf(BERNA_EDC, BERNA_CDB)))
print(BERNA_SUMMARY)

#Export Summary Report
addWorksheet(wb, "BERNA_SUMMARY")
writeData(wb, sheet = "BERNA_SUMMARY", x = BERNA_SUMMARY)

#Export QC Datasets
write_xpt(BERNA_EDC,"QC Output/Datasets/EDC/BERNA_EDC.xpt")
write_xpt(BERNA_CDB,"QC Output/Datasets/CDB/BERNA_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)