rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
BETTS_CDB <- betts
# Post processing for compare
BETTS_CDB <- BETTS_CDB %>% mutate(across(everything(), as.character))
BETTS_CDB$DLASTMOD <- substring(BETTS_CDB$DLASTMOD,1,16)
BETTS_CDB <- BETTS_CDB %>% mutate_if(is.character, ~replace_na(.,""))
BETTS_CDB <- BETTS_CDB[order(BETTS_CDB$STUDYID,BETTS_CDB$COUNTRY,BETTS_CDB$SITENUM,BETTS_CDB$SUBJID,BETTS_CDB$VISITNUM,BETTS_CDB$VISITDT,BETTS_CDB$FORMID,as.integer(BETTS_CDB$FORMSEQ),as.integer(BETTS_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

BE_TTS_01 <- be_tts_01
BE_TTS_01 <- BE_TTS_01 %>% mutate(across(everything(), as.character))
BE_TTS_01 <- BE_TTS_01 %>% mutate_if(is.character, ~replace_na(.,""))


#-----------  FINAL union query--
BETTS_UNION <-
  sqldf(
    "SELECT

'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,BE_TTS_01.COUNTRY  'COUNTRY'
,BE_TTS_01.SITENUM  'SITENUM'
,BE_TTS_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,BE_TTS_01.EGROUPDEF  'EGID'
,BE_TTS_01.ESEQ  'EGSEQ'
,CASE BE_TTS_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN BE_TTS_01.EGROUP||' '||BE_TTS_01.EVENT
ELSE BE_TTS_01.EVENT
END AS 'VISIT'
,CASE 
WHEN BE_TTS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN BE_TTS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN BE_TTS_01.EVENTEID= 'ev_DAY1' THEN BE_TTS_01.ESEQ + 0.01
WHEN BE_TTS_01.EVENTEID= 'ev_DAY8' THEN BE_TTS_01.ESEQ + 0.08
WHEN BE_TTS_01.EVENTEID= 'ev_DAY15' THEN BE_TTS_01.ESEQ + 0.15
WHEN BE_TTS_01.EVENTEID= 'ev_TUPB' THEN 41 + BE_TTS_01.ESEQ * 0.01
WHEN BE_TTS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN BE_TTS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN BE_TTS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN BE_TTS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN BE_TTS_01.EVENTEID= 'ev_PTFU' THEN 75 + BE_TTS_01.ESEQ * 0.01
WHEN BE_TTS_01.EVENTEID= 'ev_LFU' THEN 80 + BE_TTS_01.ESEQ * 0.01
WHEN BE_TTS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN BE_TTS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN BE_TTS_01.EVENTEID= 'ev_UNS' THEN 99 + BE_TTS_01.ESEQ * 0.01
ELSE BE_TTS_01.EVENTEID
END as 'VISITNUM'
,BE_TTS_01.EVENTDT  'VISITDT'
,BE_TTS_01.FORM  'FORM'
,BE_TTS_01.FORMDEF  'FORMID'
,BE_TTS_01.FSEQ  'FORMSEQ'
,CASE BE_TTS_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE BE_TTS_01.FORMSTATUS
END AS 'FORMSTATUS'
,BE_TTS_01.IGSEQ  'IGSEQ'
,BE_TTS_01.DLASTMOD  'DLASTMOD'
,BE_TTS_01.DV_BESCAT  'V_BESCAT'
,BE_TTS_01.V_QVAL_BEOCCUR 'V_QVAL_BEOCCUR'
,BE_TTS_01.V_QVAL_BEREASND 'V_QVAL_BEREASND'
,BE_TTS_01.DV_QVAL_BESPEC 'V_QVAL_BESPEC'
,BE_TTS_01.V_QVAL_BESPCCND   'V_QVAL_BESPCCND'
,BE_TTS_01.V_BEDAT  'V_BEDAT'
,BE_TTS_01.V_BEDAT  'X_BEDAT'
,BE_TTS_01.V_BSORRES_TUMSAMOR  'V_BSORRES_TUMSAMOR'
,BE_TTS_01.V_BSORRES_TUMSAMOR_OTH  'V_BSORRES_TUMSMLSP'
FROM
BE_TTS_01 BE_TTS_01,
SUBJECTS S1
WHERE
S1.SUBJID=BE_TTS_01.SUBJID
AND S1.SITENUM=BE_TTS_01.SITENUM
AND BE_TTS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND BE_TTS_01.FORMILB !='true'

")

# AND BE_TTS_01.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <-  c("V_BEDAT")
datetime_columns <-NULL
table_name <- c("BETTS_UNION")
BETTS_EDC <- Convert_Date_Vals(BETTS_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
BETTS_EDC <- BETTS_EDC[names(BETTS_CDB)]

# Post processing for compare
rownames(BETTS_EDC) <- NULL
BETTS_EDC$DLASTMOD <- substring(BETTS_EDC$DLASTMOD,1,16)
BETTS_EDC <- BETTS_EDC %>% mutate_if(is.character, ~replace_na(.,""))
BETTS_EDC <- BETTS_EDC[order(BETTS_EDC$STUDYID,BETTS_EDC$COUNTRY,BETTS_EDC$SITENUM,BETTS_EDC$SUBJID,BETTS_EDC$VISITNUM,BETTS_EDC$VISITDT,BETTS_EDC$FORMID,as.integer(BETTS_EDC$FORMSEQ),as.integer(BETTS_EDC$IGSEQ)), ]

#TTSrate Compare Summary Report
BETTS_EDC <- BETTS_EDC %>% mutate(across(everything(), as.character))
BETTS_CDB <- BETTS_CDB %>% mutate(across(everything(), as.character))
BETTS_SUMMARY <- capture.output(summary(comparedf(BETTS_EDC, BETTS_CDB)))
print(BETTS_SUMMARY)

#Export Summary Report
addWorksheet(wb, "BETTS_SUMMARY")
writeData(wb, sheet = "BETTS_SUMMARY", x = BETTS_SUMMARY)

#Export QC Datasets
write_xpt(BETTS_EDC,"QC Output/Datasets/EDC/BETTS_EDC.xpt")
write_xpt(BETTS_CDB,"QC Output/Datasets/CDB/BETTS_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)