rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
CMATM_CDB <- cmatm
# Post processing for compare
CMATM_CDB <- CMATM_CDB %>% mutate(across(everything(), as.character))
CMATM_CDB$DLASTMOD <- substring(CMATM_CDB$DLASTMOD,1,16)
CMATM_CDB$CX_LASTCODEDAT <- substring(CMATM_CDB$CX_LASTCODEDAT,1,16)
CMATM_CDB <- CMATM_CDB %>% mutate_if(is.character, ~replace_na(.,""))
CMATM_CDB <- CMATM_CDB[order(CMATM_CDB$STUDYID,CMATM_CDB$COUNTRY,CMATM_CDB$SITENUM,CMATM_CDB$SUBJID,CMATM_CDB$VISITDT,CMATM_CDB$FORMID,as.integer(CMATM_CDB$FORMSEQ),as.integer(CMATM_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

CM_ATM_01 <- cm_atm_01
CM_ATM_01 <- CM_ATM_01 %>% mutate(across(everything(), as.character))
CM_ATM_01 <- CM_ATM_01 %>% mutate_if(is.character, ~replace_na(.,""))

CM_ATM_02 <- cm_atm_02
CM_ATM_02 <- CM_ATM_02 %>% mutate(across(everything(), as.character))
CM_ATM_02 <- CM_ATM_02 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--

CMATM_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,CM_ATM_01.COUNTRY  'COUNTRY'
,CM_ATM_01.SITENUM  'SITENUM'
,CM_ATM_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'

,CM_ATM_01.EGROUPDEF  'EGID'
,CM_ATM_01.ESEQ  'EGSEQ'
,CASE CM_ATM_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN CM_ATM_01.EGROUP||' '||CM_ATM_01.EVENT
   ELSE CM_ATM_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN CM_ATM_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN CM_ATM_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN CM_ATM_01.EVENTEID= 'ev_DAY1' THEN CM_ATM_01.ESEQ + 0.01
WHEN CM_ATM_01.EVENTEID= 'ev_DAY8' THEN CM_ATM_01.ESEQ + 0.08
WHEN CM_ATM_01.EVENTEID= 'ev_DAY15' THEN CM_ATM_01.ESEQ + 0.15
WHEN CM_ATM_01.EVENTEID= 'ev_TUPB' THEN 41 + CM_ATM_01.ESEQ * 0.01
WHEN CM_ATM_01.EVENTEID= 'ev_EOT' THEN 60
WHEN CM_ATM_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN CM_ATM_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN CM_ATM_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN CM_ATM_01.EVENTEID= 'ev_PTFU' THEN 75 + CM_ATM_01.ESEQ * 0.01
WHEN CM_ATM_01.EVENTEID= 'ev_LFU' THEN 80 + CM_ATM_01.ESEQ * 0.01
WHEN CM_ATM_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN CM_ATM_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN CM_ATM_01.EVENTEID= 'ev_UNS' THEN 99 + CM_ATM_01.ESEQ * 0.01
ELSE CM_ATM_01.EVENTEID
END as 'VISITNUM'
,CM_ATM_01.EVENTDT  'VISITDT'
,CM_ATM_01.FORM  'FORM'
,CM_ATM_01.FORMDEF  'FORMID'
,CM_ATM_01.FSEQ  'FORMSEQ'
,CASE CM_ATM_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  CM_ATM_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,CM_ATM_01.IGSEQ  'IGSEQ'
,CM_ATM_01.DLASTMOD  'DLASTMOD'
,CM_ATM_01.DV_CMCAT  'V_CMCAT'
,CM_ATM_01.DV_CMGRPID_ATM  'DV_CMGRPID_ATM'
,CM_ATM_01.V_CMSCAT_ATM  'V_CMSCAT_ATM'
,CM_ATM_01.V_CMSCAT_OTH  'V_CMSCAT_OTH'
,CM_ATM_01.V_CMSTDAT_ATM  'V_CMSTDAT_ATM'
,CM_ATM_01.V_CMSTDAT_ATM  'X_CMSTDAT_ATM'
,NULL  'V_CMONGO'
,CM_ATM_01.V_CMENDAT_ATM  'V_CMENDAT_ATM'
,CM_ATM_01.V_CMENDAT_ATM  'X_CMENDAT_ATM'
,CM_ATM_01.V_FAORRES_OCCUR_DISPRG  'V_FAORRES_OCCUR_DISPRG'
,CM_ATM_01.V_FADAT_DISPRG_ATM  'V_FADAT_DISPRG_ATM'
,CM_ATM_01.V_FADAT_DISPRG_ATM  'X_FADAT_DISPRG_ATM'
,NULL    'V_QVAL_LKNEVDAT'
,NULL    'X_QVAL_LKNEVDAT'
,CM_ATM_01.V_QVAL_CMTRTSET  'V_QVAL_CMTRTSET'
,CM_ATM_01.V_QVAL_TRTSETOT  'V_QVAL_TRTSETOT'
,CM_ATM_01.V_RSORRES_BESTRESP_ATM_D  'V_RSORRES_BESTRESP_ATM'
,CM_ATM_01.V_QVAL_EOTREAS_ATM  'V_QVAL_EOTREAS_ATM'
,CM_ATM_01.V_QVAL_EOTREAOT  'V_QVAL_EOTREAOT'
,CM_ATM_01.V_CMTRT_ATM  'V_CMTRT_ATM'
,CM_ATM_01.V_CMDOSU_ATM  'V_CMDOSU_ATM'
,CM_ATM_01.V_QVAL_DOSUOT  'V_QVAL_DOSUOT'
,CM_ATM_01.CRSTATUS  'CX_CRSTATUS'
,CM_ATM_01.DICTVER  'CV_QVAL_DICTVER'

,CM_ATM_01.PREFNAME  'CV_CMDECOD'
,CM_ATM_01.PREFCODE  'CV_QVAL_PREFCODE'

,CM_ATM_01.ATC1  'CV_QVAL_CMATC1'
,CM_ATM_01.ATC1CD  'CV_QVAL_CMATC1CD'
,CM_ATM_01.ATC2  'CV_QVAL_CMATC2'
,CM_ATM_01.ATC2CD  'CV_QVAL_CMATC2CD'
,CM_ATM_01.ATC3  'CV_QVAL_CMATC3'
,CM_ATM_01.ATC3CD  'CV_QVAL_CMATC3CD'
,CM_ATM_01.ATC4  'CV_QVAL_CMATC4'
,CM_ATM_01.ATC4CD  'CV_QVAL_CMATC4CD'
,CM_ATM_01.DRUGNAME  'CV_QVAL_DRUGNAME'
,CM_ATM_01.DRUGCODE  'CV_QVAL_DRUGCODE'
,CM_ATM_01.LASTCODEDAT  'CX_LASTCODEDAT'
,CM_ATM_01.LASTCODEDBY  'CX_LASTCODEDBY'
FROM
              CM_ATM_01 CM_ATM_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=CM_ATM_01.SUBJID
              AND S1.SITENUM=CM_ATM_01.SITENUM
              AND CM_ATM_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND CM_ATM_01.FORMILB !='true'
    
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,CM_ATM_02.COUNTRY  'COUNTRY'
,CM_ATM_02.SITENUM  'SITENUM'
,CM_ATM_02.SUBJID  'SUBJID'
,	S1.STATUS  'SUBJSTATUS'
,CM_ATM_02.EGROUPDEF  'EGID'
,CM_ATM_02.ESEQ  'EGSEQ'
,CASE CM_ATM_02.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN CM_ATM_02.EGROUP||' '||CM_ATM_02.EVENT
   ELSE CM_ATM_02.EVENT
   END AS 'VISIT'
,CASE 
WHEN CM_ATM_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN CM_ATM_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN CM_ATM_02.EVENTEID= 'ev_DAY1' THEN CM_ATM_02.ESEQ + 0.01
WHEN CM_ATM_02.EVENTEID= 'ev_DAY8' THEN CM_ATM_02.ESEQ + 0.08
WHEN CM_ATM_02.EVENTEID= 'ev_DAY15' THEN CM_ATM_02.ESEQ + 0.15
WHEN CM_ATM_02.EVENTEID= 'ev_TUPB' THEN 41 + CM_ATM_02.ESEQ * 0.01
WHEN CM_ATM_02.EVENTEID= 'ev_EOT' THEN 60
WHEN CM_ATM_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN CM_ATM_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN CM_ATM_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN CM_ATM_02.EVENTEID= 'ev_PTFU' THEN 75 + CM_ATM_02.ESEQ * 0.01
WHEN CM_ATM_02.EVENTEID= 'ev_LFU' THEN 80 + CM_ATM_02.ESEQ * 0.01
WHEN CM_ATM_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN CM_ATM_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN CM_ATM_02.EVENTEID= 'ev_UNS' THEN 99 + CM_ATM_02.ESEQ * 0.01
ELSE CM_ATM_02.EVENTEID
END as 'VISITNUM'

,CM_ATM_02.EVENTDT  'VISITDT'
,CM_ATM_02.FORM  'FORM'
,CM_ATM_02.FORMDEF  'FORMID'
,CM_ATM_02.FSEQ  'FORMSEQ'
,CASE CM_ATM_02.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  CM_ATM_02.FORMSTATUS
	   END AS 'FORMSTATUS'
,CM_ATM_02.IGSEQ  'IGSEQ'
,CM_ATM_02.DLASTMOD  'DLASTMOD'
,CM_ATM_02.DV_CMCAT  'V_CMCAT'
,CM_ATM_02.DV_CMGRPID_ATM  'DV_CMGRPID_ATM'
,CM_ATM_02.V_CMSCAT_ATM  'V_CMSCAT_ATM'
,CM_ATM_02.V_CMSCAT_OTH  'V_CMSCAT_OTH'
,CM_ATM_02.V_CMSTDAT_ATM  'V_CMSTDAT_ATM'
,CM_ATM_02.V_CMSTDAT_ATM  'X_CMSTDAT_ATM'
,CM_ATM_02.V_CMONGO  'V_CMONGO'
,CM_ATM_02.V_CMENDAT_ATM  'V_CMENDAT_ATM'
,CM_ATM_02.V_CMENDAT_ATM  'X_CMENDAT_ATM'
,CM_ATM_02.V_FAORRES_OCCUR_DISPRG  'V_FAORRES_OCCUR_DISPRG'
,CM_ATM_02.V_FADAT_DISPRG_ATM  'V_FADAT_DISPRG_ATM'
,CM_ATM_02.V_FADAT_DISPRG_ATM  'X_FADAT_DISPRG_ATM'
,CM_ATM_02.V_QVAL_LKNEVDAT   'V_QVAL_LKNEVDAT'
,CM_ATM_02.V_QVAL_LKNEVDAT   'X_QVAL_LKNEVDAT'
,CM_ATM_02.V_QVAL_CMTRTSET  'V_QVAL_CMTRTSET'
,CM_ATM_02.V_QVAL_TRTSETOT  'V_QVAL_TRTSETOT'
,CM_ATM_02.V_RSORRES_BESTRESP_ATM_D  'V_RSORRES_BESTRESP_ATM'
,CM_ATM_02.V_QVAL_EOTREAS_ATM  'V_QVAL_EOTREAS_ATM'
,CM_ATM_02.V_QVAL_EOTREAOT  'V_QVAL_EOTREAOT'
,CM_ATM_02.V_CMTRT_ATM  'V_CMTRT_ATM'
,CM_ATM_02.V_CMDOSU_ATM  'V_CMDOSU_ATM'
,CM_ATM_02.V_QVAL_DOSUOT  'V_QVAL_DOSUOT'

,CM_ATM_02.CRSTATUS  'CX_CRSTATUS'
,CM_ATM_02.DICTVER  'CV_QVAL_DICTVER'
,CM_ATM_02.PREFNAME  'CV_CMDECOD'
,CM_ATM_02.PREFCODE  'CV_QVAL_PREFCODE'


,CM_ATM_02.ATC1  'CV_QVAL_CMATC1'
,CM_ATM_02.ATC1CD  'CV_QVAL_CMATC1CD'
,CM_ATM_02.ATC2  'CV_QVAL_CMATC2'
,CM_ATM_02.ATC2CD  'CV_QVAL_CMATC2CD'
,CM_ATM_02.ATC3  'CV_QVAL_CMATC3'
,CM_ATM_02.ATC3CD  'CV_QVAL_CMATC3CD'
,CM_ATM_02.ATC4  'CV_QVAL_CMATC4'
,CM_ATM_02.ATC4CD  'CV_QVAL_CMATC4CD'

,CM_ATM_02.DRUGNAME  'CV_QVAL_DRUGNAME'
,CM_ATM_02.DRUGCODE  'CV_QVAL_DRUGCODE'
,CM_ATM_02.LASTCODEDAT  'CX_LASTCODEDAT'
,CM_ATM_02.LASTCODEDBY  'CX_LASTCODEDBY'
FROM
              CM_ATM_02 CM_ATM_02,
              SUBJECTS S1

              WHERE
              S1.SUBJID=CM_ATM_02.SUBJID
              AND  S1.SITENUM=CM_ATM_02.SITENUM
              AND CM_ATM_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND CM_ATM_02.FORMILB !='true'
   "
  )


# AND CM_ATM_01.FORMILB !='true'
# AND CM_ATM_02.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <- c("V_CMSTDAT_ATM","V_CMENDAT_ATM","V_FADAT_DISPRG_ATM","V_QVAL_LKNEVDAT")
datetime_columns <- NULL
table_name <- c("CMATM_UNION")
CMATM_EDC <- Convert_Date_Vals(CMATM_UNION, CharDate_Cols,datetime_columns,table_name)


# Arrange columns same as CDB
CMATM_EDC <- CMATM_EDC[names(CMATM_CDB)]

# Post processing for compare
CMATM_EDC$DLASTMOD <- substring(CMATM_EDC$DLASTMOD,1,16)
CMATM_EDC <- CMATM_EDC %>% mutate_if(is.character, ~replace_na(.,""))
CMATM_EDC <- CMATM_EDC[order(CMATM_EDC$STUDYID,CMATM_EDC$COUNTRY,CMATM_EDC$SITENUM,CMATM_EDC$SUBJID,CMATM_EDC$VISITDT,CMATM_EDC$FORMID,as.integer(CMATM_EDC$FORMSEQ),as.integer(CMATM_EDC$IGSEQ)), ]

#Generate Compare Summary Report
CMATM_EDC <- CMATM_EDC %>% mutate(across(everything(), as.character))
CMATM_CDB <- CMATM_CDB %>% mutate(across(everything(), as.character))
CMATM_SUMMARY <- capture.output(summary(comparedf(CMATM_EDC, CMATM_CDB)))
CMATM_SUMMARY

#Export Summary Report
addWorksheet(wb, "CMATM_SUMMARY")
writeData(wb, sheet = "CMATM_SUMMARY", x = CMATM_SUMMARY)

#Export QC Datasets
write_xpt(CMATM_EDC,"QC Output/Datasets/EDC/CMATM_EDC.xpt")
write_xpt(CMATM_CDB,"QC Output/Datasets/CDB/CMATM_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)