rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
CMGEN_CDB <- cmgen

# Post processing for compare
CMGEN_CDB <- CMGEN_CDB %>% mutate(across(everything(), as.character))
CMGEN_CDB$DLASTMOD <- substring(CMGEN_CDB$DLASTMOD,1,16)
CMGEN_CDB$CX_LASTCODEDAT <- substring(CMGEN_CDB$CX_LASTCODEDAT,1,16)
CMGEN_CDB <- CMGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))
CMGEN_CDB <- CMGEN_CDB[order(CMGEN_CDB$STUDYID,CMGEN_CDB$COUNTRY,CMGEN_CDB$SITENUM,CMGEN_CDB$SUBJID,CMGEN_CDB$VISITDT,CMGEN_CDB$FORMID,as.integer(CMGEN_CDB$FORMSEQ),as.integer(CMGEN_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

CM_GEN_01 <- cm_gen_01
CM_GEN_01 <- CM_GEN_01 %>% mutate(across(everything(), as.character))
CM_GEN_01 <- CM_GEN_01 %>% mutate_if(is.character, ~replace_na(.,""))



#-----------  FINAL union query--
CMGEN_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,CM_GEN_01.COUNTRY  'COUNTRY'
,CM_GEN_01.SITENUM  'SITENUM'
,CM_GEN_01.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'

,CM_GEN_01.EGROUPDEF  'EGID'
,CM_GEN_01.ESEQ  'EGSEQ'
,CASE CM_GEN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN CM_GEN_01.EGROUP||' '||CM_GEN_01.EVENT
   ELSE CM_GEN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN CM_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN CM_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN CM_GEN_01.EVENTEID= 'ev_DAY1' THEN CM_GEN_01.ESEQ + 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_DAY8' THEN CM_GEN_01.ESEQ + 0.08
WHEN CM_GEN_01.EVENTEID= 'ev_DAY15' THEN CM_GEN_01.ESEQ + 0.15
WHEN CM_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN CM_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN CM_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN CM_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN CM_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN CM_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN CM_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + CM_GEN_01.ESEQ * 0.01
ELSE CM_GEN_01.EVENTEID
END as 'VISITNUM'   
,CM_GEN_01.EVENTDT  'VISITDT'
,CM_GEN_01.FORM  'FORM'
,CM_GEN_01.FORMDEF  'FORMID'
,CM_GEN_01.FSEQ  'FORMSEQ'
,CASE CM_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  CM_GEN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,CM_GEN_01.IGSEQ  'IGSEQ'
,CM_GEN_01.DLASTMOD  'DLASTMOD'
,CM_GEN_01.DV_CMCAT  'V_CMCAT'
,CM_GEN_01.V_CMTRT  'V_CMTRT'
,CM_GEN_01.V_CMSTDAT  'V_CMSTDAT'
,CM_GEN_01.V_CMSTDAT  'X_CMSTDAT'
,CM_GEN_01.V_CMONGO  'V_CMONGO'
,CM_GEN_01.V_CMENDAT  'V_CMENDAT'
,CM_GEN_01.V_CMENDAT  'X_CMENDAT'
,CM_GEN_01.V_CMDOSFRQ  'V_CMDOSFRQ'
,CM_GEN_01.V_QVAL_DOSFRQOT  'V_QVAL_DOSFRQOT'
,CM_GEN_01.V_CMDSTXT  'V_CMDSTXT'
,CM_GEN_01.V_CMDOSU  'V_CMDOSU'
,CM_GEN_01.V_QVAL_DOSUOT  'V_QVAL_DOSUOT'
,CM_GEN_01.V_CMROUTE  'V_CMROUTE'
,CM_GEN_01.V_QVAL_ROUTEOT  'V_QVAL_ROUTEOT'
,CM_GEN_01.V_CMINDC  'V_CMINDC'
,CM_GEN_01.V_QVAL_INDCSP  'V_QVAL_INDCSP'
,CM_GEN_01.CRSTATUS  'CX_CRSTATUS'
,CM_GEN_01.DICTVER  'CV_QVAL_DICTVER'
,CM_GEN_01.PREFNAME   'CV_CMDECOD'
,CM_GEN_01.PREFCODE  'CV_QVAL_PREFCODE'

,CM_GEN_01.ATC1  'CV_QVAL_CMATC1'
,CM_GEN_01.ATC1CD  'CV_QVAL_CMATC1CD'
,CM_GEN_01.ATC2  'CV_QVAL_CMATC2'
,CM_GEN_01.ATC2CD  'CV_QVAL_CMATC2CD'
,CM_GEN_01.ATC3  'CV_QVAL_CMATC3'
,CM_GEN_01.ATC3CD  'CV_QVAL_CMATC3CD'
,CM_GEN_01.ATC4  'CV_QVAL_CMATC4'
,CM_GEN_01.ATC4CD  'CV_QVAL_CMATC4CD'

,CM_GEN_01.DRUGNAME  'CV_QVAL_DRUGNAME'
,CM_GEN_01.DRUGCODE  'CV_QVAL_DRUGCODE'

,CM_GEN_01.LASTCODEDAT  'CX_LASTCODEDAT'
,CM_GEN_01.LASTCODEDBY  'CX_LASTCODEDBY'
,CM_GEN_01.FL_IDVARVAL_CMAE_DEF  'FL_IDVARVAL_CMAE'
,CM_GEN_01.FL_IDVARVAL_CMMH_DEF  'FL_IDVARVAL_CMMH'
FROM
              CM_GEN_01 CM_GEN_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=CM_GEN_01.SUBJID
              AND  S1.SITENUM=CM_GEN_01.SITENUM
              AND CM_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND CM_GEN_01.FORMILB !='true'
             
    			    AND CM_GEN_01.IGSEQ  = '1'

UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,CM_GEN_01.COUNTRY  'COUNTRY'
,CM_GEN_01.SITENUM  'SITENUM'
,CM_GEN_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,CM_GEN_01.EGROUPDEF  'EGID'
,CM_GEN_01.ESEQ  'EGSEQ'
,CASE CM_GEN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN CM_GEN_01.EGROUP||' '||CM_GEN_01.EVENT
   ELSE CM_GEN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN CM_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN CM_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN CM_GEN_01.EVENTEID= 'ev_DAY1' THEN CM_GEN_01.ESEQ + 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_DAY8' THEN CM_GEN_01.ESEQ + 0.08
WHEN CM_GEN_01.EVENTEID= 'ev_DAY15' THEN CM_GEN_01.ESEQ + 0.15
WHEN CM_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN CM_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN CM_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN CM_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN CM_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + CM_GEN_01.ESEQ * 0.01
WHEN CM_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN CM_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN CM_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + CM_GEN_01.ESEQ * 0.01
ELSE CM_GEN_01.EVENTEID
END as 'VISITNUM' 
,CM_GEN_01.EVENTDT  'VISITDT'
,CM_GEN_01.FORM  'FORM'
,CM_GEN_01.FORMDEF  'FORMID'
,CM_GEN_01.FSEQ  'FORMSEQ'
,CASE CM_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  CM_GEN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,CM_GEN_01.IGSEQ  'IGSEQ'
,CM_GEN_01.DLASTMOD  'DLASTMOD'
,CM_GEN_01.DV_CMCAT  'V_CMCAT'
,CM_GEN_01.V_CMTRT  'V_CMTRT'
,CM_GEN_01.V_CMSTDAT  'V_CMSTDAT'
,CM_GEN_01.V_CMSTDAT  'X_CMSTDAT'
,CM_GEN_01.V_CMONGO  'V_CMONGO'
,CM_GEN_01.V_CMENDAT  'V_CMENDAT'
,CM_GEN_01.V_CMENDAT  'X_CMENDAT'
,CM_GEN_01.V_CMDOSFRQ  'V_CMDOSFRQ'
,CM_GEN_01.V_QVAL_DOSFRQOT  'V_QVAL_DOSFRQOT'
,CM_GEN_01.V_CMDSTXT  'V_CMDSTXT'
,CM_GEN_01.V_CMDOSU  'V_CMDOSU'
,CM_GEN_01.V_QVAL_DOSUOT  'V_QVAL_DOSUOT'
,CM_GEN_01.V_CMROUTE  'V_CMROUTE'
,CM_GEN_01.V_QVAL_ROUTEOT  'V_QVAL_ROUTEOT'
,CM_GEN_01.V_CMINDC  'V_CMINDC'
,CM_GEN_01.V_QVAL_INDCSP  'V_QVAL_INDCSP'

,(select C1.CRSTATUS from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CX_CRSTATUS'
,(select C1.DICTVER from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_DICTVER'
,(select C1.PREFNAME from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
  AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
'CV_CMDECOD'
,(select C1.PREFCODE from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
  AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
'CV_QVAL_PREFCODE'
,(select C1.ATC1 from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC1'
,(select C1.ATC1CD from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC1CD'
,(select C1.ATC2 from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC2'
,(select C1.ATC2CD from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC2CD'
,(select C1.ATC3 from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC3'
,(select C1.ATC3CD from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC3CD'
,(select C1.ATC4 from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC4'
,(select C1.ATC4CD from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CV_QVAL_CMATC4CD'
	
,(select C1.DRUGNAME from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
  AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
'CV_QVAL_DRUGNAME'
,(select C1.DRUGCODE from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
  AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
'CV_QVAL_DRUGCODE'
	
	
,(select C1.LASTCODEDAT from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CX_LASTCODEDAT'
,(select C1.LASTCODEDBY from CM_GEN_01 C1
  where C1.SUBJID=CM_GEN_01.SUBJID
    AND C1.SITENUM=CM_GEN_01.SITENUM AND C1.FSEQ=CM_GEN_01.FSEQ AND C1.IGSEQ = '1')
	'CX_LASTCODEDBY'
	
,CM_GEN_01.FL_IDVARVAL_CMAE_DEF  'FL_IDVARVAL_CMAE'
,CM_GEN_01.FL_IDVARVAL_CMMH_DEF  'FL_IDVARVAL_CMMH'
FROM
              CM_GEN_01 CM_GEN_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=CM_GEN_01.SUBJID
              AND  S1.SITENUM=CM_GEN_01.SITENUM
              AND CM_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND CM_GEN_01.FORMILB !='true'
              
			        AND CM_GEN_01.IGSEQ  != '1'

   "
  )



# AND CM_GEN_01.FORMILB !='true'
# AND CM_GEN_01.FORMILB !='true'
# Call the function -Convert_Date_Vals 
CharDate_Cols <-c("V_CMSTDAT","V_CMENDAT")
datetime_columns <- NULL
table_name <- c("CMGEN_UNION")
CMGEN_EDC <- Convert_Date_Vals(CMGEN_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
CMGEN_EDC <- CMGEN_EDC[names(CMGEN_CDB)]

# Post processing for compare
CMGEN_EDC$DLASTMOD <- substring(CMGEN_EDC$DLASTMOD,1,16)
CMGEN_EDC$CX_LASTCODEDAT <- substring(CMGEN_EDC$CX_LASTCODEDAT,1,16)
CMGEN_EDC <- CMGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
CMGEN_EDC <- CMGEN_EDC[order(CMGEN_EDC$STUDYID,CMGEN_EDC$COUNTRY,CMGEN_EDC$SITENUM,CMGEN_EDC$SUBJID,CMGEN_EDC$VISITDT,CMGEN_EDC$FORMID,as.integer(CMGEN_EDC$FORMSEQ),as.integer(CMGEN_EDC$IGSEQ)), ]

#Generate Compare Summary Report
CMGEN_EDC <- CMGEN_EDC %>% mutate(across(everything(), as.character))
CMGEN_CDB <- CMGEN_CDB %>% mutate(across(everything(), as.character))
CMGEN_SUMMARY <- capture.output(summary(comparedf(CMGEN_EDC, CMGEN_CDB)))
CMGEN_SUMMARY

#Export Summary Report
addWorksheet(wb, "CMGEN_SUMMARY")
writeData(wb, sheet = "CMGEN_SUMMARY", x = CMGEN_SUMMARY)

#Export QC Datasets
write_xpt(CMGEN_EDC,"QC Output/Datasets/EDC/CMGEN_EDC.xpt")
write_xpt(CMGEN_CDB,"QC Output/Datasets/CDB/CMGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)