rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
DMGEN_CDB <- dmgen
# Post processing for compare
DMGEN_CDB <- DMGEN_CDB %>% mutate(across(everything(), as.character))
DMGEN_CDB$DLASTMOD <- substring(DMGEN_CDB$DLASTMOD,1,16)
DMGEN_CDB <- DMGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))

## Get EDC Data
SUBJECTS <- sys_sub

DM_GEN_01 <- dm_gen_01
DM_GEN_01 <- DM_GEN_01 %>% mutate(across(everything(), as.character))
DM_GEN_01 <- DM_GEN_01 %>% mutate_if(is.character, ~replace_na(.,""))

DM_STDPRT_01 <- dm_stdprt_01
DM_STDPRT_01 <- DM_STDPRT_01 %>% mutate(across(everything(), as.character))
DM_STDPRT_01 <- DM_STDPRT_01 %>% mutate_if(is.character, ~replace_na(.,""))

DM_RESCREEN_01 <- dm_rescreen_01
DM_RESCREEN_01 <- DM_RESCREEN_01 %>% mutate(across(everything(), as.character))
DM_RESCREEN_01 <- DM_RESCREEN_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
DMGEN_UNION <-
	  sqldf(
	    "SELECT
	 'EIK1001-005_TST3'  'STUDYID'
	 ,'EDC'  'SOURCE'
	,DM_GEN_01.COUNTRY  'COUNTRY'
	,DM_GEN_01.SITENUM  'SITENUM'
	,DM_GEN_01.SUBJID  'SUBJID'
	 ,	 S1.STATUS 'SUBJSTATUS'

	,DM_GEN_01.EGROUPDEF  'EGID'
	,DM_GEN_01.ESEQ  'EGSEQ'
	,CASE DM_GEN_01.EGROUPDEF
	   WHEN 'eg_TRTA1C' THEN DM_GEN_01.EGROUP||' '||DM_GEN_01.EVENT
	   ELSE DM_GEN_01.EVENT
	   END AS 'VISIT'
,CASE 
WHEN DM_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN DM_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN DM_GEN_01.EVENTEID= 'ev_DAY1' THEN DM_GEN_01.ESEQ + 0.01
WHEN DM_GEN_01.EVENTEID= 'ev_DAY8' THEN DM_GEN_01.ESEQ + 0.08
WHEN DM_GEN_01.EVENTEID= 'ev_DAY15' THEN DM_GEN_01.ESEQ + 0.15
WHEN DM_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + DM_GEN_01.ESEQ * 0.01
WHEN DM_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN DM_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN DM_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN DM_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN DM_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + DM_GEN_01.ESEQ * 0.01
WHEN DM_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + DM_GEN_01.ESEQ * 0.01
WHEN DM_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN DM_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN DM_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + DM_GEN_01.ESEQ * 0.01
ELSE DM_GEN_01.EVENTEID
END as 'VISITNUM'
	,DM_GEN_01.EVENTDT  'VISITDT'
	,DM_GEN_01.FORM  'FORM'
	,DM_GEN_01.FORMDEF  'FORMID'
	,DM_GEN_01.FSEQ  'FORMSEQ'
	,CASE DM_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE DM_GEN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
	,DM_GEN_01.IGSEQ  'IGSEQ'
	,DM_GEN_01.DLASTMOD  'DLASTMOD'

	,DM_GEN_01.V_BRTHYY  'V_BRTHYY'
	,DM_GEN_01.V_AGE  'V_AGE'
	,DM_GEN_01.V_AGE_U  'V_AGEU'
	,DM_GEN_01.LBSEX  'V_SEX'
	,DM_GEN_01.V_ETHNIC  'V_ETHNIC'
	,DM_GEN_01.V_RACE_ASIAN  'V_RACE_ASIAN'
	,DM_GEN_01.V_RACE_BLACK  'V_RACE_BLACK'
	,DM_GEN_01.V_RACE_NATHAWPI  'V_RACE_NATHAWPI'
	,DM_GEN_01.V_RACE_WHITE  'V_RACE_WHITE'
	,DM_GEN_01.V_RACE_OTHER  'V_RACE_OTHER'
	,DM_GEN_01.V_RPORRES_CHILDPOT  'V_RPORRES_CHILDPOT'
	,DM_GEN_01.V_RPORRES_PREMENL  'V_RPORRES_PREMENL'
	,DM_GEN_01.V_RPORRES_SRGSTIND  'V_RPORRES_SRGSTIND'
	,DM_GEN_01.V_RPORRES_PSTMENPL  'V_RPORRES_PSTMENPL'
	,DM_GEN_01.V_RPORRES_CPREASOT  'V_RPORRES_CPREASOT'
	,DM_GEN_01.V_QVAL_REASOTH  'V_QVAL_REASOTH'
	,DM_STDPRT_01.V_QVAL_DSCONT 'V_QVAL_DSCONT'
	,DM_STDPRT_01.V_QVAL_SBJENRID  'V_QVAL_SBJENRID'
	,DM_RESCREEN_01.X_SUBJRSCYN  'X_SUBJRSCYN'
	,DM_RESCREEN_01.V_QVAL_SBJRSCNID  'V_QVAL_SBJRSCNID'
	,DM_STDPRT_01.V_QVAL_COHORT  'V_QVAL_COHORT'
	,DM_STDPRT_01.V_QVAL_DOSLVL 'V_QVAL_DOSLVL'
	,DM_STDPRT_01.V_QVAL_STDPART  'V_QVAL_STDPART'
	,DM_STDPRT_01.V_QVAL_INTSVPK  'V_QVAL_INTSVPK'

	FROM
   DM_GEN_01 DM_GEN_01
   left join SUBJECTS S1
  ON S1.SUBJID=DM_GEN_01.SUBJID
  	AND S1.SITENUM=DM_GEN_01.SITENUM
	        left join DM_STDPRT_01 DM_STDPRT_01
  ON DM_STDPRT_01.SUBJID=DM_GEN_01.SUBJID
    	AND DM_STDPRT_01.SITENUM=DM_GEN_01.SITENUM
    	    left join DM_RESCREEN_01 DM_RESCREEN_01
    	 ON DM_RESCREEN_01.SUBJID=DM_GEN_01.SUBJID
    	AND DM_RESCREEN_01.SITENUM=DM_GEN_01.SITENUM
	WHERE
	DM_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND DM_GEN_01.FORMILB !='true'
	
	")

# AND DM_GEN_01.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <- NULL #c("VISITDT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("DMGEN_UNION")
DMGEN_EDC <- Convert_Date_Vals(DMGEN_UNION, CharDate_Cols,datetime_columns,table_name)

#arrange columns as same as CDB
DMGEN_EDC <- DMGEN_EDC[names(DMGEN_CDB)]

# Post processing for compare
DMGEN_EDC$DLASTMOD <- substring(DMGEN_EDC$DLASTMOD,1,16)
DMGEN_EDC <- DMGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
DMGEN_EDC <- DMGEN_EDC[order(DMGEN_EDC$STUDYID,DMGEN_EDC$COUNTRY,DMGEN_EDC$SITENUM,DMGEN_EDC$SUBJID,DMGEN_EDC$VISITDT,DMGEN_EDC$FORMID,as.integer(DMGEN_EDC$FORMSEQ),as.integer(DMGEN_EDC$IGSEQ)), ]

#Generate Compare Summary Report
DMGEN_CDB <- DMGEN_CDB %>% mutate(across(everything(), as.character))
DMGEN_EDC <- DMGEN_EDC %>% mutate(across(everything(), as.character))
DMGEN_SUMMARY <- capture.output(summary(comparedf(DMGEN_EDC, DMGEN_CDB)))
DMGEN_SUMMARY

#Export Summary Report
addWorksheet(wb, "DMGEN_SUMMARY")
writeData(wb, sheet = "DMGEN_SUMMARY", x = DMGEN_SUMMARY)

#Export QC Datasets
write_xpt(DMGEN_EDC,"QC Output/Datasets/EDC/DMGEN_EDC.xpt")
write_xpt(DMGEN_CDB,"QC Output/Datasets/CDB/DMGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)