rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
DSSTAT_CDB <- dsstat
# Post processing for compare
DSSTAT_CDB <- DSSTAT_CDB %>% mutate(across(everything(), as.character))
DSSTAT_CDB$DLASTMOD <- substring(DSSTAT_CDB$DLASTMOD,1,16)
DSSTAT_CDB <- DSSTAT_CDB %>% mutate_if(is.character, ~replace_na(.,""))
DSSTAT_CDB <- DSSTAT_CDB[order(DSSTAT_CDB$STUDYID,DSSTAT_CDB$COUNTRY,DSSTAT_CDB$SITENUM,DSSTAT_CDB$SUBJID,DSSTAT_CDB$VISITDT,DSSTAT_CDB$FORMID,as.integer(DSSTAT_CDB$FORMSEQ),as.integer(DSSTAT_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

DS_EOS_01 <- ds_eos_01
DS_EOS_01 <- DS_EOS_01 %>% mutate(across(everything(), as.character))
DS_EOS_01 <- DS_EOS_01 %>% mutate_if(is.character, ~replace_na(.,""))

DS_EOT_01 <- ds_eot_01
DS_EOT_01 <- DS_EOT_01 %>% mutate(across(everything(), as.character))
DS_EOT_01 <- DS_EOT_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
DSSTAT_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,DS_EOS_01.COUNTRY  'COUNTRY'
,DS_EOS_01.SITENUM  'SITENUM'
,DS_EOS_01.SUBJID  'SUBJID'
,S1.STATUS  'SUBJSTATUS'
,DS_EOS_01.EGROUPDEF  'EGID'
,DS_EOS_01.ESEQ  'EGSEQ'
,CASE DS_EOS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN DS_EOS_01.EGROUP||' '||DS_EOS_01.EVENT
   ELSE DS_EOS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN DS_EOS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN DS_EOS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN DS_EOS_01.EVENTEID= 'ev_DAY1' THEN DS_EOS_01.ESEQ + 0.01
WHEN DS_EOS_01.EVENTEID= 'ev_DAY8' THEN DS_EOS_01.ESEQ + 0.08
WHEN DS_EOS_01.EVENTEID= 'ev_DAY15' THEN DS_EOS_01.ESEQ + 0.15
WHEN DS_EOS_01.EVENTEID= 'ev_TUPB' THEN 41 + DS_EOS_01.ESEQ * 0.01
WHEN DS_EOS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN DS_EOS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN DS_EOS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN DS_EOS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN DS_EOS_01.EVENTEID= 'ev_PTFU' THEN 75 + DS_EOS_01.ESEQ * 0.01
WHEN DS_EOS_01.EVENTEID= 'ev_LFU' THEN 80 + DS_EOS_01.ESEQ * 0.01
WHEN DS_EOS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN DS_EOS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN DS_EOS_01.EVENTEID= 'ev_UNS' THEN 99 + DS_EOS_01.ESEQ * 0.01
ELSE DS_EOS_01.EVENTEID
END as 'VISITNUM'
,DS_EOS_01.EVENTDT  'VISITDT'
,DS_EOS_01.FORM  'FORM'
,DS_EOS_01.FORMDEF  'FORMID'
,DS_EOS_01.FSEQ  'FORMSEQ'
, CASE DS_EOS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  DS_EOS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,DS_EOS_01.IGSEQ  'IGSEQ'
,DS_EOS_01.DLASTMOD  'DLASTMOD'
,DS_EOS_01.DV_DSSCAT  'V_DSSCAT'
,DS_EOS_01.EVENTDT  'V_DSDAT'
,DS_EOS_01.EVENTDT  'X_DSDAT'
,DS_EOS_01.V_EPOCH  'V_EPOCH'
,DS_EOS_01.V_DSDECOD_EOS  'V_DSDECOD'
,DS_EOS_01.V_DSTERM  'V_DSTERM'
,NULL  'V_QVAL_DSCONT'
,DS_EOS_01.V_DSTERM_DISPRGPD  'V_DSTERM_DISPRGPD'
,DS_EOS_01.V_DSSTDAT_DISPRGPD  'V_DSSTDAT_DISPRGPD'
,DS_EOS_01.V_DSSTDAT_DISPRGPD  'X_DSSTDAT_DISPRGPD'
,NULL 'FL_IDVARVAL_DSAE'

FROM
              DS_EOS_01 DS_EOS_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=DS_EOS_01.SUBJID
               AND  S1.SITENUM=DS_EOS_01.SITENUM
              AND DS_EOS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND DS_EOS_01.FORMILB !='true'
    



UNION

SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,DS_EOT_01.COUNTRY  'COUNTRY'
,DS_EOT_01.SITENUM  'SITENUM'
,DS_EOT_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,DS_EOT_01.EGROUPDEF  'EGID'
,DS_EOT_01.ESEQ  'EGSEQ'
,CASE DS_EOT_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN DS_EOT_01.EGROUP||' '||DS_EOT_01.EVENT
   ELSE DS_EOT_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN DS_EOT_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN DS_EOT_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN DS_EOT_01.EVENTEID= 'ev_DAY1' THEN DS_EOT_01.ESEQ + 0.01
WHEN DS_EOT_01.EVENTEID= 'ev_DAY8' THEN DS_EOT_01.ESEQ + 0.08
WHEN DS_EOT_01.EVENTEID= 'ev_DAY15' THEN DS_EOT_01.ESEQ + 0.15
WHEN DS_EOT_01.EVENTEID= 'ev_TUPB' THEN 41 + DS_EOT_01.ESEQ * 0.01
WHEN DS_EOT_01.EVENTEID= 'ev_EOT' THEN 60
WHEN DS_EOT_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN DS_EOT_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN DS_EOT_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN DS_EOT_01.EVENTEID= 'ev_PTFU' THEN 75 + DS_EOT_01.ESEQ * 0.01
WHEN DS_EOT_01.EVENTEID= 'ev_LFU' THEN 80 + DS_EOT_01.ESEQ * 0.01
WHEN DS_EOT_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN DS_EOT_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN DS_EOT_01.EVENTEID= 'ev_UNS' THEN 99 + DS_EOT_01.ESEQ * 0.01
ELSE DS_EOT_01.EVENTEID
END as 'VISITNUM'
  
,DS_EOT_01.EVENTDT  'VISITDT'
,DS_EOT_01.FORM  'FORM'
,DS_EOT_01.FORMDEF  'FORMID'
,DS_EOT_01.FSEQ  'FORMSEQ'
,CASE DS_EOT_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  DS_EOT_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,DS_EOT_01.IGSEQ  'IGSEQ'
,DS_EOT_01.DLASTMOD  'DLASTMOD'
,DS_EOT_01.DV_DSSCAT  'V_DSSCAT'
,DS_EOT_01.EVENTDT  'V_DSDAT'
,DS_EOT_01.EVENTDT 'X_DSDAT'
,DS_EOT_01.DV_EPOCH  'V_EPOCH'
,DS_EOT_01.V_DSDECOD_EOT  'V_DSDECOD'
,DS_EOT_01.V_DSTERM  'V_DSTERM'
,DS_EOT_01.V_QVAL_DSCONT  'V_QVAL_DSCONT'
,NULL  'V_DSTERM_DISPRGPD'
,NULL  'V_DSSTDAT_DISPRGPD'
,NULL  'X_DSSTDAT_DISPRGPD'
,DS_EOT_01.FL_IDVARVAL_DSAE_DEF  'FL_IDVARVAL_DSAE'

FROM
              DS_EOT_01 DS_EOT_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=DS_EOT_01.SUBJID
              AND  S1.SITENUM=DS_EOT_01.SITENUM
              AND DS_EOT_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND DS_EOT_01.FORMILB !='true'
    "
  )



# X_DSDAT
# X_DSSTDAT_DISPRGPD

# Call the function -Convert_Date_Vals 
CharDate_Cols <- c ("V_DSSTDAT_DISPRGPD","V_DSDAT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("DSSTAT_UNION")
DSSTAT_EDC <- Convert_Date_Vals(DSSTAT_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
DSSTAT_EDC <- DSSTAT_EDC[names(DSSTAT_CDB)]

# Post processing for compare
DSSTAT_EDC$DLASTMOD <- substring(DSSTAT_EDC$DLASTMOD,1,16)
DSSTAT_EDC <- DSSTAT_EDC %>% mutate_if(is.character, ~replace_na(.,""))
DSSTAT_EDC <- DSSTAT_EDC[order(DSSTAT_EDC$STUDYID,DSSTAT_EDC$COUNTRY,DSSTAT_EDC$SITENUM,DSSTAT_EDC$SUBJID,DSSTAT_EDC$VISITDT,DSSTAT_EDC$FORMID,as.integer(DSSTAT_EDC$FORMSEQ),as.integer(DSSTAT_EDC$IGSEQ)), ]

#Generate Compare Summary Report
DSSTAT_EDC <- DSSTAT_EDC %>% mutate(across(everything(), as.character))
DSSTAT_CDB <- DSSTAT_CDB %>% mutate(across(everything(), as.character))
DSSTAT_SUMMARY <- capture.output(summary(comparedf(DSSTAT_EDC, DSSTAT_CDB)))
DSSTAT_SUMMARY

#Export Summary Report
addWorksheet(wb, "DSSTAT_SUMMARY")
writeData(wb, sheet = "DSSTAT_SUMMARY", x = DSSTAT_SUMMARY)

#Export QC Datasets
write_xpt(DSSTAT_EDC,"QC Output/Datasets/EDC/DSSTAT_EDC.xpt")
write_xpt(DSSTAT_CDB,"QC Output/Datasets/CDB/DSSTAT_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)