rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
ECGEN_CDB <- ecgen
# Post processing for compare
ECGEN_CDB <- ECGEN_CDB %>% mutate(across(everything(), as.character))
ECGEN_CDB$DLASTMOD <- substring(ECGEN_CDB$DLASTMOD,1,16)

ECGEN_CDB$V_ECSTTIM <- substring(ECGEN_CDB$V_ECSTTIM,1,5)
ECGEN_CDB$V_ECENTIM <- substring(ECGEN_CDB$V_ECENTIM,1,5)
ECGEN_CDB$V_ECCINTD_STTIM <- substring(ECGEN_CDB$V_ECCINTD_STTIM,1,5)
ECGEN_CDB$V_ECCINTD_ENTIM <- substring(ECGEN_CDB$V_ECCINTD_ENTIM,1,5)
ECGEN_CDB <- ECGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))
ECGEN_CDB <- ECGEN_CDB[order(ECGEN_CDB$STUDYID,ECGEN_CDB$COUNTRY,ECGEN_CDB$SITENUM,ECGEN_CDB$SUBJID,ECGEN_CDB$VISITNUM,ECGEN_CDB$VISIT,ECGEN_CDB$VISITDT,ECGEN_CDB$FORMID,as.integer(ECGEN_CDB$FORMSEQ),as.integer(ECGEN_CDB$EGSEQ),as.integer(ECGEN_CDB$IGSEQ)), ]


# ECGEN_CDB <- ECGEN_CDB %>% 
#   arrange(STUDYID, COUNTRY, SITENUM, SUBJID, VISIT, VISITDT, FORMID, as.integer(FORMSEQ), as.integer(EGSEQ), as.integer(IGSEQ))
## Get EDC Data
SUBJECTS <- sys_sub




EC_IV_01 <- ec_iv_01
EC_IV_01 <- EC_IV_01 %>% mutate(across(everything(), as.character))
# EC_IV_01$V_ECSTDTC <- case_when(EC_IV_01$V_ECSTDTC_TM == "00:00:00" ~ paste(EC_IV_01$V_ECSTDTC_DT,EC_IV_01$V_ECSTDTC_TM), TRUE ~ EC_IV_01$V_ECSTDTC)
EC_IV_01 <- EC_IV_01 %>% mutate_if(is.character, ~replace_na(.,""))

EC_IV_02 <- ec_iv_02
EC_IV_02 <- EC_IV_02 %>% mutate(across(everything(), as.character))
# EC_IV_02$V_ECSTDTC <- case_when(EC_IV_02$V_ECSTDTC_TM == "00:00:00" ~ paste(EC_IV_02$V_ECSTDTC_DT,EC_IV_02$V_ECSTDTC_TM), TRUE ~ EC_IV_02$V_ECSTDTC)
EC_IV_02 <- EC_IV_02 %>% mutate_if(is.character, ~replace_na(.,""))

EC_IV_03 <- ec_iv_03
EC_IV_03 <- EC_IV_03 %>% mutate(across(everything(), as.character))
# EC_IV_03$V_ECSTDTC <- case_when(EC_IV_03$V_ECSTDTC_TM == "00:00:00" ~ paste(EC_IV_03$V_ECSTDTC_DT,EC_IV_03$V_ECSTDTC_TM), TRUE ~ EC_IV_03$V_ECSTDTC)
EC_IV_03 <- EC_IV_03 %>% mutate_if(is.character, ~replace_na(.,""))

EC_IV_04 <- ec_iv_04
EC_IV_04 <- EC_IV_04 %>% mutate(across(everything(), as.character))
# EC_IV_04$V_ECSTDTC <- case_when(EC_IV_04$V_ECSTDTC_TM == "00:00:00" ~ paste(EC_IV_04$V_ECSTDTC_DT,EC_IV_04$V_ECSTDTC_TM), TRUE ~ EC_IV_04$V_ECSTDTC)
EC_IV_04 <- EC_IV_04 %>% mutate_if(is.character, ~replace_na(.,""))

EC_IV_05 <- ec_iv_05
EC_IV_05 <- EC_IV_05 %>% mutate(across(everything(), as.character))
# EC_IV_05$V_ECSTDTC <- case_when(EC_IV_05$V_ECSTDTC_TM == "00:00:00" ~ paste(EC_IV_05$V_ECSTDTC_DT,EC_IV_05$V_ECSTDTC_TM), TRUE ~ EC_IV_05$V_ECSTDTC)
EC_IV_05 <- EC_IV_05 %>% mutate_if(is.character, ~replace_na(.,""))




#--------- Final UNION Query -------
ECGEN_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EC_IV_01.COUNTRY  'COUNTRY'
,EC_IV_01.SITENUM  'SITENUM'
,EC_IV_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EC_IV_01.EGROUPDEF  'EGID'
,EC_IV_01.ESEQ  'EGSEQ'
,CASE EC_IV_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EC_IV_01.EGROUP||' '||EC_IV_01.EVENT
   ELSE EC_IV_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN EC_IV_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EC_IV_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EC_IV_01.EVENTEID= 'ev_DAY1' THEN EC_IV_01.ESEQ + 0.01
WHEN EC_IV_01.EVENTEID= 'ev_DAY8' THEN EC_IV_01.ESEQ + 0.08
WHEN EC_IV_01.EVENTEID= 'ev_DAY15' THEN EC_IV_01.ESEQ + 0.15
WHEN EC_IV_01.EVENTEID= 'ev_TUPB' THEN 41 + EC_IV_01.ESEQ * 0.01
WHEN EC_IV_01.EVENTEID= 'ev_EOT' THEN 60
WHEN EC_IV_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EC_IV_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EC_IV_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EC_IV_01.EVENTEID= 'ev_PTFU' THEN 75 + EC_IV_01.ESEQ * 0.01
WHEN EC_IV_01.EVENTEID= 'ev_LFU' THEN 80 + EC_IV_01.ESEQ * 0.01
WHEN EC_IV_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EC_IV_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN EC_IV_01.EVENTEID= 'ev_UNS' THEN 99 + EC_IV_01.ESEQ * 0.01
ELSE EC_IV_01.EVENTEID
END as 'VISITNUM'

,EC_IV_01.EVENTDT  'VISITDT'
,EC_IV_01.FORM  'FORM'
,EC_IV_01.FORMDEF  'FORMID'
,EC_IV_01.FSEQ  'FORMSEQ'
, CASE EC_IV_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EC_IV_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,EC_IV_01.IGSEQ  'IGSEQ'
,EC_IV_01.DLASTMOD  'DLASTMOD'
,EC_IV_01.DV_ECTRT  'V_ECTRT'
,EC_IV_01.V_QVAL_SCOCCUR  'V_QVAL_SCOCCUR'
,EC_IV_01.V_QVAL_SCREASOC 'V_QVAL_SCREASOC'
,EC_IV_01.V_QVAL_SCREASOT  'V_QVAL_SCREASOT'
,EC_IV_01.V_QVAL_ECADMDEV 'V_QVAL_ECADMDEV'
,EC_IV_01.V_QVAL_ECDEVOT  'V_QVAL_ECDEVOT'
,EC_IV_01.V_QVAL_AESOD  'V_QVAL_AESOD'
,EC_IV_01.V_ECDOSE_SCHEDULED  'V_ECDOSE_SCHEDULED'
,EC_IV_01.DV_ECDOSU_SCHEDULED  'V_ECDOSU_SCHEDULED'
,EC_IV_01.DV_ECROUTE  'V_ECROUTE'
,EC_IV_01.V_ECDOSE_PERFORMED  'V_ECDOSE_PERFORMED'
,EC_IV_01.DV_ECDOSU_PERFORMED 'V_ECDOSU_PERFORMED'

,EC_IV_01.V_ECSTDTC 'V_ECSTDTC'
,EC_IV_01.V_ECSTDTC_DT 'V_ECSTDAT'
,EC_IV_01.V_ECSTDTC_TM  'V_ECSTTIM'

,EC_IV_01.V_ECSTDTC 'X_ECSTDTC'
,EC_IV_01.V_ECSTDTC_DT 'X_ECSTDAT'
,EC_IV_01.V_ECSTDTC_TM  'X_ECSTTIM'

,EC_IV_01.V_ECENDTC  'V_ECENDTC'
,EC_IV_01.V_ECENDTC_DT 'V_ECENDAT'
,EC_IV_01.V_ECENDTC_TM 'V_ECENTIM'
,EC_IV_01.V_ECENDTC  'X_ECENDTC'
,EC_IV_01.V_ECENDTC_DT 'X_ECENDAT'
,EC_IV_01.V_ECENDTC_TM 'X_ECENTIM'

,EC_IV_01.V_ECREFID_S01 'V_ECREFID'
,EC_IV_01.V_ECCINTD_STTIM  'V_ECCINTD_STTIM'
,EC_IV_01.V_ECCINTD_STTIM  'X_ECCINTD_STTIM'
,EC_IV_01.V_ECCINTD_ENTIM  'V_ECCINTD_ENTIM'

,EC_IV_01.V_ECCINTD_ENTIM  'X_ECCINTD_ENTIM'
,EC_IV_01. FL_IDVARVAL_ECAE_S01_DEF FL_IDVARVAL_ECAE01
,EC_IV_01. FL_IDVARVAL_ECAE_S02_DEF FL_IDVARVAL_ECAE02



FROM
              EC_IV_01 EC_IV_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=EC_IV_01.SUBJID
               AND  S1.SITENUM=EC_IV_01.SITENUM
              AND EC_IV_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND EC_IV_01.FORMILB !='true'
    

UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EC_IV_02.COUNTRY  'COUNTRY'
,EC_IV_02.SITENUM  'SITENUM'
,EC_IV_02.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EC_IV_02.EGROUPDEF  'EGID'
,EC_IV_02.ESEQ  'EGSEQ'
,CASE EC_IV_02.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EC_IV_02.EGROUP||' '||EC_IV_02.EVENT
   ELSE EC_IV_02.EVENT
   END AS 'VISIT'
,CASE 
WHEN EC_IV_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EC_IV_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EC_IV_02.EVENTEID= 'ev_DAY1' THEN EC_IV_02.ESEQ + 0.01
WHEN EC_IV_02.EVENTEID= 'ev_DAY8' THEN EC_IV_02.ESEQ + 0.08
WHEN EC_IV_02.EVENTEID= 'ev_DAY15' THEN EC_IV_02.ESEQ + 0.15
WHEN EC_IV_02.EVENTEID= 'ev_TUPB' THEN 41 + EC_IV_02.ESEQ * 0.01
WHEN EC_IV_02.EVENTEID= 'ev_EOT' THEN 60
WHEN EC_IV_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EC_IV_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EC_IV_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EC_IV_02.EVENTEID= 'ev_PTFU' THEN 75 + EC_IV_02.ESEQ * 0.01
WHEN EC_IV_02.EVENTEID= 'ev_LFU' THEN 80 + EC_IV_02.ESEQ * 0.01
WHEN EC_IV_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EC_IV_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN EC_IV_02.EVENTEID= 'ev_UNS' THEN 99 + EC_IV_02.ESEQ * 0.01
ELSE EC_IV_02.EVENTEID
END as 'VISITNUM'

,EC_IV_02.EVENTDT  'VISITDT'
,EC_IV_02.FORM  'FORM'
,EC_IV_02.FORMDEF  'FORMID'
,EC_IV_02.FSEQ  'FORMSEQ'
, CASE EC_IV_02.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EC_IV_02.FORMSTATUS
	   END AS 'FORMSTATUS'
,EC_IV_02.IGSEQ  'IGSEQ'
,EC_IV_02.DLASTMOD  'DLASTMOD'
,EC_IV_02.DV_ECTRT  'V_ECTRT'
,EC_IV_02.V_QVAL_SCOCCUR  'V_QVAL_SCOCCUR'
,EC_IV_02.V_QVAL_SCREASOC 'V_QVAL_SCREASOC'
,EC_IV_02.V_QVAL_SCREASOT  'V_QVAL_SCREASOT'
,EC_IV_02.V_QVAL_ECADMDEV 'V_QVAL_ECADMDEV'
,EC_IV_02.V_QVAL_ECDEVOT  'V_QVAL_ECDEVOT'
,EC_IV_02.V_QVAL_AESOD  'V_QVAL_AESOD'
,EC_IV_02.V_ECDOSE_SCHEDULED  'V_ECDOSE_SCHEDULED'
,EC_IV_02.DV_ECDOSU_SCHEDULED  'V_ECDOSU_SCHEDULED'
,EC_IV_02.DV_ECROUTE  'V_ECROUTE'
,EC_IV_02.V_ECDOSE_PERFORMED  'V_ECDOSE_PERFORMED'
,EC_IV_02.DV_ECDOSU_PERFORMED 'V_ECDOSU_PERFORMED'

,EC_IV_02.V_ECSTDTC 'V_ECSTDTC'
,EC_IV_02.V_ECSTDTC_DT 'V_ECSTDAT'
,EC_IV_02.V_ECSTDTC_TM  'V_ECSTTIM'

,EC_IV_02.V_ECSTDTC 'X_ECSTDTC'
,EC_IV_02.V_ECSTDTC_DT 'X_ECSTDAT'
,EC_IV_02.V_ECSTDTC_TM  'X_ECSTTIM'

,EC_IV_02.V_ECENDTC  'V_ECENDTC'
,EC_IV_02.V_ECENDTC_DT 'V_ECENDAT'
,EC_IV_02.V_ECENDTC_TM 'V_ECENTIM'

,EC_IV_02.V_ECENDTC  'X_ECENDTC'
,EC_IV_02.V_ECENDTC_DT 'X_ECENDAT'
,EC_IV_02.V_ECENDTC_TM 'X_ECENTIM'




,EC_IV_02.V_ECREFID_S02  'V_ECREFID'
,EC_IV_02.V_ECCINTD_STTIM  'V_ECCINTD_STTIM'
,EC_IV_02.V_ECCINTD_STTIM  'X_ECCINTD_STTIM'
,EC_IV_02.V_ECCINTD_ENTIM  'V_ECCINTD_ENTIM'

,EC_IV_02.V_ECCINTD_ENTIM  'X_ECCINTD_ENTIM'
,EC_IV_02. FL_IDVARVAL_ECAE_S01_DEF FL_IDVARVAL_ECAE01
,EC_IV_02. FL_IDVARVAL_ECAE_S02_DEF FL_IDVARVAL_ECAE02


FROM
              EC_IV_02 EC_IV_02,
              SUBJECTS S1

              WHERE
              S1.SUBJID=EC_IV_02.SUBJID
               AND  S1.SITENUM=EC_IV_02.SITENUM
              AND EC_IV_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND EC_IV_02.FORMILB !='true'
    



UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EC_IV_03.COUNTRY  'COUNTRY'
,EC_IV_03.SITENUM  'SITENUM'
,EC_IV_03.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,EC_IV_03.EGROUPDEF  'EGID'
,EC_IV_03.ESEQ  'EGSEQ'
,CASE EC_IV_03.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EC_IV_03.EGROUP||' '||EC_IV_03.EVENT
   ELSE EC_IV_03.EVENT
   END AS 'VISIT'
,CASE 
WHEN EC_IV_03.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EC_IV_03.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EC_IV_03.EVENTEID= 'ev_DAY1' THEN EC_IV_03.ESEQ + 0.01
WHEN EC_IV_03.EVENTEID= 'ev_DAY8' THEN EC_IV_03.ESEQ + 0.08
WHEN EC_IV_03.EVENTEID= 'ev_DAY15' THEN EC_IV_03.ESEQ + 0.15
WHEN EC_IV_03.EVENTEID= 'ev_TUPB' THEN 41 + EC_IV_03.ESEQ * 0.01
WHEN EC_IV_03.EVENTEID= 'ev_EOT' THEN 60
WHEN EC_IV_03.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EC_IV_03.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EC_IV_03.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EC_IV_03.EVENTEID= 'ev_PTFU' THEN 75 + EC_IV_03.ESEQ * 0.01
WHEN EC_IV_03.EVENTEID= 'ev_LFU' THEN 80 + EC_IV_03.ESEQ * 0.01
WHEN EC_IV_03.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EC_IV_03.EVENTEID= 'ev_LOGS' THEN 98
WHEN EC_IV_03.EVENTEID= 'ev_UNS' THEN 99 + EC_IV_03.ESEQ * 0.01
ELSE EC_IV_03.EVENTEID
END as 'VISITNUM'
,EC_IV_03.EVENTDT  'VISITDT'
,EC_IV_03.FORM  'FORM'
,EC_IV_03.FORMDEF  'FORMID'
,EC_IV_03.FSEQ  'FORMSEQ'
, CASE EC_IV_03.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EC_IV_03.FORMSTATUS
	   END AS 'FORMSTATUS'
,EC_IV_03.IGSEQ  'IGSEQ'
,EC_IV_03.DLASTMOD  'DLASTMOD'
,EC_IV_03.DV_ECTRT  'V_ECTRT'
,EC_IV_03.V_QVAL_SCOCCUR  'V_QVAL_SCOCCUR'
,EC_IV_03.V_QVAL_SCREASOC 'V_QVAL_SCREASOC'
,EC_IV_03.V_QVAL_SCREASOT  'V_QVAL_SCREASOT'
,EC_IV_03.V_QVAL_ECADMDEV 'V_QVAL_ECADMDEV'
,EC_IV_03.V_QVAL_ECDEVOT  'V_QVAL_ECDEVOT'
,EC_IV_03.V_QVAL_AESOD  'V_QVAL_AESOD'
,EC_IV_03.V_ECDOSE_SCHEDULED  'V_ECDOSE_SCHEDULED'
,EC_IV_03.DV_ECDOSU_SCHEDULED  'V_ECDOSU_SCHEDULED'
,EC_IV_03.DV_ECROUTE  'V_ECROUTE'
,EC_IV_03.V_ECDOSE_PERFORMED  'V_ECDOSE_PERFORMED'
,EC_IV_03.DV_ECDOSU_PERFORMED 'V_ECDOSU_PERFORMED'
,EC_IV_03.V_ECSTDTC 'V_ECSTDTC'
,EC_IV_03.V_ECSTDTC_DT 'V_ECSTDAT'
,EC_IV_03.V_ECSTDTC_TM  'V_ECSTTIM'

,EC_IV_03.V_ECSTDTC 'X_ECSTDTC'
,EC_IV_03.V_ECSTDTC_DT 'X_ECSTDAT'
,EC_IV_03.V_ECSTDTC_TM  'X_ECSTTIM'

,EC_IV_03.V_ECENDTC  'V_ECENDTC'
,EC_IV_03.V_ECENDTC_DT 'V_ECENDAT'
,EC_IV_03.V_ECENDTC_TM 'V_ECENTIM'

,EC_IV_03.V_ECENDTC  'X_ECENDTC'
,EC_IV_03.V_ECENDTC_DT 'X_ECENDAT'
,EC_IV_03.V_ECENDTC_TM 'X_ECENTIM'
,EC_IV_03.V_ECREFID_S02  'V_ECREFID'
,EC_IV_03.V_ECCINTD_STTIM  'V_ECCINTD_STTIM'
,EC_IV_03.V_ECCINTD_STTIM  'X_ECCINTD_STTIM'
,EC_IV_03.V_ECCINTD_ENTIM  'V_ECCINTD_ENTIM'

,EC_IV_03.V_ECCINTD_ENTIM  'X_ECCINTD_ENTIM'
,EC_IV_03. FL_IDVARVAL_ECAE_S01_DEF FL_IDVARVAL_ECAE01
,EC_IV_03. FL_IDVARVAL_ECAE_S02_DEF FL_IDVARVAL_ECAE02

FROM
              EC_IV_03 EC_IV_03,
              SUBJECTS S1

              WHERE
              S1.SUBJID=EC_IV_03.SUBJID
               AND  S1.SITENUM=EC_IV_03.SITENUM
              AND EC_IV_03.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND EC_IV_03.FORMILB !='true'
   




UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EC_IV_04.COUNTRY  'COUNTRY'
,EC_IV_04.SITENUM  'SITENUM'
,EC_IV_04.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EC_IV_04.EGROUPDEF  'EGID'
,EC_IV_04.ESEQ  'EGSEQ'
,CASE EC_IV_04.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EC_IV_04.EGROUP||' '||EC_IV_04.EVENT
   ELSE EC_IV_04.EVENT
   END AS 'VISIT'
,CASE 
WHEN EC_IV_04.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EC_IV_04.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EC_IV_04.EVENTEID= 'ev_DAY1' THEN EC_IV_04.ESEQ + 0.01
WHEN EC_IV_04.EVENTEID= 'ev_DAY8' THEN EC_IV_04.ESEQ + 0.08
WHEN EC_IV_04.EVENTEID= 'ev_DAY15' THEN EC_IV_04.ESEQ + 0.15
WHEN EC_IV_04.EVENTEID= 'ev_TUPB' THEN 41 + EC_IV_04.ESEQ * 0.01
WHEN EC_IV_04.EVENTEID= 'ev_EOT' THEN 60
WHEN EC_IV_04.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EC_IV_04.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EC_IV_04.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EC_IV_04.EVENTEID= 'ev_PTFU' THEN 75 + EC_IV_04.ESEQ * 0.01
WHEN EC_IV_04.EVENTEID= 'ev_LFU' THEN 80 + EC_IV_04.ESEQ * 0.01
WHEN EC_IV_04.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EC_IV_04.EVENTEID= 'ev_LOGS' THEN 98
WHEN EC_IV_04.EVENTEID= 'ev_UNS' THEN 99 + EC_IV_04.ESEQ * 0.01
ELSE EC_IV_04.EVENTEID
END as 'VISITNUM' 
,EC_IV_04.EVENTDT  'VISITDT'
,EC_IV_04.FORM  'FORM'
,EC_IV_04.FORMDEF  'FORMID'
,EC_IV_04.FSEQ  'FORMSEQ'
, CASE EC_IV_04.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EC_IV_04.FORMSTATUS
	   END AS 'FORMSTATUS'
,EC_IV_04.IGSEQ  'IGSEQ'
,EC_IV_04.DLASTMOD  'DLASTMOD'
,EC_IV_04.DV_ECTRT  'V_ECTRT'
,EC_IV_04.V_QVAL_SCOCCUR  'V_QVAL_SCOCCUR'
,EC_IV_04.V_QVAL_SCREASOC 'V_QVAL_SCREASOC'
,EC_IV_04.V_QVAL_SCREASOT  'V_QVAL_SCREASOT'
,EC_IV_04.V_QVAL_ECADMDEV 'V_QVAL_ECADMDEV'
,EC_IV_04.V_QVAL_ECDEVOT  'V_QVAL_ECDEVOT'
,EC_IV_04.V_QVAL_AESOD  'V_QVAL_AESOD'
,EC_IV_04.V_ECDOSE_SCHEDULED  'V_ECDOSE_SCHEDULED'
,EC_IV_04.DV_ECDOSU_SCHEDULED  'V_ECDOSU_SCHEDULED'
,EC_IV_04.DV_ECROUTE  'V_ECROUTE'
,EC_IV_04.V_ECDOSE_PERFORMED  'V_ECDOSE_PERFORMED'
,EC_IV_04.DV_ECDOSU_PERFORMED 'V_ECDOSU_PERFORMED'

,EC_IV_04.V_ECSTDTC 'V_ECSTDTC'
,EC_IV_04.V_ECSTDTC_DT 'V_ECSTDAT'
,EC_IV_04.V_ECSTDTC_TM  'V_ECSTTIM'

,EC_IV_04.V_ECSTDTC 'X_ECSTDTC'
,EC_IV_04.V_ECSTDTC_DT 'X_ECSTDAT'
,EC_IV_04.V_ECSTDTC_TM  'X_ECSTTIM'

,EC_IV_04.V_ECENDTC  'V_ECENDTC'
,EC_IV_04.V_ECENDTC_DT 'V_ECENDAT'
,EC_IV_04.V_ECENDTC_TM 'V_ECENTIM'

,EC_IV_04.V_ECENDTC  'X_ECENDTC'
,EC_IV_04.V_ECENDTC_DT 'X_ECENDAT'
,EC_IV_04.V_ECENDTC_TM 'X_ECENTIM'

,EC_IV_04.V_ECREFID_S02  'V_ECREFID'
,EC_IV_04.V_ECCINTD_STTIM  'V_ECCINTD_STTIM'
,EC_IV_04.V_ECCINTD_STTIM  'X_ECCINTD_STTIM'
,EC_IV_04.V_ECCINTD_ENTIM  'V_ECCINTD_ENTIM'

,EC_IV_04.V_ECCINTD_ENTIM  'X_ECCINTD_ENTIM'
,EC_IV_04. FL_IDVARVAL_ECAE_S01_DEF FL_IDVARVAL_ECAE01
,EC_IV_04. FL_IDVARVAL_ECAE_S02_DEF FL_IDVARVAL_ECAE02

FROM
              EC_IV_04 EC_IV_04,
              SUBJECTS S1

              WHERE
              S1.SUBJID=EC_IV_04.SUBJID
               AND  S1.SITENUM=EC_IV_04.SITENUM
              AND EC_IV_04.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND EC_IV_04.FORMILB !='true'
   



UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EC_IV_05.COUNTRY  'COUNTRY'
,EC_IV_05.SITENUM  'SITENUM'
,EC_IV_05.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EC_IV_05.EGROUPDEF  'EGID'
,EC_IV_05.ESEQ  'EGSEQ'
,CASE EC_IV_05.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EC_IV_05.EGROUP||' '||EC_IV_05.EVENT
   ELSE EC_IV_05.EVENT
   END AS 'VISIT'
,CASE 
WHEN EC_IV_05.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EC_IV_05.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EC_IV_05.EVENTEID= 'ev_DAY1' THEN EC_IV_05.ESEQ + 0.01
WHEN EC_IV_05.EVENTEID= 'ev_DAY8' THEN EC_IV_05.ESEQ + 0.08
WHEN EC_IV_05.EVENTEID= 'ev_DAY15' THEN EC_IV_05.ESEQ + 0.15
WHEN EC_IV_05.EVENTEID= 'ev_TUPB' THEN 41 + EC_IV_05.ESEQ * 0.01
WHEN EC_IV_05.EVENTEID= 'ev_EOT' THEN 60
WHEN EC_IV_05.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EC_IV_05.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EC_IV_05.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EC_IV_05.EVENTEID= 'ev_PTFU' THEN 75 + EC_IV_05.ESEQ * 0.01
WHEN EC_IV_05.EVENTEID= 'ev_LFU' THEN 80 + EC_IV_05.ESEQ * 0.01
WHEN EC_IV_05.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EC_IV_05.EVENTEID= 'ev_LOGS' THEN 98
WHEN EC_IV_05.EVENTEID= 'ev_UNS' THEN 99 + EC_IV_05.ESEQ * 0.01
ELSE EC_IV_05.EVENTEID
END as 'VISITNUM'
,EC_IV_05.EVENTDT  'VISITDT'
,EC_IV_05.FORM  'FORM'
,EC_IV_05.FORMDEF  'FORMID'
,EC_IV_05.FSEQ  'FORMSEQ'
, CASE EC_IV_05.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EC_IV_05.FORMSTATUS
	   END AS 'FORMSTATUS'
,EC_IV_05.IGSEQ  'IGSEQ'
,EC_IV_05.DLASTMOD  'DLASTMOD'
,EC_IV_05.DV_ECTRT  'V_ECTRT'
,EC_IV_05.V_QVAL_SCOCCUR  'V_QVAL_SCOCCUR'
,EC_IV_05.V_QVAL_SCREASOC 'V_QVAL_SCREASOC'
,EC_IV_05.V_QVAL_SCREASOT  'V_QVAL_SCREASOT'
,EC_IV_05.V_QVAL_ECADMDEV 'V_QVAL_ECADMDEV'
,EC_IV_05.V_QVAL_ECDEVOT  'V_QVAL_ECDEVOT'
,EC_IV_05.V_QVAL_AESOD  'V_QVAL_AESOD'
,EC_IV_05.V_ECDOSE_SCHEDULED  'V_ECDOSE_SCHEDULED'
,EC_IV_05.DV_ECDOSU_SCHEDULED  'V_ECDOSU_SCHEDULED'
,EC_IV_05.DV_ECROUTE  'V_ECROUTE'
,EC_IV_05.V_ECDOSE_PERFORMED  'V_ECDOSE_PERFORMED'
,EC_IV_05.DV_ECDOSU_PERFORMED 'V_ECDOSU_PERFORMED'

,EC_IV_05.V_ECSTDTC 'V_ECSTDTC'
,EC_IV_05.V_ECSTDTC_DT 'V_ECSTDAT'
,EC_IV_05.V_ECSTDTC_TM  'V_ECSTTIM'

,EC_IV_05.V_ECSTDTC 'X_ECSTDTC'
,EC_IV_05.V_ECSTDTC_DT 'X_ECSTDAT'
,EC_IV_05.V_ECSTDTC_TM  'X_ECSTTIM'

,EC_IV_05.V_ECENDTC  'V_ECENDTC'
,EC_IV_05.V_ECENDTC_DT 'V_ECENDAT'
,EC_IV_05.V_ECENDTC_TM 'V_ECENTIM'

,EC_IV_05.V_ECENDTC  'X_ECENDTC'
,EC_IV_05.V_ECENDTC_DT 'X_ECENDAT'
,EC_IV_05.V_ECENDTC_TM 'X_ECENTIM'

,EC_IV_05.V_ECREFID_S02  'V_ECREFID'
,EC_IV_05.V_ECCINTD_STTIM  'V_ECCINTD_STTIM'
,EC_IV_05.V_ECCINTD_STTIM  'X_ECCINTD_STTIM'
,EC_IV_05.V_ECCINTD_ENTIM  'V_ECCINTD_ENTIM'

,EC_IV_05.V_ECCINTD_ENTIM  'X_ECCINTD_ENTIM'
,EC_IV_05. FL_IDVARVAL_ECAE_S01_DEF FL_IDVARVAL_ECAE01
,EC_IV_05. FL_IDVARVAL_ECAE_S02_DEF FL_IDVARVAL_ECAE02

FROM
              EC_IV_05 EC_IV_05,
              SUBJECTS S1

              WHERE
              S1.SUBJID=EC_IV_05.SUBJID
               AND  S1.SITENUM=EC_IV_05.SITENUM
              AND EC_IV_05.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND EC_IV_05.FORMILB !='true'
    

")

# AND EC_IV_01.FORMILB !='true'
# AND EC_IV_02.FORMILB !='true'
# AND EC_IV_03.FORMILB !='true'
# AND EC_IV_04.FORMILB !='true'
# AND EC_IV_05.FORMILB !='true'

# Call the function -Convert_Date_Vals 
# # new ly added step
# ECGEN_UNION$V_ECSTDTC<- as.POSIXct(ECGEN_UNION$V_ECSTDTC, format = "%Y-%m-%d %H:%M:%S")
# ECGEN_UNION$V_ECSTDTC  <- format(ECGEN_UNION$V_ECSTDTC, "%d-%b-%Y %H:%M")
CharDate_Cols <- c("V_ECSTDTC","V_ECSTDAT", "V_ECENDTC", "V_ECENDAT")#""
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("ECGEN_UNION")
ECGEN_EDC <- Convert_Date_Vals(ECGEN_UNION, CharDate_Cols,datetime_columns,table_name)

# 
# ECGEN_EDC$V_ECSTDTC <- parse_date(ECGEN_EDC$V_ECSTDTC, orders = c("ymd HMS", "ymd", "ym", "y"))
# ECGEN_EDC$V_ECSTDTC <- format(ECGEN_EDC$V_ECSTDTC, "%d-%b-%Y %H:%M")

# one recorde more>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Arrange columns same as CDB
ECGEN_EDC <- ECGEN_EDC[names(ECGEN_CDB)]

# Post processing for compare
ECGEN_EDC$DLASTMOD <- substring(ECGEN_EDC$DLASTMOD,1,16)
ECGEN_EDC$V_ECSTTIM <- substring(ECGEN_EDC$V_ECSTTIM,1,5)
ECGEN_EDC$V_ECENTIM <- substring(ECGEN_EDC$V_ECENTIM,1,5)
# ECGEN_EDC$V_ECSTDTC <- substring(ECGEN_EDC$V_ECSTDTC,1,5)
ECGEN_EDC$V_ECCINTD_STTIM <- substring(ECGEN_EDC$V_ECCINTD_STTIM,1,5)
ECGEN_EDC$V_ECCINTD_ENTIM <- substring(ECGEN_EDC$V_ECCINTD_ENTIM,1,5)
# ECGEN_EDC$V_ECSTDTC <- case_when(ECGEN_EDC$V_ECSTDTC == "00:00" ~ paste(ECGEN_EDC$V_ECSTDTC,ECGEN_EDC$V_ECSTDTC_TM), TRUE ~ ECGEN_EDC$V_ECSTDTC)
ECGEN_EDC <- ECGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
ECGEN_EDC <- ECGEN_EDC[order(ECGEN_EDC$STUDYID,ECGEN_EDC$COUNTRY,ECGEN_EDC$SITENUM,ECGEN_EDC$SUBJID,ECGEN_EDC$VISITNUM,ECGEN_EDC$VISIT,ECGEN_EDC$VISITDT,ECGEN_EDC$FORMID,as.integer(ECGEN_EDC$FORMSEQ),as.integer(ECGEN_EDC$EGSEQ),as.integer(ECGEN_EDC$IGSEQ)), ]

#Generate Compare Summary Report
ECGEN_EDC <- ECGEN_EDC %>% mutate(across(everything(), as.character))
ECGEN_CDB <- ECGEN_CDB %>% mutate(across(everything(), as.character))
ECGEN_SUMMARY <- capture.output(summary(comparedf(ECGEN_EDC, ECGEN_CDB)))
ECGEN_SUMMARY

#Export Summary Report
addWorksheet(wb, "ECGEN_SUMMARY")
writeData(wb, sheet = "ECGEN_SUMMARY", x = ECGEN_SUMMARY)

#Export QC Datasets
write_xpt(ECGEN_EDC,"QC Output/Datasets/EDC/ECGEN_EDC.xpt")
write_xpt(ECGEN_CDB,"QC Output/Datasets/CDB/ECGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)