rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
EGGEN_CDB <- eggen

# Post processing for compare
EGGEN_CDB <- EGGEN_CDB %>% mutate(across(everything(), as.character))
EGGEN_CDB$DLASTMOD <- substring(EGGEN_CDB$DLASTMOD,1,16)
EGGEN_CDB <- EGGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))
EGGEN_CDB <- EGGEN_CDB[order(EGGEN_CDB$STUDYID,EGGEN_CDB$COUNTRY,EGGEN_CDB$SITENUM,EGGEN_CDB$SUBJID,EGGEN_CDB$VISITDT,EGGEN_CDB$FORMID,as.integer(EGGEN_CDB$FORMSEQ),as.integer(EGGEN_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

EG_GEN_01 <- eg_gen_01
EG_GEN_01 <- EG_GEN_01 %>% mutate(across(everything(), as.character))
EG_GEN_01 <- EG_GEN_01 %>% mutate_if(is.character, ~replace_na(.,""))

EG_TPT_01 <- eg_tpt_01
EG_TPT_01 <- EG_TPT_01 %>% mutate(across(everything(), as.character))
EG_TPT_01 <- EG_TPT_01 %>% mutate_if(is.character, ~replace_na(.,""))

EG_UNS_01 <- eg_uns_01
EG_UNS_01 <- EG_UNS_01 %>% mutate(across(everything(), as.character))
EG_UNS_01 <- EG_UNS_01 %>% mutate_if(is.character, ~replace_na(.,""))


#-----------  FINAL union query--
EGGEN_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,EG_GEN_01.COUNTRY  'COUNTRY'
,EG_GEN_01.SITENUM  'SITENUM'
,EG_GEN_01.SUBJID  'SUBJID'
, S1.STATUS 'SUBJSTATUS'
,EG_GEN_01.EGROUPDEF  'EGID'
,EG_GEN_01.ESEQ  'EGSEQ'
,CASE EG_GEN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EG_GEN_01.EGROUP||' '||EG_GEN_01.EVENT
   ELSE EG_GEN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN EG_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EG_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EG_GEN_01.EVENTEID= 'ev_DAY1' THEN EG_GEN_01.ESEQ + 0.01
WHEN EG_GEN_01.EVENTEID= 'ev_DAY8' THEN EG_GEN_01.ESEQ + 0.08
WHEN EG_GEN_01.EVENTEID= 'ev_DAY15' THEN EG_GEN_01.ESEQ + 0.15
WHEN EG_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + EG_GEN_01.ESEQ * 0.01
WHEN EG_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN EG_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EG_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EG_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EG_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + EG_GEN_01.ESEQ * 0.01
WHEN EG_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + EG_GEN_01.ESEQ * 0.01
WHEN EG_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EG_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN EG_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + EG_GEN_01.ESEQ * 0.01
ELSE EG_GEN_01.EVENTEID
END as 'VISITNUM'
,EG_GEN_01.EVENTDT  'VISITDT'
,EG_GEN_01.FORM  'FORM'
,EG_GEN_01.FORMDEF  'FORMID'
,EG_GEN_01.FSEQ  'FORMSEQ'
,CASE EG_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EG_GEN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,EG_GEN_01.IGSEQ  'IGSEQ'
,EG_GEN_01.DLASTMOD  'DLASTMOD'
,EG_GEN_01.DV_EGMETHOD  'V_EGMETHOD'
,EG_GEN_01.V_EGPERF_EGALL  'V_EGPERF_EGALL'
,EG_GEN_01.V_EGREASND_EGALL  'V_EGREASND_EGALL'
,NULL 'V_EGTPTNUM'
,NULL 'V_EGTPT'
,NULL 'V_EGSPID_EGMEAS'

,EG_GEN_01.V_EGDTC  'V_EGDTC'
,EG_GEN_01.V_EGDTC_DT  'V_EGDAT'
,EG_GEN_01.V_EGDTC_TM   'V_EGTIM'
,EG_GEN_01.V_EGDTC  'X_EGDTC'
,EG_GEN_01.V_EGDTC_DT  'X_EGDAT'
,EG_GEN_01.V_EGDTC_TM   'X_EGTIM'

,EG_GEN_01.V_EGORRES_RRAG  'V_EGORRES_RRAG'
,EG_GEN_01.V_EGORRES_RRAG_U  'V_EGORRESU_RRAG'
,EG_GEN_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESC_RRAG'
,EG_GEN_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESN_RRAG'
,EG_GEN_01.V_EGORRES_RRAG_TRANSU  'V_EGSTRESU_RRAG'

,EG_GEN_01.V_EGORRES_PRAG  'V_EGORRES_PRAG'
,EG_GEN_01.V_EGORRES_PRAG_U  'V_EGORRESU_PRAG'
,EG_GEN_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESC_PRAG'
,EG_GEN_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESN_PRAG'
,EG_GEN_01.V_EGORRES_PRAG_TRANSU  'V_EGSTRESU_PRAG'

,EG_GEN_01.V_EGORRES_EGHRMN  'V_EGORRES_EGHRMN'
,EG_GEN_01.V_EGORRES_EGHRMN_U  'V_EGORRESU_EGHRMN'
,EG_GEN_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESC_EGHRMN'
,EG_GEN_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESN_EGHRMN'
,EG_GEN_01.V_EGORRES_EGHRMN_TRANSU  'V_EGSTRESU_EGHRMN'

,EG_GEN_01.V_EGORRES_QRSAG  'V_EGORRES_QRSAG'
,EG_GEN_01.V_EGORRES_QRSAG_U  'V_EGORRESU_QRSAG'
,EG_GEN_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESC_QRSAG'
,EG_GEN_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESN_QRSAG'
,EG_GEN_01.V_EGORRES_QRSAG_TRANSU  'V_EGSTRESU_QRSAG'

,EG_GEN_01.V_EGORRES_QTAG  'V_EGORRES_QTAG'
,EG_GEN_01.V_EGORRES_QTAG_U  'V_EGORRESU_QTAG'
,EG_GEN_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESC_QTAG'
,EG_GEN_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESN_QTAG'
,EG_GEN_01.V_EGORRES_QTAG_TRANSU  'V_EGSTRESU_QTAG'

,EG_GEN_01.V_EGORRES_QTCFAG  'V_EGORRES_QTCFAG'
,EG_GEN_01.V_EGORRES_QTCFAG_U  'V_EGORRESU_QTCFAG'
,EG_GEN_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESC_QTCFAG'
,EG_GEN_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESN_QTCFAG'
,EG_GEN_01.V_EGORRES_QTCFAG_TRANSU  'V_EGSTRESU_QTCFAG'

,EG_GEN_01.V_EGORRES_INTP  'V_EGORRES_INTP'
FROM
              EG_GEN_01 EG_GEN_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=EG_GEN_01.SUBJID
              AND S1.SITENUM=EG_GEN_01.SITENUM
              AND EG_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND EG_GEN_01.FORMILB !='true'
UNION

SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,EG_TPT_01.COUNTRY  'COUNTRY'
,EG_TPT_01.SITENUM  'SITENUM'
,EG_TPT_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EG_TPT_01.EGROUPDEF  'EGID'
,EG_TPT_01.ESEQ  'EGSEQ'
,CASE EG_TPT_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EG_TPT_01.EGROUP||' '||EG_TPT_01.EVENT
   ELSE EG_TPT_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN EG_TPT_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EG_TPT_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EG_TPT_01.EVENTEID= 'ev_DAY1' THEN EG_TPT_01.ESEQ + 0.01
WHEN EG_TPT_01.EVENTEID= 'ev_DAY8' THEN EG_TPT_01.ESEQ + 0.08
WHEN EG_TPT_01.EVENTEID= 'ev_DAY15' THEN EG_TPT_01.ESEQ + 0.15
WHEN EG_TPT_01.EVENTEID= 'ev_TUPB' THEN 41 + EG_TPT_01.ESEQ * 0.01
WHEN EG_TPT_01.EVENTEID= 'ev_EOT' THEN 60
WHEN EG_TPT_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EG_TPT_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EG_TPT_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EG_TPT_01.EVENTEID= 'ev_PTFU' THEN 75 + EG_TPT_01.ESEQ * 0.01
WHEN EG_TPT_01.EVENTEID= 'ev_LFU' THEN 80 + EG_TPT_01.ESEQ * 0.01
WHEN EG_TPT_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EG_TPT_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN EG_TPT_01.EVENTEID= 'ev_UNS' THEN 99 + EG_TPT_01.ESEQ * 0.01
ELSE EG_TPT_01.EVENTEID
END as 'VISITNUM'
,EG_TPT_01.EVENTDT  'VISITDT'
,EG_TPT_01.FORM  'FORM'
,EG_TPT_01.FORMDEF  'FORMID'
,EG_TPT_01.FSEQ  'FORMSEQ'
,CASE EG_TPT_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EG_TPT_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,EG_TPT_01.IGSEQ  'IGSEQ'
,EG_TPT_01.DLASTMOD  'DLASTMOD'
,EG_TPT_01.DV_EGMETHOD 'V_EGMETHOD'
,EG_TPT_01.V_EGPERF_EGALL  'V_EGPERF_EGALL'
,EG_TPT_01.V_EGREASND_EGALL  'V_EGREASND_EGALL'

,CASE EG_TPT_01.DV_EGTPT
WHEN 'PRE-INFUSION EIK1001' THEN '0'
WHEN '0.0 HOUR POST INFUSION EIK1001' THEN '0.1'
ELSE  EG_TPT_01.DV_EGTPT
END AS 'V_EGTPTNUM'
,EG_TPT_01.DV_EGTPT_D 'V_EGTPT'
,EG_TPT_01.DV_EGSPID_EGMEAS  'V_EGSPID_EGMEAS'

,EG_TPT_01.V_EGDTC  'V_EGDTC'
,EG_TPT_01.V_EGDTC_DT  'V_EGDAT'
,EG_TPT_01.V_EGDTC_TM   'V_EGTIM'
,EG_TPT_01.V_EGDTC  'X_EGDTC'
,EG_TPT_01.V_EGDTC_DT  'X_EGDAT'
,EG_TPT_01.V_EGDTC_TM   'X_EGTIM'

,EG_TPT_01.V_EGORRES_RRAG  'V_EGORRES_RRAG'
,EG_TPT_01.V_EGORRES_RRAG_U  'V_EGORRESU_RRAG'
,EG_TPT_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESC_RRAG'
,EG_TPT_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESN_RRAG'
,EG_TPT_01.V_EGORRES_RRAG_TRANSU  'V_EGSTRESU_RRAG'

,EG_TPT_01.V_EGORRES_PRAG  'V_EGORRES_PRAG'
,EG_TPT_01.V_EGORRES_PRAG_U  'V_EGORRESU_PRAG'
,EG_TPT_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESC_PRAG'
,EG_TPT_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESN_PRAG'
,EG_TPT_01.V_EGORRES_PRAG_TRANSU  'V_EGSTRESU_PRAG'

,EG_TPT_01.V_EGORRES_EGHRMN  'V_EGORRES_EGHRMN'
,EG_TPT_01.V_EGORRES_EGHRMN_U  'V_EGORRESU_EGHRMN'
,EG_TPT_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESC_EGHRMN'
,EG_TPT_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESN_EGHRMN'
,EG_TPT_01.V_EGORRES_EGHRMN_TRANSU  'V_EGSTRESU_EGHRMN'

,EG_TPT_01.V_EGORRES_QRSAG  'V_EGORRES_QRSAG'
,EG_TPT_01.V_EGORRES_QRSAG_U  'V_EGORRESU_QRSAG'
,EG_TPT_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESC_QRSAG'
,EG_TPT_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESN_QRSAG'
,EG_TPT_01.V_EGORRES_QRSAG_TRANSU  'V_EGSTRESU_QRSAG'

,EG_TPT_01.V_EGORRES_QTAG  'V_EGORRES_QTAG'
,EG_TPT_01.V_EGORRES_QTAG_U  'V_EGORRESU_QTAG'
,EG_TPT_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESC_QTAG'
,EG_TPT_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESN_QTAG'
,EG_TPT_01.V_EGORRES_QTAG_TRANSU  'V_EGSTRESU_QTAG'

,EG_TPT_01.V_EGORRES_QTCFAG  'V_EGORRES_QTCFAG'
,EG_TPT_01.V_EGORRES_QTCFAG_U  'V_EGORRESU_QTCFAG'
,EG_TPT_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESC_QTCFAG'
,EG_TPT_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESN_QTCFAG'
,EG_TPT_01.V_EGORRES_QTCFAG_TRANSU  'V_EGSTRESU_QTCFAG'

,EG_TPT_01.V_EGORRES_INTP  'V_EGORRES_INTP'
FROM
              EG_TPT_01 EG_TPT_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=EG_TPT_01.SUBJID
              AND S1.SITENUM=EG_TPT_01.SITENUM
              AND EG_TPT_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND EG_TPT_01.FORMILB !='true'
    

UNION



SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,EG_UNS_01.COUNTRY  'COUNTRY'
,EG_UNS_01.SITENUM  'SITENUM'
,EG_UNS_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,EG_UNS_01.EGROUPDEF  'EGID'
,EG_UNS_01.ESEQ  'EGSEQ'
,CASE EG_UNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN EG_UNS_01.EGROUP||' '||EG_UNS_01.EVENT
   ELSE EG_UNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN EG_UNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN EG_UNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN EG_UNS_01.EVENTEID= 'ev_DAY1' THEN EG_UNS_01.ESEQ + 0.01
WHEN EG_UNS_01.EVENTEID= 'ev_DAY8' THEN EG_UNS_01.ESEQ + 0.08
WHEN EG_UNS_01.EVENTEID= 'ev_DAY15' THEN EG_UNS_01.ESEQ + 0.15
WHEN EG_UNS_01.EVENTEID= 'ev_TUPB' THEN 41 + EG_UNS_01.ESEQ * 0.01
WHEN EG_UNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN EG_UNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN EG_UNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN EG_UNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN EG_UNS_01.EVENTEID= 'ev_PTFU' THEN 75 + EG_UNS_01.ESEQ * 0.01
WHEN EG_UNS_01.EVENTEID= 'ev_LFU' THEN 80 + EG_UNS_01.ESEQ * 0.01
WHEN EG_UNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN EG_UNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN EG_UNS_01.EVENTEID= 'ev_UNS' THEN 99 + EG_UNS_01.ESEQ * 0.01
ELSE EG_UNS_01.EVENTEID
END as 'VISITNUM'
,EG_UNS_01.EVENTDT  'VISITDT'
,EG_UNS_01.FORM  'FORM'
,EG_UNS_01.FORMDEF  'FORMID'
,EG_UNS_01.FSEQ  'FORMSEQ'
,CASE EG_UNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  EG_UNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,EG_UNS_01.IGSEQ  'IGSEQ'
,EG_UNS_01.DLASTMOD  'DLASTMOD'
,EG_UNS_01.DV_EGMETHOD  'V_EGMETHOD'
,NULL  'V_EGPERF_EGALL'
,NULL  'V_EGREASND_EGALL'
,NULL  'V_EGTPTNUM'
,NULL  'V_EGTPT'
,NULL  'V_EGSPID_EGMEAS'
,EG_UNS_01.V_EGDTC  'V_EGDTC'
,EG_UNS_01.V_EGDTC_DT  'V_EGDAT'
,EG_UNS_01.V_EGDTC_TM  'V_EGTIM'
,EG_UNS_01.V_EGDTC  'X_EGDTC'
,EG_UNS_01.V_EGDTC_DT  'X_EGDAT'
,EG_UNS_01.V_EGDTC_TM  'X_EGTIM'

,EG_UNS_01.V_EGORRES_RRAG  'V_EGORRES_RRAG'
,EG_UNS_01.V_EGORRES_RRAG_U  'V_EGORRESU_RRAG'
,EG_UNS_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESC_RRAG'
,EG_UNS_01.V_EGORRES_RRAG_TRANS  'V_EGSTRESN_RRAG'
,EG_UNS_01.V_EGORRES_RRAG_TRANSU  'V_EGSTRESU_RRAG'

,EG_UNS_01.V_EGORRES_PRAG  'V_EGORRES_PRAG'
,EG_UNS_01.V_EGORRES_PRAG_U  'V_EGORRESU_PRAG'
,EG_UNS_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESC_PRAG'
,EG_UNS_01.V_EGORRES_PRAG_TRANS  'V_EGSTRESN_PRAG'
,EG_UNS_01.V_EGORRES_PRAG_TRANSU  'V_EGSTRESU_PRAG'

,EG_UNS_01.V_EGORRES_EGHRMN  'V_EGORRES_EGHRMN'
,EG_UNS_01.V_EGORRES_EGHRMN_U  'V_EGORRESU_EGHRMN'
,EG_UNS_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESC_EGHRMN'
,EG_UNS_01.V_EGORRES_EGHRMN_TRANS  'V_EGSTRESN_EGHRMN'
,EG_UNS_01.V_EGORRES_EGHRMN_TRANSU  'V_EGSTRESU_EGHRMN'

,EG_UNS_01.V_EGORRES_QRSAG  'V_EGORRES_QRSAG'
,EG_UNS_01.V_EGORRES_QRSAG_U  'V_EGORRESU_QRSAG'
,EG_UNS_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESC_QRSAG'
,EG_UNS_01.V_EGORRES_QRSAG_TRANS  'V_EGSTRESN_QRSAG'
,EG_UNS_01.V_EGORRES_QRSAG_TRANSU  'V_EGSTRESU_QRSAG'

,EG_UNS_01.V_EGORRES_QTAG  'V_EGORRES_QTAG'
,EG_UNS_01.V_EGORRES_QTAG_U  'V_EGORRESU_QTAG'
,EG_UNS_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESC_QTAG'
,EG_UNS_01.V_EGORRES_QTAG_TRANS  'V_EGSTRESN_QTAG'
,EG_UNS_01.V_EGORRES_QTAG_TRANSU  'V_EGSTRESU_QTAG'

,EG_UNS_01.V_EGORRES_QTCFAG  'V_EGORRES_QTCFAG'
,EG_UNS_01.V_EGORRES_QTCFAG_U  'V_EGORRESU_QTCFAG'
,EG_UNS_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESC_QTCFAG'
,EG_UNS_01.V_EGORRES_QTCFAG_TRANS  'V_EGSTRESN_QTCFAG'
,EG_UNS_01.V_EGORRES_QTCFAG_TRANSU  'V_EGSTRESU_QTCFAG'

,EG_UNS_01.V_EGORRES_INTP  'V_EGORRES_INTP'
FROM
              EG_UNS_01 EG_UNS_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=EG_UNS_01.SUBJID
              AND S1.SITENUM=EG_UNS_01.SITENUM
              AND EG_UNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND EG_UNS_01.FORMILB !='true'
  
   "
  )

# AND EG_GEN_01.FORMILB !='true'
# AND EG_TPT_01.FORMILB !='true'
# AND EG_UNS_01.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <-c("V_EGDTC","V_EGDAT")
datetime_columns <- NULL #c("V_EGDTC")
table_name <- c("EGGEN_UNION")
EGGEN_EDC <- Convert_Date_Vals(EGGEN_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
EGGEN_EDC <- EGGEN_EDC[names(EGGEN_CDB)]

# Post processing for compare
EGGEN_EDC$DLASTMOD <- substring(EGGEN_EDC$DLASTMOD,1,16)
EGGEN_EDC$V_EGTIM <- substring(EGGEN_EDC$V_EGTIM,1,5)
EGGEN_EDC <- EGGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
EGGEN_EDC <- EGGEN_EDC[order(EGGEN_EDC$STUDYID,EGGEN_EDC$COUNTRY,EGGEN_EDC$SITENUM,EGGEN_EDC$SUBJID,EGGEN_EDC$VISITDT,EGGEN_EDC$FORMID,as.integer(EGGEN_EDC$FORMSEQ),as.integer(EGGEN_EDC$IGSEQ)), ]
EGGEN_EDC <- EGGEN_EDC %>% mutate(across(everything(), as.character))
#Generate Compare Summary Report
EGGEN_SUMMARY <- capture.output(summary(comparedf(EGGEN_EDC, EGGEN_CDB)))
EGGEN_SUMMARY

#Export Summary Report
addWorksheet(wb, "EGGEN_SUMMARY")
writeData(wb, sheet = "EGGEN_SUMMARY", x = EGGEN_SUMMARY)

#Export QC Datasets
write_xpt(EGGEN_EDC,"QC Output/Datasets/EDC/EGGEN_EDC.xpt")
write_xpt(EGGEN_CDB,"QC Output/Datasets/CDB/EGGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)