rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
ISADA_CDB <- isada
# Post processing for compare
ISADA_CDB <- ISADA_CDB %>% mutate(across(everything(), as.character))
ISADA_CDB$DLASTMOD <- substring(ISADA_CDB$DLASTMOD,1,16)
ISADA_CDB <- ISADA_CDB %>% mutate_if(is.character, ~replace_na(.,""))
ISADA_CDB <- ISADA_CDB[order(ISADA_CDB$STUDYID,ISADA_CDB$COUNTRY,ISADA_CDB$SITENUM,ISADA_CDB$SUBJID,ISADA_CDB$VISITDT,ISADA_CDB$FORMID,as.integer(ISADA_CDB$FORMSEQ),as.integer(ISADA_CDB$IGSEQ),ISADA_CDB$EGID,ISADA_CDB$VISIT), ]

## Get EDC Data
SUBJECTS <- sys_sub

IS_ADA_01 <- is_ada_01
IS_ADA_01 <- IS_ADA_01 %>% mutate(across(everything(), as.character))
IS_ADA_01 <- IS_ADA_01 %>% mutate_if(is.character, ~replace_na(.,""))

IS_ADAUNS_01 <- is_adauns_01
IS_ADAUNS_01 <- IS_ADAUNS_01 %>% mutate(across(everything(), as.character))
IS_ADAUNS_01 <- IS_ADAUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))



#-----------  FINAL union query--
ISADA_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,IS_ADA_01.COUNTRY  'COUNTRY'
,IS_ADA_01.SITENUM  'SITENUM'
,IS_ADA_01.SUBJID  'SUBJID'
, S1.STATUS 'SUBJSTATUS'
,IS_ADA_01.EGROUPDEF  'EGID'
,IS_ADA_01.ESEQ  'EGSEQ'
,CASE IS_ADA_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN IS_ADA_01.EGROUP||' '||IS_ADA_01.EVENT
   ELSE IS_ADA_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN IS_ADA_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN IS_ADA_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN IS_ADA_01.EVENTEID= 'ev_DAY1' THEN IS_ADA_01.ESEQ + 0.01
WHEN IS_ADA_01.EVENTEID= 'ev_DAY8' THEN IS_ADA_01.ESEQ + 0.08
WHEN IS_ADA_01.EVENTEID= 'ev_DAY15' THEN IS_ADA_01.ESEQ + 0.15
WHEN IS_ADA_01.EVENTEID= 'ev_TUPB' THEN 41 + IS_ADA_01.ESEQ * 0.01
WHEN IS_ADA_01.EVENTEID= 'ev_EOT' THEN 60
WHEN IS_ADA_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN IS_ADA_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN IS_ADA_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN IS_ADA_01.EVENTEID= 'ev_PTFU' THEN 75 + IS_ADA_01.ESEQ * 0.01
WHEN IS_ADA_01.EVENTEID= 'ev_LFU' THEN 80 + IS_ADA_01.ESEQ * 0.01
WHEN IS_ADA_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN IS_ADA_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN IS_ADA_01.EVENTEID= 'ev_UNS' THEN 99 + IS_ADA_01.ESEQ * 0.01
ELSE IS_ADA_01.EVENTEID
END as 'VISITNUM'
,IS_ADA_01.EVENTDT  'VISITDT'
,IS_ADA_01.FORM  'FORM'
,IS_ADA_01.FORMDEF  'FORMID'
,IS_ADA_01.FSEQ  'FORMSEQ'
,CASE IS_ADA_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  IS_ADA_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,IS_ADA_01.IGSEQ  'IGSEQ'
,IS_ADA_01.DLASTMOD  'DLASTMOD'
,IS_ADA_01.DV_ISCAT  'V_ISCAT'
,IS_ADA_01.DV_ISBDAGNT  'V_ISBDAGNT'
,IS_ADA_01.V_ISPERF_ISALL  'V_ISPERF_ISALL'
,IS_ADA_01.V_ISREASND  'V_ISREASND'
,IS_ADA_01.DV_ISSPEC 'V_ISSPEC'
,CASE IS_ADA_01.DV_ISTPT
WHEN '0.0' THEN '0'
ELSE  IS_ADA_01.DV_ISTPT
END AS 'V_ISTPTNUM'
,IS_ADA_01.DV_ISTPT_D  'V_ISTPT'
,IS_ADA_01.DV_ISTPTREF  'V_ISTPTREF'
,IS_ADA_01.V_ISSTAT  'V_ISSTAT'
,IS_ADA_01.V_ISDTC  'V_ISDTC'
,IS_ADA_01.V_ISDTC_DT 'V_ISDAT'
,IS_ADA_01.V_ISDTC_TM  'V_ISTIM'
,IS_ADA_01.V_ISDTC  'X_ISDTC'
,IS_ADA_01.V_ISDTC_DT 'X_ISDAT'
,IS_ADA_01.V_ISDTC_TM  'X_ISTIM'
FROM
              IS_ADA_01 IS_ADA_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=IS_ADA_01.SUBJID
              AND S1.SITENUM=IS_ADA_01.SITENUM
              AND IS_ADA_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
              AND IS_ADA_01.FORMILB !='true'
  

UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,IS_ADAUNS_01.COUNTRY  'COUNTRY'
,IS_ADAUNS_01.SITENUM  'SITENUM'
,IS_ADAUNS_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,IS_ADAUNS_01.EGROUPDEF  'EGID'
,IS_ADAUNS_01.ESEQ  'EGSEQ'
,CASE IS_ADAUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN IS_ADAUNS_01.EGROUP||' '||IS_ADAUNS_01.EVENT
   ELSE IS_ADAUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN IS_ADAUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN IS_ADAUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN IS_ADAUNS_01.EVENTEID= 'ev_DAY1' THEN IS_ADAUNS_01.ESEQ + 0.01
WHEN IS_ADAUNS_01.EVENTEID= 'ev_DAY8' THEN IS_ADAUNS_01.ESEQ + 0.08
WHEN IS_ADAUNS_01.EVENTEID= 'ev_DAY15' THEN IS_ADAUNS_01.ESEQ + 0.15
WHEN IS_ADAUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + IS_ADAUNS_01.ESEQ * 0.01
WHEN IS_ADAUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN IS_ADAUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN IS_ADAUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN IS_ADAUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN IS_ADAUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + IS_ADAUNS_01.ESEQ * 0.01
WHEN IS_ADAUNS_01.EVENTEID= 'ev_LFU' THEN 80 + IS_ADAUNS_01.ESEQ * 0.01
WHEN IS_ADAUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN IS_ADAUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN IS_ADAUNS_01.EVENTEID= 'ev_UNS' THEN 99 + IS_ADAUNS_01.ESEQ * 0.01
ELSE IS_ADAUNS_01.EVENTEID
END as 'VISITNUM'
,IS_ADAUNS_01.EVENTDT  'VISITDT'
,IS_ADAUNS_01.FORM  'FORM'
,IS_ADAUNS_01.FORMDEF  'FORMID'
,IS_ADAUNS_01.FSEQ  'FORMSEQ'
,CASE IS_ADAUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  IS_ADAUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,IS_ADAUNS_01.IGSEQ  'IGSEQ'
,IS_ADAUNS_01.DLASTMOD  'DLASTMOD'
,IS_ADAUNS_01.DV_ISCAT  'V_ISCAT'
,IS_ADAUNS_01.DV_ISBDAGNT  'V_ISBDAGNT'
,NULL  'V_ISPERF_ISALL'
,NULL  'V_ISREASND'
,IS_ADAUNS_01.DV_ISSPEC 'V_ISSPEC'
,NULL  'V_ISTPTNUM'
,NULL  'V_ISTPT'
,NULL  'V_ISTPTREF'
,NULL 'V_ISSTAT'
,IS_ADAUNS_01.V_ISDTC  'V_ISDTC'
,IS_ADAUNS_01.V_ISDTC_DT 'V_ISDAT'
,IS_ADAUNS_01.V_ISDTC_TM  'V_ISTIM'
,IS_ADAUNS_01.V_ISDTC  'X_ISDTC'
,IS_ADAUNS_01.V_ISDTC_DT 'X_ISDAT'
,IS_ADAUNS_01.V_ISDTC_TM  'X_ISTIM'
FROM
              IS_ADAUNS_01 IS_ADAUNS_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=IS_ADAUNS_01.SUBJID
              AND S1.SITENUM=IS_ADAUNS_01.SITENUM
              AND IS_ADAUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
              AND IS_ADAUNS_01.FORMILB !='true'
    
")


# AND IS_ADA_01.FORMILB !='true'
# AND IS_ADAUNS_01.FORMILB !='true'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_ISDTC", "V_ISDAT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("ISADA_UNION")
ISADA_EDC <- Convert_Date_Vals(ISADA_UNION, CharDate_Cols,datetime_columns,table_name)

#arrange columns as same as CDB
ISADA_EDC <- ISADA_EDC[names(ISADA_CDB)]

# Post processing for compare
ISADA_EDC$DLASTMOD <- substring(ISADA_EDC$DLASTMOD,1,16)
ISADA_EDC$V_ISTIM <- substring(ISADA_EDC$V_ISTIM,1,5)
ISADA_EDC <- ISADA_EDC %>% mutate_if(is.character, ~replace_na(.,""))
ISADA_EDC <- ISADA_EDC[order(ISADA_EDC$STUDYID,ISADA_EDC$COUNTRY,ISADA_EDC$SITENUM,ISADA_EDC$SUBJID,ISADA_EDC$VISITDT,ISADA_EDC$FORMID,as.integer(ISADA_EDC$FORMSEQ),as.integer(ISADA_EDC$IGSEQ),ISADA_EDC$EGID,ISADA_EDC$VISIT), ]

#Generate Compare Summary Report
ISADA_EDC <- ISADA_EDC %>% mutate(across(everything(), as.character))
ISADA_CDB <- ISADA_CDB %>% mutate(across(everything(), as.character))
ISADA_SUMMARY <- capture.output(summary(comparedf(ISADA_EDC, ISADA_CDB)))
ISADA_SUMMARY

#Export Summary Report
addWorksheet(wb, "ISADA_SUMMARY")
writeData(wb, sheet = "ISADA_SUMMARY", x = ISADA_SUMMARY)

#Export QC Datasets
write_xpt(ISADA_EDC,"QC Output/Datasets/EDC/ISADA_EDC.xpt")
write_xpt(ISADA_CDB,"QC Output/Datasets/CDB/ISADA_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)