
# library(readr)
rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)
# options(digits = 5)
## Get CDB Data
# options(scipen = -10)
LBLOCAL_CDB <- lblocal
#######################function for handle numeric
format_numeric_column <- function(x) {
  suppressWarnings(case_when(
    !is.na(as.numeric(x)) ~ 
      formatC(as.numeric(x), digits=2, format="f"), 
    TRUE ~ as.character(x)
  ))
}
#############pass variable in sling shot
columns_to_format <- c(
  "V_LBORRES", "V_LBSTRESC", "V_LBORNRLO", "V_LBORNRHI", 
  "V_LBSTNRLO", "V_LBSTNRHI", "V_LBORNRLO_OVRD", 
  "V_LBORNRHI_OVRD", "V_LBSTNRLO_OVRD", "V_LBSTNRHI_OVRD"
)

########################### call function and variables
LBLOCAL_CDB <- LBLOCAL_CDB %>%
  mutate(across(all_of(columns_to_format), ~ format_numeric_column(.)))

LBLOCAL_CDB <- LBLOCAL_CDB %>% mutate(across(everything(), as.character))
LBLOCAL_CDB$DLASTMOD <- substring(LBLOCAL_CDB$DLASTMOD,1,16)
LBLOCAL_CDB <- LBLOCAL_CDB %>% mutate_if(is.character, ~replace_na(.,""))
LBLOCAL_CDB <- LBLOCAL_CDB[order(LBLOCAL_CDB$STUDYID,LBLOCAL_CDB$COUNTRY,LBLOCAL_CDB$SITENUM,LBLOCAL_CDB$SUBJID,as.integer(LBLOCAL_CDB$EGSEQ),LBLOCAL_CDB$VISIT,LBLOCAL_CDB$VISITDT,LBLOCAL_CDB$FORMID,as.integer(LBLOCAL_CDB$FORMSEQ),LBLOCAL_CDB$DX_LBCAT,LBLOCAL_CDB$DX_LBSCAT,LBLOCAL_CDB$V_LBTESTCD), ]
unique_values <- sapply(LBLOCAL_CDB, function(x) unique(x))
 unique_values
## Get EDC Data
LBANALYTE <- sys_analytes
SYSILB <- sys_ilb

SUBJECTS <- sys_sub

LB_CHEM_01 <- lb_chem_01
dim(LB_CHEM_01)
# Example usage:
columns_to_format <- c(
  "LBORRES", "LBORRES_TRANS", "LBORNRLO", "LBORNRHI", 
  "LBORNRLO_TRANS", "LBORNRHI_TRANS", "LBOVRDNRLO", 
  "LBOVRDNRHI", "LBOVRDNRLO_TRANS", "LBOVRDNRHI_TRANS"
)

LB_CHEM_01 <-LB_CHEM_01 %>%
  mutate(across(all_of(columns_to_format), ~ format_numeric_column(.)))

LB_CHEM_01 <- LB_CHEM_01 %>% mutate(across(everything(), as.character))
LB_CHEM_01 <- LB_CHEM_01 %>% mutate_if(is.character, ~replace_na(.,""))

LB_COAG_01 <- lb_coag_01
dim(LB_COAG_01 )

columns_to_format <- c(
  "LBORRES", "LBORRES_TRANS", "LBORNRLO", "LBORNRHI", 
  "LBORNRLO_TRANS", "LBORNRHI_TRANS", "LBOVRDNRLO", 
  "LBOVRDNRHI", "LBOVRDNRLO_TRANS", "LBOVRDNRHI_TRANS"
)

LB_COAG_01 <- LB_COAG_01 %>%
  mutate(across(all_of(columns_to_format), ~ ifelse(is.na(.), ., formatC(as.numeric(.), digits = 2, format = "f"))))


LB_COAG_01 <- LB_COAG_01 %>% mutate(across(everything(), as.character))
LB_COAG_01 <- LB_COAG_01 %>% mutate_if(is.character, ~replace_na(.,""))


LB_HEMA_01 <- lb_hema_01
dim(LB_HEMA_01 )
columns_to_format <- c(
  "LBORRES", "LBORRES_TRANS", "LBORNRLO", "LBORNRHI", 
  "LBORNRLO_TRANS", "LBORNRHI_TRANS", "LBOVRDNRLO", 
  "LBOVRDNRHI", "LBOVRDNRLO_TRANS", "LBOVRDNRHI_TRANS"
)

LB_HEMA_01 <- LB_HEMA_01 %>%
  mutate(across(all_of(columns_to_format), ~ ifelse(is.na(.), ., formatC(as.numeric(.), digits = 2, format = "f"))))


LB_HEMA_01 <- LB_HEMA_01 %>% mutate(across(everything(), as.character))
LB_HEMA_01 <- LB_HEMA_01 %>% mutate_if(is.character, ~replace_na(.,""))


LB_PREG_01 <- lb_preg_01
dim(LB_PREG_01 )
LB_PREG_01 <- LB_PREG_01 %>% mutate(across(everything(), as.character))
LB_PREG_01 <- LB_PREG_01 %>% mutate_if(is.character, ~replace_na(.,""))

LB_PREGUNS_01 <- lb_preguns_01
dim(LB_PREGUNS_01 )
LB_PREGUNS_01 <- LB_PREGUNS_01 %>% mutate(across(everything(), as.character))
LB_PREGUNS_01 <- LB_PREGUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))

LB_THYR_01 <- lb_thyr_01
dim(LB_THYR_01 )
LB_THYR_01 <- LB_THYR_01 %>% mutate(across(everything(), as.character))
LB_THYR_01 <- LB_THYR_01 %>% mutate_if(is.character, ~replace_na(.,""))

LB_THYR_02 <- lb_thyr_02
dim(LB_THYR_02 )
LB_THYR_02 <- LB_THYR_02 %>% mutate(across(everything(), as.character))
LB_THYR_02 <- LB_THYR_02 %>% mutate_if(is.character, ~replace_na(.,""))



LB_URIN_01 <- lb_urin_01
dim(LB_URIN_01 )
# LB_URIN_01$V_LBORRES_URIN <- suppressWarnings(case_when(as.numeric(LB_URIN_01$V_LBORRES_URIN) != "NA" ~ formatC(as.numeric(LB_URIN_01$V_LBORRES_URIN), digits=2, format="f"), TRUE ~ LB_URIN_01$V_LBORRES_URIN))
# LB_URIN_01$V_LBORRES_MIURIN <- suppressWarnings(case_when(as.numeric(LB_URIN_01$V_LBORRES_MIURIN) != "NA" ~ formatC(as.numeric(LB_URIN_01$V_LBORRES_MIURIN), digits=2, format="f"), TRUE ~ LB_URIN_01$V_LBORRES_MIURIN))

# Example usage:
columns_to_format <- c( "V_LBORRES_URIN", "V_LBORRES_MIURIN")

# LB_URIN_01 <- LB_URIN_01  %>%
#   mutate(across(all_of(columns_to_format), ~ ifelse(is.na(.), ., formatC(as.numeric(.), digits = 2, format = "f"))))

LB_URIN_01 <- LB_URIN_01%>%
  mutate(across(all_of(columns_to_format), ~ format_numeric_column(.)))

LB_URIN_01 <- LB_URIN_01 %>% mutate(across(everything(), as.character))
LB_URIN_01 <- LB_URIN_01 %>% mutate_if(is.character, ~replace_na(.,""))

LB_URINUNS_01 <- lb_urinuns_01
dim(LB_URINUNS_01)
LB_URINUNS_01$V_LBORRES_URIN <- suppressWarnings(case_when(as.numeric(LB_URINUNS_01$V_LBORRES_URIN) != "NA" ~ formatC(as.numeric(LB_URINUNS_01$V_LBORRES_URIN), digits=2, format="f"), TRUE ~ LB_URINUNS_01$V_LBORRES_URIN))
LB_URINUNS_01$V_LBORRES_MIURIN <- suppressWarnings(case_when(as.numeric(LB_URINUNS_01$V_LBORRES_MIURIN) != "NA" ~ formatC(as.numeric(LB_URINUNS_01$V_LBORRES_MIURIN), digits=2, format="f"), TRUE ~ LB_URINUNS_01$V_LBORRES_MIURIN))
LB_URINUNS_01 <- LB_URINUNS_01 %>% mutate(across(everything(), as.character))
LB_URINUNS_01 <- LB_URINUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))

nrow(LB_CHEM_01)+nrow(LB_COAG_01)+nrow(LB_HEMA_01)+nrow(LB_PREG_01)+nrow(LB_PREGUNS_01)+nrow(LB_THYR_01)+nrow(LB_THYR_02)+nrow(LB_URIN_01)+nrow(LB_URINUNS_01)

# ----------  FINAL union query--

LBLOCAL_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_CHEM_01.COUNTRY  'COUNTRY'
,LB_CHEM_01.SITENUM  'SITENUM'
,LB_CHEM_01.SUBJID  'SUBJID'
,S1.STATUS  'SUBJSTATUS'
,LB_CHEM_01.EGROUPDEF  'EGID'
,LB_CHEM_01.ESEQ  'EGSEQ'
,CASE LB_CHEM_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_CHEM_01.EGROUP||' '||LB_CHEM_01.EVENT
   ELSE LB_CHEM_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_CHEM_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_CHEM_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_CHEM_01.EVENTEID= 'ev_DAY1' THEN LB_CHEM_01.ESEQ + 0.01
WHEN LB_CHEM_01.EVENTEID= 'ev_DAY8' THEN LB_CHEM_01.ESEQ + 0.08
WHEN LB_CHEM_01.EVENTEID= 'ev_DAY15' THEN LB_CHEM_01.ESEQ + 0.15
WHEN LB_CHEM_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_CHEM_01.ESEQ * 0.01
WHEN LB_CHEM_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_CHEM_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_CHEM_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_CHEM_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_CHEM_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_CHEM_01.ESEQ * 0.01
WHEN LB_CHEM_01.EVENTEID= 'ev_LFU' THEN 80 + LB_CHEM_01.ESEQ * 0.01
WHEN LB_CHEM_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_CHEM_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_CHEM_01.EVENTEID= 'ev_UNS' THEN 99 + LB_CHEM_01.ESEQ * 0.01
ELSE LB_CHEM_01.EVENTEID
END as 'VISITNUM'
   
,LB_CHEM_01.EVENTDT  'VISITDT'
,LB_CHEM_01.FORM  'FORM'
,LB_CHEM_01.FORMDEF  'FORMID'
,LB_CHEM_01.FSEQ  'FORMSEQ'
,CASE LB_CHEM_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_CHEM_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_CHEM_01.IGSEQ  'IGSEQ'
,LB_CHEM_01.DLASTMOD  'DLASTMOD'
, 'CHEMISTRY' 'DX_LBCAT'
, null 'DX_LBSCAT'
--,Null 'V_LBPERF_LBALL'--
,CASE 
    WHEN LB_CHEM_01.FORMILB != 'true' THEN 'Y'
    ELSE 'N'
  END AS 'V_LBPERF_LBALL'
  
,NULL 'V_LBREASND_LBALL'
  
,LB_CHEM_01.LBLOC 'V_LBNAM'
,LB_CHEM_01.LBAGE 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_CHEM_01.LBDTC 'V_LBDTC'
,LB_CHEM_01.LBDTC_DT 'V_LBDAT'
,LB_CHEM_01.LBDTC_TM 'V_LBTIM'
,LB_CHEM_01.LBDTC 'X_LBDTC'
,LB_CHEM_01.LBDTC_DT 'X_LBDAT'
,LB_CHEM_01.LBDTC_TM 'X_LBTIM'
,LB_CHEM_01.LBTEST 'V_LBTESTCD'
,(SELECT LBA.LABANALYTELABEL FROM LBANALYTE LBA
  WHERE LBA.LABANALYTENAME = LB_CHEM_01.LBTEST) AS 'V_LBTEST'
--, NULL 'V_LBSTAT'--
,CASE WHEN LB_CHEM_01.FORMILB != 'true' THEN
   CASE WHEN LB_CHEM_01.LBORRES == 'true' THEN 'true'
                ELSE NULL  END   ELSE NULL
    END AS 'V_LBSTAT'
,LB_CHEM_01.LBORRES 'V_LBORRES'
,LB_CHEM_01.LBORRES 'X_LBORRES_NUM'
--,CAST(LB_CHEM_01.LBORRES   AS DECIMAL(16,2)) AS X_LBORRES_NUM--
,LB_CHEM_01.LBORRES_U_D 'V_LBORRESU'
,LB_CHEM_01.LBORRES_TRANS 'V_LBSTRESC'
,LB_CHEM_01.LBORRES_TRANS 'V_LBSTRESN'
,LB_CHEM_01.LBORRES_TRANSU 'V_LBSTRESU'
,LB_CHEM_01.LBORNRLO 'V_LBORNRLO'
,LB_CHEM_01.LBORNRHI 'V_LBORNRHI'
,LB_CHEM_01.LBORNRLOHI_U 'V_LBORNRLOHIU'
,LB_CHEM_01.LBORNRLO_TRANS 'V_LBSTNRLO'
,LB_CHEM_01.LBORNRHI_TRANS 'V_LBSTNRHI'
,LB_CHEM_01.LBORNRLOHI_TRANSU 'X_LBSTNRLOHIU'
,LB_CHEM_01.LBOVRDNRLO 'V_LBORNRLO_OVRD'
,LB_CHEM_01.LBOVRDNRHI 'V_LBORNRHI_OVRD'
,LB_CHEM_01.LBOVRDNRLOHI_U 'V_LBORNRLOHIU_OVRD'
,LB_CHEM_01.LBOVRDNRLO_TRANS 'V_LBSTNRLO_OVRD'
,LB_CHEM_01.LBOVRDNRHI_TRANS 'V_LBSTNRHI_OVRD'
,LB_CHEM_01.LBOVRDNRLOHI_TRANSU 'X_LBSTNRLOHIU_OVRD'
,LB_CHEM_01.LBNRIND 'V_LBNRIND'
,LB_CHEM_01.LBCLSIG 'V_LBCLSIG'

FROM
  LB_CHEM_01 LB_CHEM_01,
  SUBJECTS S1
WHERE
              S1.SUBJID=LB_CHEM_01.SUBJID
              AND S1.SITENUM=LB_CHEM_01.SITENUM
              AND LB_CHEM_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
--AND  LB_CHEM_01.FORMILB !='true'--
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_COAG_01.COUNTRY  'COUNTRY'
,LB_COAG_01.SITENUM  'SITENUM'
,LB_COAG_01.SUBJID  'SUBJID'
,	S1.STATUS  'SUBJSTATUS'
,LB_COAG_01.EGROUPDEF  'EGID'
,LB_COAG_01.ESEQ  'EGSEQ'
,CASE LB_COAG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_COAG_01.EGROUP||' '||LB_COAG_01.EVENT
   ELSE LB_COAG_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_COAG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_COAG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_COAG_01.EVENTEID= 'ev_DAY1' THEN LB_COAG_01.ESEQ + 0.01
WHEN LB_COAG_01.EVENTEID= 'ev_DAY8' THEN LB_COAG_01.ESEQ + 0.08
WHEN LB_COAG_01.EVENTEID= 'ev_DAY15' THEN LB_COAG_01.ESEQ + 0.15
WHEN LB_COAG_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_COAG_01.ESEQ * 0.01
WHEN LB_COAG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_COAG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_COAG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_COAG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_COAG_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_COAG_01.ESEQ * 0.01
WHEN LB_COAG_01.EVENTEID= 'ev_LFU' THEN 80 + LB_COAG_01.ESEQ * 0.01
WHEN LB_COAG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_COAG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_COAG_01.EVENTEID= 'ev_UNS' THEN 99 + LB_COAG_01.ESEQ * 0.01
ELSE LB_COAG_01.EVENTEID
END as 'VISITNUM'
,LB_COAG_01.EVENTDT  'VISITDT'
,LB_COAG_01.FORM  'FORM'
,LB_COAG_01.FORMDEF  'FORMID'
,LB_COAG_01.FSEQ  'FORMSEQ'
,CASE LB_COAG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_COAG_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_COAG_01.IGSEQ  'IGSEQ'
,LB_COAG_01.DLASTMOD  'DLASTMOD'
, 'COAGULATION' 'DX_LBCAT'
, null 'DX_LBSCAT'
--,NULL 'V_LBPERF_LBALL'--
,CASE 
    WHEN LB_COAG_01.FORMILB != 'true' THEN 'Y'
    ELSE 'N'
  END AS 'V_LBPERF_LBALL'
, NULL 'V_LBREASND_LBALL'
,LB_COAG_01.LBLOC 'V_LBNAM'
,LB_COAG_01.LBAGE 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_COAG_01.LBDTC 'V_LBDTC'
,LB_COAG_01.LBDTC_DT 'V_LBDAT'
,LB_COAG_01.LBDTC_TM 'V_LBTIM'
,LB_COAG_01.LBDTC 'X_LBDTC'
,LB_COAG_01.LBDTC_DT 'X_LBDAT'
,LB_COAG_01.LBDTC_TM 'X_LBTIM'
,LB_COAG_01.LBTEST 'V_LBTESTCD'

,(SELECT LBA.LABANALYTELABEL FROM LBANALYTE LBA
  WHERE LBA.LABANALYTENAME = LB_COAG_01.LBTEST) AS 'V_LBTEST'

, NULL 'V_LBSTAT'

,LB_COAG_01.LBORRES 'V_LBORRES'
,LB_COAG_01.LBORRES 'X_LBORRES_NUM'
--,CAST(LB_COAG_01.LBORRES  AS DECIMAL(16,2)) AS X_LBORRES_NUM--
,LB_COAG_01.LBORRES_U_D 'V_LBORRESU'
,LB_COAG_01.LBORRES_TRANS 'V_LBSTRESC'
,LB_COAG_01.LBORRES_TRANS 'V_LBSTRESN'
,LB_COAG_01.LBORRES_TRANSU 'V_LBSTRESU'
,LB_COAG_01.LBORNRLO 'V_LBORNRLO'
,LB_COAG_01.LBORNRHI 'V_LBORNRHI'
,LB_COAG_01.LBORNRLOHI_U 'V_LBORNRLOHIU'
,LB_COAG_01.LBORNRLO_TRANS 'V_LBSTNRLO'
,LB_COAG_01.LBORNRHI_TRANS 'V_LBSTNRHI'
,LB_COAG_01.LBORNRLOHI_TRANSU 'X_LBSTNRLOHIU'
,LB_COAG_01.LBOVRDNRLO 'V_LBORNRLO_OVRD'
,LB_COAG_01.LBOVRDNRHI 'V_LBORNRHI_OVRD'
,LB_COAG_01.LBOVRDNRLOHI_U 'V_LBORNRLOHIU_OVRD'
,LB_COAG_01.LBOVRDNRLO_TRANS 'V_LBSTNRLO_OVRD'
,LB_COAG_01.LBOVRDNRHI_TRANS 'V_LBSTNRHI_OVRD'
,LB_COAG_01.LBOVRDNRLOHI_TRANSU 'X_LBSTNRLOHIU_OVRD'
,LB_COAG_01.LBNRIND 'V_LBNRIND'
,LB_COAG_01.LBCLSIG 'V_LBCLSIG'
FROM
  LB_COAG_01 LB_COAG_01,
              SUBJECTS S1
WHERE
              S1.SUBJID=LB_COAG_01.SUBJID
              AND S1.SITENUM=LB_COAG_01.SITENUM
              AND LB_COAG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
--AND  LB_COAG_01.FORMILB !='true'--
UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_HEMA_01.COUNTRY  'COUNTRY'
,LB_HEMA_01.SITENUM  'SITENUM'
,LB_HEMA_01.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,LB_HEMA_01.EGROUPDEF  'EGID'
,LB_HEMA_01.ESEQ  'EGSEQ'
,CASE LB_HEMA_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_HEMA_01.EGROUP||' '||LB_HEMA_01.EVENT
   ELSE LB_HEMA_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_HEMA_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_HEMA_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_HEMA_01.EVENTEID= 'ev_DAY1' THEN LB_HEMA_01.ESEQ + 0.01
WHEN LB_HEMA_01.EVENTEID= 'ev_DAY8' THEN LB_HEMA_01.ESEQ + 0.08
WHEN LB_HEMA_01.EVENTEID= 'ev_DAY15' THEN LB_HEMA_01.ESEQ + 0.15
WHEN LB_HEMA_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_HEMA_01.ESEQ * 0.01
WHEN LB_HEMA_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_HEMA_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_HEMA_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_HEMA_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_HEMA_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_HEMA_01.ESEQ * 0.01
WHEN LB_HEMA_01.EVENTEID= 'ev_LFU' THEN 80 + LB_HEMA_01.ESEQ * 0.01
WHEN LB_HEMA_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_HEMA_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_HEMA_01.EVENTEID= 'ev_UNS' THEN 99 + LB_HEMA_01.ESEQ * 0.01
ELSE LB_HEMA_01.EVENTEID
END as 'VISITNUM'
,LB_HEMA_01.EVENTDT  'VISITDT'
,LB_HEMA_01.FORM  'FORM'
,LB_HEMA_01.FORMDEF  'FORMID'
,LB_HEMA_01.FSEQ  'FORMSEQ'
,CASE LB_HEMA_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_HEMA_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_HEMA_01.IGSEQ  'IGSEQ'
,LB_HEMA_01.DLASTMOD  'DLASTMOD'
, 'HEMATOLOGY' 'DX_LBCAT'
, null 'DX_LBSCAT'
--, NULL 'V_LBPERF_LBALL'--
,CASE 
    WHEN LB_HEMA_01.FORMILB != 'true' THEN 'Y'
    ELSE 'N'
  END AS 'V_LBPERF_LBALL'
,NULL 'V_LBREASND_LBALL'
,LB_HEMA_01.LBLOC 'V_LBNAM'
,LB_HEMA_01.LBAGE 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_HEMA_01.LBDTC 'V_LBDTC'
,LB_HEMA_01.LBDTC_DT 'V_LBDAT'
,LB_HEMA_01.LBDTC_TM 'V_LBTIM'
,LB_HEMA_01.LBDTC 'X_LBDTC'
,LB_HEMA_01.LBDTC_DT 'X_LBDAT'
,LB_HEMA_01.LBDTC_TM 'X_LBTIM'
,LB_HEMA_01.LBTEST 'V_LBTESTCD'
,(SELECT LBA.LABANALYTELABEL FROM LBANALYTE LBA
  WHERE LBA.LABANALYTENAME = LB_HEMA_01.LBTEST) AS 'V_LBTEST'
--, NULL 'V_LBSTAT'--
, CASE 
    WHEN LB_HEMA_01.FORMILB != 'true' AND LB_HEMA_01.LBORRES == 'true' THEN 'true'
    ELSE NULL
  END AS 'V_LBSTAT'
 
  
,LB_HEMA_01.LBORRES 'V_LBORRES'
,LB_HEMA_01.LBORRES 'X_LBORRES_NUM'
--,CAST(LB_HEMA_01.LBORRES  AS DECIMAL(16,2)) AS X_LBORRES_NUM--
,LB_HEMA_01.LBORRES_U_D 'V_LBORRESU'
,LB_HEMA_01.LBORRES_TRANS 'V_LBSTRESC'
,LB_HEMA_01.LBORRES_TRANS 'V_LBSTRESN'
,LB_HEMA_01.LBORRES_TRANSU 'V_LBSTRESU'
,LB_HEMA_01.LBORNRLO 'V_LBORNRLO'
,LB_HEMA_01.LBORNRHI 'V_LBORNRHI'
,LB_HEMA_01.LBORNRLOHI_U 'V_LBORNRLOHIU'
,LB_HEMA_01.LBORNRLO_TRANS 'V_LBSTNRLO'
,LB_HEMA_01.LBORNRHI_TRANS 'V_LBSTNRHI'
,LB_HEMA_01.LBORNRLOHI_TRANSU 'X_LBSTNRLOHIU'
,LB_HEMA_01.LBOVRDNRLO 'V_LBORNRLO_OVRD'
,LB_HEMA_01.LBOVRDNRHI 'V_LBORNRHI_OVRD'
,LB_HEMA_01.LBOVRDNRLOHI_U 'V_LBORNRLOHIU_OVRD'
,LB_HEMA_01.LBOVRDNRLO_TRANS 'V_LBSTNRLO_OVRD'
,LB_HEMA_01.LBOVRDNRHI_TRANS 'V_LBSTNRHI_OVRD'
,LB_HEMA_01.LBOVRDNRLOHI_TRANSU 'X_LBSTNRLOHIU_OVRD'
,LB_HEMA_01.LBNRIND 'V_LBNRIND'
,LB_HEMA_01.LBCLSIG 'V_LBCLSIG'
FROM
  LB_HEMA_01 LB_HEMA_01,
              SUBJECTS S1
WHERE
              S1.SUBJID=LB_HEMA_01.SUBJID
              AND S1.SITENUM=LB_HEMA_01.SITENUM
              AND LB_HEMA_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
--AND  LB_HEMA_01.FORMILB !='true'--
UNION


SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_PREG_01.COUNTRY  'COUNTRY'
,LB_PREG_01.SITENUM  'SITENUM'
,LB_PREG_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,LB_PREG_01.EGROUPDEF  'EGID'
,LB_PREG_01.ESEQ  'EGSEQ'
,CASE LB_PREG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_PREG_01.EGROUP||' '||LB_PREG_01.EVENT
   ELSE LB_PREG_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_PREG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_PREG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_PREG_01.EVENTEID= 'ev_DAY1' THEN LB_PREG_01.ESEQ + 0.01
WHEN LB_PREG_01.EVENTEID= 'ev_DAY8' THEN LB_PREG_01.ESEQ + 0.08
WHEN LB_PREG_01.EVENTEID= 'ev_DAY15' THEN LB_PREG_01.ESEQ + 0.15
WHEN LB_PREG_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_PREG_01.ESEQ * 0.01
WHEN LB_PREG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_PREG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_PREG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_PREG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_PREG_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_PREG_01.ESEQ * 0.01
WHEN LB_PREG_01.EVENTEID= 'ev_LFU' THEN 80 + LB_PREG_01.ESEQ * 0.01
WHEN LB_PREG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_PREG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_PREG_01.EVENTEID= 'ev_UNS' THEN 99 + LB_PREG_01.ESEQ * 0.01
ELSE LB_PREG_01.EVENTEID
END as 'VISITNUM'
,LB_PREG_01.EVENTDT  'VISITDT'
,LB_PREG_01.FORM  'FORM'
,LB_PREG_01.FORMDEF  'FORMID'
,LB_PREG_01.FSEQ  'FORMSEQ'
,CASE LB_PREG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_PREG_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_PREG_01.IGSEQ  'IGSEQ'
,LB_PREG_01.DLASTMOD  'DLASTMOD'
, 'PREGNANCY' 'DX_LBCAT'
, null 'DX_LBSCAT'
,LB_PREG_01.V_LBPERF_LBALL  'V_LBPERF_LBALL'
,LB_PREG_01.V_LBREASND_LBALL  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
,LB_PREG_01.V_LBSPEC_PREG 'V_LBSPEC'
,LB_PREG_01.V_LBTDTC 'V_LBDTC'
,LB_PREG_01.V_LBTDTC_DT 'V_LBDAT'
,LB_PREG_01.V_LBTDTC_TM 'V_LBTIM'
,LB_PREG_01.V_LBTDTC 'X_LBDTC'
,LB_PREG_01.V_LBTDTC_DT 'X_LBDAT'
,LB_PREG_01.V_LBTDTC_TM 'X_LBTIM'
,LB_PREG_01.DV_LBTEST_PREG 'V_LBTESTCD'
,LB_PREG_01.DV_LBTEST_PREG_D 'V_LBTEST'
, null 'V_LBSTAT'
,LB_PREG_01.V_LBORRES_PREG 'V_LBORRES'
,NULL 'X_LBORRES_NUM'
, null 'V_LBORRESU'
, null 'V_LBSTRESC'
, null 'V_LBSTREN'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
, null 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_PREG_01 LB_PREG_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_PREG_01.SUBJID
   AND S1.SITENUM=LB_PREG_01.SITENUM
   AND LB_PREG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND  LB_PREG_01.FORMILB !='true'
   
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_PREGUNS_01.COUNTRY  'COUNTRY'
,LB_PREGUNS_01.SITENUM  'SITENUM'
,LB_PREGUNS_01.SUBJID  'SUBJID'
,S1.STATUS 'SUBJSTATUS'
,LB_PREGUNS_01.EGROUPDEF  'EGID'
,LB_PREGUNS_01.ESEQ  'EGSEQ'
,CASE LB_PREGUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_PREGUNS_01.EGROUP||' '||LB_PREGUNS_01.EVENT
   ELSE LB_PREGUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_PREGUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_PREGUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_PREGUNS_01.EVENTEID= 'ev_DAY1' THEN LB_PREGUNS_01.ESEQ + 0.01
WHEN LB_PREGUNS_01.EVENTEID= 'ev_DAY8' THEN LB_PREGUNS_01.ESEQ + 0.08
WHEN LB_PREGUNS_01.EVENTEID= 'ev_DAY15' THEN LB_PREGUNS_01.ESEQ + 0.15
WHEN LB_PREGUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_PREGUNS_01.ESEQ * 0.01
WHEN LB_PREGUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_PREGUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_PREGUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_PREGUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_PREGUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_PREGUNS_01.ESEQ * 0.01
WHEN LB_PREGUNS_01.EVENTEID= 'ev_LFU' THEN 80 + LB_PREGUNS_01.ESEQ * 0.01
WHEN LB_PREGUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_PREGUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_PREGUNS_01.EVENTEID= 'ev_UNS' THEN 99 + LB_PREGUNS_01.ESEQ * 0.01
ELSE LB_PREGUNS_01.EVENTEID
END as 'VISITNUM'
,LB_PREGUNS_01.EVENTDT  'VISITDT'
,LB_PREGUNS_01.FORM  'FORM'
,LB_PREGUNS_01.FORMDEF  'FORMID'
,LB_PREGUNS_01.FSEQ  'FORMSEQ'
,CASE LB_PREGUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_PREGUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_PREGUNS_01.IGSEQ  'IGSEQ'
,LB_PREGUNS_01.DLASTMOD  'DLASTMOD'
, 'PREGNANCY' 'DX_LBCAT'
, null 'DX_LBSCAT'
, null  'V_LBPERF_LBALL'
, null  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
,LB_PREGUNS_01.V_LBSPEC_PREG 'V_LBSPEC'
,LB_PREGUNS_01.V_LBTDTC 'V_LBDTC'
,LB_PREGUNS_01.V_LBTDTC_DT 'V_LBDAT'
,LB_PREGUNS_01.V_LBTDTC_TM 'V_LBTIM'
,LB_PREGUNS_01.V_LBTDTC 'X_LBDTC'
,LB_PREGUNS_01.V_LBTDTC_DT 'X_LBDAT'
,LB_PREGUNS_01.V_LBTDTC_TM 'X_LBTIM'
,LB_PREGUNS_01.DV_LBTEST_PREG 'V_LBTESTCD'
,LB_PREGUNS_01.DV_LBTEST_PREG_D 'V_LBTEST'
, null 'V_LBSTAT'
,LB_PREGUNS_01.V_LBORRES_PREG 'V_LBORRES'
,NULL 'X_LBORRES_NUM'
, null 'V_LBORRESU'
, null 'V_LBSTRESC'
, null 'V_LBSTRESN'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
, null 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_PREGUNS_01 LB_PREGUNS_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_PREGUNS_01.SUBJID
   AND S1.SITENUM=LB_PREGUNS_01.SITENUM
   AND LB_PREGUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND  LB_PREGUNS_01.FORMILB !='true'
 
    
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_THYR_01.COUNTRY  'COUNTRY'
,LB_THYR_01.SITENUM  'SITENUM'
,LB_THYR_01.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,LB_THYR_01.EGROUPDEF  'EGID'
,LB_THYR_01.ESEQ  'EGSEQ'
,CASE LB_THYR_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN LB_THYR_01.EGROUP||' '||LB_THYR_01.EVENT
ELSE LB_THYR_01.EVENT
END AS 'VISIT'
,CASE 
WHEN LB_THYR_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_THYR_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_THYR_01.EVENTEID= 'ev_DAY1' THEN LB_THYR_01.ESEQ + 0.01
WHEN LB_THYR_01.EVENTEID= 'ev_DAY8' THEN LB_THYR_01.ESEQ + 0.08
WHEN LB_THYR_01.EVENTEID= 'ev_DAY15' THEN LB_THYR_01.ESEQ + 0.15
WHEN LB_THYR_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_THYR_01.ESEQ * 0.01
WHEN LB_THYR_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_THYR_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_THYR_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_THYR_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_THYR_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_THYR_01.ESEQ * 0.01
WHEN LB_THYR_01.EVENTEID= 'ev_LFU' THEN 80 + LB_THYR_01.ESEQ * 0.01
WHEN LB_THYR_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_THYR_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_THYR_01.EVENTEID= 'ev_UNS' THEN 99 + LB_THYR_01.ESEQ * 0.01
ELSE LB_THYR_01.EVENTEID
END as 'VISITNUM'
,LB_THYR_01.EVENTDT  'VISITDT'
,LB_THYR_01.FORM  'FORM'
,LB_THYR_01.FORMDEF  'FORMID'
,LB_THYR_01.FSEQ  'FORMSEQ'
,CASE LB_THYR_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE  LB_THYR_01.FORMSTATUS
END AS 'FORMSTATUS'
,LB_THYR_01.IGSEQ  'IGSEQ'
,LB_THYR_01.DLASTMOD  'DLASTMOD'
, 'OTHER CHEMISTRY TESTING' 'DX_LBCAT'
, 'ENDOCRINE TESTS' 'DX_LBSCAT'
--, NULL  'V_LBPERF_LBALL'--

,CASE 
    WHEN LB_THYR_01.FORMILB != 'true' THEN 'Y'
    ELSE 'N'
  END AS 'V_LBPERF_LBALL'
, NULL  'V_LBREASND_LBALL'  
, LB_THYR_01.LBLOC 'V_LBNAM'
, LB_THYR_01.LBAGE 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_THYR_01.LBDTC 'V_LBDTC'
,LB_THYR_01.LBDTC_DT 'V_LBDAT'
,LB_THYR_01.LBDTC_TM 'V_LBTIM'
,LB_THYR_01.LBDTC 'X_LBDTC'
,LB_THYR_01.LBDTC_DT 'X_LBDAT'
,LB_THYR_01.LBDTC_TM 'X_LBTIM'
,LB_THYR_01.LBTEST 'V_LBTESTCD'
,(SELECT LBA.LABANALYTELABEL FROM LBANALYTE LBA
  WHERE LBA.LABANALYTENAME = LB_THYR_01.LBTEST) AS 'V_LBTEST'

--,NULL 'V_LBSTAT'--

, CASE 
    WHEN LB_THYR_01.FORMILB != 'true' AND LB_THYR_01.LBORRES == 'true' THEN 'true'
    ELSE NULL
  END AS 'V_LBSTAT'
,LB_THYR_01.LBORRES 'V_LBORRES'
,LB_THYR_01.LBORRES 'X_LBORRES_NUM'
--,CAST(LB_THYR_01.LBORRES  AS DECIMAL(16,2)) AS X_LBORRES_NUM--
, LB_THYR_01.LBORRES_U_D 'V_LBORRESU'
, LB_THYR_01.LBORRES_TRANS 'V_LBSTRESC'
, LB_THYR_01.LBORRES_TRANS 'V_LBSTRESN'
, LB_THYR_01.LBORRES_TRANSU 'V_LBSTRESU'
, LB_THYR_01.LBORNRLO 'V_LBORNRLO'
, LB_THYR_01.LBORNRHI 'V_LBORNRHI'
, LB_THYR_01.LBORNRLOHI_U 'V_LBORNRLOHIU'
, LB_THYR_01.LBORNRLO_TRANS 'V_LBSTNRLO'
, LB_THYR_01.LBORNRHI_TRANS 'V_LBSTNRHI'
, LB_THYR_01.LBORNRLOHI_TRANSU 'X_LBSTNRLOHIU'
, LB_THYR_01.LBOVRDNRLO 'V_LBORNRLO_OVRD'
, LB_THYR_01.LBOVRDNRLO_TRANS 'V_LBORNRHI_OVRD'
, LB_THYR_01.LBOVRDNRHI 'V_LBORNRLOHIU_OVRD'
, LB_THYR_01.LBOVRDNRHI_TRANS 'V_LBSTNRLO_OVRD'
, LB_THYR_01.LBOVRDNRHI_TRANS  'V_LBSTNRHI_OVRD'
, LB_THYR_01.LBOVRDNRLOHI_TRANSU 'X_LBSTNRLOHIU_OVRD'
,LB_THYR_01.LBNRIND 'V_LBNRIND'
, LB_THYR_01.LBCLSIG  'V_LBCLSIG'
FROM
LB_THYR_01 LB_THYR_01,
SUBJECTS S1
WHERE
S1.SUBJID=LB_THYR_01.SUBJID
AND S1.SITENUM=LB_THYR_01.SITENUM
AND LB_THYR_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
--AND LB_THYR_01.FORMILB !='true'--

UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_THYR_02.COUNTRY  'COUNTRY'
,LB_THYR_02.SITENUM  'SITENUM'
,LB_THYR_02.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,LB_THYR_02.EGROUPDEF  'EGID'
,LB_THYR_02.ESEQ  'EGSEQ'
,CASE LB_THYR_02.EGROUPDEF
WHEN 'eg_TRTA1C' THEN LB_THYR_02.EGROUP||' '||LB_THYR_02.EVENT
ELSE LB_THYR_02.EVENT
END AS 'VISIT'
,CASE 
WHEN LB_THYR_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_THYR_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_THYR_02.EVENTEID= 'ev_DAY1' THEN LB_THYR_02.ESEQ + 0.01
WHEN LB_THYR_02.EVENTEID= 'ev_DAY8' THEN LB_THYR_02.ESEQ + 0.08
WHEN LB_THYR_02.EVENTEID= 'ev_DAY15' THEN LB_THYR_02.ESEQ + 0.15
WHEN LB_THYR_02.EVENTEID= 'ev_TUPB' THEN 41 + LB_THYR_02.ESEQ * 0.01
WHEN LB_THYR_02.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_THYR_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_THYR_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_THYR_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_THYR_02.EVENTEID= 'ev_PTFU' THEN 75 + LB_THYR_02.ESEQ * 0.01
WHEN LB_THYR_02.EVENTEID= 'ev_LFU' THEN 80 + LB_THYR_02.ESEQ * 0.01
WHEN LB_THYR_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_THYR_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_THYR_02.EVENTEID= 'ev_UNS' THEN 99 + LB_THYR_02.ESEQ * 0.01
ELSE LB_THYR_02.EVENTEID
END as 'VISITNUM'
,LB_THYR_02.EVENTDT  'VISITDT'
,LB_THYR_02.FORM  'FORM'
,LB_THYR_02.FORMDEF  'FORMID'
,LB_THYR_02.FSEQ  'FORMSEQ'
,CASE LB_THYR_02.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE  LB_THYR_02.FORMSTATUS
END AS 'FORMSTATUS'
,LB_THYR_02.IGSEQ  'IGSEQ'
,LB_THYR_02.DLASTMOD  'DLASTMOD'
, 'OTHER CHEMISTRY TESTING' 'DX_LBCAT'
, 'ENDOCRINE TESTS' 'DX_LBSCAT'
--, NULL  'V_LBPERF_LBALL'-- 
,CASE 
    WHEN LB_THYR_02.FORMILB != 'true' THEN 'Y'
    ELSE 'N'
  END AS 'V_LBPERF_LBALL'

, NULL  'V_LBREASND_LBALL'  
, LB_THYR_02.LBLOC 'V_LBNAM'
, LB_THYR_02.LBAGE 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_THYR_02.LBDTC 'V_LBDTC'
,LB_THYR_02.LBDTC_DT 'V_LBDAT'
,LB_THYR_02.LBDTC_TM 'V_LBTIM'
,LB_THYR_02.LBDTC 'X_LBDTC'
,LB_THYR_02.LBDTC_DT 'X_LBDAT'
,LB_THYR_02.LBDTC_TM 'X_LBTIM'

,LB_THYR_02.LBTEST 'V_LBTESTCD'
,(SELECT LBA.LABANALYTELABEL FROM LBANALYTE LBA
  WHERE LBA.LABANALYTENAME = LB_THYR_02.LBTEST) AS 'V_LBTEST'

--,NULL 'V_LBSTAT'--

, CASE 
    WHEN LB_THYR_02.FORMILB != 'true' AND LB_THYR_02.LBORRES == 'true' THEN 'true'
    ELSE NULL
  END AS 'V_LBSTAT'
  
,LB_THYR_02.LBORRES 'V_LBORRES'
,LB_THYR_02.LBORRES 'X_LBORRES_NUM'
--,CAST(LB_THYR_02.LBORRES  AS DECIMAL(16,2)) AS X_LBORRES_NUM--
, LB_THYR_02.LBORRES_U_D 'V_LBORRESU'
, LB_THYR_02.LBORRES_TRANS 'V_LBSTRESC'
, LB_THYR_02.LBORRES_TRANS 'V_LBSTRESN'
, LB_THYR_02.LBORRES_TRANSU 'V_LBSTRESU'
, LB_THYR_02.LBORNRLO 'V_LBORNRLO'
, LB_THYR_02.LBORNRHI 'V_LBORNRHI'
, LB_THYR_02.LBORNRLOHI_U 'V_LBORNRLOHIU'
, LB_THYR_02.LBORNRLO_TRANS 'V_LBSTNRLO'
, LB_THYR_02.LBORNRHI_TRANS 'V_LBSTNRHI'
, LB_THYR_02.LBORNRLOHI_TRANSU 'X_LBSTNRLOHIU'
, LB_THYR_02.LBOVRDNRLO 'V_LBORNRLO_OVRD'
, LB_THYR_02.LBOVRDNRLO_TRANS 'V_LBORNRHI_OVRD'
, LB_THYR_02.LBOVRDNRHI 'V_LBORNRLOHIU_OVRD'
, LB_THYR_02.LBOVRDNRHI_TRANS 'V_LBSTNRLO_OVRD'
, LB_THYR_02.LBOVRDNRHI_TRANS  'V_LBSTNRHI_OVRD'
, LB_THYR_02.LBOVRDNRLOHI_TRANSU 'X_LBSTNRLOHIU_OVRD'
,LB_THYR_02.LBNRIND 'V_LBNRIND'
, LB_THYR_02.LBCLSIG  'V_LBCLSIG'
FROM
LB_THYR_02 LB_THYR_02,
SUBJECTS S1
WHERE
S1.SUBJID=LB_THYR_02.SUBJID
AND S1.SITENUM=LB_THYR_02.SITENUM
AND LB_THYR_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
--AND LB_THYR_02.FORMILB !='true'--
UNION


SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_URIN_01.COUNTRY  'COUNTRY'
,LB_URIN_01.SITENUM  'SITENUM'
,LB_URIN_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,LB_URIN_01.EGROUPDEF  'EGID'
,LB_URIN_01.ESEQ  'EGSEQ'
,CASE LB_URIN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_URIN_01.EGROUP||' '||LB_URIN_01.EVENT
   ELSE LB_URIN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_URIN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_URIN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_URIN_01.EVENTEID= 'ev_DAY1' THEN LB_URIN_01.ESEQ + 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_DAY8' THEN LB_URIN_01.ESEQ + 0.08
WHEN LB_URIN_01.EVENTEID= 'ev_DAY15' THEN LB_URIN_01.ESEQ + 0.15
WHEN LB_URIN_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_URIN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_URIN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_URIN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_URIN_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_LFU' THEN 80 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_URIN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_URIN_01.EVENTEID= 'ev_UNS' THEN 99 + LB_URIN_01.ESEQ * 0.01
ELSE LB_URIN_01.EVENTEID
END as 'VISITNUM'

,LB_URIN_01.EVENTDT  'VISITDT'
,LB_URIN_01.FORM  'FORM'
,LB_URIN_01.FORMDEF  'FORMID'
,LB_URIN_01.FSEQ  'FORMSEQ'
,CASE LB_URIN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_URIN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_URIN_01.IGSEQ  'IGSEQ'
,LB_URIN_01.DLASTMOD  'DLASTMOD'
, 'URINALYSIS' 'DX_LBCAT'
, null 'DX_LBSCAT'
,LB_URIN_01.V_LBPERF_LBALL   'V_LBPERF_LBALL'
,LB_URIN_01.V_LBREASND_LBALL  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_URIN_01.V_LBTDTC 'V_LBDTC'
,LB_URIN_01.V_LBTDTC_DT 'V_LBDAT'
,LB_URIN_01.V_LBTDTC_TM 'V_LBTIM'
,LB_URIN_01.V_LBTDTC 'X_LBDTC'
,LB_URIN_01.V_LBTDTC_DT 'X_LBDAT'
,LB_URIN_01.V_LBTDTC_TM 'X_LBTIM'
,LB_URIN_01.DV_LBTEST_URIN 'V_LBTESTCD'
,LB_URIN_01.DV_LBTEST_URIN_D 'V_LBTEST'
,LB_URIN_01.V_LBSTAT  'V_LBSTAT'

	/*   ,CASE WHEN LB_URIN_01.FORMILB != 'true' THEN
   CASE WHEN LB_URIN_01.V_LBORRES_URIN == 'true' THEN 'true'
                ELSE NULL  END   ELSE NULL
    END AS 'V_LBSTAT' */
,LB_URIN_01.V_LBORRES_URIN 'V_LBORRES'
,LB_URIN_01.V_LBORRES_URIN 'X_LBORRES_NUM'
--,CAST(LB_URIN_01.V_LBORRES_URIN AS DECIMAL(16,2)) AS X_LBORRES_NUM--
, null 'V_LBORRESU'
, null 'V_LBSTRESC'
, null 'V_LBSTRESN'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
,LB_URIN_01.V_LBNRIND_URIN 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_URIN_01 LB_URIN_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_URIN_01.SUBJID
   AND S1.SITENUM=LB_URIN_01.SITENUM
   AND LB_URIN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND LB_URIN_01.FORMILB !='true'
   
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_URIN_01.COUNTRY  'COUNTRY'
,LB_URIN_01.SITENUM  'SITENUM'
,LB_URIN_01.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,LB_URIN_01.EGROUPDEF  'EGID'
,LB_URIN_01.ESEQ  'EGSEQ'
,CASE LB_URIN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_URIN_01.EGROUP||' '||LB_URIN_01.EVENT
   ELSE LB_URIN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_URIN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_URIN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_URIN_01.EVENTEID= 'ev_DAY1' THEN LB_URIN_01.ESEQ + 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_DAY8' THEN LB_URIN_01.ESEQ + 0.08
WHEN LB_URIN_01.EVENTEID= 'ev_DAY15' THEN LB_URIN_01.ESEQ + 0.15
WHEN LB_URIN_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_URIN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_URIN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_URIN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_URIN_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_LFU' THEN 80 + LB_URIN_01.ESEQ * 0.01
WHEN LB_URIN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_URIN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_URIN_01.EVENTEID= 'ev_UNS' THEN 99 + LB_URIN_01.ESEQ * 0.01
ELSE LB_URIN_01.EVENTEID
END as 'VISITNUM'

,LB_URIN_01.EVENTDT  'VISITDT'
,LB_URIN_01.FORM  'FORM'
,LB_URIN_01.FORMDEF  'FORMID'
,LB_URIN_01.FSEQ  'FORMSEQ'
,CASE LB_URIN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_URIN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_URIN_01.IGSEQ  'IGSEQ'
,LB_URIN_01.DLASTMOD  'DLASTMOD'
, 'URINALYSIS' 'DX_LBCAT'
, 'MICROSCOPIC' 'DX_LBSCAT'
,LB_URIN_01.V_LBPERF_LBALL   'V_LBPERF_LBALL'
,LB_URIN_01.V_LBREASND_LBALL  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_URIN_01.V_LBTDTC 'V_LBDTC'
,LB_URIN_01.V_LBTDTC_DT 'V_LBDAT'
,LB_URIN_01.V_LBTDTC_TM 'V_LBTIM'
,LB_URIN_01.V_LBTDTC 'X_LBDTC'
,LB_URIN_01.V_LBTDTC_DT 'X_LBDAT'
,LB_URIN_01.V_LBTDTC_TM 'X_LBTIM'
,LB_URIN_01.V_LBTEST_MIURIN 'V_LBTESTCD'
,LB_URIN_01.V_LBTEST_MIURIN_D 'V_LBTEST'
,NULL  'V_LBSTAT'
,LB_URIN_01.V_LBORRES_MIURIN 'V_LBORRES'
,null 'X_LBORRES_NUM'
,LB_URIN_01.V_LBUNIT_MIURIN  'V_LBORRESU'
, null 'V_LBSTRESC'
, null 'V_LBSTRESN'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
,LB_URIN_01.V_LBNRIND_MIURIN 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_URIN_01 LB_URIN_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_URIN_01.SUBJID
   AND S1.SITENUM=LB_URIN_01.SITENUM
   AND LB_URIN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND LB_URIN_01.FORMILB !='true'
  
    AND LB_URIN_01.V_LBTEST_MIURIN !=''
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_URINUNS_01.COUNTRY  'COUNTRY'
,LB_URINUNS_01.SITENUM  'SITENUM'
,LB_URINUNS_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,LB_URINUNS_01.EGROUPDEF  'EGID'
,LB_URINUNS_01.ESEQ  'EGSEQ'
,CASE LB_URINUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_URINUNS_01.EGROUP||' '||LB_URINUNS_01.EVENT
   ELSE LB_URINUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_URINUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_URINUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY1' THEN LB_URINUNS_01.ESEQ + 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY8' THEN LB_URINUNS_01.ESEQ + 0.08
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY15' THEN LB_URINUNS_01.ESEQ + 0.15
WHEN LB_URINUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_URINUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_URINUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_URINUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_URINUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_LFU' THEN 80 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_URINUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_URINUNS_01.EVENTEID= 'ev_UNS' THEN 99 + LB_URINUNS_01.ESEQ * 0.01
ELSE LB_URINUNS_01.EVENTEID
END as 'VISITNUM'
,LB_URINUNS_01.EVENTDT  'VISITDT'
,LB_URINUNS_01.FORM  'FORM'
,LB_URINUNS_01.FORMDEF  'FORMID'
,LB_URINUNS_01.FSEQ  'FORMSEQ'
,CASE LB_URINUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_URINUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_URINUNS_01.IGSEQ  'IGSEQ'
,LB_URINUNS_01.DLASTMOD  'DLASTMOD'
, 'URINALYSIS' 'DX_LBCAT'
, null 'DX_LBSCAT'
, null  'V_LBPERF_LBALL'
, null  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_URINUNS_01.V_LBTDTC 'V_LBDTC'
,LB_URINUNS_01.V_LBTDTC_DT 'V_LBDAT'
,LB_URINUNS_01.V_LBTDTC_TM 'V_LBTIM'
,LB_URINUNS_01.V_LBTDTC 'X_LBDTC'
,LB_URINUNS_01.V_LBTDTC_DT 'X_LBDAT'
,LB_URINUNS_01.V_LBTDTC_TM 'X_LBTIM'

,LB_URINUNS_01.DV_LBTEST_URIN 'V_LBTESTCD'
,LB_URINUNS_01.DV_LBTEST_URIN_D 'V_LBTEST'
,LB_URINUNS_01.V_LBSTAT  'V_LBSTAT'

/*, case when LB_URINUNS_01.FORMILB != 'true'
    then case when LB_URINUNS_01.V_LBORRES_URIN == 'true' then 'true' else null end
	   else null end
       'V_LBSTAT'*/
,LB_URINUNS_01.V_LBORRES_URIN 'V_LBORRES'
,NULL 'X_LBORRES_NUM'
, null 'V_LBORRESU'
, null 'V_LBORRESN'
, null 'V_LBSTRESC'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
,LB_URINUNS_01.V_LBNRIND_URIN 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_URINUNS_01 LB_URINUNS_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_URINUNS_01.SUBJID
   AND S1.SITENUM=LB_URINUNS_01.SITENUM
   AND LB_URINUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND LB_URINUNS_01.FORMILB !='true'
   
   
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,LB_URINUNS_01.COUNTRY  'COUNTRY'
,LB_URINUNS_01.SITENUM  'SITENUM'
,LB_URINUNS_01.SUBJID  'SUBJID'
, S1.STATUS 'SUBJSTATUS'
,LB_URINUNS_01.EGROUPDEF  'EGID'
,LB_URINUNS_01.ESEQ  'EGSEQ'
,CASE LB_URINUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN LB_URINUNS_01.EGROUP||' '||LB_URINUNS_01.EVENT
   ELSE LB_URINUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN LB_URINUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN LB_URINUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY1' THEN LB_URINUNS_01.ESEQ + 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY8' THEN LB_URINUNS_01.ESEQ + 0.08
WHEN LB_URINUNS_01.EVENTEID= 'ev_DAY15' THEN LB_URINUNS_01.ESEQ + 0.15
WHEN LB_URINUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN LB_URINUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN LB_URINUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN LB_URINUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN LB_URINUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_LFU' THEN 80 + LB_URINUNS_01.ESEQ * 0.01
WHEN LB_URINUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN LB_URINUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN LB_URINUNS_01.EVENTEID= 'ev_UNS' THEN 99 + LB_URINUNS_01.ESEQ * 0.01
ELSE LB_URINUNS_01.EVENTEID
END as 'VISITNUM'
,LB_URINUNS_01.EVENTDT  'VISITDT'
,LB_URINUNS_01.FORM  'FORM'
,LB_URINUNS_01.FORMDEF  'FORMID'
,LB_URINUNS_01.FSEQ  'FORMSEQ'
,CASE LB_URINUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  LB_URINUNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,LB_URINUNS_01.IGSEQ  'IGSEQ'
,LB_URINUNS_01.DLASTMOD  'DLASTMOD'
, 'URINALYSIS' 'DX_LBCAT'
, 'MICROSCOPIC' 'DX_LBSCAT'
, null  'V_LBPERF_LBALL'
, null  'V_LBREASND_LBALL'
, null 'V_LBNAM'
, null 'DX_LBAGE'
, null 'V_LBSPEC'
,LB_URINUNS_01.V_LBTDTC 'V_LBDTC'
,LB_URINUNS_01.V_LBTDTC_DT 'V_LBDAT'
,LB_URINUNS_01.V_LBTDTC_TM 'V_LBTIM'
,LB_URINUNS_01.V_LBTDTC 'X_LBDTC'
,LB_URINUNS_01.V_LBTDTC_DT 'X_LBDAT'
,LB_URINUNS_01.V_LBTDTC_TM 'X_LBTIM'

,LB_URINUNS_01.V_LBTEST_MIURIN 'V_LBTESTCD'
,LB_URINUNS_01.V_LBTEST_MIURIN_D 'V_LBTEST'
--,LB_URINUNS_01.V_LBSTAT 'V_LBSTAT'--
,NULL 'V_LBSTAT'
,LB_URINUNS_01.V_LBORRES_MIURIN 'V_LBORRES'
,null 'X_LBORRES_NUM'
,LB_URINUNS_01.V_LBUNIT_MIURIN  'V_LBORRESU'
, null 'V_LBSTRESC'
, null 'V_LBSTRESN'
, null 'V_LBSTRESU'
, null 'V_LBORNRLO'
, null 'V_LBORNRHI'
, null 'V_LBORNRLOHIU'
, null 'V_LBSTNRLO'
, null 'V_LBSTNRHI'
, null 'X_LBSTNRLOHIU'
, null 'V_LBORNRLO_OVRD'
, null 'V_LBORNRHI_OVRD'
, null 'V_LBORNRLOHIU_OVRD'
, null 'V_LBSTNRLO_OVRD'
, null 'V_LBSTNRHI_OVRD'
, null 'X_LBSTNRLOHIU_OVRD'
,LB_URINUNS_01.V_LBNRIND_MIURIN 'V_LBNRIND'
, null 'V_LBCLSIG'
FROM
  LB_URINUNS_01 LB_URINUNS_01,
              SUBJECTS S1
WHERE
   S1.SUBJID=LB_URINUNS_01.SUBJID
   AND S1.SITENUM=LB_URINUNS_01.SITENUM
   AND LB_URINUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND LB_URINUNS_01.FORMILB !='true'
    AND LB_URINUNS_01.V_LBTEST_MIURIN !=''


    ")
dim(LBLOCAL_UNION)
LBLOCAL_UNION[] <- lapply(LBLOCAL_UNION, function(x) ifelse(is.na(x), "", x))
unique_values <- sapply(LBLOCAL_UNION, function(x) unique(x))
unique_values
LBLOCAL_UNION <- sqldf("
  SELECT
    LB.STUDYID,
    LB.SOURCE,
    LB.COUNTRY,
    LB.SITENUM,
    LB.SUBJID,
    LB.SUBJSTATUS,
    LB.EGID,
    LB.EGSEQ,
    LB.VISITNUM,
    LB.VISIT,
    LB.VISITDT,
    LB.FORM,
    LB.FORMID,
    LB.FORMSEQ,
    LB.FORMSTATUS,
    LB.IGSEQ,
    LB.DLASTMOD,
    LB.DX_LBCAT,
    LB.DX_LBSCAT,
    LB.V_LBPERF_LBALL,
    LB.V_LBREASND_LBALL,
    LB.V_LBNAM,
    LB.DX_LBAGE,
    LB.V_LBSPEC,
    LB.V_LBDTC,
    LB.V_LBDAT,
    LB.V_LBTIM,
    LB.X_LBDTC,
    LB.X_LBDAT,
    LB.X_LBTIM,
    LB.V_LBTESTCD,
    LB.V_LBTEST,
    LB.V_LBSTAT,
    LB.V_LBORRES,
    LB.X_LBORRES_NUM,
    LB.V_LBORRESU,
    LB.V_LBORNRLO,
    LB.V_LBORNRHI,
    LB.V_LBORNRLOHIU,
    LB.V_LBSTRESC,
    LB.V_LBSTRESN,
    LB.V_LBSTRESU,
    LB.V_LBSTRESN * LBCONV.X_CONVFACT_US  AS V_LBSTRESC_US,
    LB.V_LBSTRESN * LBCONV.X_CONVFACT_US  AS V_LBSTRESN_US,
    
   -- CAST(ROUND(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US, 2) AS CHAR) AS V_LBSTRESC_US,--
   -- ROUND(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US, 2) AS V_LBSTRESN_US,--
    --FLOOR(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US) AS V_LBSTRESC_US,--
   -- CEIL(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US) AS V_LBSTRESN_US,--
  --FORMAT(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US, 'F2') AS V_LBSTRESC_US,--
--FORMAT(LB.V_LBSTRESN * LBCONV.X_CONVFACT_US, 'F0') AS V_LBSTRESN_US,--

    LBCONV.V_LBSTRESU_US AS V_LBSTRESU_US,
    LB.V_LBSTNRLO,
    LB.V_LBSTNRHI,
    LB.X_LBSTNRLOHIU,
    ROUND(LB.V_LBORNRLO * LBCONV.X_CONVFACT_US, 2) AS V_LBSTNRLO_US,
    ROUND(LB.V_LBORNRHI * LBCONV.X_CONVFACT_US, 2) AS V_LBSTNRHI_US,
    LBCONV.V_LBSTRESU_US AS X_LBSTNRLOHIU_US,
    LB.V_LBORNRLO_OVRD,
    LB.V_LBORNRHI_OVRD,
    LB.V_LBORNRLOHIU_OVRD,
    LB.V_LBSTNRLO_OVRD,
    LB.V_LBSTNRHI_OVRD,
    LB.X_LBSTNRLOHIU_OVRD,
    CAST(ROUND(LB.V_LBSTNRLO_OVRD * LBCONV.X_CONVFACT_US, 2) AS CHAR) AS V_LBSTNRLO_OVRD_US,
    CAST(ROUND(LB.V_LBSTNRHI_OVRD * LBCONV.X_CONVFACT_US, 2)AS CHAR) AS V_LBSTNRHI_OVRD_US,
    LBCONV.V_LBSTRESU_US AS X_LBSTNRLOHIU_OVRD_US,
    LB.V_LBNRIND,
    LB.V_LBCLSIG
  FROM LBLOCAL_UNION LB
  LEFT JOIN LBCONV_SITOUS LBCONV
    ON LB.DX_LBCAT = LBCONV.DX_LBCAT
    AND COALESCE(LB.DX_LBSCAT, '') = COALESCE(LBCONV.DX_LBSCAT, '')
    AND LB.V_LBTESTCD = LBCONV.V_LBTESTCD
    
  ORDER BY
    LB.STUDYID,
    LB.COUNTRY,
    LB.SITENUM,
    LB.SUBJID,
    LB.VISITNUM,
    LB.VISIT,
    LB.VISITDT,
    LB.FORMID,
    LB.FORMSEQ,
    LBCONV.DX_LBSCAT,
    LB.IGSEQ
")

# function formats numeric columns, 
# rounding them to two decimal places and replacing zero values with an empty string.
format_numbers <- function(df_lb0, cols) {
  df_lb0[, cols] <- lapply(df_lb0[, cols], function(x) {
    if (is.numeric(x)) {
      ifelse(x == 0, "", round(x, 2))  # Round and replace 0 with an empty string
    } else {
      x  # Return as is for non-numeric columns
    }
  })
  return(df_lb0)
}

# Function applies similar logic but is extended to work with both numeric and 
# character columns. In the case of character columns, it specifically handles "0.0" values.
format_numbers_ <- function(df_lb, cols) {
  df_lb[, cols] <- lapply(df_lb[, cols], function(x) {
    if (is.numeric(x) || is.character(x)) {
      ifelse(x == "0.0", "", round(as.numeric(x), 2))  # Handle "0.0" as a character
    } else {
      x  # Return as is for other data types
    }
  })
  return(df_lb)
}

# format_numbers_C <- function(df_lbC, cols) {
#   df_lbC[, cols] <- lapply(df_lbC[, cols], function(x) {
#     if (is.character(x)) {
#       ""
#     } else {
#       x
#     }
#   })
#   return(df_lbC)
# }

# format_numbers and format_numbers_ functions to format specific numeric 
# columns. In these functions, numeric values are rounded, and zeros are removed.
LBLOCAL_UNION <- format_numbers(LBLOCAL_UNION, c("V_LBSTRESC_US", "V_LBSTRESN_US", 
                                                 "V_LBSTNRLO_US","V_LBSTNRHI_US"))#"
LBLOCAL_UNION <- format_numbers_(LBLOCAL_UNION, c("V_LBSTNRLO_OVRD_US", 
                                                  "V_LBSTNRHI_OVRD_US"))
# LBLOCAL_UNION <- format_numbers_C(LBLOCAL_UNION, c("X_LBORRES_NUM"))
# LBLOCAL_UNION$X_LBORRES_NUM <- formatC(LBLOCAL_UNION$X_LBORRES_NUM, format = "f", digits = 2)

# convert specific columns to numeric and round them to two decimal places.
LBLOCAL_UNION$X_LBORRES_NUM <- as.numeric(LBLOCAL_UNION$X_LBORRES_NUM)
LBLOCAL_UNION$X_LBORRES_NUM <- round(LBLOCAL_UNION$X_LBORRES_NUM, 2)
LBLOCAL_UNION$V_LBSTRESN <- as.numeric(LBLOCAL_UNION$V_LBSTRESN)
LBLOCAL_UNION$V_LBSTRESN <- round(LBLOCAL_UNION$V_LBSTRESN, 2)
LBLOCAL_UNION$V_LBSTRESC_US  <- as.numeric(LBLOCAL_UNION$V_LBSTRESC_US )
LBLOCAL_UNION$V_LBSTRESC_US  <- round(LBLOCAL_UNION$V_LBSTRESC_US , 2)

# replace all NA values in the dataframe with an empty string.
LBLOCAL_UNION[] <- lapply(LBLOCAL_UNION, function(x) ifelse(is.na(x), "", x))


# LBLOCAL_UNION$X_LBORRES_NUM <- as.numeric(as.character(LBLOCAL_UNION$X_LBORRES_NUM))
# 
# LBLOCAL_UNION$X_LBORRES_NUM <- ifelse(is.na(LBLOCAL_UNION$X_LBORRES_NUM), "", LBLOCAL_UNION$X_LBORRES_NUM)
# Replace NA values with a placeholder (e.g., 0)
# LBLOCAL_UNION$X_LBORRES_NUM[is.na(LBLOCAL_UNION$X_LBORRES_NUM)] <- ""

dim(LBLOCAL_UNION)
# Call the function -Convert_Date_Vals 
CharDate_Cols <- c("V_LBDTC","V_LBDAT")
datetime_columns <- NULL # c("")
table_name <- c("LBLOCAL_UNION")
LBLOCAL_EDC <- Convert_Date_Vals(LBLOCAL_UNION, CharDate_Cols,datetime_columns,table_name)

unique_values <- sapply(LBLOCAL_UNION, function(x) unique(x))
unique_values
# LBLOCAL_EDC <- convert_and_round(LBLOCAL_EDC, LBCONV_SITOUS)

# Arrange columns same as CDB
LBLOCAL_EDC <- LBLOCAL_EDC[names(LBLOCAL_CDB)]

# Post processing for compare
# LBLOCAL_EDC$V_LBORRES <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBORRES) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBORRES), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBORRES))
# LBLOCAL_EDC$V_LBSTRESC <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBSTRESC) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBSTRESC), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBSTRESC))
# LBLOCAL_EDC$V_LBORNRLO <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBORNRLO) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBORNRLO), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBORNRLO))
# LBLOCAL_EDC$V_LBORNRHI <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBORNRHI) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBORNRHI), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBORNRHI))
# LBLOCAL_EDC$V_LBSTNRLO <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBSTNRLO) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBSTNRLO), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBSTNRLO))
# LBLOCAL_EDC$V_LBSTNRHI <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBSTNRHI) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBSTNRHI), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBSTNRHI))
# LBLOCAL_EDC$V_LBORNRLO_OVRD <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBORNRLO_OVRD) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBORNRLO_OVRD), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBORNRLO_OVRD))
# LBLOCAL_EDC$V_LBORNRHI_OVRD <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBORNRHI_OVRD) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBORNRHI_OVRD), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBORNRHI_OVRD))
# LBLOCAL_EDC$V_LBSTNRLO_OVRD <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBSTNRLO_OVRD) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBSTNRLO_OVRD), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBSTNRLO_OVRD))
# LBLOCAL_EDC$V_LBSTNRHI_OVRD <- suppressWarnings(case_when(as.numeric(LBLOCAL_EDC$V_LBSTNRHI_OVRD) != "NA" ~ formatC(as.numeric(LBLOCAL_EDC$V_LBSTNRHI_OVRD), digits=2, format="f"), TRUE ~ LBLOCAL_EDC$V_LBSTNRHI_OVRD))

columns_to_format <- c(
  "V_LBORRES", "V_LBSTRESC", "V_LBORNRLO", "V_LBORNRHI", 
  "V_LBSTNRLO", "V_LBSTNRHI", "V_LBORNRLO_OVRD", 
  "V_LBORNRHI_OVRD", "V_LBSTNRLO_OVRD", "V_LBSTNRHI_OVRD"
)

LBLOCAL_EDC <-LBLOCAL_EDC %>%
  mutate(across(all_of(columns_to_format), ~ format_numeric_column(.)))


LBLOCAL_EDC$DLASTMOD <- substring(LBLOCAL_EDC$DLASTMOD,1,16)
LBLOCAL_EDC$V_LBTIM <- substring(LBLOCAL_EDC$V_LBTIM,1,5)
LBLOCAL_EDC <- LBLOCAL_EDC %>% mutate_if(is.character, ~replace_na(.,""))
LBLOCAL_EDC <- LBLOCAL_EDC[order(LBLOCAL_EDC$STUDYID,LBLOCAL_EDC$COUNTRY,LBLOCAL_EDC$SITENUM,LBLOCAL_EDC$SUBJID,as.integer(LBLOCAL_EDC$EGSEQ),LBLOCAL_EDC$VISIT,LBLOCAL_EDC$VISITDT,LBLOCAL_EDC$FORMID,as.integer(LBLOCAL_EDC$FORMSEQ),LBLOCAL_EDC$DX_LBCAT,LBLOCAL_EDC$DX_LBSCAT,LBLOCAL_EDC$V_LBTESTCD), ]



LBLOCAL_EDC <- LBLOCAL_EDC %>% mutate(across(everything(), as.character))
LBLOCAL_CDB <- LBLOCAL_CDB %>% mutate(across(everything(), as.character))

LBLOCAL_SUMMARY <- capture.output(summary(comparedf(LBLOCAL_EDC, LBLOCAL_CDB)))
LBLOCAL_SUMMARY

unique_values <- sapply(LBLOCAL_EDC, function(x) unique(x))
unique_values 
unique_values <- sapply(LBLOCAL_CDB, function(x) unique(x))
unique_values 
#Export Summary Report

addWorksheet(wb, "LBLOCAL_SUMMARY")
writeData(wb, sheet = "LBLOCAL_SUMMARY", x = LBLOCAL_SUMMARY)

write_xpt(LBLOCAL_EDC,"QC Output/Datasets/EDC/LBLOCAL_EDC.xpt")
write_xpt(LBLOCAL_CDB,"QC Output/Datasets/CDB/LBLOCAL_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)