rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
MHSDD_CDB <- mhsdd
# Post processing for compare
MHSDD_CDB <- MHSDD_CDB %>% mutate(across(everything(), as.character))
MHSDD_CDB$DLASTMOD <- substring(MHSDD_CDB$DLASTMOD,1,16)
MHSDD_CDB <- MHSDD_CDB %>% mutate_if(is.character, ~replace_na(.,""))
MHSDD_CDB <- MHSDD_CDB[order(MHSDD_CDB$STUDYID,MHSDD_CDB$COUNTRY,MHSDD_CDB$SITENUM,MHSDD_CDB$SUBJID,MHSDD_CDB$VISITDT,MHSDD_CDB$FORMID,as.integer(MHSDD_CDB$FORMSEQ),as.integer(MHSDD_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

MH_SDD_01 <- mh_sdd_01
MH_SDD_01 <- MH_SDD_01 %>% mutate(across(everything(), as.character))
MH_SDD_01 <- MH_SDD_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
MHSDD_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,MH_SDD_01.COUNTRY  'COUNTRY'
,MH_SDD_01.SITENUM  'SITENUM'
,MH_SDD_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'

,MH_SDD_01.EGROUPDEF  'EGID'
,MH_SDD_01.ESEQ  'EGSEQ'
,CASE MH_SDD_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN MH_SDD_01.EGROUP||' '||MH_SDD_01.EVENT
   ELSE MH_SDD_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN MH_SDD_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN MH_SDD_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN MH_SDD_01.EVENTEID= 'ev_DAY1' THEN MH_SDD_01.ESEQ + 0.01
WHEN MH_SDD_01.EVENTEID= 'ev_DAY8' THEN MH_SDD_01.ESEQ + 0.08
WHEN MH_SDD_01.EVENTEID= 'ev_DAY15' THEN MH_SDD_01.ESEQ + 0.15
WHEN MH_SDD_01.EVENTEID= 'ev_TUPB' THEN 41 + MH_SDD_01.ESEQ * 0.01
WHEN MH_SDD_01.EVENTEID= 'ev_EOT' THEN 60
WHEN MH_SDD_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN MH_SDD_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN MH_SDD_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN MH_SDD_01.EVENTEID= 'ev_PTFU' THEN 75 + MH_SDD_01.ESEQ * 0.01
WHEN MH_SDD_01.EVENTEID= 'ev_LFU' THEN 80 + MH_SDD_01.ESEQ * 0.01
WHEN MH_SDD_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN MH_SDD_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN MH_SDD_01.EVENTEID= 'ev_UNS' THEN 99 + MH_SDD_01.ESEQ * 0.01
ELSE MH_SDD_01.EVENTEID
END as 'VISITNUM' 
,MH_SDD_01.EVENTDT  'VISITDT'
,MH_SDD_01.FORM  'FORM'
,MH_SDD_01.FORMDEF  'FORMID'
,MH_SDD_01.FSEQ  'FORMSEQ'
,CASE MH_SDD_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  MH_SDD_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,MH_SDD_01.IGSEQ  'IGSEQ'
,MH_SDD_01.DLASTMOD  'DLASTMOD'
,MH_SDD_01.DV_MHCAT  'V_MHCAT'
,MH_SDD_01.DV_MHTERM_SDD  'V_MHTERM_SDD'
,MH_SDD_01.V_QVAL_DISCLAS  'V_QVAL_DISCLAS'
,MH_SDD_01.V_QVAL_PRDIAGYN  'V_QVAL_PRDIAGYN'
,MH_SDD_01.V_MHSTDAT_SDD  'V_MHSTDAT_SDD'
,MH_SDD_01.V_MHSTDAT_SDD  'X_MHSTDAT_SDD'
,MH_SDD_01.V_QVAL_SDDTSTAG  'V_QVAL_SDDTSTAG'
, case 
  when MH_SDD_01.V_QVAL_SDDTSSTG_S01 != '' then MH_SDD_01.V_QVAL_SDDTSSTG_S01
  when MH_SDD_01.V_QVAL_SDDTSSTG_S02 != '' then MH_SDD_01.V_QVAL_SDDTSSTG_S02
	when MH_SDD_01.V_QVAL_SDDTSSTG_S03 != '' then MH_SDD_01.V_QVAL_SDDTSSTG_S03
	else MH_SDD_01.V_QVAL_SDDTSSTG_S04 end
	   AS V_QVAL_SDDTSSTG

,MH_SDD_01.V_QVAL_SDDNSTAG  'V_QVAL_SDDNSTAG'
, CASE 
 when MH_SDD_01.V_QVAL_SDDNSSTG_S01 != '' then MH_SDD_01.V_QVAL_SDDNSSTG_S01
	   else MH_SDD_01.V_QVAL_SDDNSSTG_S02 end
	   AS V_QVAL_SDDNSSTG
,MH_SDD_01.V_QVAL_SDDMSTAG  'V_QVAL_SDDMSTAG'
,MH_SDD_01.V_QVAL_SDDMSSTG_S01  'V_QVAL_SDDMSSTG'
,MH_SDD_01.V_QVAL_SDDSTAGE  'V_QVAL_SDDSTAGE'


, CASE 
  when MH_SDD_01.V_QVAL_SDDSSTG_S01 != '' then MH_SDD_01.V_QVAL_SDDSSTG_S01
  when MH_SDD_01.V_QVAL_SDDSSTG_S02 != '' then MH_SDD_01.V_QVAL_SDDSSTG_S02
	when MH_SDD_01.V_QVAL_SDDSSTG_S03 != '' then MH_SDD_01.V_QVAL_SDDSSTG_S03
	else MH_SDD_01.V_QVAL_SDDSSTG_S04 end
	 AS V_QVAL_SDDSSTG

,MH_SDD_01.V_FAORRES_OCCUR_UNRESTBL  'V_FAORRES_OCCUR_UNRESTBL'
,MH_SDD_01.V_FAORRES_OCCUR_LOCADV  'V_FAORRES_OCCUR_LOCADV'
,MH_SDD_01.V_FAORRES_OCCUR_LOCREC  'V_FAORRES_OCCUR_LOCREC'
,MH_SDD_01.V_FAORRES_OCCUR_LOCMET  'V_FAORRES_OCCUR_LOCMET'
,MH_SDD_01.V_FALOC_LYMPH_LOCMET  'V_FALOC_LYMPH_LOCMET'
,MH_SDD_01.V_FALOC_OTHER_LOCMET  'V_FALOC_OTHER_LOCMET'
,MH_SDD_01.V_FALOC_OTHERSP_LOCMET  'V_FALOC_OTHERSP_LOCMET'
,MH_SDD_01.V_FAORRES_OCCUR_DISMET  'V_FAORRES_OCCUR_DISMET'
,MH_SDD_01.V_FALOC_ADRGL_DISMET  'V_FALOC_ADRGL_DISMET'
,MH_SDD_01.V_FALOC_BONE_DISMET  'V_FALOC_BONE_DISMET'
,MH_SDD_01.V_FALOC_BRAIN_DISMET  'V_FALOC_BRAIN_DISMET'
,MH_SDD_01.V_FALOC_DISLYMPH_DISMET  'V_FALOC_DISLYMPH_DISMET'
,MH_SDD_01.V_FALOC_KIDNEY_DISMET  'V_FALOC_KIDNEY_DISMET'
,MH_SDD_01.V_FALOC_LIVER_DISMET  'V_FALOC_LIVER_DISMET'
,MH_SDD_01.V_FALOC_LUNG_DISMET  'V_FALOC_LUNG_DISMET'
,MH_SDD_01.V_FALOC_MEDSTN_DISMET  'V_FALOC_MEDSTN_DISMET'
,MH_SDD_01.V_FALOC_OVARY_DISMET  'V_FALOC_OVARY_DISMET'
,MH_SDD_01.V_FALOC_PELVIC_DISMET  'V_FALOC_PELVIC_DISMET'
,MH_SDD_01.V_FALOC_PERICDM_DISMET  'V_FALOC_PERICDM_DISMET'
,MH_SDD_01.V_FALOC_PERITN_DISMET  'V_FALOC_PERITN_DISMET'
,MH_SDD_01.V_FALOC_PLEURA_DISMET  'V_FALOC_PLEURA_DISMET'
,MH_SDD_01.V_FALOC_SKIN_DISMET  'V_FALOC_SKIN_DISMET'
,MH_SDD_01.V_FALOC_SUBCTT_DISMET  'V_FALOC_SUBCTT_DISMET'
,MH_SDD_01.V_FALOC_UTERUS_DISMET  'V_FALOC_UTERUS_DISMET'
,MH_SDD_01.V_FALOC_OTHER_DISMET  'V_FALOC_OTHER_DISMET'
,MH_SDD_01.V_FALOC_OTHERSP_DISMET  'V_FALOC_OTHERSP_DISMET'
,MH_SDD_01.V_FAORRES_SDDTSTAG  'V_FAORRES_SDDTSTAG'
, case 
  when MH_SDD_01.V_FAORRES_SDDTSSTG_S01 != '' then MH_SDD_01.V_FAORRES_SDDTSSTG_S01
  when MH_SDD_01.V_FAORRES_SDDTSSTG_S02 != '' then MH_SDD_01.V_FAORRES_SDDTSSTG_S02
	when MH_SDD_01.V_FAORRES_SDDTSSTG_S03 != '' then MH_SDD_01.V_FAORRES_SDDTSSTG_S03
	else MH_SDD_01.V_FAORRES_SDDTSSTG_S04 end
	   AS V_FAORRES_SDDTSSTG

,MH_SDD_01.V_FAORRES_SDDNSTAG  'V_FAORRES_SDDNSTAG'
, case
  when MH_SDD_01.V_FAORRES_SDDNSSTG_S01 != '' then MH_SDD_01.V_FAORRES_SDDNSSTG_S01
	   else MH_SDD_01.V_FAORRES_SDDNSSTG_S02 end
	   AS V_FAORRES_SDDNSSTG

,MH_SDD_01.V_FAORRES_SDDMSTAG  'V_FAORRES_SDDMSTAG'
,MH_SDD_01.V_FAORRES_SDDMSSTG_S01  'V_FAORRES_SDDMSSTG'
,MH_SDD_01.V_FAORRES_SDDSTAGE  'V_FAORRES_SDDSTAGE'

, case 
  when MH_SDD_01.V_FAORRES_SDDSSTG_S01 != '' then MH_SDD_01.V_FAORRES_SDDSSTG_S01
  when MH_SDD_01.V_FAORRES_SDDSSTG_S02 != '' then MH_SDD_01.V_FAORRES_SDDSSTG_S02
	when MH_SDD_01.V_FAORRES_SDDSSTG_S03 != '' then MH_SDD_01.V_FAORRES_SDDSSTG_S03
	else MH_SDD_01.V_FAORRES_SDDSSTG_S04 end
	 AS  V_FAORRES_SDDSSTG

,MH_SDD_01.V_FAORRES_GFMTEGFR  'V_FAORRES_GFMTEGFR'
,MH_SDD_01.V_FAORRES_GFMTALK  'V_FAORRES_GFMTALK'
,MH_SDD_01.V_FAORRES_GFMTROS  'V_FAORRES_GFMTROS'
,MH_SDD_01.V_FAORRES_GFMTBRAF  'V_FAORRES_GFMTBRAF'
,MH_SDD_01.V_FAORRES_GFMTRET  'V_FAORRES_GFMTRET'
,MH_SDD_01.V_FAORRES_GFMTOTHR  'V_FAORRES_GFMTOTHR'
,MH_SDD_01.V_FAORRES_GFMTKRAS  'V_FAORRES_GFMTKRAS'
,MH_SDD_01.V_FAORRES_GFMTNTRK  'V_FAORRES_GFMTNTRK'
,MH_SDD_01.V_FAORRES_GFMTEHER2  'V_FAORRES_GFMTEHER2'
,MH_SDD_01.V_FAORRES_GFMTOTH  'V_FAORRES_GFMTOTH'
,MH_SDD_01.V_FAORRES_GFMTOTSP  'V_FAORRES_GFMTOTSP'
FROM
              MH_SDD_01 MH_SDD_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=MH_SDD_01.SUBJID
              AND S1.SITENUM=MH_SDD_01.SITENUM
              AND MH_SDD_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND MH_SDD_01.FORMILB !='true'
  
 "
  )

# AND MH_SDD_01.FORMILB !='true'
# Call the function -Convert_Date_Vals 
CharDate_Cols <-c("V_MHSTDAT_SDD")
datetime_columns <- NULL
table_name <- c("MHSDD_UNION")
MHSDD_EDC <- Convert_Date_Vals(MHSDD_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
MHSDD_EDC <- MHSDD_EDC[names(MHSDD_CDB)]

# Post processing for compare
MHSDD_EDC$DLASTMOD <- substring(MHSDD_EDC$DLASTMOD,1,16)
MHSDD_EDC <- MHSDD_EDC %>% mutate_if(is.character, ~replace_na(.,""))
MHSDD_EDC <- MHSDD_EDC[order(MHSDD_EDC$STUDYID,MHSDD_EDC$COUNTRY,MHSDD_EDC$SITENUM,MHSDD_EDC$SUBJID,MHSDD_EDC$VISITDT,MHSDD_EDC$FORMID,as.integer(MHSDD_EDC$FORMSEQ),as.integer(MHSDD_EDC$IGSEQ)), ]

#Generate Compare Summary Report
MHSDD_EDC <- MHSDD_EDC %>% mutate(across(everything(), as.character))
MHSDD_CDB <- MHSDD_CDB %>% mutate(across(everything(), as.character))
MHSDD_SUMMARY <- capture.output(summary(comparedf(MHSDD_EDC, MHSDD_CDB)))
print(MHSDD_SUMMARY)

#Export Summary Report
addWorksheet(wb, "MHSDD_SUMMARY")
writeData(wb, sheet = "MHSDD_SUMMARY", x = MHSDD_SUMMARY)

#Export QC Datasets
write_xpt(MHSDD_EDC,"QC Output/Datasets/EDC/MHSDD_EDC.xpt")
write_xpt(MHSDD_CDB,"QC Output/Datasets/CDB/MHSDD_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)