rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
MIPDL1_CDB <- mipdl1
# Post processing for compare
MIPDL1_CDB <- MIPDL1_CDB %>% mutate(across(everything(), as.character))
MIPDL1_CDB$DLASTMOD <- substring(MIPDL1_CDB$DLASTMOD,1,16)
MIPDL1_CDB <- MIPDL1_CDB %>% mutate_if(is.character, ~replace_na(.,""))
MIPDL1_CDB <- MIPDL1_CDB[order(MIPDL1_CDB$STUDYID,MIPDL1_CDB$COUNTRY,MIPDL1_CDB$SITENUM,MIPDL1_CDB$SUBJID,MIPDL1_CDB$VISITDT,MIPDL1_CDB$FORMID,as.integer(MIPDL1_CDB$FORMSEQ),as.integer(MIPDL1_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

MI_PDL1_01 <- mi_pdl1_01
MI_PDL1_01 <- MI_PDL1_01 %>% mutate(across(everything(), as.character))
MI_PDL1_01 <- MI_PDL1_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
MIPDL1_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,MI_PDL1_01.COUNTRY  'COUNTRY'
,MI_PDL1_01.SITENUM  'SITENUM'
,MI_PDL1_01.SUBJID  'SUBJID'
,	S1.STATUS'SUBJSTATUS'
,MI_PDL1_01.EGROUPDEF  'EGID'
,MI_PDL1_01.ESEQ  'EGSEQ'
,CASE MI_PDL1_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN MI_PDL1_01.EGROUP||' '||MI_PDL1_01.EVENT
   ELSE MI_PDL1_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN MI_PDL1_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN MI_PDL1_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN MI_PDL1_01.EVENTEID= 'ev_DAY1' THEN MI_PDL1_01.ESEQ + 0.01
WHEN MI_PDL1_01.EVENTEID= 'ev_DAY8' THEN MI_PDL1_01.ESEQ + 0.08
WHEN MI_PDL1_01.EVENTEID= 'ev_DAY15' THEN MI_PDL1_01.ESEQ + 0.15
WHEN MI_PDL1_01.EVENTEID= 'ev_TUPB' THEN 41 + MI_PDL1_01.ESEQ * 0.01
WHEN MI_PDL1_01.EVENTEID= 'ev_EOT' THEN 60
WHEN MI_PDL1_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN MI_PDL1_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN MI_PDL1_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN MI_PDL1_01.EVENTEID= 'ev_PTFU' THEN 75 + MI_PDL1_01.ESEQ * 0.01
WHEN MI_PDL1_01.EVENTEID= 'ev_LFU' THEN 80 + MI_PDL1_01.ESEQ * 0.01
WHEN MI_PDL1_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN MI_PDL1_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN MI_PDL1_01.EVENTEID= 'ev_UNS' THEN 99 + MI_PDL1_01.ESEQ * 0.01
ELSE MI_PDL1_01.EVENTEID
END as 'VISITNUM'
,MI_PDL1_01.EVENTDT  'VISITDT'
,MI_PDL1_01.FORM  'FORM'
,MI_PDL1_01.FORMDEF  'FORMID'
,MI_PDL1_01.FSEQ  'FORMSEQ'
,CASE MI_PDL1_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  MI_PDL1_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,MI_PDL1_01.IGSEQ  'IGSEQ'
,MI_PDL1_01.DLASTMOD  'DLASTMOD'
,MI_PDL1_01.DV_MICAT  'V_MICAT'
,MI_PDL1_01.V_QVAL_PDL1DAT 'V_QVAL_PDL1DAT'
,MI_PDL1_01.V_QVAL_PDL1DAT 'X_QVAL_PDL1DAT'
,MI_PDL1_01.V_MIORRES_PDL1  'V_MIORRES_PDL1'
,MI_PDL1_01.V_MIORRES_PDL1_U  'V_MIORRESU_PDL1'
,MI_PDL1_01.V_MIORRES_PDL1_TRANS 'V_MISTRESC_PDL1'
,MI_PDL1_01.V_MIORRES_PDL1_TRANS 'V_MISTRESN_PDL1'
,MI_PDL1_01.V_MIORRES_PDL1_TRANSU 'V_MISTRESU_PDL1'
,MI_PDL1_01.V_QVAL_IHCAB  'V_QVAL_IHCAB'

FROM

  MI_PDL1_01 MI_PDL1_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=MI_PDL1_01.SUBJID
              AND S1.SITENUM=MI_PDL1_01.SITENUM
              AND MI_PDL1_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                  AND MI_PDL1_01.FORMILB !='true'
    




 "
  )


# AND MI_PDL1_01.FORMILB !='true'

# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_QVAL_PDL1DAT")
datetime_columns <- NULL
table_name <- c("MIPDL1_UNION")
MIPDL1_EDC <- Convert_Date_Vals(MIPDL1_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
MIPDL1_EDC <- MIPDL1_EDC[names(MIPDL1_CDB)]

# Post processing for compare
MIPDL1_EDC$DLASTMOD <- substring(MIPDL1_EDC$DLASTMOD,1,16)
MIPDL1_EDC <- MIPDL1_EDC %>% mutate_if(is.character, ~replace_na(.,""))
MIPDL1_EDC <- MIPDL1_EDC[order(MIPDL1_EDC$STUDYID,MIPDL1_EDC$COUNTRY,MIPDL1_EDC$SITENUM,MIPDL1_EDC$SUBJID,MIPDL1_EDC$VISITDT,MIPDL1_EDC$FORMID,as.integer(MIPDL1_EDC$FORMSEQ),as.integer(MIPDL1_EDC$IGSEQ)), ]

#Generate Compare Summary Report
MIPDL1_EDC <- MIPDL1_EDC %>% mutate(across(everything(), as.character))
MIPDL1_CDB <- MIPDL1_CDB %>% mutate(across(everything(), as.character))
MIPDL1_SUMMARY <- capture.output(summary(comparedf(MIPDL1_EDC, MIPDL1_CDB)))
print(MIPDL1_SUMMARY)

#Export Summary Report
addWorksheet(wb, "MIPDL1_SUMMARY")
writeData(wb, sheet = "MIPDL1_SUMMARY", x = MIPDL1_SUMMARY)

#Export QC Datasets
write_xpt(MIPDL1_EDC,"QC Output/Datasets/EDC/MIPDL1_EDC.xpt")
write_xpt(MIPDL1_CDB,"QC Output/Datasets/CDB/MIPDL1_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)