rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
NRCOMMONQ_CDB <- nrcommonq
# Post processing for compare
NRCOMMONQ_CDB <- NRCOMMONQ_CDB %>% mutate(across(everything(), as.character))
NRCOMMONQ_CDB$DLASTMOD <- substring(NRCOMMONQ_CDB$DLASTMOD,1,16)
NRCOMMONQ_CDB <- NRCOMMONQ_CDB %>% mutate_if(is.character, ~replace_na(.,""))
NRCOMMONQ_CDB <- NRCOMMONQ_CDB[order(NRCOMMONQ_CDB$STUDYID,NRCOMMONQ_CDB$COUNTRY,NRCOMMONQ_CDB$SITENUM,NRCOMMONQ_CDB$SUBJID,NRCOMMONQ_CDB$VISITDT,NRCOMMONQ_CDB$FORMID,as.integer(NRCOMMONQ_CDB$FORMSEQ),as.integer(NRCOMMONQ_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

NR_COMMONQ_01 <- nr_commonq_01
NR_COMMONQ_01 <- NR_COMMONQ_01 %>% mutate(across(everything(), as.character))
NR_COMMONQ_01 <- NR_COMMONQ_01 %>% mutate_if(is.character, ~replace_na(.,""))

 # -----------  FINAL union query--
NRCOMMONQ_UNION <-
    sqldf(
      " SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,NR_COMMONQ_01.COUNTRY  'COUNTRY'
,NR_COMMONQ_01.SITENUM  'SITENUM'
,NR_COMMONQ_01.SUBJID  'SUBJID'
,S1.STATUS  'SUBJSTATUS'

,NR_COMMONQ_01.EGROUPDEF  'EGID'
,NR_COMMONQ_01.ESEQ  'EGSEQ'
,CASE NR_COMMONQ_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN NR_COMMONQ_01.EGROUP||' '||NR_COMMONQ_01.EVENT
   ELSE NR_COMMONQ_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN NR_COMMONQ_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN NR_COMMONQ_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN NR_COMMONQ_01.EVENTEID= 'ev_DAY1' THEN NR_COMMONQ_01.ESEQ + 0.01
WHEN NR_COMMONQ_01.EVENTEID= 'ev_DAY8' THEN NR_COMMONQ_01.ESEQ + 0.08
WHEN NR_COMMONQ_01.EVENTEID= 'ev_DAY15' THEN NR_COMMONQ_01.ESEQ + 0.15
WHEN NR_COMMONQ_01.EVENTEID= 'ev_TUPB' THEN 41 + NR_COMMONQ_01.ESEQ * 0.01
WHEN NR_COMMONQ_01.EVENTEID= 'ev_EOT' THEN 60
WHEN NR_COMMONQ_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN NR_COMMONQ_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN NR_COMMONQ_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN NR_COMMONQ_01.EVENTEID= 'ev_PTFU' THEN 75 + NR_COMMONQ_01.ESEQ * 0.01
WHEN NR_COMMONQ_01.EVENTEID= 'ev_LFU' THEN 80 + NR_COMMONQ_01.ESEQ * 0.01
WHEN NR_COMMONQ_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN NR_COMMONQ_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN NR_COMMONQ_01.EVENTEID= 'ev_UNS' THEN 99 + NR_COMMONQ_01.ESEQ * 0.01
ELSE NR_COMMONQ_01.EVENTEID
END as 'VISITNUM'
,NR_COMMONQ_01.EVENTDT  'VISITDT'
,NR_COMMONQ_01.FORM  'FORM'
,NR_COMMONQ_01.FORMDEF  'FORMID'
,NR_COMMONQ_01.FSEQ  'FORMSEQ'
,CASE NR_COMMONQ_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  NR_COMMONQ_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,NR_COMMONQ_01.IGSEQ  'IGSEQ'
,NR_COMMONQ_01.DLASTMOD  'DLASTMOD'
,NR_COMMONQ_01.X_AEYN  		 'X_AEYN'
,NR_COMMONQ_01.X_CMYN  		 'X_CMYN'
,NR_COMMONQ_01.X_PRYN  		 'X_PRYN'
,NR_COMMONQ_01.X_ATRADIYN 	 'X_ATRADIYN'
,NR_COMMONQ_01.X_ATCMYN 	 'X_ATCMYN'
FROM
              NR_COMMONQ_01 NR_COMMONQ_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=NR_COMMONQ_01.SUBJID
              AND S1.SITENUM=NR_COMMONQ_01.SITENUM
              AND NR_COMMONQ_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                   AND NR_COMMONQ_01.FORMILB !='true'
    


 "
  )

# AND NR_COMMONQ_01.FORMILB !='true'
 
# Call the function -Convert_Date_Vals

CharDate_Cols <-c()
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("NRCOMMONQ_UNION")
NRCOMMONQ_EDC <- Convert_Date_Vals(NRCOMMONQ_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
NRCOMMONQ_EDC <- NRCOMMONQ_EDC[names(NRCOMMONQ_CDB)]

# Post processing for compare
NRCOMMONQ_EDC$DLASTMOD <- substring(NRCOMMONQ_EDC$DLASTMOD,1,16)
NRCOMMONQ_EDC <- NRCOMMONQ_EDC %>% mutate_if(is.character, ~replace_na(.,""))
NRCOMMONQ_EDC <- NRCOMMONQ_EDC[order(NRCOMMONQ_EDC$STUDYID,NRCOMMONQ_EDC$COUNTRY,NRCOMMONQ_EDC$SITENUM,NRCOMMONQ_EDC$SUBJID,NRCOMMONQ_EDC$VISITDT,NRCOMMONQ_EDC$FORMID,as.integer(NRCOMMONQ_EDC$FORMSEQ),as.integer(NRCOMMONQ_EDC$IGSEQ)), ]

#Generate Compare Summary Report
NRCOMMONQ_EDC <- NRCOMMONQ_EDC %>% mutate(across(everything(), as.character))
NRCOMMONQ_CDB <- NRCOMMONQ_CDB %>% mutate(across(everything(), as.character))
NRCOMMONQ_SUMMARY <- capture.output(summary(comparedf(NRCOMMONQ_EDC, NRCOMMONQ_CDB)))
print(NRCOMMONQ_SUMMARY)

#Export Summary Report
addWorksheet(wb, "NRCOMMONQ_SUMMARY")
writeData(wb, sheet = "NRCOMMONQ_SUMMARY", x = NRCOMMONQ_SUMMARY)

#Export QC Datasets
write_xpt(NRCOMMONQ_EDC,"QC Output/Datasets/EDC/NRCOMMONQ_EDC.xpt")
write_xpt(NRCOMMONQ_CDB,"QC Output/Datasets/CDB/NRCOMMONQ_CDB.xpt")
  
rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)