rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
PCSAMPLE_CDB <- pcsample
# Post processing for compare
PCSAMPLE_CDB <- PCSAMPLE_CDB %>% mutate(across(everything(), as.character))
PCSAMPLE_CDB$DLASTMOD <- substring(PCSAMPLE_CDB$DLASTMOD,1,16)
PCSAMPLE_CDB$V_PCTIM <- substring(PCSAMPLE_CDB$V_PCTIM,1,5)
PCSAMPLE_CDB$V_QVAL_PCLEXTIM <- substring(PCSAMPLE_CDB$V_QVAL_PCLEXTIM,1,5)
PCSAMPLE_CDB <- PCSAMPLE_CDB %>% mutate_if(is.character, ~replace_na(.,""))
PCSAMPLE_CDB <- PCSAMPLE_CDB[order(PCSAMPLE_CDB$STUDYID,PCSAMPLE_CDB$COUNTRY,PCSAMPLE_CDB$SITENUM,PCSAMPLE_CDB$SUBJID,PCSAMPLE_CDB$VISITDT,PCSAMPLE_CDB$FORMID,as.integer(PCSAMPLE_CDB$FORMSEQ),as.integer(PCSAMPLE_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

PC_INTSVTPT_01 <- pc_intsvtpt_01
PC_INTSVTPT_01 <- PC_INTSVTPT_01 %>% mutate(across(everything(), as.character))
PC_INTSVTPT_01 <- PC_INTSVTPT_01 %>% mutate_if(is.character, ~replace_na(.,""))

PC_SPARSE_01 <- pc_sparse_01
PC_SPARSE_01 <- PC_SPARSE_01 %>% mutate(across(everything(), as.character))
PC_SPARSE_01 <- PC_SPARSE_01 %>% mutate_if(is.character, ~replace_na(.,""))

PC_SPARSE_02 <- pc_sparse_02
PC_SPARSE_02 <- PC_SPARSE_02 %>% mutate(across(everything(), as.character))
PC_SPARSE_02 <- PC_SPARSE_02 %>% mutate_if(is.character, ~replace_na(.,""))

PC_SPARSE_03 <- pc_sparse_03
PC_SPARSE_03 <- PC_SPARSE_03 %>% mutate(across(everything(), as.character))
PC_SPARSE_03 <- PC_SPARSE_03 %>% mutate_if(is.character, ~replace_na(.,""))

PC_UNS_01 <- pc_uns_01
PC_UNS_01 <- PC_UNS_01 %>% mutate(across(everything(), as.character))
PC_UNS_01 <- PC_UNS_01 %>% mutate_if(is.character, ~replace_na(.,""))

PC_URINTPT_01 <- pc_urintpt_01
PC_URINTPT_01 <- PC_URINTPT_01 %>% mutate(across(everything(), as.character))
PC_URINTPT_01 <- PC_URINTPT_01 %>% mutate_if(is.character, ~replace_na(.,""))

PC_URINUNS_01<-pc_urinuns_01
PC_URINUNS_01 <- PC_URINUNS_01 %>% mutate(across(everything(), as.character))
PC_URINUNS_01 <- PC_URINUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))




#-----------  FINAL union query--
PCSAMPLE_UNION <-
  sqldf(
    " 
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_INTSVTPT_01.COUNTRY  'COUNTRY'
,PC_INTSVTPT_01.SITENUM  'SITENUM'
,PC_INTSVTPT_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PC_INTSVTPT_01.EGROUPDEF  'EGID'
,PC_INTSVTPT_01.ESEQ  'EGSEQ'
,CASE PC_INTSVTPT_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_INTSVTPT_01.EGROUP||' '||PC_INTSVTPT_01.EVENT
   ELSE PC_INTSVTPT_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_DAY1' THEN PC_INTSVTPT_01.ESEQ + 0.01
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_DAY8' THEN PC_INTSVTPT_01.ESEQ + 0.08
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_DAY15' THEN PC_INTSVTPT_01.ESEQ + 0.15
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_TUPB' THEN 41 + PC_INTSVTPT_01.ESEQ * 0.01
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_PTFU' THEN 75 + PC_INTSVTPT_01.ESEQ * 0.01
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_LFU' THEN 80 + PC_INTSVTPT_01.ESEQ * 0.01
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_INTSVTPT_01.EVENTEID= 'ev_UNS' THEN 99 + PC_INTSVTPT_01.ESEQ * 0.01
ELSE PC_INTSVTPT_01.EVENTEID
END as 'VISITNUM'
,PC_INTSVTPT_01.EVENTDT  'VISITDT'
,PC_INTSVTPT_01.FORM  'FORM'
,PC_INTSVTPT_01.FORMDEF  'FORMID'
,PC_INTSVTPT_01.FSEQ  'FORMSEQ'
,CASE PC_INTSVTPT_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_INTSVTPT_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_INTSVTPT_01.IGSEQ  'IGSEQ'
,PC_INTSVTPT_01.DLASTMOD  'DLASTMOD'
,PC_INTSVTPT_01.V_PCPERF_PCALL  'V_PCPERF_PCALL'
,PC_INTSVTPT_01.V_PCREASND_PCALL  'V_PCREASND_PCALL'
,PC_INTSVTPT_01.DV_PCSPEC  'V_PCSPEC'
,PC_INTSVTPT_01.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'

,CASE PC_INTSVTPT_01.DV_PCTPT 
WHEN '0.0' THEN '0'
WHEN '0.25D' THEN '0.0025'
WHEN '0.5D' THEN '0.005'
WHEN '0.5' THEN '0.5'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
WHEN '0.0-24.0' THEN '0.1024'
ELSE  PC_INTSVTPT_01.DV_PCTPT
END AS 'V_PCTPTNUM'

,PC_INTSVTPT_01.DV_PCTPT_D  'V_PCTPT'
,PC_INTSVTPT_01.DV_PCTPTREF  'V_PCTPTREF'
,PC_INTSVTPT_01.V_PCSTAT  'V_PCSTAT'

,PC_INTSVTPT_01.V_PCREASND  'V_PCREASND'
,PC_INTSVTPT_01.V_PCDTC 'V_PCDTC'
,PC_INTSVTPT_01.V_PCDTC_DT  'V_PCDAT'
,PC_INTSVTPT_01.V_PCDTC_TM  'V_PCTIM'
,PC_INTSVTPT_01.V_PCDTC 'X_PCDTC'
,PC_INTSVTPT_01.V_PCDTC_DT  'X_PCDAT'
,PC_INTSVTPT_01.V_PCDTC_TM  'X_PCTIM'
,NULL 'V_PCORRES_VOLUME'
,NULL 'V_PCORRESU_VOLUME'
,NULL 'V_PCSTRESC_VOLUME'
,NULL 'V_PCSTRESN_VOLUME'
,NULL 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
              PC_INTSVTPT_01 PC_INTSVTPT_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_INTSVTPT_01.SUBJID
               AND  S1.SITENUM=PC_INTSVTPT_01.SITENUM
              AND PC_INTSVTPT_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_INTSVTPT_01.FORMILB !='true'
    
UNION


SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_SPARSE_01.COUNTRY  'COUNTRY'
,PC_SPARSE_01.SITENUM  'SITENUM'
,PC_SPARSE_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,PC_SPARSE_01.EGROUPDEF  'EGID'
,PC_SPARSE_01.ESEQ  'EGSEQ'
,CASE PC_SPARSE_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_SPARSE_01.EGROUP||' '||PC_SPARSE_01.EVENT
   ELSE PC_SPARSE_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_SPARSE_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_SPARSE_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_SPARSE_01.EVENTEID= 'ev_DAY1' THEN PC_SPARSE_01.ESEQ + 0.01
WHEN PC_SPARSE_01.EVENTEID= 'ev_DAY8' THEN PC_SPARSE_01.ESEQ + 0.08
WHEN PC_SPARSE_01.EVENTEID= 'ev_DAY15' THEN PC_SPARSE_01.ESEQ + 0.15
WHEN PC_SPARSE_01.EVENTEID= 'ev_TUPB' THEN 41 + PC_SPARSE_01.ESEQ * 0.01
WHEN PC_SPARSE_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_SPARSE_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_SPARSE_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_SPARSE_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_SPARSE_01.EVENTEID= 'ev_PTFU' THEN 75 + PC_SPARSE_01.ESEQ * 0.01
WHEN PC_SPARSE_01.EVENTEID= 'ev_LFU' THEN 80 + PC_SPARSE_01.ESEQ * 0.01
WHEN PC_SPARSE_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_SPARSE_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_SPARSE_01.EVENTEID= 'ev_UNS' THEN 99 + PC_SPARSE_01.ESEQ * 0.01
ELSE PC_SPARSE_01.EVENTEID
END as 'VISITNUM'
,PC_SPARSE_01.EVENTDT  'VISITDT'
,PC_SPARSE_01.FORM  'FORM'
,PC_SPARSE_01.FORMDEF  'FORMID'
,PC_SPARSE_01.FSEQ  'FORMSEQ'
,CASE PC_SPARSE_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_SPARSE_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_SPARSE_01.IGSEQ  'IGSEQ'
,PC_SPARSE_01.DLASTMOD  'DLASTMOD'
,PC_SPARSE_01.V_PCPERF_PCALL  'V_PCPERF_PCALL'
,PC_SPARSE_01.V_PCREASND_PCALL  'V_PCREASND_PCALL'
,PC_SPARSE_01.DV_PCSPEC  'V_PCSPEC'
,PC_SPARSE_01.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'
,NULL 'V_PCTPTNUM'
,NULL  'V_PCTPT'
,NULL  'V_PCTPTREF'
,NULL  'V_PCSTAT'

,NULL 'V_PCREASND'
,PC_SPARSE_01.V_PCDTC  'V_PCDTC'
,PC_SPARSE_01.V_PCDTC_DT  'V_PCDAT'
,PC_SPARSE_01.V_PCDTC_TM  'V_PCTIM'
,PC_SPARSE_01.V_PCDTC  'X_PCDTC'
,PC_SPARSE_01.V_PCDTC_DT  'X_PCDAT'
,PC_SPARSE_01.V_PCDTC_TM  'X_PCTIM'
,NULL 'V_PCORRES_VOLUME'
,NULL 'V_PCORRESU_VOLUME'
,NULL 'V_PCSTRESC_VOLUME'
,NULL 'V_PCSTRESN_VOLUME'
,NULL 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
              PC_SPARSE_01 PC_SPARSE_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_SPARSE_01.SUBJID
               AND  S1.SITENUM=PC_SPARSE_01.SITENUM
              AND PC_SPARSE_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_SPARSE_01.FORMILB !='true'
   
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_SPARSE_02.COUNTRY  'COUNTRY'
,PC_SPARSE_02.SITENUM  'SITENUM'
,PC_SPARSE_02.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PC_SPARSE_02.EGROUPDEF  'EGID'
,PC_SPARSE_02.ESEQ  'EGSEQ'
,CASE PC_SPARSE_02.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_SPARSE_02.EGROUP||' '||PC_SPARSE_02.EVENT
   ELSE PC_SPARSE_02.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_SPARSE_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_SPARSE_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_SPARSE_02.EVENTEID= 'ev_DAY1' THEN PC_SPARSE_02.ESEQ + 0.01
WHEN PC_SPARSE_02.EVENTEID= 'ev_DAY8' THEN PC_SPARSE_02.ESEQ + 0.08
WHEN PC_SPARSE_02.EVENTEID= 'ev_DAY15' THEN PC_SPARSE_02.ESEQ + 0.15
WHEN PC_SPARSE_02.EVENTEID= 'ev_TUPB' THEN 41 + PC_SPARSE_02.ESEQ * 0.01
WHEN PC_SPARSE_02.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_SPARSE_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_SPARSE_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_SPARSE_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_SPARSE_02.EVENTEID= 'ev_PTFU' THEN 75 + PC_SPARSE_02.ESEQ * 0.01
WHEN PC_SPARSE_02.EVENTEID= 'ev_LFU' THEN 80 + PC_SPARSE_02.ESEQ * 0.01
WHEN PC_SPARSE_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_SPARSE_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_SPARSE_02.EVENTEID= 'ev_UNS' THEN 99 + PC_SPARSE_02.ESEQ * 0.01
ELSE PC_SPARSE_02.EVENTEID
END as 'VISITNUM'
,PC_SPARSE_02.EVENTDT  'VISITDT'
,PC_SPARSE_02.FORM  'FORM'
,PC_SPARSE_02.FORMDEF  'FORMID'
,PC_SPARSE_02.FSEQ  'FORMSEQ'
,CASE PC_SPARSE_02.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_SPARSE_02.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_SPARSE_02.IGSEQ  'IGSEQ'
,PC_SPARSE_02.DLASTMOD  'DLASTMOD'
,PC_SPARSE_02.V_PCPERF_PCALL  'V_PCPERF_PCALL'
,PC_SPARSE_02.V_PCREASND_PCALL  'V_PCREASND_PCALL'
,PC_SPARSE_02.DV_PCSPEC  'V_PCSPEC'
,PC_SPARSE_02.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'

,CASE PC_SPARSE_02.DV_PCTPT 
WHEN '0.0' THEN '0'
WHEN '0.25D' THEN '0.0025'
WHEN '0.5D' THEN '0.005'
WHEN '0.5' THEN '0.5'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
WHEN '0.0-24.0' THEN '0.1024'
ELSE  PC_SPARSE_02.DV_PCTPT
END AS 'V_PCTPTNUM'

,PC_SPARSE_02.DV_PCTPT_D  'V_PCTPT'
,PC_SPARSE_02.DV_PCTPTREF  'V_PCTPTREF'
,PC_SPARSE_02.V_PCSTAT  'V_PCSTAT'

,NULL 'V_PCREASND'
,PC_SPARSE_02.V_PCDTC  'V_PCDTC'
,PC_SPARSE_02.V_PCDTC_DT  'V_PCDAT'
,PC_SPARSE_02.V_PCDTC_TM  'V_PCTIM'
,PC_SPARSE_02.V_PCDTC  'X_PCDTC'
,PC_SPARSE_02.V_PCDTC_DT  'X_PCDAT'
,PC_SPARSE_02.V_PCDTC_TM  'X_PCTIM'
,NULL 'V_PCORRES_VOLUME'
,NULL 'V_PCORRESU_VOLUME'
,NULL 'V_PCSTRESC_VOLUME'
,NULL 'V_PCSTRESN_VOLUME'
,NULL 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
              PC_SPARSE_02 PC_SPARSE_02,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_SPARSE_02.SUBJID
               AND  S1.SITENUM=PC_SPARSE_02.SITENUM
              AND PC_SPARSE_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_SPARSE_02.FORMILB !='true'
   
UNION    

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_SPARSE_03.COUNTRY  'COUNTRY'
,PC_SPARSE_03.SITENUM  'SITENUM'
,PC_SPARSE_03.SUBJID  'SUBJID'
, S1.STATUS 'SUBJSTATUS'
,PC_SPARSE_03.EGROUPDEF  'EGID'
,PC_SPARSE_03.ESEQ  'EGSEQ'
,CASE PC_SPARSE_03.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_SPARSE_03.EGROUP||' '||PC_SPARSE_03.EVENT
   ELSE PC_SPARSE_03.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_SPARSE_03.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_SPARSE_03.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_SPARSE_03.EVENTEID= 'ev_DAY1' THEN PC_SPARSE_03.ESEQ + 0.01
WHEN PC_SPARSE_03.EVENTEID= 'ev_DAY8' THEN PC_SPARSE_03.ESEQ + 0.08
WHEN PC_SPARSE_03.EVENTEID= 'ev_DAY15' THEN PC_SPARSE_03.ESEQ + 0.15
WHEN PC_SPARSE_03.EVENTEID= 'ev_TUPB' THEN 41 + PC_SPARSE_03.ESEQ * 0.01
WHEN PC_SPARSE_03.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_SPARSE_03.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_SPARSE_03.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_SPARSE_03.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_SPARSE_03.EVENTEID= 'ev_PTFU' THEN 75 + PC_SPARSE_03.ESEQ * 0.01
WHEN PC_SPARSE_03.EVENTEID= 'ev_LFU' THEN 80 + PC_SPARSE_03.ESEQ * 0.01
WHEN PC_SPARSE_03.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_SPARSE_03.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_SPARSE_03.EVENTEID= 'ev_UNS' THEN 99 + PC_SPARSE_03.ESEQ * 0.01
ELSE PC_SPARSE_03.EVENTEID
END as 'VISITNUM'
,PC_SPARSE_03.EVENTDT  'VISITDT'
,PC_SPARSE_03.FORM  'FORM'
,PC_SPARSE_03.FORMDEF  'FORMID'
,PC_SPARSE_03.FSEQ  'FORMSEQ'
,CASE PC_SPARSE_03.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_SPARSE_03.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_SPARSE_03.IGSEQ  'IGSEQ'
,PC_SPARSE_03.DLASTMOD  'DLASTMOD'
,PC_SPARSE_03.V_PCPERF_PCALL  'V_PCPERF_PCALL'
,PC_SPARSE_03.V_PCREASND_PCALL  'V_PCREASND_PCALL'
,PC_SPARSE_03.DV_PCSPEC  'V_PCSPEC'
,PC_SPARSE_03.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'

,CASE PC_SPARSE_03.DV_PCTPT 
WHEN '0.0' THEN '0'
WHEN '0.25D' THEN '0.0025'
WHEN '0.5D' THEN '0.005'
WHEN '0.5' THEN '0.5'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
WHEN '0.0-24.0' THEN '0.1024'
ELSE  PC_SPARSE_03.DV_PCTPT
END AS 'V_PCTPTNUM'
,PC_SPARSE_03.DV_PCTPT_D  'V_PCTPT'
,PC_SPARSE_03.DV_PCTPTREF  'V_PCTPTREF'
,PC_SPARSE_03.V_PCSTAT  'V_PCSTAT'

,NULL 'V_PCREASND'
,PC_SPARSE_03.V_PCDTC  'V_PCDTC'
,PC_SPARSE_03.V_PCDTC_DT  'V_PCDAT'
,PC_SPARSE_03.V_PCDTC_TM  'V_PCTIM'
,PC_SPARSE_03.V_PCDTC  'X_PCDTC'
,PC_SPARSE_03.V_PCDTC_DT  'X_PCDAT'
,PC_SPARSE_03.V_PCDTC_TM  'X_PCTIM'
,NULL 'V_PCORRES_VOLUME'
,NULL 'V_PCORRESU_VOLUME'
,NULL 'V_PCSTRESC_VOLUME'
,NULL 'V_PCSTRESN_VOLUME'
,NULL 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
              PC_SPARSE_03 PC_SPARSE_03,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_SPARSE_03.SUBJID
               AND  S1.SITENUM=PC_SPARSE_03.SITENUM
              AND PC_SPARSE_03.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_SPARSE_03.FORMILB !='true'
   
UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_UNS_01.COUNTRY  'COUNTRY'
,PC_UNS_01.SITENUM  'SITENUM'
,PC_UNS_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,PC_UNS_01.EGROUPDEF  'EGID'
,PC_UNS_01.ESEQ  'EGSEQ'
,CASE PC_UNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_UNS_01.EGROUP||' '||PC_UNS_01.EVENT
   ELSE PC_UNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_UNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_UNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_UNS_01.EVENTEID= 'ev_DAY1' THEN PC_UNS_01.ESEQ + 0.01
WHEN PC_UNS_01.EVENTEID= 'ev_DAY8' THEN PC_UNS_01.ESEQ + 0.08
WHEN PC_UNS_01.EVENTEID= 'ev_DAY15' THEN PC_UNS_01.ESEQ + 0.15
WHEN PC_UNS_01.EVENTEID= 'ev_TUPB' THEN 41 + PC_UNS_01.ESEQ * 0.01
WHEN PC_UNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_UNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_UNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_UNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_UNS_01.EVENTEID= 'ev_PTFU' THEN 75 + PC_UNS_01.ESEQ * 0.01
WHEN PC_UNS_01.EVENTEID= 'ev_LFU' THEN 80 + PC_UNS_01.ESEQ * 0.01
WHEN PC_UNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_UNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_UNS_01.EVENTEID= 'ev_UNS' THEN 99 + PC_UNS_01.ESEQ * 0.01
ELSE PC_UNS_01.EVENTEID
END as 'VISITNUM'
,PC_UNS_01.EVENTDT  'VISITDT'
,PC_UNS_01.FORM  'FORM'
,PC_UNS_01.FORMDEF  'FORMID'
,PC_UNS_01.FSEQ  'FORMSEQ'
,CASE PC_UNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_UNS_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_UNS_01.IGSEQ  'IGSEQ'
,PC_UNS_01.DLASTMOD  'DLASTMOD'
,NULL  'V_PCPERF_PCALL'
,NULL  'V_PCREASND_PCALL'
,PC_UNS_01.DV_PCSPEC  'V_PCSPEC'
,PC_UNS_01.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'
,NULL 'V_PCTPTNUM'
,NULL  'V_PCTPT'
,NULL  'V_PCTPTREF'
,NULL   'V_PCSTAT'

,NULL 'V_PCREASND'
,PC_UNS_01.V_PCDTC 'V_PCDTC'
,PC_UNS_01.V_PCDTC_DT  'V_PCDAT'
,PC_UNS_01.V_PCDTC_TM  'V_PCTIM'
,PC_UNS_01.V_PCDTC 'X_PCDTC'
,PC_UNS_01.V_PCDTC_DT  'X_PCDAT'
,PC_UNS_01.V_PCDTC_TM  'X_PCTIM'
,NULL 'V_PCORRES_VOLUME'
,NULL 'V_PCORRESU_VOLUME'
,NULL 'V_PCSTRESC_VOLUME'
,NULL 'V_PCSTRESN_VOLUME'
,NULL 'V_PCSTRESU_VOLUME'
,PC_UNS_01.V_QVAL_PCLEXDTC 'V_QVAL_PCLEXDTC'
,PC_UNS_01.V_QVAL_PCLEXDTC_DT 'V_QVAL_PCLEXDAT'
,PC_UNS_01.V_QVAL_PCLEXDTC_TM 'V_QVAL_PCLEXTIM'
,PC_UNS_01.V_QVAL_PCLEXDTC 'X_QVAL_PCLEXDTC'
,PC_UNS_01.V_QVAL_PCLEXDTC_DT 'X_QVAL_PCLEXDAT'
,PC_UNS_01.V_QVAL_PCLEXDTC_TM 'X_QVAL_PCLEXTIM'
FROM
              PC_UNS_01 PC_UNS_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_UNS_01.SUBJID
               AND  S1.SITENUM=PC_UNS_01.SITENUM
              AND PC_UNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_UNS_01.FORMILB !='true'
  
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_URINTPT_01.COUNTRY  'COUNTRY'
,PC_URINTPT_01.SITENUM  'SITENUM'
,PC_URINTPT_01.SUBJID  'SUBJID'
, S1.STATUS  'SUBJSTATUS'
,PC_URINTPT_01.EGROUPDEF  'EGID'
,PC_URINTPT_01.ESEQ  'EGSEQ'
,CASE PC_URINTPT_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PC_URINTPT_01.EGROUP||' '||PC_URINTPT_01.EVENT
   ELSE PC_URINTPT_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PC_URINTPT_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_URINTPT_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_URINTPT_01.EVENTEID= 'ev_DAY1' THEN PC_URINTPT_01.ESEQ + 0.01
WHEN PC_URINTPT_01.EVENTEID= 'ev_DAY8' THEN PC_URINTPT_01.ESEQ + 0.08
WHEN PC_URINTPT_01.EVENTEID= 'ev_DAY15' THEN PC_URINTPT_01.ESEQ + 0.15
WHEN PC_URINTPT_01.EVENTEID= 'ev_TUPB' THEN 41 + PC_URINTPT_01.ESEQ * 0.01
WHEN PC_URINTPT_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_URINTPT_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_URINTPT_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_URINTPT_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_URINTPT_01.EVENTEID= 'ev_PTFU' THEN 75 + PC_URINTPT_01.ESEQ * 0.01
WHEN PC_URINTPT_01.EVENTEID= 'ev_LFU' THEN 80 + PC_URINTPT_01.ESEQ * 0.01
WHEN PC_URINTPT_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_URINTPT_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_URINTPT_01.EVENTEID= 'ev_UNS' THEN 99 + PC_URINTPT_01.ESEQ * 0.01
ELSE PC_URINTPT_01.EVENTEID
END as 'VISITNUM'
,PC_URINTPT_01.EVENTDT  'VISITDT'
,PC_URINTPT_01.FORM  'FORM'
,PC_URINTPT_01.FORMDEF  'FORMID'
,PC_URINTPT_01.FSEQ  'FORMSEQ'
,CASE PC_URINTPT_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PC_URINTPT_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PC_URINTPT_01.IGSEQ  'IGSEQ'
,PC_URINTPT_01.DLASTMOD  'DLASTMOD'
,PC_URINTPT_01.V_PCPERF_PCALL  'V_PCPERF_PCALL'
,PC_URINTPT_01.V_PCREASND_PCALL  'V_PCREASND_PCALL'
,PC_URINTPT_01.DV_PCSPEC  'V_PCSPEC'
,PC_URINTPT_01.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'

,CASE PC_URINTPT_01.DV_PCTPT 
WHEN '0.0' THEN '0'
WHEN '0.25D' THEN '0.0025'
WHEN '0.5D' THEN '0.005'
WHEN '0.5' THEN '0.5'
WHEN '1.0' THEN '1'
WHEN '2.0' THEN '2'
WHEN '4.0' THEN '4'
WHEN '6.0' THEN '6'
WHEN '24.0' THEN '24'
WHEN '0.0-24.0' THEN '0.1024'
ELSE  PC_URINTPT_01.DV_PCTPT
END AS 'V_PCTPTNUM'
,PC_URINTPT_01.DV_PCTPT_D  'V_PCTPT'
,PC_URINTPT_01.DV_PCTPTREF  'V_PCTPTREF'
,PC_URINTPT_01.V_PCSTAT  'V_PCSTAT'

,PC_URINTPT_01.V_PCREASND 'V_PCREASND'
,PC_URINTPT_01.V_PCDTC 'V_PCDTC'
,PC_URINTPT_01.V_PCDTC_DT  'V_PCDAT'
,PC_URINTPT_01.V_PCDTC_TM  'V_PCTIM'
,PC_URINTPT_01.V_PCDTC 'X_PCDTC'
,PC_URINTPT_01.V_PCDTC_DT  'X_PCDAT'
,PC_URINTPT_01.V_PCDTC_TM  'X_PCTIM'
,PC_URINTPT_01.V_PCORRES_VOLUME  'V_PCORRES_VOLUME'
,PC_URINTPT_01.V_PCORRES_VOLUME_U 'V_PCORRESU_VOLUME'
,PC_URINTPT_01.V_PCORRES_VOLUME_TRANS 'V_PCSTRESC_VOLUME'
,PC_URINTPT_01.V_PCORRES_VOLUME_TRANS 'V_PCSTRESN_VOLUME'
,PC_URINTPT_01.V_PCORRES_VOLUME_TRANSU 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
              PC_URINTPT_01 PC_URINTPT_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PC_URINTPT_01.SUBJID
               AND  S1.SITENUM=PC_URINTPT_01.SITENUM
              AND PC_URINTPT_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_URINTPT_01.FORMILB !='true'
              
 UNION
 SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PC_URINUNS_01.COUNTRY  'COUNTRY'
,PC_URINUNS_01.SITENUM  'SITENUM'
,PC_URINUNS_01.SUBJID  'SUBJID'
,	 S1.STATUS  'SUBJSTATUS'
,PC_URINUNS_01.EGROUPDEF  'EGID'
,PC_URINUNS_01.ESEQ  'EGSEQ'
,CASE PC_URINUNS_01.EGROUPDEF
WHEN 'eg_TRTA1C' THEN PC_URINUNS_01.EGROUP||' '||PC_URINUNS_01.EVENT
ELSE PC_URINUNS_01.EVENT
END AS 'VISIT'
,CASE 
WHEN PC_URINUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PC_URINUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PC_URINUNS_01.EVENTEID= 'ev_DAY1' THEN PC_URINUNS_01.ESEQ + 0.01
WHEN PC_URINUNS_01.EVENTEID= 'ev_DAY8' THEN PC_URINUNS_01.ESEQ + 0.08
WHEN PC_URINUNS_01.EVENTEID= 'ev_DAY15' THEN PC_URINUNS_01.ESEQ + 0.15
WHEN PC_URINUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + PC_URINUNS_01.ESEQ * 0.01
WHEN PC_URINUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PC_URINUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PC_URINUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PC_URINUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PC_URINUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + PC_URINUNS_01.ESEQ * 0.01
WHEN PC_URINUNS_01.EVENTEID= 'ev_LFU' THEN 80 + PC_URINUNS_01.ESEQ * 0.01
WHEN PC_URINUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PC_URINUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PC_URINUNS_01.EVENTEID= 'ev_UNS' THEN 99 + PC_URINUNS_01.ESEQ * 0.01
ELSE PC_URINUNS_01.EVENTEID
END as 'VISITNUM'
,PC_URINUNS_01.EVENTDT  'VISITDT'
,PC_URINUNS_01.FORM  'FORM'
,PC_URINUNS_01.FORMDEF  'FORMID'
,PC_URINUNS_01.FSEQ  'FORMSEQ'
,CASE PC_URINUNS_01.FORMSTATUS
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE  PC_URINUNS_01.FORMSTATUS
END AS 'FORMSTATUS'
,PC_URINUNS_01.IGSEQ  'IGSEQ'
,PC_URINUNS_01.DLASTMOD  'DLASTMOD'
,NULL 'V_PCPERF_PCALL'
,NUll  'V_PCREASND_PCALL'
,PC_URINUNS_01.DV_PCSPEC  'V_PCSPEC'
,PC_URINUNS_01.DV_PCTEST_ANALYTE  'V_PCTEST_ANALYTE'
,NULL 'V_PCTPTNUM'

,NULL 'V_PCTPT'
,NULL  'V_PCTPTREF'
,NULL 'V_PCSTAT'
,NULL 'V_PCREASND'
,PC_URINUNS_01.V_PCDTC 'V_PCDTC'
,PC_URINUNS_01.V_PCDTC_DT  'V_PCDAT'
,PC_URINUNS_01.V_PCDTC_TM  'V_PCTIM'
,PC_URINUNS_01.V_PCDTC 'X_PCDTC'
,PC_URINUNS_01.V_PCDTC_DT  'X_PCDAT'
,PC_URINUNS_01.V_PCDTC_TM  'X_PCTIM'
,PC_URINUNS_01.V_PCORRES_VOLUME  'V_PCORRES_VOLUME'
,PC_URINUNS_01.V_PCORRES_VOLUME_U 'V_PCORRESU_VOLUME'
,PC_URINUNS_01.V_PCORRES_VOLUME_TRANS 'V_PCSTRESC_VOLUME'
,PC_URINUNS_01.V_PCORRES_VOLUME_TRANS 'V_PCSTRESN_VOLUME'
,PC_URINUNS_01.V_PCORRES_VOLUME_TRANSU 'V_PCSTRESU_VOLUME'
,NULL 'V_QVAL_PCLEXDTC'
,NULL 'V_QVAL_PCLEXDAT'
,NULL 'V_QVAL_PCLEXTIM'
,NULL 'X_QVAL_PCLEXDTC'
,NULL 'X_QVAL_PCLEXDAT'
,NULL 'X_QVAL_PCLEXTIM'
FROM
PC_URINUNS_01 PC_URINUNS_01,
SUBJECTS S1

WHERE
S1.SUBJID=PC_URINUNS_01.SUBJID
AND  S1.SITENUM=PC_URINUNS_01.SITENUM
AND PC_URINUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PC_URINUNS_01.FORMILB !='true'
              
 "
  )


# AND PC_INTSVTPT_01.FORMILB !='true'
# AND PC_SPARSE_01.FORMILB !='true'
# AND PC_SPARSE_02.FORMILB !='true'
# AND PC_SPARSE_03.FORMILB !='true'    
# AND PC_UNS_01.FORMILB !='true'
# AND PC_URINTPT_01.FORMILB !='true'

# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_PCDTC","V_PCDAT","V_QVAL_PCLEXDTC","V_QVAL_PCLEXDAT")
datetime_columns <-NULL
table_name <- c("PCSAMPLE_UNION")
PCSAMPLE_EDC <- Convert_Date_Vals(PCSAMPLE_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
PCSAMPLE_EDC <- PCSAMPLE_EDC[names(PCSAMPLE_CDB)]

# Post processing for compare
PCSAMPLE_EDC$DLASTMOD <- substring(PCSAMPLE_EDC$DLASTMOD,1,16)
PCSAMPLE_EDC$V_PCTIM <- substring(PCSAMPLE_EDC$V_PCTIM,1,5)
PCSAMPLE_EDC$V_QVAL_PCLEXTIM <- substring(PCSAMPLE_EDC$V_QVAL_PCLEXTIM,1,5)
PCSAMPLE_EDC <- PCSAMPLE_EDC %>% mutate_if(is.character, ~replace_na(.,""))
PCSAMPLE_EDC <- PCSAMPLE_EDC[order(PCSAMPLE_EDC$STUDYID,PCSAMPLE_EDC$COUNTRY,PCSAMPLE_EDC$SITENUM,PCSAMPLE_EDC$SUBJID,PCSAMPLE_EDC$VISITDT,PCSAMPLE_EDC$FORMID,as.integer(PCSAMPLE_EDC$FORMSEQ),as.integer(PCSAMPLE_EDC$IGSEQ)), ]

#Generate Compare Summary Report
PCSAMPLE_EDC <- PCSAMPLE_EDC %>% mutate(across(everything(), as.character))
PCSAMPLE_CDB <- PCSAMPLE_CDB %>% mutate(across(everything(), as.character))
PCSAMPLE_SUMMARY <- capture.output(summary(comparedf(PCSAMPLE_EDC, PCSAMPLE_CDB)))
print(PCSAMPLE_SUMMARY)

#Export Summary Report
addWorksheet(wb, "PCSAMPLE_SUMMARY")
writeData(wb, sheet = "PCSAMPLE_SUMMARY", x = PCSAMPLE_SUMMARY)

#Export QC Datasets
write_xpt(PCSAMPLE_EDC,"QC Output/Datasets/EDC/PCSAMPLE_EDC.xpt")
write_xpt(PCSAMPLE_CDB,"QC Output/Datasets/CDB/PCSAMPLE_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)