rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
PRATRADI_CDB <- pratradi
# Post processing for compare
PRATRADI_CDB <- PRATRADI_CDB %>% mutate(across(everything(), as.character))
PRATRADI_CDB$DLASTMOD <- substring(PRATRADI_CDB$DLASTMOD,1,16)
PRATRADI_CDB <- PRATRADI_CDB %>% mutate_if(is.character, ~replace_na(.,""))
PRATRADI_CDB <- PRATRADI_CDB[order(PRATRADI_CDB$STUDYID,PRATRADI_CDB$COUNTRY,PRATRADI_CDB$SITENUM,PRATRADI_CDB$SUBJID,PRATRADI_CDB$VISITDT,PRATRADI_CDB$FORMID,as.integer(PRATRADI_CDB$FORMSEQ),as.integer(PRATRADI_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub
PR_ATRADI_01 <- pr_atradi_01
PR_ATRADI_01 <- PR_ATRADI_01 %>% mutate(across(everything(), as.character))
PR_ATRADI_01 <- PR_ATRADI_01 %>% mutate_if(is.character, ~replace_na(.,""))

PR_ATRADI_02 <- pr_atradi_02
PR_ATRADI_02 <- PR_ATRADI_02 %>% mutate(across(everything(), as.character))
PR_ATRADI_02 <- PR_ATRADI_02 %>% mutate_if(is.character, ~replace_na(.,""))

# -----------  FINAL union query--
PRATRADI_UNION <-
    sqldf(
      " SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,PR_ATRADI_01.COUNTRY  'COUNTRY'
,PR_ATRADI_01.SITENUM  'SITENUM'
,PR_ATRADI_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PR_ATRADI_01.EGROUPDEF  'EGID'
,PR_ATRADI_01.ESEQ  'EGSEQ'
,CASE PR_ATRADI_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_ATRADI_01.EGROUP||' '||PR_ATRADI_01.EVENT
   ELSE PR_ATRADI_01.EVENT
   END AS 'VISIT'
 ,CASE 
WHEN PR_ATRADI_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_ATRADI_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_ATRADI_01.EVENTEID= 'ev_DAY1' THEN PR_ATRADI_01.ESEQ + 0.01
WHEN PR_ATRADI_01.EVENTEID= 'ev_DAY8' THEN PR_ATRADI_01.ESEQ + 0.08
WHEN PR_ATRADI_01.EVENTEID= 'ev_DAY15' THEN PR_ATRADI_01.ESEQ + 0.15
WHEN PR_ATRADI_01.EVENTEID= 'ev_TUPB' THEN 41 + PR_ATRADI_01.ESEQ * 0.01
WHEN PR_ATRADI_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_ATRADI_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_ATRADI_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_ATRADI_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_ATRADI_01.EVENTEID= 'ev_PTFU' THEN 75 + PR_ATRADI_01.ESEQ * 0.01
WHEN PR_ATRADI_01.EVENTEID= 'ev_LFU' THEN 80 + PR_ATRADI_01.ESEQ * 0.01
WHEN PR_ATRADI_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_ATRADI_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_ATRADI_01.EVENTEID= 'ev_UNS' THEN 99 + PR_ATRADI_01.ESEQ * 0.01
ELSE PR_ATRADI_01.EVENTEID
END as 'VISITNUM'
   
,PR_ATRADI_01.EVENTDT  'VISITDT'
,PR_ATRADI_01.FORM  'FORM'
,PR_ATRADI_01.FORMDEF  'FORMID'
,PR_ATRADI_01.FSEQ  'FORMSEQ'
,CASE PR_ATRADI_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_ATRADI_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_ATRADI_01.IGSEQ  'IGSEQ'
,PR_ATRADI_01.DLASTMOD  'DLASTMOD'
,PR_ATRADI_01.DV_PRCAT  'V_PRCAT'
,PR_ATRADI_01.V_QVAL_PRTYPE  'V_QVAL_PRTYPE'
,PR_ATRADI_01.V_QVAL_PRTYPEOT  'V_QVAL_PRTYPEOT'
,PR_ATRADI_01.V_PRLOC_ATRADI  'V_PRLOC_ATRADI'
,PR_ATRADI_01.V_QVAL_PRLOCSP  'V_QVAL_PRLOCSP'
,PR_ATRADI_01.V_PRDOSE_ATRADI  'V_PRDOSE_ATRADI'
,PR_ATRADI_01.V_PRDOSE_ATRADI_U   'V_PRDOSU_ATRADI'
,PR_ATRADI_01.V_PRSTDAT_ATRADI  'V_PRSTDAT_ATRADI'
,PR_ATRADI_01.V_PRSTDAT_ATRADI  'X_PRSTDAT_ATRADI'
,PR_ATRADI_01.V_PRENDAT_ATRADI  'V_PRENDAT_ATRADI'
,PR_ATRADI_01.V_PRENDAT_ATRADI  'X_PRENDAT_ATRADI'
,PR_ATRADI_01.V_QVAL_PRTRTSET  'V_QVAL_PRTRTSET'
,PR_ATRADI_01.V_QVAL_TRTSETOT  'V_QVAL_TRTSETOT'
,PR_ATRADI_01.V_RSORRES_BESTRESP_ATRADI_D   'V_RSORRES_BESTRESP_ATRADI'
,PR_ATRADI_01.V_QVAL_EOTREAS_ATRADI  'V_QVAL_EOTREAS_ATRADI'
,PR_ATRADI_01.V_QVAL_EOTREAOT  'V_QVAL_EOTREAOT'

FROM
              PR_ATRADI_01 PR_ATRADI_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PR_ATRADI_01.SUBJID
              AND S1.SITENUM=PR_ATRADI_01.SITENUM
              AND PR_ATRADI_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
           AND PR_ATRADI_01.FORMILB !='true'
   

union

SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,PR_ATRADI_02.COUNTRY  'COUNTRY'
,PR_ATRADI_02.SITENUM  'SITENUM'
,PR_ATRADI_02.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PR_ATRADI_02.EGROUPDEF  'EGID'
,PR_ATRADI_02.ESEQ  'EGSEQ'
,CASE PR_ATRADI_02.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_ATRADI_02.EGROUP||' '||PR_ATRADI_02.EVENT
   ELSE PR_ATRADI_02.EVENT
   END AS 'VISIT'
,CASE 
WHEN PR_ATRADI_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_ATRADI_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_ATRADI_02.EVENTEID= 'ev_DAY1' THEN PR_ATRADI_02.ESEQ + 0.01
WHEN PR_ATRADI_02.EVENTEID= 'ev_DAY8' THEN PR_ATRADI_02.ESEQ + 0.08
WHEN PR_ATRADI_02.EVENTEID= 'ev_DAY15' THEN PR_ATRADI_02.ESEQ + 0.15
WHEN PR_ATRADI_02.EVENTEID= 'ev_TUPB' THEN 41 + PR_ATRADI_02.ESEQ * 0.01
WHEN PR_ATRADI_02.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_ATRADI_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_ATRADI_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_ATRADI_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_ATRADI_02.EVENTEID= 'ev_PTFU' THEN 75 + PR_ATRADI_02.ESEQ * 0.01
WHEN PR_ATRADI_02.EVENTEID= 'ev_LFU' THEN 80 + PR_ATRADI_02.ESEQ * 0.01
WHEN PR_ATRADI_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_ATRADI_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_ATRADI_02.EVENTEID= 'ev_UNS' THEN 99 + PR_ATRADI_02.ESEQ * 0.01
ELSE PR_ATRADI_02.EVENTEID
END as 'VISITNUM'
,PR_ATRADI_02.EVENTDT  'VISITDT'
,PR_ATRADI_02.FORM  'FORM'
,PR_ATRADI_02.FORMDEF  'FORMEID'
,PR_ATRADI_02.FSEQ  'FORMSEQ'
,CASE PR_ATRADI_02.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_ATRADI_02.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_ATRADI_02.IGSEQ  'IGSEQ'
,PR_ATRADI_02.DLASTMOD  'DLASTMOD'
,PR_ATRADI_02.DV_PRCAT  'V_PRCAT'
,PR_ATRADI_02.V_QVAL_PRTYPE  'V_QVAL_PRTYPE'
,PR_ATRADI_02.V_QVAL_PRTYPEOT  'V_QVAL_PRTYPEOT'
,PR_ATRADI_02.V_PRLOC_ATRADI  'V_PRLOC_ATRADI'
,PR_ATRADI_02.V_QVAL_PRLOCSP  'V_QVAL_PRLOCSP'
,PR_ATRADI_02.V_PRDOSE_ATRADI  'V_PRDOSE_ATRADI'
,PR_ATRADI_02.V_PRDOSE_ATRADI_U   'V_PRDOSU_ATRADI'
,PR_ATRADI_02.V_PRSTDAT_ATRADI  'V_PRSTDAT_ATRADI'
,PR_ATRADI_02.V_PRSTDAT_ATRADI  'X_PRSTDAT_ATRADI'
,PR_ATRADI_02.V_PRENDAT_ATRADI  'V_PRENDAT_ATRADI'
,PR_ATRADI_02.V_PRENDAT_ATRADI  'X_PRENDAT_ATRADI'
,PR_ATRADI_02.V_QVAL_PRTRTSET  'V_QVAL_PRTRTSET'
,PR_ATRADI_02.V_QVAL_TRTSETOT  'V_QVAL_TRTSETOT'
,NULL   'V_RSORRES_BESTRESP_ATRADI'
,NULL  'V_QVAL_EOTREAS_ATRADI'
,NULL 'V_QVAL_EOTREAOT'

FROM
              PR_ATRADI_02 PR_ATRADI_02,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PR_ATRADI_02.SUBJID
              AND S1.SITENUM=PR_ATRADI_02.SITENUM
              AND PR_ATRADI_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
              AND PR_ATRADI_02.FORMILB !='true'
    


  "
  )

# AND PR_ATRADI_01.FORMILB !='true'
# AND PR_ATRADI_02.FORMILB !='true'

# Call the function -Convert_Date_Vals 
CharDate_Cols <-c("V_PRSTDAT_ATRADI", "V_PRENDAT_ATRADI")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("PRATRADI_UNION")
PRATRADI_EDC <- Convert_Date_Vals(PRATRADI_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
PRATRADI_EDC <- PRATRADI_EDC[names(PRATRADI_CDB)]

# Post processing for compare
PRATRADI_EDC$DLASTMOD <- substring(PRATRADI_EDC$DLASTMOD,1,16)
PRATRADI_EDC <- PRATRADI_EDC %>% mutate_if(is.character, ~replace_na(.,""))
PRATRADI_EDC <- PRATRADI_EDC[order(PRATRADI_EDC$STUDYID,PRATRADI_EDC$COUNTRY,PRATRADI_EDC$SITENUM,PRATRADI_EDC$SUBJID,PRATRADI_EDC$VISITDT,PRATRADI_EDC$FORMID,as.integer(PRATRADI_EDC$FORMSEQ),as.integer(PRATRADI_EDC$IGSEQ)), ]

#Generate Compare Summary Report
PRATRADI_EDC <- PRATRADI_EDC%>% mutate(across(everything(), as.character))
PRATRADI_CDB <- PRATRADI_CDB %>% mutate(across(everything(), as.character))
PRATRADI_SUMMARY <- capture.output(summary(comparedf(PRATRADI_EDC, PRATRADI_CDB)))
print(PRATRADI_SUMMARY)

#Export Summary Report
addWorksheet(wb, "PRATRADI_SUMMARY")
writeData(wb, sheet = "PRATRADI_SUMMARY", x = PRATRADI_SUMMARY)

#Export QC Datasets
write_xpt(PRATRADI_EDC,"QC Output/Datasets/EDC/PRATRADI_EDC.xpt")
write_xpt(PRATRADI_CDB,"QC Output/Datasets/CDB/PRATRADI_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)