rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
PRATSURG_CDB <- pratsurg
# Post processing for compare
PRATSURG_CDB <- PRATSURG_CDB %>% mutate(across(everything(), as.character))
PRATSURG_CDB$DLASTMOD <- substring(PRATSURG_CDB$DLASTMOD,1,16)
PRATSURG_CDB <- PRATSURG_CDB %>% mutate_if(is.character, ~replace_na(.,""))
PRATSURG_CDB <- PRATSURG_CDB[order(PRATSURG_CDB$STUDYID,PRATSURG_CDB$COUNTRY,PRATSURG_CDB$SITENUM,PRATSURG_CDB$SUBJID,PRATSURG_CDB$VISITDT,PRATSURG_CDB$FORMID,as.integer(PRATSURG_CDB$FORMSEQ),as.integer(PRATSURG_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub
PR_ATSURG_01 <- pr_atsurg_01
PR_ATSURG_01 <- PR_ATSURG_01 %>% mutate(across(everything(), as.character))
PR_ATSURG_01 <- PR_ATSURG_01 %>% mutate_if(is.character, ~replace_na(.,""))

PR_ATSURG_02 <- pr_atsurg_02
PR_ATSURG_02 <- PR_ATSURG_02 %>% mutate(across(everything(), as.character))
PR_ATSURG_02 <- PR_ATSURG_02 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
PRATSURG_UNION <-
  sqldf(
    "
 SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PR_ATSURG_01.COUNTRY  'COUNTRY'
,PR_ATSURG_01.SITENUM  'SITENUM'
,PR_ATSURG_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PR_ATSURG_01.EGROUPDEF  'EGID'
,PR_ATSURG_01.ESEQ  'EGSEQ'
,CASE PR_ATSURG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_ATSURG_01.EGROUP||' '||PR_ATSURG_01.EVENT
   ELSE PR_ATSURG_01.EVENT
   END AS 'VISIT'
   
,CASE 
WHEN PR_ATSURG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_ATSURG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_ATSURG_01.EVENTEID= 'ev_DAY1' THEN PR_ATSURG_01.ESEQ + 0.01
WHEN PR_ATSURG_01.EVENTEID= 'ev_DAY8' THEN PR_ATSURG_01.ESEQ + 0.08
WHEN PR_ATSURG_01.EVENTEID= 'ev_DAY15' THEN PR_ATSURG_01.ESEQ + 0.15
WHEN PR_ATSURG_01.EVENTEID= 'ev_TUPB' THEN 41 + PR_ATSURG_01.ESEQ * 0.01
WHEN PR_ATSURG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_ATSURG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_ATSURG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_ATSURG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_ATSURG_01.EVENTEID= 'ev_PTFU' THEN 75 + PR_ATSURG_01.ESEQ * 0.01
WHEN PR_ATSURG_01.EVENTEID= 'ev_LFU' THEN 80 + PR_ATSURG_01.ESEQ * 0.01
WHEN PR_ATSURG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_ATSURG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_ATSURG_01.EVENTEID= 'ev_UNS' THEN 99 + PR_ATSURG_01.ESEQ * 0.01
ELSE PR_ATSURG_01.EVENTEID
END as 'VISITNUM'

,PR_ATSURG_01.EVENTDT  'VISITDT'
,PR_ATSURG_01.FORM  'FORM'
,PR_ATSURG_01.FORMDEF  'FORMID'
,PR_ATSURG_01.FSEQ  'FORMSEQ'
,CASE PR_ATSURG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_ATSURG_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_ATSURG_01.IGSEQ  'IGSEQ'
,PR_ATSURG_01.DLASTMOD  'DLASTMOD'
,PR_ATSURG_01.DV_PRCAT  'V_PRCAT'
,PR_ATSURG_01.V_PRTRT_ATSURG_CL  'V_PRTRT_ATSURG_CL'
,PR_ATSURG_01.V_PRTRT_OTH_ATSURG  'V_PRTRT_OTH_ATSURG'
,PR_ATSURG_01.V_PRSTDAT_ATSURG  'V_PRSTDAT_ATSURG'
,PR_ATSURG_01.V_PRSTDAT_ATSURG  'X_PRSTDAT_ATSURG'


FROM
	PR_ATSURG_01 PR_ATSURG_01,
	SUBJECTS S1

              WHERE
              S1.SUBJID=PR_ATSURG_01.SUBJID
              AND S1.SITENUM=PR_ATSURG_01.SITENUM
              AND PR_ATSURG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                AND PR_ATSURG_01.FORMILB !='true'
  UNION
SELECT
'EIK1003-001_(IMP1734-101)_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,PR_ATSURG_02.COUNTRY  'COUNTRY'
,PR_ATSURG_02.SITENUM  'SITENUM'
,PR_ATSURG_02.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS' 
,PR_ATSURG_02.EGROUPDEF  'EGID'
,PR_ATSURG_02.ESEQ  'EGSEQ'
,CASE PR_ATSURG_02.EGROUPDEF
WHEN 'eg_TRTA1C' THEN PR_ATSURG_02.EGROUP||' '||PR_ATSURG_02.EVENT
ELSE PR_ATSURG_02.EVENT
END AS 'VISIT'  

,CASE 
WHEN PR_ATSURG_02.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_ATSURG_02.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_ATSURG_02.EVENTEID= 'ev_DAY1' THEN PR_ATSURG_02.ESEQ + 0.01
WHEN PR_ATSURG_02.EVENTEID= 'ev_DAY8' THEN PR_ATSURG_02.ESEQ + 0.08
WHEN PR_ATSURG_02.EVENTEID= 'ev_DAY15' THEN PR_ATSURG_02.ESEQ + 0.15
WHEN PR_ATSURG_02.EVENTEID= 'ev_TUPB' THEN 41 + PR_ATSURG_02.ESEQ * 0.01
WHEN PR_ATSURG_02.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_ATSURG_02.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_ATSURG_02.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_ATSURG_02.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_ATSURG_02.EVENTEID= 'ev_PTFU' THEN 75 + PR_ATSURG_02.ESEQ * 0.01
WHEN PR_ATSURG_02.EVENTEID= 'ev_LFU' THEN 80 + PR_ATSURG_02.ESEQ * 0.01
WHEN PR_ATSURG_02.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_ATSURG_02.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_ATSURG_02.EVENTEID= 'ev_UNS' THEN 99 + PR_ATSURG_02.ESEQ * 0.01
ELSE PR_ATSURG_02.EVENTEID
END as 'VISITNUM'

,PR_ATSURG_02.EVENTDT  'VISITDT'
,PR_ATSURG_02.FORM  'FORM'
,PR_ATSURG_02.FORMDEF  'FORMID'
,PR_ATSURG_02.FSEQ  'FORMSEQ'
,CASE PR_ATSURG_02.FORMSTATUS 
WHEN 'Submitted' THEN 'submitted__v'
WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
WHEN 'In Edit' THEN 'in_progress_post_submit__v'
ELSE  PR_ATSURG_02.FORMSTATUS  
END AS 'FORMSTATUS'
,PR_ATSURG_02.IGSEQ  'IGSEQ'
,PR_ATSURG_02.DLASTMOD  'DLASTMOD'	
,PR_ATSURG_02.DV_PRCAT  'V_PRCAT'
,PR_ATSURG_02.V_PRTRT_ATSURG_CL  'V_PRTRT_ATSURG_CL'
,PR_ATSURG_02.V_PRTRT_OTH_ATSURG  'V_PRTRT_OTH_ATSURG'
,PR_ATSURG_02.V_PRSTDAT_ATSURG  'V_PRSTDAT_ATSURG'
,PR_ATSURG_02.V_PRSTDAT_ATSURG  'X_PRSTDAT_ATSURG'


FROM
PR_ATSURG_02 PR_ATSURG_02,
SUBJECTS S1
WHERE
S1.SUBJID=PR_ATSURG_02.SUBJID
AND S1.SITENUM=PR_ATSURG_02.SITENUM
AND PR_ATSURG_02.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                AND PR_ATSURG_02.FORMILB !='true'

    
	")

# AND PR_ATSURG_01.FORMILB !='true'
# AND PR_ATSURG_02.FORMILB !='true'
# ,PR_ATSURG_01.V_PRSTDAT_ATSURG  'X_PRSTDAT_ATSURG'
# ,PR_ATSURG_02.V_PRSTDAT_ATSURG     'X_PRSTDAT_ATSURG'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_PRSTDAT_ATSURG")
datetime_columns <- NULL #c("V_TUDAT")
table_name <- c("PRATSURG_UNION")
PRATSURG_EDC <- Convert_Date_Vals(PRATSURG_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
PRATSURG_EDC <- PRATSURG_EDC[names(PRATSURG_EDC)]

# Post processing for compare
PRATSURG_EDC$DLASTMOD <- substring(PRATSURG_EDC$DLASTMOD,1,16)
PRATSURG_EDC <- PRATSURG_EDC %>% mutate_if(is.character, ~replace_na(.,""))
PRATSURG_EDC <- PRATSURG_EDC[order(PRATSURG_EDC$STUDYID,PRATSURG_EDC$COUNTRY,PRATSURG_EDC$SITENUM,PRATSURG_EDC$SUBJID,PRATSURG_EDC$VISITDT,PRATSURG_EDC$FORMID,as.integer(PRATSURG_EDC$FORMSEQ),as.integer(PRATSURG_EDC$IGSEQ)), ]

#Generate Compare Summary Report
PRATSURG_EDC <- PRATSURG_EDC%>% mutate(across(everything(), as.character))
PRATSURG_CDB <- PRATSURG_CDB %>% mutate(across(everything(), as.character))
PRATSURG_SUMMARY <- capture.output(summary(comparedf(PRATSURG_EDC, PRATSURG_CDB)))
print(PRATSURG_SUMMARY)

#Export Summary Report
addWorksheet(wb, "PRATSURG_SUMMARY")
writeData(wb, sheet = "PRATSURG_SUMMARY", x = PRATSURG_SUMMARY)

#Export QC Datasets
write_xpt(PRATSURG_EDC,"QC Output/Datasets/EDC/PRATSURG_EDC.xpt")
write_xpt(PRATSURG_CDB,"QC Output/Datasets/CDB/PRATSURG_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)