rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
PRGEN_CDB <- prgen
# Post processing for compare
PRGEN_CDB <- PRGEN_CDB %>% mutate(across(everything(), as.character))
PRGEN_CDB$DLASTMOD <- substring(PRGEN_CDB$DLASTMOD,1,16)
PRGEN_CDB$CX_LASTCODEDAT <- substring(PRGEN_CDB$CX_LASTCODEDAT,1,16)
PRGEN_CDB <- PRGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))
PRGEN_CDB <- PRGEN_CDB[order(PRGEN_CDB$STUDYID,PRGEN_CDB$COUNTRY,PRGEN_CDB$SITENUM,PRGEN_CDB$SUBJID,PRGEN_CDB$VISITDT,PRGEN_CDB$FORMID,as.integer(PRGEN_CDB$FORMSEQ),as.integer(PRGEN_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub
PR_GEN_01 <- pr_gen_01
PR_GEN_01 <- PR_GEN_01 %>% mutate(across(everything(), as.character))
PR_GEN_01 <- PR_GEN_01 %>% mutate_if(is.character, ~replace_na(.,""))

# -----------  FINAL union query--
PRGEN_UNION <-
  sqldf(
    " SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,PR_GEN_01.COUNTRY  'COUNTRY'
,PR_GEN_01.SITENUM  'SITENUM'
,PR_GEN_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,PR_GEN_01.EGROUPDEF  'EGID'
,PR_GEN_01.ESEQ  'EGSEQ'
,CASE PR_GEN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_GEN_01.EGROUP||' '||PR_GEN_01.EVENT
   ELSE PR_GEN_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PR_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_GEN_01.EVENTEID= 'ev_DAY1' THEN PR_GEN_01.ESEQ + 0.01
WHEN PR_GEN_01.EVENTEID= 'ev_DAY8' THEN PR_GEN_01.ESEQ + 0.08
WHEN PR_GEN_01.EVENTEID= 'ev_DAY15' THEN PR_GEN_01.ESEQ + 0.15
WHEN PR_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + PR_GEN_01.ESEQ * 0.01
WHEN PR_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + PR_GEN_01.ESEQ * 0.01
WHEN PR_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + PR_GEN_01.ESEQ * 0.01
WHEN PR_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + PR_GEN_01.ESEQ * 0.01
ELSE PR_GEN_01.EVENTEID
END as 'VISITNUM'
,PR_GEN_01.EVENTDT  'VISITDT'
,PR_GEN_01.FORM  'FORM'
,PR_GEN_01.FORMDEF  'FORMID'
,PR_GEN_01.FSEQ  'FORMSEQ'
,CASE PR_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_GEN_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_GEN_01.IGSEQ  'IGSEQ'
,PR_GEN_01.DLASTMOD  'DLASTMOD'
,PR_GEN_01.DV_PRCAT  'V_PRCAT'
,PR_GEN_01.V_PRTRT  'V_PRTRT'
,PR_GEN_01.V_PRSTDAT  'V_PRSTDAT'
,PR_GEN_01.V_PRSTDAT  'X_PRSTDAT'
,PR_GEN_01.V_PRONGO  'V_PRONGO'
,PR_GEN_01.V_PRENDAT  'V_PRENDAT'
,PR_GEN_01.V_PRENDAT  'X_PRENDAT'
,PR_GEN_01.V_PRINDC  'V_PRINDC'
,PR_GEN_01.V_QVAL_PRINDCSP  'V_QVAL_PRINDCSP'
,PR_GEN_01.FL_IDVARVAL_PRAE_DEF  'FL_IDVARVAL_PRAE'
,PR_GEN_01.FL_IDVARVAL_PRMH_DEF  'FL_IDVARVAL_PRMH'
,PR_GEN_01.CRSTATUS  'CX_CRSTATUS'
,PR_GEN_01.DICTVER  'CV_QVAL_DICTVER'
,PR_GEN_01.LLT  'CV_QVAL_PRLLT'
,PR_GEN_01.LLTID  'CV_QVAL_PRLLTCD'
,PR_GEN_01.PT  'CV_PRDECOD'
,PR_GEN_01.PTID  'CV_QVAL_PRPTCD'
,PR_GEN_01.HLT  'CV_QVAL_PRHLT'
,PR_GEN_01.HLTID  'CV_QVAL_PRHLTCD'
,PR_GEN_01.HLGT  'CV_QVAL_PRHLGT'
,PR_GEN_01.HLGTID  'CV_QVAL_PRHLGTCD'
,PR_GEN_01.SOC  'CV_QVAL_PRSOC'
,PR_GEN_01.SOCID  'CV_QVAL_PRSOCCD'
,PR_GEN_01.PRIMPATH  'CX_PRIMPATH'
,PR_GEN_01.LASTCODEDAT  'CX_LASTCODEDAT'
,PR_GEN_01.LASTCODEDBY  'CX_LASTCODEDBY'
FROM
              PR_GEN_01 PR_GEN_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=PR_GEN_01.SUBJID
              AND S1.SITENUM=PR_GEN_01.SITENUM
              AND PR_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
               AND PR_GEN_01.FORMILB !='true'
              
              AND PR_GEN_01.IGSEQ  = '1'
   "
  )

# AND PR_GEN_01.FORMILB !='true'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_PRSTDAT","V_PRENDAT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("PRGEN_UNION")
PRGEN_EDC <- Convert_Date_Vals(PRGEN_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
PRGEN_EDC <- PRGEN_EDC[names(PRGEN_CDB)]

# Post processing for compare
PRGEN_EDC$DLASTMOD <- substring(PRGEN_EDC$DLASTMOD,1,16)
PRGEN_EDC$CX_LASTCODEDAT <- substring(PRGEN_EDC$CX_LASTCODEDAT,1,16)
PRGEN_EDC <- PRGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
PRGEN_EDC <- PRGEN_EDC[order(PRGEN_EDC$STUDYID,PRGEN_EDC$COUNTRY,PRGEN_EDC$SITENUM,PRGEN_EDC$SUBJID,PRGEN_EDC$VISITDT,PRGEN_EDC$FORMID,as.integer(PRGEN_EDC$FORMSEQ),as.integer(PRGEN_EDC$IGSEQ)), ]

#Generate Compare Summary Report
PRGEN_EDC <- PRGEN_EDC %>% mutate(across(everything(), as.character))
PRGEN_CDB <- PRGEN_CDB %>% mutate(across(everything(), as.character))
PRGEN_SUMMARY <- capture.output(summary(comparedf(PRGEN_EDC, PRGEN_CDB)))
print(PRGEN_SUMMARY)

#Export Summary Report
addWorksheet(wb, "PRGEN_SUMMARY")
writeData(wb, sheet = "PRGEN_SUMMARY", x = PRGEN_SUMMARY)

#Export QC Datasets
write_xpt(PRGEN_EDC,"QC Output/Datasets/EDC/PRGEN_EDC.xpt")
write_xpt(PRGEN_CDB,"QC Output/Datasets/CDB/PRGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)