rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
PRPE_CDB <- prpe
# Post processing for compare
PRPE_CDB <- PRPE_CDB %>% mutate(across(everything(), as.character))
PRPE_CDB$DLASTMOD <- substring(PRPE_CDB$DLASTMOD,1,16)
PRPE_CDB <- PRPE_CDB %>% mutate_if(is.character, ~replace_na(.,""))
PRPE_CDB <- PRPE_CDB[order(PRPE_CDB$STUDYID,PRPE_CDB$COUNTRY,PRPE_CDB$SITENUM,PRPE_CDB$SUBJID,PRPE_CDB$VISITDT,PRPE_CDB$FORMID,as.integer(PRPE_CDB$FORMSEQ),as.integer(PRPE_CDB$IGSEQ),PRPE_CDB$EGID,PRPE_CDB$EGSEQ,PRPE_CDB$VISIT), ]

## Get EDC Data
SUBJECTS <- sys_sub

PR_PE_01 <- pr_pe_01
PR_PE_01 <- PR_PE_01 %>% mutate(across(everything(), as.character))
PR_PE_01 <- PR_PE_01 %>% mutate_if(is.character, ~replace_na(.,""))

PR_PEUNS_01 <- pr_peuns_01
PR_PEUNS_01 <- PR_PEUNS_01 %>% mutate(across(everything(), as.character))
PR_PEUNS_01 <- PR_PEUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))

# -----------  FINAL union query--
PRPE_UNION <-
    sqldf(
      " SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,PR_PE_01.COUNTRY  'COUNTRY'
,PR_PE_01.SITENUM  'SITENUM'
,PR_PE_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'

,PR_PE_01.EGROUPDEF  'EGID'
,PR_PE_01.ESEQ  'EGSEQ'
,CASE PR_PE_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_PE_01.EGROUP||' '||PR_PE_01.EVENT
   ELSE PR_PE_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PR_PE_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_PE_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_PE_01.EVENTEID= 'ev_DAY1' THEN PR_PE_01.ESEQ + 0.01
WHEN PR_PE_01.EVENTEID= 'ev_DAY8' THEN PR_PE_01.ESEQ + 0.08
WHEN PR_PE_01.EVENTEID= 'ev_DAY15' THEN PR_PE_01.ESEQ + 0.15
WHEN PR_PE_01.EVENTEID= 'ev_TUPB' THEN 41 + PR_PE_01.ESEQ * 0.01
WHEN PR_PE_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_PE_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_PE_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_PE_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_PE_01.EVENTEID= 'ev_PTFU' THEN 75 + PR_PE_01.ESEQ * 0.01
WHEN PR_PE_01.EVENTEID= 'ev_LFU' THEN 80 + PR_PE_01.ESEQ * 0.01
WHEN PR_PE_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_PE_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_PE_01.EVENTEID= 'ev_UNS' THEN 99 + PR_PE_01.ESEQ * 0.01
ELSE PR_PE_01.EVENTEID
END as 'VISITNUM'
,PR_PE_01.EVENTDT  'VISITDT'
,PR_PE_01.FORM  'FORM'
,PR_PE_01.FORMDEF  'FORMID'
,PR_PE_01.FSEQ  'FORMSEQ'
,CASE PR_PE_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_PE_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_PE_01.IGSEQ  'IGSEQ'
,PR_PE_01.DLASTMOD  'DLASTMOD'
,PR_PE_01.DV_PRCAT  'V_PRCAT'
,PR_PE_01.V_PROCCUR_PE  'V_PROCCUR_PE'
,PR_PE_01.V_QVAL_PRREASOC  'V_QVAL_PRREASOC'
,PR_PE_01.V_PRSTDAT_PE  'V_PRSTDAT_PE'
,PR_PE_01.V_PRSTDAT_PE  'X_PRSTDAT_PE'
FROM
              PR_PE_01 PR_PE_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=PR_PE_01.SUBJID
              AND S1.SITENUM=PR_PE_01.SITENUM
              AND PR_PE_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
             AND PR_PE_01.FORMILB !='true'


union
SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,PR_PEUNS_01.COUNTRY  'COUNTRY'
,PR_PEUNS_01.SITENUM  'SITENUM'
,PR_PEUNS_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'

,PR_PEUNS_01.EGROUPDEF  'EGID'
,PR_PEUNS_01.ESEQ  'EGSEQ'
,CASE PR_PEUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN PR_PEUNS_01.EGROUP||' '||PR_PEUNS_01.EVENT
   ELSE PR_PEUNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN PR_PEUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN PR_PEUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN PR_PEUNS_01.EVENTEID= 'ev_DAY1' THEN PR_PEUNS_01.ESEQ + 0.01
WHEN PR_PEUNS_01.EVENTEID= 'ev_DAY8' THEN PR_PEUNS_01.ESEQ + 0.08
WHEN PR_PEUNS_01.EVENTEID= 'ev_DAY15' THEN PR_PEUNS_01.ESEQ + 0.15
WHEN PR_PEUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + PR_PEUNS_01.ESEQ * 0.01
WHEN PR_PEUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN PR_PEUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN PR_PEUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN PR_PEUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN PR_PEUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + PR_PEUNS_01.ESEQ * 0.01
WHEN PR_PEUNS_01.EVENTEID= 'ev_LFU' THEN 80 + PR_PEUNS_01.ESEQ * 0.01
WHEN PR_PEUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN PR_PEUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN PR_PEUNS_01.EVENTEID= 'ev_UNS' THEN 99 + PR_PEUNS_01.ESEQ * 0.01
ELSE PR_PEUNS_01.EVENTEID
END as 'VISITNUM'
,PR_PEUNS_01.EVENTDT  'VISITDT'
,PR_PEUNS_01.FORM  'FORM'
,PR_PEUNS_01.FORMDEF  'FORMID'
,PR_PEUNS_01.FSEQ  'FORMSEQ'
,CASE PR_PEUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  PR_PEUNS_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,PR_PEUNS_01.IGSEQ  'IGSEQ'
,PR_PEUNS_01.DLASTMOD  'DLASTMOD'
,PR_PEUNS_01.DV_PRCAT  'V_PRCAT'
,NULL  'V_PROCCUR_PE'
,NULL  'V_QVAL_PRREASOC'
,PR_PEUNS_01.V_PRSTDAT_PE  'V_PRSTDAT_PE'
,PR_PEUNS_01.V_PRSTDAT_PE  'X_PRSTDAT_PE'
FROM
              PR_PEUNS_01 PR_PEUNS_01,
              SUBJECTS S1

              WHERE
              S1.SUBJID=PR_PEUNS_01.SUBJID
               AND S1.SITENUM=PR_PEUNS_01.SITENUM
              AND PR_PEUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND PR_PEUNS_01.FORMILB !='true'
    

   "
    )
# AND PR_PE_01.FORMILB !='true'
# AND PR_PEUNS_01.FORMILB !='true'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_PRSTDAT_PE")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("PRPE_UNION")
PRPE_EDC <- Convert_Date_Vals(PRPE_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
PRPE_EDC <- PRPE_EDC[names(PRPE_CDB)]

# Post processing for compare
PRPE_EDC$DLASTMOD <- substring(PRPE_EDC$DLASTMOD,1,16)
PRPE_EDC <- PRPE_EDC %>% mutate_if(is.character, ~replace_na(.,""))
PRPE_EDC <- PRPE_EDC[order(PRPE_EDC$STUDYID,PRPE_EDC$COUNTRY,PRPE_EDC$SITENUM,PRPE_EDC$SUBJID,PRPE_EDC$VISITDT,PRPE_EDC$FORMID,as.integer(PRPE_EDC$FORMSEQ),as.integer(PRPE_EDC$IGSEQ),PRPE_EDC$EGID,PRPE_EDC$EGSEQ,PRPE_EDC$VISIT), ]

#Generate Compare Summary Report
PRPE_EDC <- PRPE_EDC %>% mutate(across(everything(), as.character))
PRPE_CDB <- PRPE_CDB %>% mutate(across(everything(), as.character))
PRPE_SUMMARY <- capture.output(summary(comparedf(PRPE_EDC, PRPE_CDB)))
print(PRPE_SUMMARY)

#Export Summary Report
addWorksheet(wb, "PRPE_SUMMARY")
writeData(wb, sheet = "PRPE_SUMMARY", x = PRPE_SUMMARY)
 
#Export QC Datasets
write_xpt(PRPE_EDC,"QC Output/Datasets/EDC/PRPE_EDC.xpt")
write_xpt(PRPE_CDB,"QC Output/Datasets/CDB/PRPE_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)