rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
RSECOG_CDB <- rsecog
# Post processing for compare
RSECOG_CDB <- RSECOG_CDB %>% mutate(across(everything(), as.character))
RSECOG_CDB$DLASTMOD <- substring(RSECOG_CDB$DLASTMOD,1,16)
RSECOG_CDB <- RSECOG_CDB %>% mutate_if(is.character, ~replace_na(.,""))
RSECOG_CDB <- RSECOG_CDB[order(RSECOG_CDB$STUDYID,RSECOG_CDB$COUNTRY,RSECOG_CDB$SITENUM,RSECOG_CDB$SUBJID,RSECOG_CDB$VISITDT,RSECOG_CDB$FORMID,as.integer(RSECOG_CDB$FORMSEQ),as.integer(RSECOG_CDB$IGSEQ),RSECOG_CDB$EGID,RSECOG_CDB$EGSEQ,RSECOG_CDB$VISIT), ]

## Get EDC Data
SUBJECTS <- sys_sub

RS_ECOG_01 <- rs_ecog_01
RS_ECOG_01 <- RS_ECOG_01 %>% mutate(across(everything(), as.character))
RS_ECOG_01 <- RS_ECOG_01 %>% mutate_if(is.character, ~replace_na(.,""))

RS_ECOGUNS_01 <- rs_ecoguns_01
RS_ECOGUNS_01 <- RS_ECOGUNS_01 %>% mutate(across(everything(), as.character))
RS_ECOGUNS_01 <- RS_ECOGUNS_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
RSECOG_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,RS_ECOG_01.COUNTRY  'COUNTRY'
,RS_ECOG_01.SITENUM  'SITENUM'
,RS_ECOG_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,RS_ECOG_01.EGROUPDEF  'EGID'
,RS_ECOG_01.ESEQ  'EGSEQ'
,CASE RS_ECOG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN RS_ECOG_01.EGROUP||' '||RS_ECOG_01.EVENT
   ELSE RS_ECOG_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN RS_ECOG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN RS_ECOG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN RS_ECOG_01.EVENTEID= 'ev_DAY1' THEN RS_ECOG_01.ESEQ + 0.01
WHEN RS_ECOG_01.EVENTEID= 'ev_DAY8' THEN RS_ECOG_01.ESEQ + 0.08
WHEN RS_ECOG_01.EVENTEID= 'ev_DAY15' THEN RS_ECOG_01.ESEQ + 0.15
WHEN RS_ECOG_01.EVENTEID= 'ev_TUPB' THEN 41 + RS_ECOG_01.ESEQ * 0.01
WHEN RS_ECOG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN RS_ECOG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN RS_ECOG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN RS_ECOG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN RS_ECOG_01.EVENTEID= 'ev_PTFU' THEN 75 + RS_ECOG_01.ESEQ * 0.01
WHEN RS_ECOG_01.EVENTEID= 'ev_LFU' THEN 80 + RS_ECOG_01.ESEQ * 0.01
WHEN RS_ECOG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN RS_ECOG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN RS_ECOG_01.EVENTEID= 'ev_UNS' THEN 99 + RS_ECOG_01.ESEQ * 0.01
ELSE RS_ECOG_01.EVENTEID
END as 'VISITNUM'
,RS_ECOG_01.EVENTDT  'VISITDT'
,RS_ECOG_01.FORM  'FORM'
,RS_ECOG_01.FORMDEF  'FORMID'
,RS_ECOG_01.FSEQ  'FORMSEQ'
,CASE RS_ECOG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  RS_ECOG_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,RS_ECOG_01.IGSEQ  'IGSEQ'
,RS_ECOG_01.DLASTMOD  'DLASTMOD'
,RS_ECOG_01.DV_RSCAT_CCCAT  'V_RSCAT_CCCAT'
,RS_ECOG_01.V_RSPERF_RSALL  'V_RSPERF_RSALL'
,RS_ECOG_01.V_RSREASND_RSALL  'V_RSREASND_RSALL'
,RS_ECOG_01.V_RSDAT  'V_RSDAT'
,RS_ECOG_01.V_RSDAT  'X_RSDAT'
,RS_ECOG_01.V_RSORRES_ECOG101  'V_RSSTRESC_ECOG101'
,RS_ECOG_01.V_RSORRES_ECOG101_D  'V_RSORRES_ECOG101'

FROM
              RS_ECOG_01 RS_ECOG_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=RS_ECOG_01.SUBJID
              AND S1.SITENUM=RS_ECOG_01.SITENUM
              AND RS_ECOG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                     AND RS_ECOG_01.FORMILB !='true'

    


UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,RS_ECOGUNS_01.COUNTRY  'COUNTRY'
,RS_ECOGUNS_01.SITENUM  'SITENUM'
,RS_ECOGUNS_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,RS_ECOGUNS_01.EGROUPDEF  'EGID'
,RS_ECOGUNS_01.ESEQ  'EGSEQ'
,CASE RS_ECOGUNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN RS_ECOGUNS_01.EGROUP||' '||RS_ECOGUNS_01.EVENT
   ELSE RS_ECOGUNS_01.EVENT
   END AS 'VISIT'
   
,CASE 
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_DAY1' THEN RS_ECOGUNS_01.ESEQ + 0.01
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_DAY8' THEN RS_ECOGUNS_01.ESEQ + 0.08
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_DAY15' THEN RS_ECOGUNS_01.ESEQ + 0.15
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_TUPB' THEN 41 + RS_ECOGUNS_01.ESEQ * 0.01
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_PTFU' THEN 75 + RS_ECOGUNS_01.ESEQ * 0.01
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_LFU' THEN 80 + RS_ECOGUNS_01.ESEQ * 0.01
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN RS_ECOGUNS_01.EVENTEID= 'ev_UNS' THEN 99 + RS_ECOGUNS_01.ESEQ * 0.01
ELSE RS_ECOGUNS_01.EVENTEID
END as 'VISITNUM'

,RS_ECOGUNS_01.EVENTDT  'VISITDT'
,RS_ECOGUNS_01.FORM  'FORM'
,RS_ECOGUNS_01.FORMDEF  'FORMEID'
,RS_ECOGUNS_01.FSEQ  'FORMSEQ'
,CASE RS_ECOGUNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  RS_ECOGUNS_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,RS_ECOGUNS_01.IGSEQ  'IGSEQ'
,RS_ECOGUNS_01.DLASTMOD  'DLASTMOD'
,RS_ECOGUNS_01.DV_RSCAT_CCCAT  'V_RSCAT_CCCAT'
,NULL  'V_RSPERF_RSALL'
,NULL  'V_RSREASND_RSALL'
,RS_ECOGUNS_01.V_RSDAT  'V_RSDAT'
,RS_ECOGUNS_01.V_RSDAT  'X_RSDAT'
,RS_ECOGUNS_01.V_RSORRES_ECOG101  'V_RSSTRESC_ECOG101'
,RS_ECOGUNS_01.V_RSORRES_ECOG101_D  'V_RSORRES_ECOG101'
FROM
              RS_ECOGUNS_01 RS_ECOGUNS_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=RS_ECOGUNS_01.SUBJID
              AND S1.SITENUM=RS_ECOGUNS_01.SITENUM
              AND RS_ECOGUNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                     AND RS_ECOGUNS_01.FORMILB !='true'

  "
  )

# AND RS_ECOG_01.FORMILB !='true'
# AND RS_ECOGUNS_01.FORMILB !='true'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_RSDAT")
datetime_columns <- NULL
table_name <- c("RSECOG_UNION")
RSECOG_EDC <- Convert_Date_Vals(RSECOG_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
RSECOG_EDC <- RSECOG_EDC[names(RSECOG_CDB)]

# Post processing for compare
RSECOG_EDC$DLASTMOD <- substring(RSECOG_EDC$DLASTMOD,1,16)
#RSECOG_EDC$CX_LASTCODEDAT <- substring(RSECOG_EDC$CX_LASTCODEDAT,1,16)
RSECOG_EDC <- RSECOG_EDC %>% mutate_if(is.character, ~replace_na(.,""))
RSECOG_EDC <- RSECOG_EDC[order(RSECOG_EDC$STUDYID,RSECOG_EDC$COUNTRY,RSECOG_EDC$SITENUM,RSECOG_EDC$SUBJID,RSECOG_EDC$VISITDT,RSECOG_EDC$FORMID,as.integer(RSECOG_EDC$FORMSEQ),as.integer(RSECOG_EDC$IGSEQ),RSECOG_EDC$EGID,RSECOG_EDC$EGSEQ,RSECOG_EDC$VISIT), ]

#Generate Compare Summary Report
RSECOG_EDC <- RSECOG_EDC %>% mutate(across(everything(), as.character))
RSECOG_CDB <- RSECOG_CDB %>% mutate(across(everything(), as.character))
RSECOG_SUMMARY <- capture.output(summary(comparedf(RSECOG_EDC, RSECOG_CDB)))
print(RSECOG_SUMMARY)

#Export Summary Report
addWorksheet(wb, "RSECOG_SUMMARY")
writeData(wb, sheet = "RSECOG_SUMMARY", x = RSECOG_SUMMARY)

#Export QC Datasets
write_xpt(RSECOG_EDC,"QC Output/Datasets/EDC/RSECOG_EDC.xpt")
write_xpt(RSECOG_CDB,"QC Output/Datasets/CDB/RSECOG_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)