rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
RSEVAL_CDB <- rseval
# Post processing for compare
RSEVAL_CDB <- RSEVAL_CDB %>% mutate(across(everything(), as.character))
RSEVAL_CDB$DLASTMOD <- substring(RSEVAL_CDB$DLASTMOD,1,16)
RSEVAL_CDB <- RSEVAL_CDB %>% mutate_if(is.character, ~replace_na(.,""))
RSEVAL_CDB <- RSEVAL_CDB[order(RSEVAL_CDB$STUDYID,RSEVAL_CDB$COUNTRY,RSEVAL_CDB$SITENUM,RSEVAL_CDB$SUBJID,RSEVAL_CDB$VISITDT,RSEVAL_CDB$FORMID,as.integer(RSEVAL_CDB$FORMSEQ),as.integer(RSEVAL_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

RS_IREVAL_01 <- rs_ireval_01
RS_IREVAL_01 <- RS_IREVAL_01 %>% mutate(across(everything(), as.character))
RS_IREVAL_01 <- RS_IREVAL_01 %>% mutate_if(is.character, ~replace_na(.,""))


RS_R11EVAL_01 <- rs_r11eval_01
RS_R11EVAL_01 <- RS_R11EVAL_01 %>% mutate(across(everything(), as.character))
RS_R11EVAL_01 <- RS_R11EVAL_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
RSEVAL_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,RS_IREVAL_01.COUNTRY  'COUNTRY'
,RS_IREVAL_01.SITENUM  'SITENUM'
,RS_IREVAL_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,RS_IREVAL_01.EGROUPDEF  'EGID'
,RS_IREVAL_01.ESEQ  'EGSEQ'
,CASE RS_IREVAL_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN RS_IREVAL_01.EGROUP||' '||RS_IREVAL_01.EVENT
   ELSE RS_IREVAL_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN RS_IREVAL_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN RS_IREVAL_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN RS_IREVAL_01.EVENTEID= 'ev_DAY1' THEN RS_IREVAL_01.ESEQ + 0.01
WHEN RS_IREVAL_01.EVENTEID= 'ev_DAY8' THEN RS_IREVAL_01.ESEQ + 0.08
WHEN RS_IREVAL_01.EVENTEID= 'ev_DAY15' THEN RS_IREVAL_01.ESEQ + 0.15
WHEN RS_IREVAL_01.EVENTEID= 'ev_TUPB' THEN 41 + RS_IREVAL_01.ESEQ * 0.01
WHEN RS_IREVAL_01.EVENTEID= 'ev_EOT' THEN 60
WHEN RS_IREVAL_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN RS_IREVAL_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN RS_IREVAL_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN RS_IREVAL_01.EVENTEID= 'ev_PTFU' THEN 75 + RS_IREVAL_01.ESEQ * 0.01
WHEN RS_IREVAL_01.EVENTEID= 'ev_LFU' THEN 80 + RS_IREVAL_01.ESEQ * 0.01
WHEN RS_IREVAL_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN RS_IREVAL_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN RS_IREVAL_01.EVENTEID= 'ev_UNS' THEN 99 + RS_IREVAL_01.ESEQ * 0.01
ELSE RS_IREVAL_01.EVENTEID
END as 'VISITNUM'
,RS_IREVAL_01.EVENTDT  'VISITDT'
,RS_IREVAL_01.FORM  'FORM'
,RS_IREVAL_01.FORMDEF  'FORMID'
,RS_IREVAL_01.FSEQ  'FORMSEQ'
,CASE RS_IREVAL_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  RS_IREVAL_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,RS_IREVAL_01.IGSEQ  'IGSEQ'
,RS_IREVAL_01.DLASTMOD  'DLASTMOD'
,RS_IREVAL_01.DV_RSCAT_ONCRSCAT  'V_RSCAT_ONCRSCAT'
,RS_IREVAL_01.V_RSPERF   'V_RSPERF'
,NULL 'V_RSREASND'
,NULL 'V_RSDAT'
,NULL 'X_RSDAT'
,NULL 'V_RSORRES_TRGRESP'
,NULL 'V_RSORRES_NTRGRESP'
,RS_IREVAL_01.V_RSORRES_OVRLRESP_IR_D  'V_RSORRES_OVRLRESP'
,RS_IREVAL_01.V_QVAL_OVRLRSSP   'V_QVAL_OVRLRSSP'

  FROM

  RS_IREVAL_01 RS_IREVAL_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=RS_IREVAL_01.SUBJID
              AND S1.SITENUM=RS_IREVAL_01.SITENUM
              AND RS_IREVAL_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
              AND RS_IREVAL_01.FORMILB !='true'

    UNION

    SELECT
'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,RS_R11EVAL_01.COUNTRY  'COUNTRY'
,RS_R11EVAL_01.SITENUM  'SITENUM'
,RS_R11EVAL_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,RS_R11EVAL_01.EGROUPDEF  'EGID'
,RS_R11EVAL_01.ESEQ  'EGSEQ'
,CASE RS_R11EVAL_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN RS_R11EVAL_01.EGROUP||' '||RS_R11EVAL_01.EVENT
   ELSE RS_R11EVAL_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN RS_R11EVAL_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN RS_R11EVAL_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN RS_R11EVAL_01.EVENTEID= 'ev_DAY1' THEN RS_R11EVAL_01.ESEQ + 0.01
WHEN RS_R11EVAL_01.EVENTEID= 'ev_DAY8' THEN RS_R11EVAL_01.ESEQ + 0.08
WHEN RS_R11EVAL_01.EVENTEID= 'ev_DAY15' THEN RS_R11EVAL_01.ESEQ + 0.15
WHEN RS_R11EVAL_01.EVENTEID= 'ev_TUPB' THEN 41 + RS_R11EVAL_01.ESEQ * 0.01
WHEN RS_R11EVAL_01.EVENTEID= 'ev_EOT' THEN 60
WHEN RS_R11EVAL_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN RS_R11EVAL_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN RS_R11EVAL_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN RS_R11EVAL_01.EVENTEID= 'ev_PTFU' THEN 75 + RS_R11EVAL_01.ESEQ * 0.01
WHEN RS_R11EVAL_01.EVENTEID= 'ev_LFU' THEN 80 + RS_R11EVAL_01.ESEQ * 0.01
WHEN RS_R11EVAL_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN RS_R11EVAL_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN RS_R11EVAL_01.EVENTEID= 'ev_UNS' THEN 99 + RS_R11EVAL_01.ESEQ * 0.01
ELSE RS_R11EVAL_01.EVENTEID
END as 'VISITNUM'


,RS_R11EVAL_01.EVENTDT  'VISITDT'
,RS_R11EVAL_01.FORM  'FORM'
,RS_R11EVAL_01.FORMDEF  'FORMID'
,RS_R11EVAL_01.FSEQ  'FORMSEQ'
,CASE RS_R11EVAL_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  RS_R11EVAL_01.FORMSTATUS
	    END AS 'FORMSTATUS'
,RS_R11EVAL_01.IGSEQ  'IGSEQ'
,RS_R11EVAL_01.DLASTMOD  'DLASTMOD'
,RS_R11EVAL_01.DV_RSCAT_ONCRSCAT  'DV_RSCAT_ONCRSCAT'
,RS_R11EVAL_01.V_RSPERF  'V_RSPERF'
,RS_R11EVAL_01.V_RSREASND  'V_RSREASND'
,RS_R11EVAL_01.V_RSDAT  'V_RSDAT'
,RS_R11EVAL_01.V_RSDAT  'X_RSDAT'
,RS_R11EVAL_01.V_RSORRES_TRGRESP_R11_D  'V_RSORRES_TRGRESP'
,RS_R11EVAL_01.V_RSORRES_NTRGRESP_R11_D  'V_RSORRES_NTRGRESP'
,RS_R11EVAL_01.V_RSORRES_OVRLRESP_R11_D  'V_RSORRES_OVRLRESP'
,RS_R11EVAL_01.V_QVAL_OVRLRSSP  'V_QVAL_OVRLRSSP'

FROM
              RS_R11EVAL_01 RS_R11EVAL_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=RS_R11EVAL_01.SUBJID
              AND S1.SITENUM=RS_R11EVAL_01.SITENUM
              AND RS_R11EVAL_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
              AND RS_R11EVAL_01.FORMILB !='true'
 
  "
    )

# AND RS_IREVAL_01.FORMILB !='true'
# 
# AND RS_R11EVAL_01.FORMILB !='true'
# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_RSDAT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("RSEVAL_UNION")
RSEVAL_EDC <- Convert_Date_Vals(RSEVAL_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
RSEVAL_EDC <- RSEVAL_EDC[names(RSEVAL_CDB)]

# Post processing for compare
RSEVAL_EDC$DLASTMOD <- substring(RSEVAL_EDC$DLASTMOD,1,16)
RSEVAL_EDC <- RSEVAL_EDC %>% mutate_if(is.character, ~replace_na(.,""))
RSEVAL_EDC <- RSEVAL_EDC[order(RSEVAL_EDC$STUDYID,RSEVAL_EDC$COUNTRY,RSEVAL_EDC$SITENUM,RSEVAL_EDC$SUBJID,RSEVAL_EDC$VISITDT,RSEVAL_EDC$FORMID,as.integer(RSEVAL_EDC$FORMSEQ),as.integer(RSEVAL_EDC$IGSEQ)), ]

#Generate Compare Summary Report
RSEVAL_EDC <- RSEVAL_EDC %>% mutate(across(everything(), as.character))
RSEVAL_CDB <- RSEVAL_CDB %>% mutate(across(everything(), as.character))
RSEVAL_SUMMARY <- capture.output(summary(comparedf(RSEVAL_EDC, RSEVAL_CDB)))
print(RSEVAL_SUMMARY)

#Export Summary Report
addWorksheet(wb, "RSEVAL_SUMMARY")
writeData(wb, sheet = "RSEVAL_SUMMARY", x = RSEVAL_SUMMARY)

#Export QC Datasets
write_xpt(RSEVAL_EDC,"QC Output/Datasets/EDC/RSEVAL_EDC.xpt")
write_xpt(RSEVAL_CDB,"QC Output/Datasets/CDB/RSEVAL_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)