rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
SVUNSCH_CDB <- svunsch
# Post processing for compare
SVUNSCH_CDB <- SVUNSCH_CDB %>% mutate(across(everything(), as.character))
SVUNSCH_CDB$DLASTMOD <- substring(SVUNSCH_CDB$DLASTMOD,1,16)
SVUNSCH_CDB <- SVUNSCH_CDB %>% mutate_if(is.character, ~replace_na(.,""))
SVUNSCH_CDB <- SVUNSCH_CDB[order(SVUNSCH_CDB$STUDYID,SVUNSCH_CDB$COUNTRY,SVUNSCH_CDB$SITENUM,SVUNSCH_CDB$SUBJID,SVUNSCH_CDB$VISITDT,SVUNSCH_CDB$FORMID,as.integer(SVUNSCH_CDB$FORMSEQ),as.integer(SVUNSCH_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub
SV_UNSCH_01 <- sv_unsch_01
SV_UNSCH_01 <- SV_UNSCH_01 %>% mutate(across(everything(), as.character))
SV_UNSCH_01 <- SV_UNSCH_01 %>% mutate_if(is.character, ~replace_na(.,""))

#-----------  FINAL union query--
SVUNSCH_UNION <-
  sqldf(
    " SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,SV_UNSCH_01.COUNTRY  'COUNTRY'
,SV_UNSCH_01.SITENUM  'SITENUM'
,SV_UNSCH_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,SV_UNSCH_01.EGROUPDEF  'EGID'
,SV_UNSCH_01.ESEQ  'EGSEQ'
,CASE SV_UNSCH_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN SV_UNSCH_01.EGROUP||' '||SV_UNSCH_01.EVENT
   ELSE SV_UNSCH_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN SV_UNSCH_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN SV_UNSCH_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN SV_UNSCH_01.EVENTEID= 'ev_DAY1' THEN SV_UNSCH_01.ESEQ + 0.01
WHEN SV_UNSCH_01.EVENTEID= 'ev_DAY8' THEN SV_UNSCH_01.ESEQ + 0.08
WHEN SV_UNSCH_01.EVENTEID= 'ev_DAY15' THEN SV_UNSCH_01.ESEQ + 0.15
WHEN SV_UNSCH_01.EVENTEID= 'ev_TUPB' THEN 41 + SV_UNSCH_01.ESEQ * 0.01
WHEN SV_UNSCH_01.EVENTEID= 'ev_EOT' THEN 60
WHEN SV_UNSCH_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN SV_UNSCH_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN SV_UNSCH_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN SV_UNSCH_01.EVENTEID= 'ev_PTFU' THEN 75 + SV_UNSCH_01.ESEQ * 0.01
WHEN SV_UNSCH_01.EVENTEID= 'ev_LFU' THEN 80 + SV_UNSCH_01.ESEQ * 0.01
WHEN SV_UNSCH_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN SV_UNSCH_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN SV_UNSCH_01.EVENTEID= 'ev_UNS' THEN 99 + SV_UNSCH_01.ESEQ * 0.01
ELSE SV_UNSCH_01.EVENTEID
END as 'VISITNUM'
,SV_UNSCH_01.EVENTDT  'VISITDT'
,SV_UNSCH_01.FORM  'FORM'
,SV_UNSCH_01.FORMDEF  'FORMID'
,SV_UNSCH_01.FSEQ  'FORMSEQ'
,CASE SV_UNSCH_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  SV_UNSCH_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,SV_UNSCH_01.IGSEQ  'IGSEQ'
,SV_UNSCH_01.DLASTMOD  'DLASTMOD'
,SV_UNSCH_01.V_QVAL_SVREAUNS  'V_QVAL_SVREAUNS'
,SV_UNSCH_01.V_QVAL_REAUNSOT  'V_QVAL_REAUNSOT'
,SV_UNSCH_01.V_SVCNTMOD_SVUNSCH  'V_SVCNTMOD_SVUNSCH'
,SV_UNSCH_01.V_QVAL_CNTMODOT  'V_QVAL_CNTMODOT'
,SV_UNSCH_01.X_UNSCH_PRPE  'X_UNSCH_PRPE'
,SV_UNSCH_01.X_UNSCH_VS  'X_UNSCH_VS'
,SV_UNSCH_01.X_UNSCH_EG  'X_UNSCH_EG'
,SV_UNSCH_01.X_UNSCH_QSECOG  'X_UNSCH_QSECOG'
,SV_UNSCH_01.X_UNSCH_LBHEMA  'X_UNSCH_LBHEMA'
,SV_UNSCH_01.X_UNSCH_LBCHEM  'X_UNSCH_LBCHEM'
,SV_UNSCH_01.X_UNSCH_LBCOAG  'X_UNSCH_LBCOAG'
,SV_UNSCH_01.X_UNSCH_LBTHYR   'X_UNSCH_LBTHYR'
,SV_UNSCH_01.X_UNSCH_LBURIN  'X_UNSCH_LBURIN'
,SV_UNSCH_01.X_UNSCH_LBPREG  'X_UNSCH_LBPREG'
,SV_UNSCH_01.X_UNSCH_PC  'X_UNSCH_PC'
,SV_UNSCH_01.X_UNSCH_PCURIN  'X_UNSCH_PCURIN'
,SV_UNSCH_01.X_UNSCH_ISADA  'X_UNSCH_ISADA'
,SV_UNSCH_01.X_UNSCH_BEBIOMRKR  'X_UNSCH_BEBIOMRKR'
,SV_UNSCH_01.X_UNSCH_BECTDNA   'X_UNSCH_BECTDNA'
,SV_UNSCH_01.X_UNSCH_BERNA  'X_UNSCH_BERNA'
,SV_UNSCH_01.X_UNSCH_BEDNA  'X_UNSCH_BEDNA'
FROM
              SV_UNSCH_01 SV_UNSCH_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=SV_UNSCH_01.SUBJID
               AND S1.SITENUM=SV_UNSCH_01.SITENUM
              AND SV_UNSCH_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
                AND SV_UNSCH_01.FORMILB !='true'
            
"
)



# AND SV_UNSCH_01.FORMILB !='true'

# Call the function -Convert_Date_Vals
CharDate_Cols <-c()
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("SVUNSCH_UNION")
SVUNSCH_EDC <- Convert_Date_Vals(SVUNSCH_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
SVUNSCH_EDC <- SVUNSCH_EDC[names(SVUNSCH_CDB)]

# Post processing for compare
SVUNSCH_EDC$DLASTMOD <- substring(SVUNSCH_EDC$DLASTMOD,1,16)
SVUNSCH_EDC <- SVUNSCH_EDC %>% mutate_if(is.character, ~replace_na(.,""))
SVUNSCH_EDC <- SVUNSCH_EDC[order(SVUNSCH_EDC$STUDYID,SVUNSCH_EDC$COUNTRY,SVUNSCH_EDC$SITENUM,SVUNSCH_EDC$SUBJID,SVUNSCH_EDC$VISITDT,SVUNSCH_EDC$FORMID,as.integer(SVUNSCH_EDC$FORMSEQ),as.integer(SVUNSCH_EDC$IGSEQ)), ]

#Generate Compare Summary Report
SVUNSCH_EDC <- SVUNSCH_EDC %>% mutate(across(everything(), as.character))
SVUNSCH_CDB <- SVUNSCH_CDB %>% mutate(across(everything(), as.character))
SVUNSCH_SUMMARY <- capture.output(summary(comparedf(SVUNSCH_EDC, SVUNSCH_CDB)))
print(SVUNSCH_SUMMARY)

#Export Summary Report
addWorksheet(wb, "SVUNSCH_SUMMARY")
writeData(wb, sheet = "SVUNSCH_SUMMARY", x = SVUNSCH_SUMMARY)

#Export QC Datasets
write_xpt(SVUNSCH_EDC,"QC Output/Datasets/EDC/SVUNSCH_EDC.xpt")
write_xpt(SVUNSCH_CDB,"QC Output/Datasets/CDB/SVUNSCH_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)