rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)

## Get CDB Data
TUTR_CDB <- tutr
# Post processing for compare
TUTR_CDB <- TUTR_CDB %>% mutate(across(everything(), as.character))
TUTR_CDB$DLASTMOD <- substring(TUTR_CDB$DLASTMOD,1,16)
TUTR_CDB <- TUTR_CDB %>% mutate_if(is.character, ~replace_na(.,""))
TUTR_CDB <- TUTR_CDB[order(TUTR_CDB$STUDYID,TUTR_CDB$COUNTRY,TUTR_CDB$SITENUM,TUTR_CDB$SUBJID,TUTR_CDB$VISITDT,TUTR_CDB$FORMID,as.integer(TUTR_CDB$FORMSEQ),as.integer(TUTR_CDB$IGSEQ)), ]

## Get EDC Data
SUBJECTS <- sys_sub

TU_NEW_01 <- tu_new_01
TU_NEW_01 <- TU_NEW_01 %>% mutate(across(everything(), as.character))
TU_NEW_01 <- TU_NEW_01 %>% mutate_if(is.character, ~replace_na(.,""))


TU_NTRG_01 <- tu_ntrg_01
TU_NTRG_01 <- TU_NTRG_01 %>% mutate(across(everything(), as.character))
TU_NTRG_01<- TU_NTRG_01 %>% mutate_if(is.character, ~replace_na(.,""))


TU_SCR_01 <- tu_scr_01
TU_SCR_01 <- TU_SCR_01 %>% mutate(across(everything(), as.character))
TU_SCR_01<- TU_SCR_01 %>% mutate_if(is.character, ~replace_na(.,""))


TU_TRG_01 <- tu_trg_01
TU_TRG_01 <- TU_TRG_01 %>% mutate(across(everything(), as.character))
TU_TRG_01<- TU_TRG_01 %>% mutate_if(is.character, ~replace_na(.,""))



#-----------  FINAL union query--
TUTR_UNION <-
  sqldf(
    "     
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,TU_SCR_01.COUNTRY  'COUNTRY'
,TU_SCR_01.SITENUM  'SITENUM'
,TU_SCR_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,TU_SCR_01.EGROUPDEF  'EGID'
,TU_SCR_01.ESEQ  'EGSEQ'
,CASE TU_SCR_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN TU_SCR_01.EGROUP||' '||TU_SCR_01.EVENT
   ELSE TU_SCR_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN TU_SCR_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN TU_SCR_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN TU_SCR_01.EVENTEID= 'ev_DAY1' THEN TU_SCR_01.ESEQ + 0.01
WHEN TU_SCR_01.EVENTEID= 'ev_DAY8' THEN TU_SCR_01.ESEQ + 0.08
WHEN TU_SCR_01.EVENTEID= 'ev_DAY15' THEN TU_SCR_01.ESEQ + 0.15
WHEN TU_SCR_01.EVENTEID= 'ev_TUPB' THEN 41 + TU_SCR_01.ESEQ * 0.01
WHEN TU_SCR_01.EVENTEID= 'ev_EOT' THEN 60
WHEN TU_SCR_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN TU_SCR_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN TU_SCR_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN TU_SCR_01.EVENTEID= 'ev_PTFU' THEN 75 + TU_SCR_01.ESEQ * 0.01
WHEN TU_SCR_01.EVENTEID= 'ev_LFU' THEN 80 + TU_SCR_01.ESEQ * 0.01
WHEN TU_SCR_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN TU_SCR_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN TU_SCR_01.EVENTEID= 'ev_UNS' THEN 99 + TU_SCR_01.ESEQ * 0.01
ELSE TU_SCR_01.EVENTEID
END as 'VISITNUM'
,TU_SCR_01.EVENTDT  'VISITDT'
,TU_SCR_01.FORM  'FORM'
,TU_SCR_01.FORMDEF  'FORMID'
,TU_SCR_01.FSEQ  'FORMSEQ'
,CASE TU_SCR_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  TU_SCR_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,TU_SCR_01.IGSEQ  'IGSEQ'
,TU_SCR_01.DLASTMOD  'DLASTMOD'
,TU_SCR_01.V_QVAL_TUOCCUR_SCR  'V_QVAL_TUOCCUR'
,TU_SCR_01.V_QVAL_PRLOCUET  'V_QVAL_PRLOCUET'
,TU_SCR_01.V_QVAL_PRLOCLET 'V_QVAL_PRLOCLET'
,TU_SCR_01.V_QVAL_PRLOCHED 'V_QVAL_PRLOCHED'
,TU_SCR_01.V_QVAL_PRLOCNEK 'V_QVAL_PRLOCNEK'
,TU_SCR_01.V_QVAL_PRLOCCST 'V_QVAL_PRLOCCST'
,TU_SCR_01.V_QVAL_PRLOCABD 'V_QVAL_PRLOCABD'
,TU_SCR_01.V_QVAL_PRLOCPLC 'V_QVAL_PRLOCPLC'
,TU_SCR_01.V_QVAL_PRLOCBON 'V_QVAL_PRLOCBON'
,TU_SCR_01.V_QVAL_TUTRGYN 'V_QVAL_TUTRGYN'
,TU_SCR_01.V_QVAL_NTUTRGYN 'V_QVAL_NTUTRGYN'

,TU_SCR_01.DV_TRORRES_STLDIAM  'DV_TRORRES_STLDIAM'
,TU_SCR_01.DV_TRORRES_STLDIAM_U 'DV_TRORRESU_STLDIAM'

,TU_SCR_01.DV_TRORRES_STLDIAM_TRANS 'DV_TRSTRESC_STLDIAM'
,TU_SCR_01.DV_TRORRES_STLDIAM_TRANS 'DV_TRSTRESN_STLDIAM'
,TU_SCR_01.DV_TRORRES_STLDIAM_TRANSU 'DV_TRSTRESU_STLDIAM'
,NULL  'V_RSORRES_NEWLIND'
,TU_SCR_01.V_TUORRES_TUMIDENT_SCR 'V_TUORRES_TUMIDENT'

	, CASE 
  when TU_SCR_01.V_TULNKID_TRG !=  '' then TU_SCR_01.V_TULNKID_TRG
  	else TU_SCR_01.V_TULNKID_NTRG end
	 AS V_TULNKID

,TU_SCR_01.V_TULOC  'V_TULOC'
,TU_SCR_01.V_QVAL_TULOCOT  'V_QVAL_TULOCOT'
,TU_SCR_01.V_QVAL_TULOCDTL  'V_QVAL_TULOCDTL'

,TU_SCR_01.V_TUDAT  'V_TUDAT'
,TU_SCR_01.V_TUDAT  'X_TUDAT'
,TU_SCR_01.V_TUMETHOD  'V_TUMETHOD'
,TU_SCR_01.V_QVAL_TUMETHOT  'V_QVAL_TUMETHOT'
,TU_SCR_01.V_TRORRES_TLDIAMMI 'V_TRORRES_TLDIAMMI'
,TU_SCR_01.V_TRORRES_TLDIAM_S01 'V_TRORRES_TLDIAM'
,TU_SCR_01.V_TRORRES_TLDIAM_S01_U 'V_TRORRESU_TLDIAM'

,TU_SCR_01.V_TRORRES_TLDIAM_S01 'V_TRSTRESC_TLDIAM'
,TU_SCR_01.V_TRORRES_TLDIAM_S01_TRANS  'V_TRSTRESN_TLDIAM'
,TU_SCR_01.V_TRORRES_TLDIAM_S01_TRANSU  'V_TRSTRESU_TLDIAM'
,NULL  'V_TRSTAT'
,NULL 'V_TUORRES_TUCHANGE'
,NULL  'V_TRORRES_TUMSTATE'
FROM
              TU_SCR_01 TU_SCR_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=TU_SCR_01.SUBJID
               AND S1.SITENUM=TU_SCR_01.SITENUM
              AND TU_SCR_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND TU_SCR_01.FORMILB !='true'
UNION
 SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,TU_TRG_01.COUNTRY  'COUNTRY'
,TU_TRG_01.SITENUM  'SITENUM'
,TU_TRG_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,TU_TRG_01.EGROUPDEF  'EGID'
,TU_TRG_01.ESEQ  'EGSEQ'
,CASE TU_TRG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN TU_TRG_01.EGROUP||' '||TU_TRG_01.EVENT
   ELSE TU_TRG_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN TU_TRG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN TU_TRG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN TU_TRG_01.EVENTEID= 'ev_DAY1' THEN TU_TRG_01.ESEQ + 0.01
WHEN TU_TRG_01.EVENTEID= 'ev_DAY8' THEN TU_TRG_01.ESEQ + 0.08
WHEN TU_TRG_01.EVENTEID= 'ev_DAY15' THEN TU_TRG_01.ESEQ + 0.15
WHEN TU_TRG_01.EVENTEID= 'ev_TUPB' THEN 41 + TU_TRG_01.ESEQ * 0.01
WHEN TU_TRG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN TU_TRG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN TU_TRG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN TU_TRG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN TU_TRG_01.EVENTEID= 'ev_PTFU' THEN 75 + TU_TRG_01.ESEQ * 0.01
WHEN TU_TRG_01.EVENTEID= 'ev_LFU' THEN 80 + TU_TRG_01.ESEQ * 0.01
WHEN TU_TRG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN TU_TRG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN TU_TRG_01.EVENTEID= 'ev_UNS' THEN 99 + TU_TRG_01.ESEQ * 0.01
ELSE TU_TRG_01.EVENTEID
END as 'VISITNUM'
,TU_TRG_01.EVENTDT  'VISITDT'
,TU_TRG_01.FORM  'FORM'
,TU_TRG_01.FORMDEF  'FORMID'
,TU_TRG_01.FSEQ  'FORMSEQ'
,CASE TU_TRG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  TU_TRG_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,TU_TRG_01.IGSEQ  'IGSEQ'
,TU_TRG_01.DLASTMOD  'DLASTMOD'
,TU_TRG_01.V_QVAL_TUOCCUR_TRG  'V_QVAL_TUOCCUR'
,NULL  'V_QVAL_PRLOCUET'
,NULL 'V_QVAL_PRLOCLET'
,NULL 'V_QVAL_PRLOCHED'
,NULL 'V_QVAL_PRLOCNEK'
,NULL'V_QVAL_PRLOCCST'
,NULL 'V_QVAL_PRLOCABD'
,NULL 'V_QVAL_PRLOCPLC'
,NULL 'V_QVAL_PRLOCBON'
,NULL 'V_QVAL_TUTRGYN'
,NULL'V_QVAL_NTUTRGYN'
,TU_TRG_01.DV_TRORRES_STLDIAM 'DV_TRORRES_STLDIAM'
,TU_TRG_01.DV_TRORRES_STLDIAM_U 'DV_TRORRESU_STLDIAM'
,TU_TRG_01.DV_TRORRES_STLDIAM_TRANS 'DV_TRSTRESC_STLDIAM'
,TU_TRG_01.DV_TRORRES_STLDIAM_TRANS 'DV_TRSTRESN_STLDIAM'
,TU_TRG_01.DV_TRORRES_STLDIAM_TRANSU 'DV_TRSTRESU_STLDIAM'
,NULL  'V_RSORRES_NEWLIND'
,TU_TRG_01.DV_TUORRES_TUMIDENT 'V_TUORRES_TUMIDENT'
,TU_TRG_01.V_TULNKID_TRG  'V_TULNKID'
,TU_TRG_01.V_TULOC  'V_TULOC'
,TU_TRG_01.V_QVAL_TULOCOT  'V_QVAL_TULOCOT'
,TU_TRG_01.V_QVAL_TULOCDTL  'V_QVAL_TULOCDTL'

,TU_TRG_01.V_TUDAT  'V_TUDAT'
,TU_TRG_01.V_TUDAT  'X_TUDAT'
,TU_TRG_01.V_TUMETHOD  'V_TUMETHOD'
,TU_TRG_01.V_QVAL_TUMETHOT  'V_QVAL_TUMETHOT'
,TU_TRG_01.V_TRORRES_TLDIAMMI 'V_TRORRES_TLDIAMMI'
,TU_TRG_01.V_TRORRES_TLDIAM_S02 'V_TRORRES_TLDIAM'
,TU_TRG_01.V_TRORRES_TLDIAM_S02_U 'V_TRORRESU_TLDIAM'
,TU_TRG_01.V_TRORRES_TLDIAM_S02  'V_TRSTRESC_TLDIAM'
,TU_TRG_01.V_TRORRES_TLDIAM_S02_TRANS 'V_TRSTRESN_TLDIAM'
,TU_TRG_01.V_TRORRES_TLDIAM_S02_TRANSU 'V_TRSTRESU_TLDIAM'
--,TU_TRG_01.V_TRSTAT  'V_TRSTAT'--

, case when TU_TRG_01.V_TRSTAT = '0' then 'false'
	   when TU_TRG_01.V_TRSTAT = '1'     then 'true'
	   else  TU_TRG_01.V_TRSTAT  end 
	   'V_TRSTAT'
,TU_TRG_01.V_TUORRES_TUCHANGE 'V_TUORRES_TUCHANGE'
,TU_TRG_01.V_TRORRES_TUMSTATE_TRG  'V_TRORRES_TUMSTATE'


FROM
              TU_TRG_01 TU_TRG_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=TU_TRG_01.SUBJID
               AND S1.SITENUM=TU_TRG_01.SITENUM
              AND TU_TRG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND TU_TRG_01.FORMILB !='true'
    
    
UNION

SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,TU_NTRG_01.COUNTRY  'COUNTRY'
,TU_NTRG_01.SITENUM  'SITENUM'
,TU_NTRG_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,TU_NTRG_01.EGROUPDEF  'EGID'
,TU_NTRG_01.ESEQ  'EGSEQ'
,CASE TU_NTRG_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN TU_NTRG_01.EGROUP||' '||TU_NTRG_01.EVENT
   ELSE TU_NTRG_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN TU_NTRG_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN TU_NTRG_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN TU_NTRG_01.EVENTEID= 'ev_DAY1' THEN TU_NTRG_01.ESEQ + 0.01
WHEN TU_NTRG_01.EVENTEID= 'ev_DAY8' THEN TU_NTRG_01.ESEQ + 0.08
WHEN TU_NTRG_01.EVENTEID= 'ev_DAY15' THEN TU_NTRG_01.ESEQ + 0.15
WHEN TU_NTRG_01.EVENTEID= 'ev_TUPB' THEN 41 + TU_NTRG_01.ESEQ * 0.01
WHEN TU_NTRG_01.EVENTEID= 'ev_EOT' THEN 60
WHEN TU_NTRG_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN TU_NTRG_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN TU_NTRG_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN TU_NTRG_01.EVENTEID= 'ev_PTFU' THEN 75 + TU_NTRG_01.ESEQ * 0.01
WHEN TU_NTRG_01.EVENTEID= 'ev_LFU' THEN 80 + TU_NTRG_01.ESEQ * 0.01
WHEN TU_NTRG_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN TU_NTRG_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN TU_NTRG_01.EVENTEID= 'ev_UNS' THEN 99 + TU_NTRG_01.ESEQ * 0.01
ELSE TU_NTRG_01.EVENTEID
END as 'VISITNUM'
,TU_NTRG_01.EVENTDT  'VISITDT'
,TU_NTRG_01.FORM  'FORM'
,TU_NTRG_01.FORMDEF  'FORMID'
,TU_NTRG_01.FSEQ  'FORMSEQ'
,CASE TU_NTRG_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  TU_NTRG_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,TU_NTRG_01.IGSEQ  'IGSEQ'
,TU_NTRG_01.DLASTMOD  'DLASTMOD'
,TU_NTRG_01.V_QVAL_TUOCCUR_NTRG  'V_QVAL_TUOCCUR'
,NULL 'V_QVAL_PRLOCUET'
,NULL 'V_QVAL_PRLOCLET'
,NULL 'V_QVAL_PRLOCHED'
,NULL 'V_QVAL_PRLOCNEK'
,NULL 'V_QVAL_PRLOCCST'
,NULL 'V_QVAL_PRLOCABD'
,NULL 'V_QVAL_PRLOCPLC'
,NULL 'V_QVAL_PRLOCBON'
,NULL 'V_QVAL_TUTRGYN'
,NULL 'V_QVAL_NTUTRGYN'
,NULL 'DV_TRORRES_STLDIAM'
,NULL 'DV_TRORRESU_STLDIAM'
,NULL 'DV_TRSTRESC_STLDIAM'
,NULL 'DV_TRSTRESN_STLDIAM'
,NULL 'DV_TRSTRESU_STLDIAM'
,NULL  'V_RSORRES_NEWLIND'
,TU_NTRG_01.DV_TUORRES_TUMIDENT  'V_TUORRES_TUMIDENT'
,TU_NTRG_01.V_TULNKID_NTRG  'V_TULNKID'
	
,TU_NTRG_01.V_TULOC  'V_TULOC'
,TU_NTRG_01.V_QVAL_TULOCOT  'V_QVAL_TULOCOT'
,TU_NTRG_01.V_QVAL_TULOCDTL  'V_QVAL_TULOCDTL'

,TU_NTRG_01.V_TUDAT  'V_TUDAT'
,TU_NTRG_01.V_TUDAT  'X_TUDAT'
,TU_NTRG_01.V_TUMETHOD  'V_TUMETHOD'
,TU_NTRG_01.V_QVAL_TUMETHOT  'V_QVAL_TUMETHOT'
,NULL 'V_TRORRES_TLDIAMMI'
,NULL 'V_TRORRES_TLDIAM'
,NULL 'V_TRORRESU_TLDIAM'
,NULL 'V_TRSTRESC_TLDIAM'
,NULL 'V_TRSTRESN_TLDIAM'
,NULL  'V_TRSTRESU_TLDIAM'
--,TU_NTRG_01.V_TRSTAT  'V_TRSTAT'--
, case when TU_NTRG_01.V_TRSTAT = '0' then 'false'
	   when TU_NTRG_01.V_TRSTAT = '1'     then 'true'
	   else  TU_NTRG_01.V_TRSTAT  end 
	   'V_TRSTAT'
,NULL 'V_TUORRES_TUCHANGE'
,TU_NTRG_01.V_TRORRES_TUMSTATE_NTRG   'V_TRORRES_TUMSTATE'
FROM
              TU_NTRG_01 TU_NTRG_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=TU_NTRG_01.SUBJID
               AND S1.SITENUM=TU_NTRG_01.SITENUM
              AND TU_NTRG_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND TU_NTRG_01.FORMILB !='true'
    

    
    


UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,TU_NEW_01.COUNTRY  'COUNTRY'
,TU_NEW_01.SITENUM  'SITENUM'
,TU_NEW_01.SUBJID  'SUBJID'
,	S1.STATUS 'SUBJSTATUS'
,TU_NEW_01.EGROUPDEF  'EGID'
,TU_NEW_01.ESEQ  'EGSEQ'
,CASE TU_NEW_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN TU_NEW_01.EGROUP||' '||TU_NEW_01.EVENT
   ELSE TU_NEW_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN TU_NEW_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN TU_NEW_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN TU_NEW_01.EVENTEID= 'ev_DAY1' THEN TU_NEW_01.ESEQ + 0.01
WHEN TU_NEW_01.EVENTEID= 'ev_DAY8' THEN TU_NEW_01.ESEQ + 0.08
WHEN TU_NEW_01.EVENTEID= 'ev_DAY15' THEN TU_NEW_01.ESEQ + 0.15
WHEN TU_NEW_01.EVENTEID= 'ev_TUPB' THEN 41 + TU_NEW_01.ESEQ * 0.01
WHEN TU_NEW_01.EVENTEID= 'ev_EOT' THEN 60
WHEN TU_NEW_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN TU_NEW_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN TU_NEW_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN TU_NEW_01.EVENTEID= 'ev_PTFU' THEN 75 + TU_NEW_01.ESEQ * 0.01
WHEN TU_NEW_01.EVENTEID= 'ev_LFU' THEN 80 + TU_NEW_01.ESEQ * 0.01
WHEN TU_NEW_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN TU_NEW_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN TU_NEW_01.EVENTEID= 'ev_UNS' THEN 99 + TU_NEW_01.ESEQ * 0.01
ELSE TU_NEW_01.EVENTEID
END as 'VISITNUM'
,TU_NEW_01.EVENTDT  'VISITDT'
,TU_NEW_01.FORM  'FORM'
,TU_NEW_01.FORMDEF  'FORMID'
,TU_NEW_01.FSEQ  'FORMSEQ'
,CASE TU_NEW_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE  TU_NEW_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,TU_NEW_01.IGSEQ  'IGSEQ'
,TU_NEW_01.DLASTMOD  'DLASTMOD'
,NULL 'V_QVAL_TUOCCUR'
,NULL 'V_QVAL_PRLOCUET'
,NULL 'V_QVAL_PRLOCLET'
,NULL 'V_QVAL_PRLOCHED'
,NULL 'V_QVAL_PRLOCNEK'
,NULL 'V_QVAL_PRLOCCST'
,NULL 'V_QVAL_PRLOCABD'
,NULL 'V_QVAL_PRLOCPLC'
,NULL 'V_QVAL_PRLOCBON'
,NULL 'V_QVAL_TUTRGYN'
,NULL 'V_QVAL_NTUTRGYN'
,NULL 'DV_TRORRES_STLDIAM'
,NULL 'DV_TRORRESU_STLDIAM'
,NULL 'DV_TRSTRESC_STLDIAM'
,NULL 'DV_TRSTRESN_STLDIAM'
,NULL 'DV_TRSTRESU_STLDIAM'
,TU_NEW_01.V_RSORRES_NEWLIND  'V_RSORRES_NEWLIND'
,TU_NEW_01.V_TUORRES_TUMIDENT_NEWLIN 'V_TUORRES_TUMIDENT'
,TU_NEW_01.V_TULNKID_NEWLIN  'V_TULNKID'

,TU_NEW_01.V_TULOC  'V_TULOC'
,TU_NEW_01.V_QVAL_TULOCOT  'V_QVAL_TULOCOT'
,TU_NEW_01.V_QVAL_TULOCDTL  'V_QVAL_TULOCDTL'
,TU_NEW_01.V_TUDAT  'V_TUDAT'
,TU_NEW_01.V_TUDAT  'X_TUDAT'
,TU_NEW_01.V_TUMETHOD  'V_TUMETHOD'

,TU_NEW_01.V_QVAL_TUMETHOT  'V_QVAL_TUMETHOT'

,TU_NEW_01.V_TRORRES_TLDIAMMI 'V_TRORRES_TLDIAMMI'
,TU_NEW_01.V_TRORRES_TLDIAM_S03 'V_TRORRES_TLDIAM'
,TU_NEW_01.V_TRORRES_TLDIAM_S03_U  'V_TRORRESU_TLDIAM'

,TU_NEW_01.V_TRORRES_TLDIAM_S03  'V_TRSTRESC_TLDIAM'
,TU_NEW_01.V_TRORRES_TLDIAM_S03_TRANS  'V_TRSTRESN_TLDIAM'
,TU_NEW_01.V_TRORRES_TLDIAM_S03_TRANSU  'V_TRSTRESU_TLDIAM'
,NULL 'V_TRSTAT'
,NULL 'V_TUORRES_TUCHANGE'
,TU_NEW_01.V_TRORRES_TUMSTATE_NLRESP  'V_TRORRES_TUMSTATE'
FROM
              TU_NEW_01 TU_NEW_01,
              SUBJECTS S1
              WHERE
              S1.SUBJID=TU_NEW_01.SUBJID
               AND S1.SITENUM=TU_NEW_01.SITENUM
              AND TU_NEW_01.FORMSTATUS  IN ('Submitted','In Progress Post Submit','In Edit') 
AND TU_NEW_01.FORMILB !='true'



"
)


# AND TU_NEW_01.FORMILB !='true'

# Call the function -Convert_Date_Vals
CharDate_Cols <-c("V_TUDAT")
datetime_columns <- NULL #c("DLASTMOD")
table_name <- c("TUTR_UNION")
TUTR_EDC <- Convert_Date_Vals(TUTR_UNION, CharDate_Cols,datetime_columns,table_name)
TUTR_EDC <- TUTR_EDC %>% mutate(across(everything(), as.character))
# Arrange columns same as CDB
TUTR_EDC <- TUTR_EDC[names(TUTR_CDB)]

# Post processing for compare
TUTR_EDC$DLASTMOD <- substring(TUTR_EDC$DLASTMOD,1,16)
TUTR_EDC <- TUTR_EDC %>% mutate_if(is.character, ~replace_na(.,""))
TUTR_EDC <- TUTR_EDC[order(TUTR_EDC$STUDYID,TUTR_EDC$COUNTRY,TUTR_EDC$SITENUM,TUTR_EDC$SUBJID,TUTR_EDC$VISITDT,TUTR_EDC$FORMID,as.integer(TUTR_EDC$FORMSEQ),as.integer(TUTR_EDC$IGSEQ)), ]

#Generate Compare Summary Report
TUTR_SUMMARY <- capture.output(summary(comparedf(TUTR_EDC, TUTR_CDB)))
print(TUTR_SUMMARY)

#Export Summary Report
addWorksheet(wb, "TUTR_SUMMARY")
writeData(wb, sheet = "TUTR_SUMMARY", x = TUTR_SUMMARY)

#Export QC Datasets
write_xpt(TUTR_EDC,"QC Output/Datasets/EDC/TUTR_EDC.xpt")
write_xpt(TUTR_CDB,"QC Output/Datasets/CDB/TUTR_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)