rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)
options(digits = 5)

## Get CDB Data
VSGEN_CDB <- vsgen
# Post processing for compare
VSGEN_CDB <- VSGEN_CDB %>% mutate(across(everything(), as.character))
VSGEN_CDB$V_VSORRES_HEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSORRES_HEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSORRES_HEIGHT), digits=1, format="f"), TRUE ~ VSGEN_CDB$V_VSORRES_HEIGHT))
VSGEN_CDB$V_VSSTRESC_HEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSSTRESC_HEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSSTRESC_HEIGHT), digits=1, format="f"), TRUE ~ VSGEN_CDB$V_VSSTRESC_HEIGHT))
VSGEN_CDB$V_VSORRES_WEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSORRES_WEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSORRES_WEIGHT), digits=2, format="f"), TRUE ~ VSGEN_CDB$V_VSORRES_WEIGHT))
VSGEN_CDB$V_VSSTRESC_WEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSSTRESC_WEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSSTRESC_WEIGHT), digits=2, format="f"), TRUE ~ VSGEN_CDB$V_VSSTRESC_WEIGHT))
VSGEN_CDB$V_VSORRES_TEMP <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSORRES_TEMP) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSORRES_TEMP), digits=1, format="f"), TRUE ~ VSGEN_CDB$V_VSORRES_TEMP))
VSGEN_CDB$V_VSSTRESC_TEMP <- suppressWarnings(case_when(as.numeric(VSGEN_CDB$V_VSSTRESC_TEMP) != "NA" ~ formatC(as.numeric(VSGEN_CDB$V_VSSTRESC_TEMP), digits=1, format="f"), TRUE ~ VSGEN_CDB$V_VSSTRESC_TEMP))
VSGEN_CDB$DLASTMOD <- substring(VSGEN_CDB$DLASTMOD,1,16)
VSGEN_CDB <- VSGEN_CDB %>% mutate_if(is.character, ~replace_na(.,""))
# VSGEN_CDB <- VSGEN_CDB[order(VSGEN_CDB$STUDYID,VSGEN_CDB$COUNTRY,VSGEN_CDB$SITENUM,VSGEN_CDB$SUBJID,VSGEN_CDB$EGID,as.integer(VSGEN_CDB$EGSEQ),VSGEN_CDB$VISIT,VSGEN_CDB$VISITDT,VSGEN_CDB$FORMID,as.integer(VSGEN_CDB$FORMSEQ),as.integer(VSGEN_CDB$IGSEQ)), ]
VSGEN_CDB <- VSGEN_CDB[order(VSGEN_CDB$STUDYID, VSGEN_CDB$COUNTRY, VSGEN_CDB$SITENUM, VSGEN_CDB$SUBJID, VSGEN_CDB$VISITNUM, VSGEN_CDB$VISIT,VSGEN_CDB$VISITDT, VSGEN_CDB$FORMID, VSGEN_CDB$FORMSEQ, VSGEN_CDB$IGSEQ), ]
## Get EDC Data
SUBJECTS <- sys_sub

VS_GEN_01 <- vs_gen_01
VS_GEN_01 <- VS_GEN_01 %>% mutate(across(everything(), as.character))
VS_GEN_01 <- VS_GEN_01 %>% mutate_if(is.character, ~replace_na(.,""))

VS_SCR_01 <- vs_scr_01
VS_SCR_01 <- VS_SCR_01 %>% mutate(across(everything(), as.character))
VS_SCR_01 <- VS_SCR_01 %>% mutate_if(is.character, ~replace_na(.,""))

VS_UNS_01 <- vs_uns_01
VS_UNS_01 <- VS_UNS_01 %>% mutate(across(everything(), as.character))
VS_UNS_01 <- VS_UNS_01 %>% mutate_if(is.character, ~replace_na(.,""))




#-----------  FINAL union query--
VSGEN_UNION <-
  sqldf(
    "SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,VS_GEN_01.COUNTRY  'COUNTRY'
,VS_GEN_01.SITENUM  'SITENUM'
,VS_GEN_01.SUBJID  'SUBJID'
,	S1.STATUS  'SUBJSTATUS'
,VS_GEN_01.EGROUPDEF  'EGID'
,VS_GEN_01.ESEQ  'EGSEQ'
,CASE VS_GEN_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN VS_GEN_01.EGROUP||' '||VS_GEN_01.EVENT
   ELSE VS_GEN_01.EVENT
   END AS 'VISIT'
 ,CASE 
WHEN VS_GEN_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN VS_GEN_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN VS_GEN_01.EVENTEID= 'ev_DAY1' THEN VS_GEN_01.ESEQ + 0.01
WHEN VS_GEN_01.EVENTEID= 'ev_DAY8' THEN VS_GEN_01.ESEQ + 0.08
WHEN VS_GEN_01.EVENTEID= 'ev_DAY15' THEN VS_GEN_01.ESEQ + 0.15
WHEN VS_GEN_01.EVENTEID= 'ev_TUPB' THEN 41 + VS_GEN_01.ESEQ * 0.01
WHEN VS_GEN_01.EVENTEID= 'ev_EOT' THEN 60
WHEN VS_GEN_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN VS_GEN_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN VS_GEN_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN VS_GEN_01.EVENTEID= 'ev_PTFU' THEN 75 + VS_GEN_01.ESEQ * 0.01
WHEN VS_GEN_01.EVENTEID= 'ev_LFU' THEN 80 + VS_GEN_01.ESEQ * 0.01
WHEN VS_GEN_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN VS_GEN_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN VS_GEN_01.EVENTEID= 'ev_UNS' THEN 99 + VS_GEN_01.ESEQ * 0.01
ELSE VS_GEN_01.EVENTEID
END as 'VISITNUM'
,VS_GEN_01.EVENTDT  'VISITDT'
,VS_GEN_01.FORM  'FORM'
,VS_GEN_01.FORMDEF  'FORMID'
,VS_GEN_01.FSEQ  'FORMSEQ'
,CASE VS_GEN_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE VS_GEN_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,VS_GEN_01.IGSEQ  'IGSEQ'
,VS_GEN_01.DLASTMOD  'DLASTMOD'
,VS_GEN_01.V_VSPERF_VSALL  'V_VSPERF_VSALL'
,VS_GEN_01.V_VSREASND_VSALL  'V_VSREASND_VSALL'
,VS_GEN_01.V_VSPOS  'V_VSPOS'
,VS_GEN_01.V_VSDTC  'V_VSDTC'
,VS_GEN_01.V_VSDTC_DT  'V_VSDAT'
,VS_GEN_01.V_VSDTC_TM  'V_VSTIM'
,VS_GEN_01.V_VSDTC  'X_VSDTC'
,VS_GEN_01.V_VSDTC_DT  'X_VSDAT'
,VS_GEN_01.V_VSDTC_TM  'X_VSTIM'

,NULL 'V_VSORRES_HEIGHT'
,NULL 'V_VSORRESU_HEIGHT'
,NULL 'V_VSSTRESC_HEIGHT'
,NULL 'V_VSSTRESN_HEIGHT'
,NULL 'V_VSSTRESU_HEIGHT'

,VS_GEN_01.V_VSORRES_WEIGHT  'V_VSORRES_WEIGHT'
,VS_GEN_01.V_VSORRES_WEIGHT_U  'V_VSORRESU_WEIGHT'
,VS_GEN_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESC_WEIGHT'
,VS_GEN_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESN_WEIGHT'
,VS_GEN_01.V_VSORRES_WEIGHT_TRANSU  'V_VSSTRESU_WEIGHT'

,NULL 'V_QVAL_BSAFRML'

,NULL 'DV_VSORRES_BSA'
,NULL 'DV_VSORRESU_BSA'
,NULL 'DV_VSSTRESC_BSA'
,NULL 'DV_VSSTRESN_BSA'
,NULL 'DV_VSSTRESU_BSA'

,NULL 'DV_VSORRES_BMI'
,NULL 'DV_VSORRESU_BMI'
,NULL 'DV_VSSTRESC_BMI'
,NULL 'DV_VSSTRESN_BMI'
,NULL 'DV_VSSTRESU_BMI'

,VS_GEN_01.V_VSORRES_TEMP  'V_VSORRES_TEMP'
,VS_GEN_01.V_VSORRES_TEMP_U  'V_VSORRESU_TEMP'
,VS_GEN_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESC_TEMP'
,VS_GEN_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESN_TEMP'
,VS_GEN_01.V_VSORRES_TEMP_TRANSU  'V_VSSTRESU_TEMP'

,VS_GEN_01.V_VSORRES_RESP  'V_VSORRES_RESP'
,VS_GEN_01.V_VSORRES_RESP_U  'V_VSORRESU_RESP'
,VS_GEN_01.V_VSORRES_RESP_TRANS  'V_VSSTRESC_RESP'
,VS_GEN_01.V_VSORRES_RESP_TRANS  'V_VSSTRESN_RESP'
,VS_GEN_01.V_VSORRES_RESP_TRANSU  'V_VSSTRESU_RESP'

,VS_GEN_01.V_VSORRES_PULSE  'V_VSORRES_PULSE'
,VS_GEN_01.V_VSORRES_PULSE_U  'V_VSORRESU_PULSE'
,VS_GEN_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESC_PULSE'
,VS_GEN_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESN_PULSE'
,VS_GEN_01.V_VSORRES_PULSE_TRANSU  'V_VSSTRESU_PULSE'

,VS_GEN_01.V_VSORRES_SYSBP  'V_VSORRES_SYSBP'
,VS_GEN_01.V_VSORRES_SYSBP_U  'V_VSORRESU_SYSBP'
,VS_GEN_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESC_SYSBP'
,VS_GEN_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESN_SYSBP'
,VS_GEN_01.V_VSORRES_SYSBP_TRANSU  'V_VSSTRESU_SYSBP'

,VS_GEN_01.V_VSORRES_DIABP  'V_VSORRES_DIABP'
,VS_GEN_01.V_VSORRES_DIABP_U  'V_VSORRESU_DIABP'
,VS_GEN_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESC_DIABP'
,VS_GEN_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESN_DIABP'
,VS_GEN_01.V_VSORRES_DIABP_TRANSU  'V_VSSTRESU_DIABP'

,VS_GEN_01.V_VSORRES_O2  'V_VSORRES_O2'
,VS_GEN_01.V_VSORRES_O2_U  'V_VSORRESU_O2'
,VS_GEN_01.V_VSORRES_O2_TRANS  'V_VSSTRESC_O2'
,VS_GEN_01.V_VSORRES_O2_TRANS  'V_VSSTRESN_O2'
,VS_GEN_01.V_VSORRES_O2_TRANSU  'V_VSSTRESU_O2'
FROM
VS_GEN_01 VS_GEN_01
,SUBJECTS S1

              WHERE
              S1.SUBJID=VS_GEN_01.SUBJID
               AND S1.SITENUM=VS_GEN_01.SITENUM
              AND VS_GEN_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND VS_GEN_01.FORMILB !='true'
    
UNION
SELECT
'EIK1001-005_TST3'  'STUDYID'
,'EDC'  'SOURCE'
,VS_SCR_01.COUNTRY  'COUNTRY'
,VS_SCR_01.SITENUM  'SITENUM'
,VS_SCR_01.SUBJID  'SUBJID'
,	 S1.STATUS 'SUBJSTATUS'
,VS_SCR_01.EGROUPDEF  'EGID'
,VS_SCR_01.ESEQ  'EGSEQ'
,CASE VS_SCR_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN VS_SCR_01.EGROUP||' '||VS_SCR_01.EVENT
   ELSE VS_SCR_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN VS_SCR_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN VS_SCR_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN VS_SCR_01.EVENTEID= 'ev_DAY1' THEN VS_SCR_01.ESEQ + 0.01
WHEN VS_SCR_01.EVENTEID= 'ev_DAY8' THEN VS_SCR_01.ESEQ + 0.08
WHEN VS_SCR_01.EVENTEID= 'ev_DAY15' THEN VS_SCR_01.ESEQ + 0.15
WHEN VS_SCR_01.EVENTEID= 'ev_TUPB' THEN 41 + VS_SCR_01.ESEQ * 0.01
WHEN VS_SCR_01.EVENTEID= 'ev_EOT' THEN 60
WHEN VS_SCR_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN VS_SCR_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN VS_SCR_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN VS_SCR_01.EVENTEID= 'ev_PTFU' THEN 75 + VS_SCR_01.ESEQ * 0.01
WHEN VS_SCR_01.EVENTEID= 'ev_LFU' THEN 80 + VS_SCR_01.ESEQ * 0.01
WHEN VS_SCR_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN VS_SCR_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN VS_SCR_01.EVENTEID= 'ev_UNS' THEN 99 + VS_SCR_01.ESEQ * 0.01
ELSE VS_SCR_01.EVENTEID
END as 'VISITNUM'
,VS_SCR_01.EVENTDT  'VISITDT'
,VS_SCR_01.FORM  'FORM'
,VS_SCR_01.FORMDEF  'FORMID'
,VS_SCR_01.FSEQ  'FORMSEQ'
,CASE VS_SCR_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE VS_SCR_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,VS_SCR_01.IGSEQ  'IGSEQ'
,VS_SCR_01.DLASTMOD  'DLASTMOD'
,VS_SCR_01.V_VSPERF_VSALL  'V_VSPERF_VSALL'
,VS_SCR_01.V_VSREASND_VSALL  'V_VSREASND_VSALL'
,VS_SCR_01.V_VSPOS  'V_VSPOS'
,VS_SCR_01.V_VSDTC  'V_VSDTC'
,VS_SCR_01.V_VSDTC_DT  'V_VSDAT'
,VS_SCR_01.V_VSDTC_TM  'V_VSTIM'
,VS_SCR_01.V_VSDTC  'X_VSDTC'
,VS_SCR_01.V_VSDTC_DT  'X_VSDAT'
,VS_SCR_01.V_VSDTC_TM  'X_VSTIM'

,VS_SCR_01.V_VSORRES_HEIGHT  'V_VSORRES_HEIGHT'
,VS_SCR_01.V_VSORRES_HEIGHT_U  'V_VSORRESU_HEIGHT'
,VS_SCR_01.V_VSORRES_HEIGHT_TRANS  'V_VSSTRESC_HEIGHT'
,VS_SCR_01.V_VSORRES_HEIGHT_TRANS  'V_VSSTRESN_HEIGHT'
,VS_SCR_01.V_VSORRES_HEIGHT_TRANSU  'V_VSSTRESU_HEIGHT'

,VS_SCR_01.V_VSORRES_WEIGHT  'V_VSORRES_WEIGHT'
,VS_SCR_01.V_VSORRES_WEIGHT_U  'V_VSORRESU_WEIGHT'
,VS_SCR_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESC_WEIGHT'
,VS_SCR_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESN_WEIGHT'
,VS_SCR_01.V_VSORRES_WEIGHT_TRANSU  'V_VSSTRESU_WEIGHT'

,VS_SCR_01.V_QVAL_BSAFRML  'V_QVAL_BSAFRML'

,VS_SCR_01.DV_VSORRES_BSA  'DV_VSORRES_BSA'
,VS_SCR_01.DV_VSORRES_BSA_U  'DV_VSORRESU_BSA'
,VS_SCR_01.DV_VSORRES_BSA_TRANS  'DV_VSSTRESC_BSA'
,VS_SCR_01.DV_VSORRES_BSA_TRANS  'DV_VSSTRESN_BSA'
,VS_SCR_01.DV_VSORRES_BSA_TRANSU  'DV_VSSTRESU_BSA'

,VS_SCR_01.DV_VSORRES_BMI  'DV_VSORRES_BMI'
,VS_SCR_01.DV_VSORRES_BMI_U  'DV_VSORRESU_BMI'
,VS_SCR_01.DV_VSORRES_BMI_TRANS  'DV_VSSTRESC_BMI'
,VS_SCR_01.DV_VSORRES_BMI_TRANS  'DV_VSSTRESN_BMI'
,VS_SCR_01.DV_VSORRES_BMI_TRANSU  'DV_VSSTRESU_BMI'

,VS_SCR_01.V_VSORRES_TEMP 'V_VSORRES_TEMP'
,VS_SCR_01.V_VSORRES_TEMP_U  'V_VSORRESU_TEMP'
,VS_SCR_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESC_TEMP'
,VS_SCR_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESN_TEMP'
,VS_SCR_01.V_VSORRES_TEMP_TRANSU  'V_VSSTRESU_TEMP'

,VS_SCR_01.V_VSORRES_RESP  'V_VSORRES_RESP'
,VS_SCR_01.V_VSORRES_RESP_U  'V_VSORRESU_RESP'
,VS_SCR_01.V_VSORRES_RESP_TRANS  'V_VSSTRESC_RESP'
,VS_SCR_01.V_VSORRES_RESP_TRANS  'V_VSSTRESN_RESP'
,VS_SCR_01.V_VSORRES_RESP_TRANSU  'V_VSSTRESU_RESP'

,VS_SCR_01.V_VSORRES_PULSE 'V_VSORRES_PULSE'
,VS_SCR_01.V_VSORRES_PULSE_U  'V_VSORRESU_PULSE'
,VS_SCR_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESC_PULSE'
,VS_SCR_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESN_PULSE'
,VS_SCR_01.V_VSORRES_PULSE_TRANSU  'V_VSSTRESU_PULSE'

,VS_SCR_01.V_VSORRES_SYSBP  'V_VSORRES_SYSBP'
,VS_SCR_01.V_VSORRES_SYSBP_U  'V_VSORRESU_SYSBP'
,VS_SCR_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESC_SYSBP'
,VS_SCR_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESN_SYSBP'
,VS_SCR_01.V_VSORRES_SYSBP_TRANSU  'V_VSSTRESU_SYSBP'

,VS_SCR_01.V_VSORRES_DIABP  'V_VSORRES_DIABP'
,VS_SCR_01.V_VSORRES_DIABP_U  'V_VSORRESU_DIABP'
,VS_SCR_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESC_DIABP'
,VS_SCR_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESN_DIABP'
,VS_SCR_01.V_VSORRES_DIABP_TRANSU  'V_VSSTRESU_DIABP'

,VS_SCR_01.V_VSORRES_O2  'V_VSORRES_O2'
,VS_SCR_01.V_VSORRES_O2_U  'V_VSORRESU_O2'
,VS_SCR_01.V_VSORRES_O2_TRANS  'V_VSSTRESC_O2'
,VS_SCR_01.V_VSORRES_O2_TRANS  'V_VSSTRESN_O2'
,VS_SCR_01.V_VSORRES_O2_TRANSU  'V_VSSTRESU_O2'

FROM
VS_SCR_01 VS_SCR_01
,SUBJECTS S1

              WHERE
              S1.SUBJID=VS_SCR_01.SUBJID
              AND S1.SITENUM=VS_SCR_01.SITENUM
              AND VS_SCR_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND VS_SCR_01.FORMILB !='true'
    

UNION

SELECT
 'EIK1001-005_TST3'  'STUDYID'
 ,'EDC'  'SOURCE'
,VS_UNS_01.COUNTRY  'COUNTRY'
,VS_UNS_01.SITENUM  'SITENUM'
,VS_UNS_01.SUBJID  'SUBJID'
,S1.STATUS  'SUBJSTATUS'
,VS_UNS_01.EGROUPDEF  'EGID'
,VS_UNS_01.ESEQ  'EGSEQ'
,CASE VS_UNS_01.EGROUPDEF
   WHEN 'eg_TRTA1C' THEN VS_UNS_01.EGROUP||' '||VS_UNS_01.EVENT
   ELSE VS_UNS_01.EVENT
   END AS 'VISIT'
,CASE 
WHEN VS_UNS_01.EVENTEID= 'ev_SCREEN' THEN -28
WHEN VS_UNS_01.EVENTEID= 'ev_ENROLL' THEN  -2
WHEN VS_UNS_01.EVENTEID= 'ev_DAY1' THEN VS_UNS_01.ESEQ + 0.01
WHEN VS_UNS_01.EVENTEID= 'ev_DAY8' THEN VS_UNS_01.ESEQ + 0.08
WHEN VS_UNS_01.EVENTEID= 'ev_DAY15' THEN VS_UNS_01.ESEQ + 0.15
WHEN VS_UNS_01.EVENTEID= 'ev_TUPB' THEN 41 + VS_UNS_01.ESEQ * 0.01
WHEN VS_UNS_01.EVENTEID= 'ev_EOT' THEN 60
WHEN VS_UNS_01.EVENTEID= 'ev_DSEOT' THEN 60.1
WHEN VS_UNS_01.EVENTEID= 'ev_SFU30D' THEN 70.30
WHEN VS_UNS_01.EVENTEID= 'ev_SFU90D' THEN 70.90
WHEN VS_UNS_01.EVENTEID= 'ev_PTFU' THEN 75 + VS_UNS_01.ESEQ * 0.01
WHEN VS_UNS_01.EVENTEID= 'ev_LFU' THEN 80 + VS_UNS_01.ESEQ * 0.01
WHEN VS_UNS_01.EVENTEID= 'ev_DSEOS' THEN 90.1
WHEN VS_UNS_01.EVENTEID= 'ev_LOGS' THEN 98
WHEN VS_UNS_01.EVENTEID= 'ev_UNS' THEN 99 + VS_UNS_01.ESEQ * 0.01
ELSE VS_UNS_01.EVENTEID
END as 'VISITNUM'
,VS_UNS_01.EVENTDT  'V_VSDAT'
,VS_UNS_01.FORM  'FORM'
,VS_UNS_01.FORMDEF  'FORMID'
,VS_UNS_01.FSEQ  'FORMSEQ'
,CASE VS_UNS_01.FORMSTATUS
	   WHEN 'Submitted' THEN 'submitted__v'
	   WHEN 'In Progress Post Submit' THEN 'in_progress_post_submit__v'
	   WHEN 'In Edit' THEN 'in_progress_post_submit__v'
	   ELSE VS_UNS_01.FORMSTATUS
	   END AS 'FORMSTATUS'
,VS_UNS_01.IGSEQ  'IGSEQ'
,VS_UNS_01.DLASTMOD  'DLASTMOD'
,NULL 'V_VSPERF_VSALL'
,NULL 'V_VSREASND_VSALL'
,VS_UNS_01.V_VSPOS  'V_VSPOS'
,VS_UNS_01.V_VSDTC  'V_VSDTC'
,VS_UNS_01.V_VSDTC_DT  'V_VSDTC_DT'
,VS_UNS_01.V_VSDTC_TM  'V_VSTIM'
,VS_UNS_01.V_VSDTC  'X_VSDTC'
,VS_UNS_01.V_VSDTC_DT  'X_VSDTC_DT'
,VS_UNS_01.V_VSDTC_TM  'X_VSTIM'

,VS_UNS_01.V_VSORRES_HEIGHT  'V_VSORRES_HEIGHT'
,VS_UNS_01.V_VSORRES_HEIGHT_U  'V_VSORRESU_HEIGHT'
,VS_UNS_01.V_VSORRES_HEIGHT_TRANS  'V_VSSTRESC_HEIGHT'
,VS_UNS_01.V_VSORRES_HEIGHT_TRANS  'V_VSSTRESN_HEIGHT'
,VS_UNS_01.V_VSORRES_HEIGHT_TRANSU  'V_VSSTRESU_HEIGHT'

,VS_UNS_01.V_VSORRES_WEIGHT  'V_VSORRES_WEIGHT'
,VS_UNS_01.V_VSORRES_WEIGHT_U  'V_VSORRESU_WEIGHT'
,VS_UNS_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESC_WEIGHT'
,VS_UNS_01.V_VSORRES_WEIGHT_TRANS  'V_VSSTRESN_WEIGHT'
,VS_UNS_01.V_VSORRES_WEIGHT_TRANSU  'V_VSSTRESU_WEIGHT'

,VS_UNS_01.V_QVAL_BSAFRML  'V_QVAL_BSAFRML'

,VS_UNS_01.DV_VSORRES_BSA  'DV_VSORRES_BSA'
,VS_UNS_01.DV_VSORRES_BSA_U  'DV_VSORRESU_BSA'
,VS_UNS_01.DV_VSORRES_BSA_TRANS  'DV_VSSTRESC_BSA'
,VS_UNS_01.DV_VSORRES_BSA_TRANS  'DV_VSSTRESN_BSA'
,VS_UNS_01.DV_VSORRES_BSA_TRANSU  'DV_VSSTRESU_BSA'

,VS_UNS_01.DV_VSORRES_BMI  'DV_VSORRES_BMI'
,VS_UNS_01.DV_VSORRES_BMI_U  'DV_VSORRESU_BMI'
,VS_UNS_01.DV_VSORRES_BMI_TRANS  'DV_VSSTRESC_BMI'
,VS_UNS_01.DV_VSORRES_BMI_TRANS  'DV_VSSTRESN_BMI'
,VS_UNS_01.DV_VSORRES_BMI_TRANSU  'DV_VSSTRESU_BMI'

,VS_UNS_01.V_VSORRES_TEMP  'V_VSORRES_TEMP'
,VS_UNS_01.V_VSORRES_TEMP_U  'V_VSORRESU_TEMP'
,VS_UNS_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESC_TEMP'
,VS_UNS_01.V_VSORRES_TEMP_TRANS  'V_VSSTRESN_TEMP'
,VS_UNS_01.V_VSORRES_TEMP_TRANSU  'V_VSSTRESU_TEMP'

,VS_UNS_01.V_VSORRES_RESP  'V_VSORRES_RESP'
,VS_UNS_01.V_VSORRES_RESP_U  'V_VSORRESU_RESP'
,VS_UNS_01.V_VSORRES_RESP_TRANS  'V_VSSTRESC_RESP'
,VS_UNS_01.V_VSORRES_RESP_TRANS  'V_VSSTRESN_RESP'
,VS_UNS_01.V_VSORRES_RESP_TRANSU  'V_VSSTRESU_RESP'

,VS_UNS_01.V_VSORRES_PULSE  'V_VSORRES_PULSE'
,VS_UNS_01.V_VSORRES_PULSE_U  'V_VSORRESU_PULSE'
,VS_UNS_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESC_PULSE'
,VS_UNS_01.V_VSORRES_PULSE_TRANS  'V_VSSTRESN_PULSE'
,VS_UNS_01.V_VSORRES_PULSE_TRANSU  'V_VSSTRESU_PULSE'

,VS_UNS_01.V_VSORRES_SYSBP  'V_VSORRES_SYSBP'
,VS_UNS_01.V_VSORRES_SYSBP_U  'V_VSORRESU_SYSBP'
,VS_UNS_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESC_SYSBP'
,VS_UNS_01.V_VSORRES_SYSBP_TRANS  'V_VSSTRESN_SYSBP'
,VS_UNS_01.V_VSORRES_SYSBP_TRANSU  'V_VSSTRESU_SYSBP'

,VS_UNS_01.V_VSORRES_DIABP  'V_VSORRES_DIABP'
,VS_UNS_01.V_VSORRES_DIABP_U  'V_VSORRESU_DIABP'
,VS_UNS_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESC_DIABP'
,VS_UNS_01.V_VSORRES_DIABP_TRANS  'V_VSSTRESn_DIABP'
,VS_UNS_01.V_VSORRES_DIABP_TRANSU  'V_VSSTRESU_DIABP'

,VS_UNS_01.V_VSORRES_O2  'V_VSORRES_O2'
,VS_UNS_01.V_VSORRES_O2_U  'V_VSORRESU_O2'
,VS_UNS_01.V_VSORRES_O2_TRANS  'V_VSSTRESC_O2'
,VS_UNS_01.V_VSORRES_O2_TRANS  'V_VSSTRESN_O2'
,VS_UNS_01.V_VSORRES_O2_TRANSU  'V_VSSTRESU_O2'
FROM
VS_UNS_01 VS_UNS_01
,SUBJECTS S1

              WHERE
              S1.SUBJID=VS_UNS_01.SUBJID
               AND S1.SITENUM=VS_UNS_01.SITENUM
              AND VS_UNS_01.FORMSTATUS IN ('Submitted','In Progress Post Submit','In Edit') 
AND VS_UNS_01.FORMILB !='true'
    
 "
  )

# AND VS_SCR_01.FORMILB !='true'
# AND VS_GEN_01.FORMILB !='true'
# AND VS_UNS_01.FORMILB !='true'

# Call the function -Convert_Date_Vals

CharDate_Cols <-c("V_VSDTC","V_VSDAT")
datetime_columns <- NULL
table_name <- c("VSGEN_UNION")
VSGEN_EDC <- Convert_Date_Vals(VSGEN_UNION, CharDate_Cols,datetime_columns,table_name)

# Arrange columns same as CDB
VSGEN_EDC <- VSGEN_EDC[names(VSGEN_CDB)]

# Post processing for compare
VSGEN_EDC$V_VSORRES_HEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSORRES_HEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSORRES_HEIGHT), digits=1, format="f"), TRUE ~ VSGEN_EDC$V_VSORRES_HEIGHT))
VSGEN_EDC$V_VSSTRESC_HEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSSTRESC_HEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSSTRESC_HEIGHT), digits=1, format="f"), TRUE ~ VSGEN_EDC$V_VSSTRESC_HEIGHT))
VSGEN_EDC$V_VSORRES_WEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSORRES_WEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSORRES_WEIGHT), digits=2, format="f"), TRUE ~ VSGEN_EDC$V_VSORRES_WEIGHT))
VSGEN_EDC$V_VSSTRESC_WEIGHT <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSSTRESC_WEIGHT) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSSTRESC_WEIGHT), digits=2, format="f"), TRUE ~ VSGEN_EDC$V_VSSTRESC_WEIGHT))
VSGEN_EDC$V_VSORRES_TEMP <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSORRES_TEMP) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSORRES_TEMP), digits=1, format="f"), TRUE ~ VSGEN_EDC$V_VSORRES_TEMP))
VSGEN_EDC$V_VSSTRESC_TEMP <- suppressWarnings(case_when(as.numeric(VSGEN_EDC$V_VSSTRESC_TEMP) != "NA" ~ formatC(as.numeric(VSGEN_EDC$V_VSSTRESC_TEMP), digits=1, format="f"), TRUE ~ VSGEN_EDC$V_VSSTRESC_TEMP))
VSGEN_EDC$DLASTMOD <- substring(VSGEN_EDC$DLASTMOD,1,16)
VSGEN_EDC$V_VSTIM <- substring(VSGEN_EDC$V_VSTIM,1,5)
VSGEN_EDC <- VSGEN_EDC %>% mutate_if(is.character, ~replace_na(.,""))
VSGEN_EDC <- VSGEN_EDC %>% mutate(across(everything(), as.character))
# VSGEN_EDC <- VSGEN_EDC[order(VSGEN_EDC$STUDYID,VSGEN_EDC$COUNTRY,VSGEN_EDC$SITENUM,VSGEN_EDC$SUBJID,VSGEN_EDC$EGID,as.integer(VSGEN_EDC$EGSEQ),VSGEN_CDB$VISIT,VSGEN_EDC$VISITDT,VSGEN_EDC$FORMID,as.integer(VSGEN_EDC$FORMSEQ),as.integer(VSGEN_EDC$IGSEQ)), ]
VSGEN_EDC <- VSGEN_EDC[order(VSGEN_EDC$STUDYID, VSGEN_EDC$COUNTRY, VSGEN_EDC$SITENUM, VSGEN_EDC$SUBJID, VSGEN_EDC$VISITNUM, VSGEN_EDC$VISIT,VSGEN_EDC$VISITDT, VSGEN_EDC$FORMID, as.integer(VSGEN_EDC$FORMSEQ), as.integer(VSGEN_EDC$IGSEQ)), ]
#Generate Compare Summary Report
VSGEN_EDC <- VSGEN_EDC %>% mutate(across(everything(), as.character))
VSGEN_CDB <- VSGEN_CDB %>% mutate(across(everything(), as.character))
VSGEN_SUMMARY <- capture.output(summary(comparedf(VSGEN_EDC, VSGEN_CDB)))
print(VSGEN_SUMMARY)

#Export Summary Report
addWorksheet(wb, "VSGEN_SUMMARY")
writeData(wb, sheet = "VSGEN_SUMMARY", x = VSGEN_SUMMARY)

#Export QC Datasets
write_xpt(VSGEN_EDC,"QC Output/Datasets/EDC/VSGEN_EDC.xpt")
write_xpt(VSGEN_CDB,"QC Output/Datasets/CDB/VSGEN_CDB.xpt")

rm(SUBJECTS)
rm(CharDate_Cols)
rm(datetime_columns)
rm(table_name)